Memkeydb blog
pmem/pmem.github.io pull request #143
Opened 2020-09-25 10:27 UTC by jschmieg

2020-09-25 11:19 UTC, lukaszstolarczuk reviewed
can you please add link to a preview (on your fork)

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/143#-:-MI3zH3kANayYEQXkCXw:b-crzlco)* status: 0 of 2 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-25 11:31 UTC, jschmieg commented
https://jschmieg.github.io/2020/09/25/memkeydb.html

2020-09-25 14:31 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/143)* status: all files reviewed, 21 unresolved discussions (waiting on @jschmieg)

___
*[_posts/2020/2020-09-25-memkeydb.md, line 11 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4AwZ25_zmpHjMmu6I:-MI4AwZ25_zmpHjMmu6J:b-hrjaks) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L11)):*
> ```Markdown
> # Context
> 
> Redis is in-memory database that supports many different data-structures and stores them in main memory. To support data durability Redis relies on creating periodical snapshots of dataset or logging all commands that are reaching server. 
> ```

is **an** in-memory database
___
*[_posts/2020/2020-09-25-memkeydb.md, line 11 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4B227BxO1jUD63t_q:-MI4B227BxO1jUD63t_r:b-wx8i2k) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L11)):*
> ```Markdown
> # Context
> 
> Redis is in-memory database that supports many different data-structures and stores them in main memory. To support data durability Redis relies on creating periodical snapshots of dataset or logging all commands that are reaching server. 
> ```

trailing space at the end of the line
___
*[_posts/2020/2020-09-25-memkeydb.md, line 13 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4B87iC2ozT-Ery5Dh:-MI4B87iC2ozT-Ery5Di:bi8uej6) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L13)):*
> ```Markdown
> Redis is in-memory database that supports many different data-structures and stores them in main memory. To support data durability Redis relies on creating periodical snapshots of dataset or logging all commands that are reaching server. 
> 
> When persistent memory started to appear, we started working on various approaches to using it in Redis. Apart from using its persistence, we also had at our disposal its huge capacity.
> ```

to appear...? where?
___
*[_posts/2020/2020-09-25-memkeydb.md, line 13 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4BG3J6nuNMXdyN8AR:-MI4BG3J6nuNMXdyN8AS:b-flrj7n) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L13)):*
> ```Markdown
> Redis is in-memory database that supports many different data-structures and stores them in main memory. To support data durability Redis relies on creating periodical snapshots of dataset or logging all commands that are reaching server. 
> 
> When persistent memory started to appear, we started working on various approaches to using it in Redis. Apart from using its persistence, we also had at our disposal its huge capacity.
> ```

approaches **of** using it (?)
___
*[_posts/2020/2020-09-25-memkeydb.md, line 13 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4BMZF2iX4mhjbKw3Z:-MI4BMZF2iX4mhjbKw3_:b-zhgkfw) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L13)):*
> ```Markdown
> Redis is in-memory database that supports many different data-structures and stores them in main memory. To support data durability Redis relies on creating periodical snapshots of dataset or logging all commands that are reaching server. 
> 
> When persistent memory started to appear, we started working on various approaches to using it in Redis. Apart from using its persistence, we also had at our disposal its huge capacity.
> ```

**we've** started
___
*[_posts/2020/2020-09-25-memkeydb.md, line 15 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4Cj-e2ohAyBn3o0pv:-MI4Cj-e2ohAyBn3o0pw:b8xgri4) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L15)):*
> ```Markdown
> When persistent memory started to appear, we started working on various approaches to using it in Redis. Apart from using its persistence, we also had at our disposal its huge capacity.
> 
> Our first approaches focused on the replacement of the internal mechanisms of Redis' persistence by the persistency of the medium. However, we have concluded that the exclusion of these functions can be negatively perceived by current users, all the more so because the snapshot creation mechanism is also used by the remote data replication mechanism. On the other hand, Redis uses a copy-on-write mechanism to generate database snapshots, which behavior on FS-DAX is problematic, and causes transparent data migration from the PMEM to DRAM: parent process is modifying data in PMEM, at the same time as child process is reading it. Copy-on-write mechanism duplicates pages before modification and allocates their copies in DRAM. In order to solve this, we have tried various workarounds such as: adopting kind of lazy-free mechanism and other ways to not trigger data modification during Redis fork(). The result was a complex modification of the application, which occurred in many places in the code.
> ```

by current users. All the more...
___
*[_posts/2020/2020-09-25-memkeydb.md, line 15 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4D0lZ6bBrPlQqPMxj:-MI4D0lZ6bBrPlQqPMxk:bhd8u70) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L15)):*
> ```Markdown
> When persistent memory started to appear, we started working on various approaches to using it in Redis. Apart from using its persistence, we also had at our disposal its huge capacity.
> 
> Our first approaches focused on the replacement of the internal mechanisms of Redis' persistence by the persistency of the medium. However, we have concluded that the exclusion of these functions can be negatively perceived by current users, all the more so because the snapshot creation mechanism is also used by the remote data replication mechanism. On the other hand, Redis uses a copy-on-write mechanism to generate database snapshots, which behavior on FS-DAX is problematic, and causes transparent data migration from the PMEM to DRAM: parent process is modifying data in PMEM, at the same time as child process is reading it. Copy-on-write mechanism duplicates pages before modification and allocates their copies in DRAM. In order to solve this, we have tried various workarounds such as: adopting kind of lazy-free mechanism and other ways to not trigger data modification during Redis fork(). The result was a complex modification of the application, which occurred in many places in the code.
> ```

Sentence starting with `On the other hand` is really long, please break it.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 15 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4DYn_9XZPO-VBlHIF:-MI4DYn_9XZPO-VBlHIG:b-lcuahm) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L15)):*
> ```Markdown
> When persistent memory started to appear, we started working on various approaches to using it in Redis. Apart from using its persistence, we also had at our disposal its huge capacity.
> 
> Our first approaches focused on the replacement of the internal mechanisms of Redis' persistence by the persistency of the medium. However, we have concluded that the exclusion of these functions can be negatively perceived by current users, all the more so because the snapshot creation mechanism is also used by the remote data replication mechanism. On the other hand, Redis uses a copy-on-write mechanism to generate database snapshots, which behavior on FS-DAX is problematic, and causes transparent data migration from the PMEM to DRAM: parent process is modifying data in PMEM, at  [...]

2020-09-28 12:23 UTC, jschmieg reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/143)* status: 1 of 2 files reviewed, 21 unresolved discussions (waiting on @jschmieg and @lukaszstolarczuk)

___
*[_posts/2020/2020-09-25-memkeydb.md, line 11 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4AwZ25_zmpHjMmu6I:-MIJeZF39-hpJh1UuFh9:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

is **an** in-memory database
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 11 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4B227BxO1jUD63t_q:-MIJe_-p11dkVUNIQdyj:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

trailing space at the end of the line
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 13 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4B87iC2ozT-Ery5Dh:-MIJea1D4mriucXHIwXD:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

to appear...? where?
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 13 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4BG3J6nuNMXdyN8AR:-MIJeaGYAsBHhwqYOxEy:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

approaches **of** using it (?)
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 13 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4BMZF2iX4mhjbKw3Z:-MIJeb1i1zFuTxPqPu1f:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

**we've** started
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 15 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4Cj-e2ohAyBn3o0pv:-MIJecA3EXJiYnRa60xG:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

by current users. All the more...
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 15 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4D0lZ6bBrPlQqPMxj:-MIJecRC26TVugkvBSHk:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Sentence starting with `On the other hand` is really long, please break it.
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 17 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4by7VACuaPuXr8cdH:-MIJedUwDawr1bdkUMSW:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

\`fork()\`
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 19 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4cI19A1fEFlUHlyWt:-MIJeeFi8LjIdcIaIRfC:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L19)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

AOF and RDB?
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 23 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4cZ7C9wzxAJd3j99m:-MIJef3C9n6CvZDQL_75:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L23)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"malloc" -> \`malloc\`
"free" -> \`free\`
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 23 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4csss6iVZKEwZUiCw:-MIJefNo42afutqr_YSR:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L23)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

to allocate **on** both mediums (?)
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 33 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4dJic3mIyk_cw9mVD:-MIJegTx-peNbrEa3v_y:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L33)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

parameter. It allows to select...
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 37 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4dmMJAo6hFKgCTQqW:-MIJehGTCOknp3Qb8cPh:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L37)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`is it worth` -> `it is worth` ;)
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 37 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4dvLD1tfjvCofpxIU:-MIJehVZ3W5MAirfWmn4:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L37)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

, e.g. buffers
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 42 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4eEM628AjJhQJ6MeD:-MIJeiSGC3-AyO02ENRt:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

storing (lowercase)
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 42 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4eFwn3-sLpIH_KRxh:-MIJeip26ailxbcRKqMM:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`,` at the end of the line (instead of `.`)
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 43 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4eQbsCGGVABN3qQGV:-MIJekBy2whD2EZaMeya:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L43)):*
<details><summary> [...]

2020-09-29 16:17 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/143)* status: all files reviewed, 3 unresolved discussions (waiting on @jschmieg)

___
*[_posts/2020/2020-09-25-memkeydb.md, line 11 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4AwZ25_zmpHjMmu6I:-MIPczSv075lv5xsfeCx:b-9qg1u4) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L11)):*
<details><summary><i>Previously, jschmieg wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done
___
*[_posts/2020/2020-09-25-memkeydb.md, line 13 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4B87iC2ozT-Ery5Dh:-MIPd5Gv7O84BmkvghwF:bls6crj) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L13)):*
<details><summary><i>Previously, jschmieg wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`started came to market` ;)
___
*[_posts/2020/2020-09-25-memkeydb.md, line 13 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4BG3J6nuNMXdyN8AR:-MIPdCQ6BpjPhkjRzc23:b-w9e9ul) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L13)):*
<details><summary><i>Previously, jschmieg wrote…</i></summary><blockquote>

Done.
</blockquote></details>

now we have `of to using`


<!-- Sent from Reviewable.io -->

2020-09-29 17:27 UTC, jschmieg reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/143)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[_posts/2020/2020-09-25-memkeydb.md, line 11 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4AwZ25_zmpHjMmu6I:-MIPtcZOBsTqX_GTRuN-:bb7f2mf) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not done
</blockquote></details>

done
___
*[_posts/2020/2020-09-25-memkeydb.md, line 13 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4B87iC2ozT-Ery5Dh:-MIPte9kEiYA-43qnuv1:bb7f2mf) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`started came to market` ;)
</blockquote></details>

done
___
*[_posts/2020/2020-09-25-memkeydb.md, line 13 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4BG3J6nuNMXdyN8AR:-MIPtfcW49aSd1aqE1QZ:bb7f2mf) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

now we have `of to using`
</blockquote></details>

done
___
*[_posts/2020/2020-09-25-memkeydb.md, line 15 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MI4DYn_9XZPO-VBlHIF:-MIPtmW51he9BeEcFTd6:b-xb058j) ([raw file](https://github.com/pmem/pmem.github.io/blob/bbff65a7202b0e207536550c18fc144d6ea432de/_posts/2020/2020-09-25-memkeydb.md#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"fork()" -> "\`fork()\`"
</blockquote></details>

done previously


<!-- Sent from Reviewable.io -->

2020-09-30 07:02 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/143)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-30 07:03 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/143#-:-MISoZjSDRbNn6k4hnG6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-01 12:00 UTC, George330 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/143)* status: all files reviewed, 22 unresolved discussions (waiting on @jschmieg)

___
*[_posts/2020/2020-09-25-memkeydb.md, line 11 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYtz-UCJ-ctJvvXgrS:-MIYtz-VB_0YoBNqTbsW:b-c3lr40) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L11)):*
> ```
> many different
> ```
various
___
*[_posts/2020/2020-09-25-memkeydb.md, line 11 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYu0do7Cep76WKA0z6:-MIYu0do7Cep76WKA0z7:btynzd) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L11)):*
> ```
> To support data durability
> ```
To support data durability,
___
*[_posts/2020/2020-09-25-memkeydb.md, line 11 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYu84FA_3_eCXhZGqt:-MIYu84FA_3_eCXhZGqu:b-nlbq0w) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L11)):*
> ```
> are reaching server
> ```
reach the server
___
*[_posts/2020/2020-09-25-memkeydb.md, line 13 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYuJ5-0g0W3tPjGRdB:-MIYuJ5-0g0W3tPjGRdC:b-ygzne1) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L13)):*
> ```
> at our disposal its huge capacity
> ```
its huge capacity at our disposal 
___
*[_posts/2020/2020-09-25-memkeydb.md, line 15 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYuh2HBaWL4WU20_oT:-MIYuh2HBaWL4WU20_oU:blrg3bp) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L15)):*
> ```
> approaches
> ```
approach
___
*[_posts/2020/2020-09-25-memkeydb.md, line 15 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYuk3126s1icumsMq5:-MIYuk3126s1icumsMq6:brbiw6z) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L15)):*
> ```
> current
> ```
existing
___
*[_posts/2020/2020-09-25-memkeydb.md, line 15 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYvJBU6obkLHvvEEb2:-MIYvJBU6obkLHvvEEb3:b-up5kl1) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L15)):*
> ```
> parent process is modifying data in PMEM, at the same time as child process is reading it
> ```
the parent process modifies data in PMem, at the same moment when the child process reads it
___
*[_posts/2020/2020-09-25-memkeydb.md, line 15 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYviRi0ScmsV31sMPc:-MIYviRi0ScmsV31sMPd:bqoajte) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L15)):*
> ```
> modification
> ```
the modification
___
*[_posts/2020/2020-09-25-memkeydb.md, line 15 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYvqChD1SEsn58Dwfs:-MIYvqChD1SEsn58Dwft:b-rnizu3) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L15)):*
> ```
> ways to not trigger
> ```
ways not to trigger
___
*[_posts/2020/2020-09-25-memkeydb.md, line 20 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYwv6I6nGtzfOiSLEO:-MIYwv6I6nGtzfOiSLEP:b3ira3g) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L20)):*
> ```
> Having the above described possibilities
> ```
With the possibilities described above 
___
*[_posts/2020/2020-09-25-memkeydb.md, line 23 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYxWeFBtoe9Q8uWXjC:-MIYxWeFBtoe9Q8uWXjD:b29o2gf) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L23)):*
> ```
> In MemKeyDB
> ```
In MemKeyDB,
___
*[_posts/2020/2020-09-25-memkeydb.md, line 23 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYxd2NAVNfuxHb44C0:-MIYxd2NAVNfuxHb44C1:bcjcjbo) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L23)):*
> ```
> introducing the idea of memory kinds
> ```
introducing memory kinds
___
*[_posts/2020/2020-09-25-memkeydb.md, line 37 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIZ-9Vh-66trRv0G23N:-MIZ-9Vh-66trRv0G23O:bf2h8ch) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L37)):*
> ```
> As they are used as temporary
> ```
Since they are used as temporary
___
*[_posts/2020/2020-09-25-memkeydb.md, line 37 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIZ-Ci692yQf7peO7lL:-MIZ-Ci692yQf7peO7lM:b-snu09j) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L37)):*
> ```
> For performance reason
> ```
For performance reason,
___
*[_posts/2020/2020-09-25-memkeydb.md, line 37 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIZ-GN-A3W1QaukmRid:-MIZ-GN-A3W1QaukmRie:b7bwfjl) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L37)):*
> ```
> it is worth to always allocate them on DRAM
> ```
it is always worth  allocating them on DRAM
___
*[_posts/2020/2020-09-25-memkeydb.md, line 37 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIZ-dK99QJudzj5xpII:-MIZ-dKAB2brtJ7zzXVe:b1cvdws) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L37)):*
> ```
> to send to the client
> ```
to be sent to the client
___
*[_posts/2020/2020-09-25-memkeydb.md, line 41 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIZ-yp05Vf6ICeQ_j_Q:-MIZ-yp05Vf6ICeQ_j_R:b-jqul7y) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L41)):*
> ```
> that are describing user data
> ```
that describe users' data
___
*[_posts/2020/2020-09-25-memkeydb.md, line 41 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIZ06EL1ApNTA6p71EP:-MIZ06EM7CgyU40jPdsB:bj7cjh4) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L41)):*
> ```
> small comparing to keys
> ```
small compared to keys
___
*[_posts/2020/2020-09-25-memkeydb.md, line 41 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIZ0Ei37kZwzi8HxutZ:-MIZ0Ei37kZwzi8Hxut_:b-8g78i4) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L41)):*
> ```
> There were introduced code optimizations related to:
> ```
We introduced code optimizations related to:
___
*[_posts/2020/2020-09-25-memkeydb.md, line 45 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIZ0pz90M1Nz4mZB6Pu:-MIZ0pz90M1Nz4mZB6Pv:b-tjiwb2) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L45)):*
> ```
> a good idea is
> ```
it is recommended to pass...
___
*[_posts/2020/2020-09-25-memkeydb.md, line 45 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIZ0w7UAYc2TSq9YP0m:-MIZ0w7UAYc2TSq9YP0n:b-prkd42) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L45)):*
> ```
> this information
> ```
this piece of information
___
*[_posts/2020/2020-09-25-m [...]

2020-10-02 13:02 UTC, pbalcer requested changes
split lines at 80.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/143#-:-MIdIBnhDravZks7i34V:bywnytx)* status: all files reviewed, 26 unresolved discussions (waiting on @jschmieg)

___
*[_posts/2020/2020-09-25-memkeydb.md, line 11 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIdIEVYE7VHTqIQbpN8:-MIdIEVYE7VHTqIQbpN9:bihjwlt) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L11)):*
> ```Markdown
> # Context
> 
> Redis is an in-memory database that supports many different data-structures and stores them in main memory. To support data durability Redis relies on creating periodical snapshots of dataset or logging all commands that are reaching server.
> ```

on periodically creating snapshots of data or ... that reach the server.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 13 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIdIPvS7Jgg7EV44Aly:-MIdIPvS7Jgg7EV44Alz:bekchoy) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L13)):*
> ```Markdown
> Redis is an in-memory database that supports many different data-structures and stores them in main memory. To support data durability Redis relies on creating periodical snapshots of dataset or logging all commands that are reaching server.
> 
> When persistent memory started to appear on the market, we've started working on various approaches of using it in Redis. Apart from using its persistence, we also had at our disposal its huge capacity.
> ```

When Persistent Memory was first introduced, we've started
___
*[_posts/2020/2020-09-25-memkeydb.md, line 15 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIdIipSAmuK7EuWavxa:-MIdIipSAmuK7EuWavxb:bpo2zmt) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L15)):*
> ```Markdown
> When persistent memory started to appear on the market, we've started working on various approaches of using it in Redis. Apart from using its persistence, we also had at our disposal its huge capacity.
> 
> Our first approaches focused on the replacement of the internal mechanisms of Redis' persistence by the persistency of the medium. However, we have concluded that the exclusion of these functions can be negatively perceived by current users. All the more so because the snapshot creation mechanism is also used by the remote data replication mechanism. On the other hand, Redis uses a copy-on-write mechanism to generate database snapshots. Its behavior on FS-DAX is problematic, and causes transparent data migration from the PMEM to DRAM: parent process is modifying data in PMEM, at the same time as child process is reading it. Copy-on-write mechanism duplicates pages before modification and allocates their copies in DRAM. In order to solve this, we have tried various workarounds such as: adopting kind of lazy-free mechanism and other ways to not trigger data modification during Redis `fork()`. The result was a complex modification of the application, which occurred in many places in the code.
> ```

these features.

"negatively percevied by the users" - that's not a useful information. It's better to explain why that's the case. (... "because the same mechanisms are also used for replication" ?)

You say "on the other hand", but I don't see what this refers to.


Same with "in order to solve this" - you didn't present a problem, but marely described how redis cow works.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 17 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIdLFJ_1fuXF3DbUtbZ:-MIdLFJ_1fuXF3DbUtb_:b-ked4sf) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L17)):*
> ```Markdown
> Our first approaches focused on the replacement of the internal mechanisms of Redis' persistence by the persistency of the medium. However, we have concluded that the exclusion of these functions can be negatively perceived by current users. All the more so because the snapshot creation mechanism is also used by the remote data replication mechanism. On the other hand, Redis uses a copy-on-write mechanism to generate database snapshots. Its behavior on FS-DAX is problematic, and causes transparent data migration from the PMEM to DRAM: parent process is modifying data in PMEM, at the same time as child process is reading it. Copy-on-write mechanism duplicates pages before modification and allocates their copies in DRAM. In order to solve this, we have tried various workarounds such as: adopting kind of lazy-free mechanism and other ways to not trigger data modification during Redis `fork()`. The result was a complex modification of the application, which occurred in many places in the code.
> 
> The situation became much simpler when the Linux kernel 5.1 included support for the [KMEM DAX](https://patchwork.kernel.org/cover/10829019/) mechanism and the possibility of exposing memory from the device as an additional NUMA node. Using this feature, support for Copy-on-Write was transparent and the memory pages modified during the `fork()` were allocated from the same NUMA node to which the parent process was bound. Support for this mechanism has been added in our volatile memory allocator – [Memkind](https://pmem.io/2020/01/20/libmemkind.html) as an additional [static kind](https://pmem.io/2020/01/20/memkind-dax-kmem.html).
> ```

Isn't it a bit disingenuous to claim that KMEM DAX "solves" the cow problem? The performance penalty is still there.
What I think you should mention is that DAX for PMEM only works with MAP_SHARED, which means that it won't even work.


<!-- Sent from Reviewable.io -->

2020-10-06 09:11 UTC, jschmieg reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/143)* status: 1 of 2 files reviewed, 26 unresolved discussions (waiting on @George330, @lukaszstolarczuk, and @pbalcer)

___
*[_posts/2020/2020-09-25-memkeydb.md, line 11 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYtz-UCJ-ctJvvXgrS:-MIxA-MSA4veqgwmUj7I:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L11)):*
<details><summary><i>Previously, George330 wrote…</i></summary><blockquote>

> ```
> many different
> ```
various
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 11 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYu0do7Cep76WKA0z6:-MIxA-og3IMP0JP1-7iK:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L11)):*
<details><summary><i>Previously, George330 wrote…</i></summary><blockquote>

> ```
> To support data durability
> ```
To support data durability,
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 11 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYu84FA_3_eCXhZGqt:-MIxA0BvA5rMShRlJQpN:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L11)):*
<details><summary><i>Previously, George330 wrote…</i></summary><blockquote>

> ```
> are reaching server
> ```
reach the server
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 11 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIdIEVYE7VHTqIQbpN8:-MIxA0YZ35pRkKoOZC7p:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L11)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

on periodically creating snapshots of data or ... that reach the server.
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 13 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYuJ5-0g0W3tPjGRdB:-MIxA1DY1NAwf_8Ab4dC:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L13)):*
<details><summary><i>Previously, George330 wrote…</i></summary><blockquote>

> ```
> at our disposal its huge capacity
> ```
its huge capacity at our disposal 
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 13 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIdIPvS7Jgg7EV44Aly:-MIxA1lfBfS5F1T0Rg2X:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L13)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

When Persistent Memory was first introduced, we've started
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 15 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIdIipSAmuK7EuWavxa:-MIx9Y_F5ahAjVhHuqP6:bjqng3v) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L15)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

these features.

"negatively percevied by the users" - that's not a useful information. It's better to explain why that's the case. (... "because the same mechanisms are also used for replication" ?)

You say "on the other hand", but I don't see what this refers to.


Same with "in order to solve this" - you didn't present a problem, but marely described how redis cow works.
</blockquote></details>

I added more description of why CoW is a problem on DAX. Also, I rewrote some sentences.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 15 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYuh2HBaWL4WU20_oT:-MIxA2DCBaHA9gJo4AMf:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L15)):*
<details><summary><i>Previously, George330 wrote…</i></summary><blockquote>

> ```
> approaches
> ```
approach
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 15 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYuk3126s1icumsMq5:-MIxA2ar4NZCKOl-7byW:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L15)):*
<details><summary><i>Previously, George330 wrote…</i></summary><blockquote>

> ```
> current
> ```
existing
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 15 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYvJBU6obkLHvvEEb2:-MIxA2wUC5f7S4kXZQl0:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L15)):*
<details><summary><i>Previously, George330 wrote…</i></summary><blockquote>

> ```
> parent process is modifying data in PMEM, at the same time as child process is reading it
> ```
the parent process modifies data in PMem, at the same moment when the child process reads it
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 15 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYviRi0ScmsV31sMPc:-MIxA3L982fv5sG50E16:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L15)):*
<details><summary><i>Previously, George330 wrote…</i></summary><blockquote>

> ```
> modification
> ```
the modification
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 15 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYvqChD1SEsn58Dwfs:-MIxA3kAEIogGrig-YMp:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L15)):*
<details><summary><i>Previously, George330 wrote…</i></summary><blockquote>

> ```
> ways to not trigger
> ```
ways not to trigger
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 17 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIdLFJ_1fuXF3DbUtbZ:-MIxA5XM4kYGiyabP_GD:b-9jyl1b) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L17)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

Isn't it a bit disingenuous to claim that KMEM DAX "solves" the cow problem? The performance penalty is still there.
What I think you should mention is that DAX for PMEM only works with MAP_SHARED, which means that it won't even work.
</blockquote></details>

I added some more info there.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 20 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYwv6I6nGtzfOiSLEO:-MIxA8yr2oczlO-Cf3xx:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L20)):*
<details><summary><i>Previously, George330 wrote…</i></summary><blockquote>

> ```
> Having the above described possibilities
> ```
With the possibilities described above 
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 23 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIYxWeFBtoe9Q8uWXjC:-MIxA9RBCxW9hECylOAJ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/995529a74d6e10f439439b49ab599a4e58946187/_posts/2020/2020-09-25-memkeydb.md#L23)):*
<details><summary><i>Previously, George330 wrote…</i></summary><blockquote>

> ```
> In MemKeyDB
> ```
In MemKeyDB,
</blockquote></details>

Done.
___
*[_post [...]

2020-10-06 13:58 UTC, pbalcer requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/143)* status: 1 of 2 files reviewed, 27 unresolved discussions (waiting on @George330, @jschmieg, and @lukaszstolarczuk)

___
*[_posts/2020/2020-09-25-memkeydb.md, line 24 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIy4-gb3MGVSu73nYMK:-MIy4-gb3MGVSu73nYML:b-s71r8u) ([raw file](https://github.com/pmem/pmem.github.io/blob/d42a416adf3bd1553a3bca34fd3b473f7a9dd874/_posts/2020/2020-09-25-memkeydb.md#L24)):*
> ```Markdown
> users for at least two reasons: the same mechanism (snapshot creation) is used
> for replication and current infrastructure and software are adopted to use
> snapshot files for backup. However, maintaining support for these mechanisms
> ```

remove the "however", and change this to something like this: "Keeping support for these mechanism when introducing support for pmem requires solving additional problems"
___
*[_posts/2020/2020-09-25-memkeydb.md, line 48 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIyB7-U3s8hEHKzpF7t:-MIyB7-VCYHYtWy7jJV2:bz0o8af) ([raw file](https://github.com/pmem/pmem.github.io/blob/d42a416adf3bd1553a3bca34fd3b473f7a9dd874/_posts/2020/2020-09-25-memkeydb.md#L48)):*
> ```Markdown
> [Memkind](https://pmem.io/2020/01/20/libmemkind.html) as an additional [static
> kind](https://pmem.io/2020/01/20/memkind-dax-kmem.html). The disadvantage of
> this approach will be a possible decrease in performance due to copying entire
> ```

... aproach is a possible ...
___
*[_posts/2020/2020-09-25-memkeydb.md, line 52 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIyBLYrDUaz3PFuNcXJ:-MIyBLYsBWTi2c05rBi7:b-73wqhj) ([raw file](https://github.com/pmem/pmem.github.io/blob/d42a416adf3bd1553a3bca34fd3b473f7a9dd874/_posts/2020/2020-09-25-memkeydb.md#L52)):*
> ```Markdown
> 
> With the possibilities described above, we modified Redis by adding a new type
> of memory used in a volatile way, while leaving the native mechanisms of
> ```

while retaining
___
*[_posts/2020/2020-09-25-memkeydb.md, line 54 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIyBPdw2nOTkqpHpSzt:-MIyBPdw2nOTkqpHpSzu:b4avap8) ([raw file](https://github.com/pmem/pmem.github.io/blob/d42a416adf3bd1553a3bca34fd3b473f7a9dd874/_posts/2020/2020-09-25-memkeydb.md#L54)):*
> ```Markdown
> of memory used in a volatile way, while leaving the native mechanisms of
> persistence: logging (AOF) and snapshoting (RDB). At the same time, we collected
> functional requirements from clients and created a community around the project
> ```

from stakeholders
___
*[_posts/2020/2020-09-25-memkeydb.md, line 126 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIyCC4DEU2laU4dCpYo:-MIyCC4DEU2laU4dCpYp:bfjghd8) ([raw file](https://github.com/pmem/pmem.github.io/blob/d42a416adf3bd1553a3bca34fd3b473f7a9dd874/_posts/2020/2020-09-25-memkeydb.md#L126)):*
> ```Markdown
>   arenas.
> * Lg_quantum – inherits the value from jemalloc config in Redis. It creates an
>   addition allocation class which is very often used by Redis. This helps to
> ```

additional


<!-- Sent from Reviewable.io -->

2020-10-07 08:45 UTC, pbalcer requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/143)* status: 1 of 2 files reviewed, 27 unresolved discussions (waiting on @George330, @jschmieg, and @lukaszstolarczuk)

___
*[_posts/2020/2020-09-25-memkeydb.md, line 24 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIy4-gb3MGVSu73nYMK:-MJ1Dzl6BVFwckEemCMZ:b-yhfhmx) ([raw file](https://github.com/pmem/pmem.github.io/blob/d42a416adf3bd1553a3bca34fd3b473f7a9dd874/_posts/2020/2020-09-25-memkeydb.md#L24)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

remove the "however", and change this to something like this: "Keeping support for these mechanism when introducing support for pmem requires solving additional problems"
</blockquote></details>

I just realized I wrote support twice.
"Keeping support for these mechanisms when introducing pmem requires solving additional problems"


<!-- Sent from Reviewable.io -->

2020-10-07 09:28 UTC, jschmieg reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/143)* status: 1 of 2 files reviewed, 27 unresolved discussions (waiting on @George330, @lukaszstolarczuk, and @pbalcer)

___
*[_posts/2020/2020-09-25-memkeydb.md, line 24 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIy4-gb3MGVSu73nYMK:-MJ1NkPB0j-JDkct-IEJ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/d42a416adf3bd1553a3bca34fd3b473f7a9dd874/_posts/2020/2020-09-25-memkeydb.md#L24)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

I just realized I wrote support twice.
"Keeping support for these mechanisms when introducing pmem requires solving additional problems"
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 48 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIyB7-U3s8hEHKzpF7t:-MJ1Nl2W63JYzBp9cu3D:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/d42a416adf3bd1553a3bca34fd3b473f7a9dd874/_posts/2020/2020-09-25-memkeydb.md#L48)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

... aproach is a possible ...
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 52 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIyBLYrDUaz3PFuNcXJ:-MJ1NlTP7cNbjKA1R9es:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/d42a416adf3bd1553a3bca34fd3b473f7a9dd874/_posts/2020/2020-09-25-memkeydb.md#L52)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

while retaining
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 54 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIyBPdw2nOTkqpHpSzt:-MJ1NltL89WsSFPFcUub:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/d42a416adf3bd1553a3bca34fd3b473f7a9dd874/_posts/2020/2020-09-25-memkeydb.md#L54)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

from stakeholders
</blockquote></details>

Done.
___
*[_posts/2020/2020-09-25-memkeydb.md, line 126 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/143#-MIyCC4DEU2laU4dCpYo:-MJ1NmJo976e6jMxBAmd:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/d42a416adf3bd1553a3bca34fd3b473f7a9dd874/_posts/2020/2020-09-25-memkeydb.md#L126)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

additional
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-09 11:55 UTC, pbalcer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/143#-:-MJCCmJmAk9V4TWIW0Kq:bnfp4nl)* status: 1 of 2 files reviewed, 22 unresolved discussions (waiting on @George330 and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2020-10-09 11:55 UTC, merged