Add blog post about concurrency considerations
pmem/pmem.github.io pull request #160
Opened 2021-08-04 14:52 UTC by igchor

This post is meant to describe problems with concurrency programming and serve as an introduction to the blog post about concurrent_hash_map and concurrent_map which we are working on.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/160)

2021-08-05 09:02 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor)

___
*[_posts/2021/2021-07-28-concurrency.md, line 53 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MgKUv2OCXlgrXr8fx5N:-MgKUv2OCXlgrXr8fx5O:b-uaejon) ([raw file](https://github.com/pmem/pmem.github.io/blob/3fbee714f95e921c8c59f9b7132455639539c094/_posts/2021/2021-07-28-concurrency.md#L53)):*
> ```Markdown
> ```
> 
> This solution makes (`pmem->a = 0`, `pmem->b = 1`) case impossible at the cost of additional persist on each read. To optimize this approach, we can add a dirty bit inside the value, which indicates whether the value was explicitly persisted or not. When modifying the value, the dirty flag is set to true. All readers, first check this flag and proceed as follows:
> ```

`All readers first check` (no comma)
___
*[_posts/2021/2021-07-28-concurrency.md, line 59 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MgKVUHP27oLKnZqqSsW:-MgKVUHP27oLKnZqqSsX:b-r4o34k) ([raw file](https://github.com/pmem/pmem.github.io/blob/3fbee714f95e921c8c59f9b7132455639539c094/_posts/2021/2021-07-28-concurrency.md#L59)):*
> ```Markdown
> 
> You can see an example of such implementation [here](
> https://github.com/pmem/pmdk/blob/master/src/examples/libpmem2/ringbuf/ringbuf.c)
> ```

add `.` at the end of the sentence
___
*[_posts/2021/2021-07-28-concurrency.md, line 98 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MgKVti65bTdlLZ0yvca:-MgKVti65bTdlLZ0yvcb:b36pozb) ([raw file](https://github.com/pmem/pmem.github.io/blob/3fbee714f95e921c8c59f9b7132455639539c094/_posts/2021/2021-07-28-concurrency.md#L98)):*
> ```Markdown
> ```
> 
> Let's assume that there are two threads calling insert() concurrently, and they start incrementing size simultaneously. They will both store the same initial `size` value in theirs undo logs. If the transaction in the first thread aborts, it will abort the `size` value to the initial state. It will completely ignore the changes made by the second transaction.
> ```

`insert`? did you mean `push_back`?
___
*[_posts/2021/2021-07-28-concurrency.md, line 102 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MgKWe8C0IeBHb1YQeDB:-MgKWe8C0IeBHb1YQeDC:b7dgo6l) ([raw file](https://github.com/pmem/pmem.github.io/blob/3fbee714f95e921c8c59f9b7132455639539c094/_posts/2021/2021-07-28-concurrency.md#L102)):*
> ```Markdown
> One other problem is that readers might suffer from the 'dirty reads' phenomenon. If a reader reads size variable while another thread modifies it inside a transaction, it reads uncommitted data. If a transaction aborts or a power failure happens, the size variable can be rolled back, and the reader's view of the data might be incorrect. In addition to that, the rollback itself is not thread-safe.
> 
> One possible solution is to make the global size volatile. The volatile variable can be modified using atomic instructions (after the transaction completes) while providing the number of elements in O(1) time. To restore the size on application restart, we can introduce a per-thread size variable that can be safely modified in a transaction. Per-thread sizes can be summed up to provide the actual size. Libpmemobj-cpp implements a helper data structure (which as of 2021-07-28 is not yet released as a public API) called [enumerable_thread_specific](https://pmem.io/libpmemobj-cpp/master/doxygen/classpmem_1_1detail_1_1enumerable__thread__specific.html). It provides API to request memory which will be private to a thread and iteration API. Enumerable thread-specific is used in concurrent_map and concurrent_hash_map to solve the shared state problem.
> ```

I'd drop the hardcoded date here
___
*[_posts/2021/2021-07-28-concurrency.md, line 104 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MgKWvqg25ek14tBSjuJ:-MgKWvqg25ek14tBSjuK:buqv0a6) ([raw file](https://github.com/pmem/pmem.github.io/blob/3fbee714f95e921c8c59f9b7132455639539c094/_posts/2021/2021-07-28-concurrency.md#L104)):*
> ```Markdown
> One possible solution is to make the global size volatile. The volatile variable can be modified using atomic instructions (after the transaction completes) while providing the number of elements in O(1) time. To restore the size on application restart, we can introduce a per-thread size variable that can be safely modified in a transaction. Per-thread sizes can be summed up to provide the actual size. Libpmemobj-cpp implements a helper data structure (which as of 2021-07-28 is not yet released as a public API) called [enumerable_thread_specific](https://pmem.io/libpmemobj-cpp/master/doxygen/classpmem_1_1detail_1_1enumerable__thread__specific.html). It provides API to request memory which will be private to a thread and iteration API. Enumerable thread-specific is used in concurrent_map and concurrent_hash_map to solve the shared state problem.
> 
> **Publishing allocations**
> ```

not a `###` section?
___
*[_posts/2021/2021-07-28-concurrency.md, line 138 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MgKXKfg1d80fQQFqXDs:-MgKXKfk-wqwgrCjhwax:bolu9du) ([raw file](https://github.com/pmem/pmem.github.io/blob/3fbee714f95e921c8c59f9b7132455639539c094/_posts/2021/2021-07-28-concurrency.md#L138)):*
> ```Markdown
> ```
> 
> The implementation uses self_relative_ptr as it's currently the only pmem::obj pointer type that is supported by std::atomic.
> ```

` is supported by`? perhaps `only pmem::obj pointer type working with std::atomic.`


<!-- Sent from Reviewable.io -->

2021-08-05 12:26 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160)* status: all files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[_posts/2021/2021-07-28-concurrency.md, line 53 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MgKUv2OCXlgrXr8fx5N:-MgLFRlWEMPmW4hqyO0s:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/3fbee714f95e921c8c59f9b7132455639539c094/_posts/2021/2021-07-28-concurrency.md#L53)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`All readers first check` (no comma)
</blockquote></details>

Done.
___
*[_posts/2021/2021-07-28-concurrency.md, line 59 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MgKVUHP27oLKnZqqSsW:-MgLFT_L1DA1qDJCKatw:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/3fbee714f95e921c8c59f9b7132455639539c094/_posts/2021/2021-07-28-concurrency.md#L59)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

add `.` at the end of the sentence
</blockquote></details>

Done.
___
*[_posts/2021/2021-07-28-concurrency.md, line 98 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MgKVti65bTdlLZ0yvca:-MgLFYJZBkvb9hl7PPpC:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/3fbee714f95e921c8c59f9b7132455639539c094/_posts/2021/2021-07-28-concurrency.md#L98)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`insert`? did you mean `push_back`?
</blockquote></details>

Done.
___
*[_posts/2021/2021-07-28-concurrency.md, line 102 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MgKWe8C0IeBHb1YQeDB:-MgLFam-7ZISUK6ba-EC:b-33agfn) ([raw file](https://github.com/pmem/pmem.github.io/blob/3fbee714f95e921c8c59f9b7132455639539c094/_posts/2021/2021-07-28-concurrency.md#L102)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'd drop the hardcoded date here
</blockquote></details>

Hm, when we release enumerable_thread_specific as public API and forget to update this, it will still be correct (if we leave the date) ;d
___
*[_posts/2021/2021-07-28-concurrency.md, line 104 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MgKWvqg25ek14tBSjuJ:-MgLFpoA580YsfMaE723:bu4i861) ([raw file](https://github.com/pmem/pmem.github.io/blob/3fbee714f95e921c8c59f9b7132455639539c094/_posts/2021/2021-07-28-concurrency.md#L104)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not a `###` section?
</blockquote></details>

It's kind of a subsection of `Shared state consistency`.  Should I just use `###`?
___
*[_posts/2021/2021-07-28-concurrency.md, line 138 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MgKXKfg1d80fQQFqXDs:-MgLG-akDqgBRIucmoX8:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/3fbee714f95e921c8c59f9b7132455639539c094/_posts/2021/2021-07-28-concurrency.md#L138)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

` is supported by`? perhaps `only pmem::obj pointer type working with std::atomic.`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-06 12:17 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[_posts/2021/2021-07-28-concurrency.md, line 102 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MgKWe8C0IeBHb1YQeDB:-MgQO0sH7VEIPO8w-TZS:bx489yd) ([raw file](https://github.com/pmem/pmem.github.io/blob/3fbee714f95e921c8c59f9b7132455639539c094/_posts/2021/2021-07-28-concurrency.md#L102)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, when we release enumerable_thread_specific as public API and forget to update this, it will still be correct (if we leave the date) ;d
</blockquote></details>

I thought, maybe something like "publish date of this blog post" :wink: 
___
*[_posts/2021/2021-07-28-concurrency.md, line 104 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MgKWvqg25ek14tBSjuJ:-MgQOD3N30TCZ2XGHnFq:b-x1pp4l) ([raw file](https://github.com/pmem/pmem.github.io/blob/3fbee714f95e921c8c59f9b7132455639539c094/_posts/2021/2021-07-28-concurrency.md#L104)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

It's kind of a subsection of `Shared state consistency`.  Should I just use `###`?
</blockquote></details>

hmm, perhaps `####` - a sub-section, but with proper header style


<!-- Sent from Reviewable.io -->

2021-09-13 13:18 UTC, vinser52 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[_posts/2021/2021-07-28-concurrency.md, line 176 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjUICmU99DKCnvSVJpE:-MjUICmU99DKCnvSVJpF:bqrmlog) ([raw file](https://github.com/pmem/pmem.github.io/blob/7014eeec5817985364141cdc6f56f6a964af7b45/_posts/2021/2021-07-28-concurrency.md#L176)):*
> ```Markdown
> However, there is still one other issue - a possible memory leak. If a crash happens during the `push_back` method just after the new node is allocated, but before it is linked to the list, it will not be reachable after a restart. `new_node` pointer is kept on the stack, which means it will not survive a restart.
> 
> A solution to this problem is, once again, enumerable_thread_specific. With the help of this data structure, `push_back` can be rewritten like this:
> ```

At the beginning of the "Publish allocation" section you mentioned that it is single-writer & multiple readers list. For that case, we do not need enumerable_thread_specific, just a single member variable is enough, isn't it?


<!-- Sent from Reviewable.io -->

2021-09-14 15:54 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @vinser52)

___
*[_posts/2021/2021-07-28-concurrency.md, line 176 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjUICmU99DKCnvSVJpE:-MjZynV53h8d95cZi91y:b-uky1yt) ([raw file](https://github.com/pmem/pmem.github.io/blob/7014eeec5817985364141cdc6f56f6a964af7b45/_posts/2021/2021-07-28-concurrency.md#L176)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

At the beginning of the "Publish allocation" section you mentioned that it is single-writer & multiple readers list. For that case, we do not need enumerable_thread_specific, just a single member variable is enough, isn't it?
</blockquote></details>

Right, good point. I rewrote this slightly.


<!-- Sent from Reviewable.io -->

2021-09-15 12:10 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk and @vinser52)

___
*[_posts/2021/2021-07-28-concurrency.md, line 102 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MgKWe8C0IeBHb1YQeDB:-MjdMHIsDhMYdVVMziMe:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/3fbee714f95e921c8c59f9b7132455639539c094/_posts/2021/2021-07-28-concurrency.md#L102)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I thought, maybe something like "publish date of this blog post" :wink: 
</blockquote></details>

Done.
___
*[_posts/2021/2021-07-28-concurrency.md, line 104 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MgKWvqg25ek14tBSjuJ:-MjdMM4Y5A4hISMO9aCm:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/3fbee714f95e921c8c59f9b7132455639539c094/_posts/2021/2021-07-28-concurrency.md#L104)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm, perhaps `####` - a sub-section, but with proper header style
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-15 14:33 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @vinser52)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjdjpVTAXK4b8Hl_ct3:-MjdjpVTAXK4b8Hl_ct4:b-vlajp6) (no related file):*
I guess you can update the post date a little :wink: 

---
___
*[_posts/2021/2021-07-28-concurrency.md, line 190 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjdoVhbAJcKz-jDHDGJ:-MjdoVhbAJcKz-jDHDGK:bwoxb45) ([raw file](https://github.com/pmem/pmem.github.io/blob/51bb7aea421bba4b0763f6bfe201d948f73fc420/_posts/2021/2021-07-28-concurrency.md#L190)):*
> ```Markdown
> ```
> 
> Because `new_node` now resides on persistent memory, even if it is not linked to the list, it is always reachable on restart. There are no problems with dirty reads or visibility as `new_node` is never read during normal execution (only on recovery). If `push_back` would need to be thread-safe, `new_node` variable can be replaced with enumerable_thread_specific.
> ```

`can be replaced` -> `could be replaced`


<!-- Sent from Reviewable.io -->

2021-09-16 12:10 UTC, PatKamin reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160#-:-MjiVr5S2p-XeegI6pr9:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor and @vinser52)

___
*[_posts/2021/2021-07-28-concurrency.md, line 176 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjiVP-466QSqemIK_rE:-MjiVP-466QSqemIK_rF:b-c4w6t4) ([raw file](https://github.com/pmem/pmem.github.io/blob/51bb7aea421bba4b0763f6bfe201d948f73fc420/_posts/2021/2021-07-28-concurrency.md#L176)):*
> ```
> problem is, to move
> ```
nit: Remove comma.


<!-- Sent from Reviewable.io -->

2021-09-17 09:16 UTC, KFilipek reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160#-:-Mjn1ehlCxb7GpePLcZW:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor and @vinser52)



<!-- Sent from Reviewable.io -->

2021-09-17 09:40 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk and @vinser52)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjdjpVTAXK4b8Hl_ct3:-Mjn5uSD6gKxGzV5V8td:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess you can update the post date a little :wink: 
</blockquote></details>

Done.

---
___
*[_posts/2021/2021-07-28-concurrency.md, line 190 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjdoVhbAJcKz-jDHDGJ:-Mjn6mlGDpPxgc6c-DU0:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/51bb7aea421bba4b0763f6bfe201d948f73fc420/_posts/2021/2021-07-28-concurrency.md#L190)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`can be replaced` -> `could be replaced`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-17 10:49 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160#-:-MjnMv610_MosGuEGyXI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @vinser52)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjdjpVTAXK4b8Hl_ct3:-MjnMu0_1lEC-NOulpUw:bb7p5eq) (no related file):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx!

---


<!-- Sent from Reviewable.io -->

2021-09-17 11:34 UTC, pbalcer requested changes
Split lines at 80.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160#-:-MjnQm4QC8Tt2sOyocCC:b-5o1eiz)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor and @vinser52)

___
*[_posts/2021/2021-09-17-concurrency.md, line 10 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjnQ6z68_GM0zzoDFLy:-MjnQ6z68_GM0zzoDFLz:bo79sza) ([raw file](https://github.com/pmem/pmem.github.io/blob/4eeff882f7d601bf1ea10c23e24e4370a7ff9935/_posts/2021/2021-09-17-concurrency.md#L10)):*
> ```Markdown
> ### Introduction
> 
> Ensuring data consistency on pmem is a challenging task. It gets even more complicated if data is accessed concurrently. This blog post describes several challenges related to data visibility, using transactions in multi-threaded environments, and memory leaks.
> ```

how does concurrent *access* make data consistency any harder?  I think you meant writes/mutation/modification.
___
*[_posts/2021/2021-09-17-concurrency.md, line 14 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjnQac97a9ZnKthJQM3:-MjnQac97a9ZnKthJQM4:bw0weh5) ([raw file](https://github.com/pmem/pmem.github.io/blob/4eeff882f7d601bf1ea10c23e24e4370a7ff9935/_posts/2021/2021-09-17-concurrency.md#L14)):*
> ```Markdown
> ### Lock-free programming on pmem
> 
> A fundamental issue (if [eADR](https://pmem.io/glossary/#eadr) is not used) is data visibility. When a thread issues a temporal (e.g., MOV) store instruction, the modification is visible to other threads before it is persistent (data can still be in cache). Consider the following scenario with one thread writing to a variable using atomic operations and the second one reading from it:
> ```

This might be true on x86, but might not be on other architectures with weak ordering. I'd rephrase this a bit.
___
*[_posts/2021/2021-09-17-concurrency.md, line 32 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjnRToS21MSJZdfUya_:-MjnRToS21MSJZdfUyaa:b3xjwbm) ([raw file](https://github.com/pmem/pmem.github.io/blob/4eeff882f7d601bf1ea10c23e24e4370a7ff9935/_posts/2021/2021-09-17-concurrency.md#L32)):*
> ```Markdown
> ```
> 
> Let's analyze the values of pmem->a and pmem->b from a second thread perspective. If a crash happened during the application execution, the possible values on restart are:
> ```

the second thread
___
*[_posts/2021/2021-09-17-concurrency.md, line 102 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjnW05Y2VwUwy455df2:-MjnW05Y2VwUwy455df3:bv9kvkj) ([raw file](https://github.com/pmem/pmem.github.io/blob/4eeff882f7d601bf1ea10c23e24e4370a7ff9935/_posts/2021/2021-09-17-concurrency.md#L102)):*
> ```Markdown
> One other problem is that readers might suffer from the 'dirty reads' phenomenon. If a reader reads size variable while another thread modifies it inside a transaction, it reads uncommitted data. If a transaction aborts or a power failure happens, the size variable can be rolled back, and the reader's view of the data might be incorrect. In addition to that, the rollback itself is not thread-safe.
> 
> One possible solution is to make the global size volatile. The volatile variable can be modified using atomic instructions (after the transaction completes) while providing the number of elements in O(1) time. To restore the size on application restart, we can introduce a per-thread size variable that can be safely modified in a transaction. Per-thread sizes can be summed up to provide the actual size. Libpmemobj-cpp implements a helper data structure (which as of publish date of this blog post is not yet released as a public API) called [enumerable_thread_specific](https://pmem.io/libpmemobj-cpp/master/doxygen/classpmem_1_1detail_1_1enumerable__thread__specific.html). It provides API to request memory which will be private to a thread and iteration API. Enumerable thread-specific is used in concurrent_map and concurrent_hash_map to solve the shared state problem.
> ```

I don't understand how introducing per-thread size helps restore the size on restart.
___
*[_posts/2021/2021-09-17-concurrency.md, line 190 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjnXKt32feKcqjBQMt0:-MjnXKt32feKcqjBQMt1:b-v0qm0d) ([raw file](https://github.com/pmem/pmem.github.io/blob/4eeff882f7d601bf1ea10c23e24e4370a7ff9935/_posts/2021/2021-09-17-concurrency.md#L190)):*
> ```Markdown
> ```
> 
> Because `new_node` now resides on persistent memory, even if it is not linked to the list, it is always reachable on restart. There are no problems with dirty reads or visibility as `new_node` is never read during normal execution (only on recovery). If `push_back` would need to be thread-safe, `new_node` variable could be replaced with enumerable_thread_specific.
> ```

Maybe add a short summary that repeats the key points.


<!-- Sent from Reviewable.io -->

2021-09-17 12:47 UTC, igchor reviewed
Done.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160#-:-Mjnkql21GtyQgUkiK48:b-896fix)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor, @pbalcer, and @vinser52)

___
*[_posts/2021/2021-09-17-concurrency.md, line 10 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjnQ6z68_GM0zzoDFLy:-Mjnjsll0AB3co5JEdHF:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/4eeff882f7d601bf1ea10c23e24e4370a7ff9935/_posts/2021/2021-09-17-concurrency.md#L10)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

how does concurrent *access* make data consistency any harder?  I think you meant writes/mutation/modification.
</blockquote></details>

Done.
___
*[_posts/2021/2021-09-17-concurrency.md, line 14 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjnQac97a9ZnKthJQM3:-MjnlG5L4wH2e-SzGuAr:b-jiw0sg) ([raw file](https://github.com/pmem/pmem.github.io/blob/4eeff882f7d601bf1ea10c23e24e4370a7ff9935/_posts/2021/2021-09-17-concurrency.md#L14)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

This might be true on x86, but might not be on other architectures with weak ordering. I'd rephrase this a bit.
</blockquote></details>

Hm, would it be OK if I wrote that modification **might** be visible to other threads before it is persitsent? And for the example, I would write that the analysis is done for x86.
___
*[_posts/2021/2021-09-17-concurrency.md, line 32 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjnRToS21MSJZdfUya_:-Mjnlso31VueTXbRkdV0:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/4eeff882f7d601bf1ea10c23e24e4370a7ff9935/_posts/2021/2021-09-17-concurrency.md#L32)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

the second thread
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-17 12:51 UTC, pbalcer requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @igchor, @lukaszstolarczuk, @pbalcer, and @vinser52)

___
*[_posts/2021/2021-09-17-concurrency.md, line 14 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjnQac97a9ZnKthJQM3:-Mjnntad05QfTCB1rlSR:bve3bo9) ([raw file](https://github.com/pmem/pmem.github.io/blob/4eeff882f7d601bf1ea10c23e24e4370a7ff9935/_posts/2021/2021-09-17-concurrency.md#L14)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, would it be OK if I wrote that modification **might** be visible to other threads before it is persitsent? And for the example, I would write that the analysis is done for x86.
</blockquote></details>

yup, that's more accurate.


<!-- Sent from Reviewable.io -->

2021-09-17 14:15 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk, @pbalcer, and @vinser52)

___
*[_posts/2021/2021-09-17-concurrency.md, line 14 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjnQac97a9ZnKthJQM3:-Mjo0Zb9ClMGNZjTJoqG:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/4eeff882f7d601bf1ea10c23e24e4370a7ff9935/_posts/2021/2021-09-17-concurrency.md#L14)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

yup, that's more accurate.
</blockquote></details>

Done.
___
*[_posts/2021/2021-09-17-concurrency.md, line 102 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjnW05Y2VwUwy455df2:-Mjnxf8jAsRpR1sqXTw2:bfe0ucn) ([raw file](https://github.com/pmem/pmem.github.io/blob/4eeff882f7d601bf1ea10c23e24e4370a7ff9935/_posts/2021/2021-09-17-concurrency.md#L102)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

I don't understand how introducing per-thread size helps restore the size on restart.
</blockquote></details>

I rewrote this a bit and added extra example
___
*[_posts/2021/2021-09-17-concurrency.md, line 190 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjnXKt32feKcqjBQMt0:-MjnyuxH-_iiOkm9b2nH:b76gwur) ([raw file](https://github.com/pmem/pmem.github.io/blob/4eeff882f7d601bf1ea10c23e24e4370a7ff9935/_posts/2021/2021-09-17-concurrency.md#L190)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

Maybe add a short summary that repeats the key points.
</blockquote></details>

Done. I'm not good at writing summaries so let me know if you think this is OK or should I extend it or make something more clear ;d

Once the blog post describing concurrent data structures is done I will also add link to it.


<!-- Sent from Reviewable.io -->

2021-09-17 15:10 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160)* status: all files reviewed, 10 unresolved discussions (waiting on @igchor, @pbalcer, and @vinser52)

___
*[_posts/2021/2021-09-17-concurrency.md, line 108 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjoGvCcE3GsddfrPDei:-MjoGvCcE3GsddfrPDej:b-ms1q9l) ([raw file](https://github.com/pmem/pmem.github.io/blob/b7cc47e439a26d170f0a37c428568ec5a447929b/_posts/2021/2021-09-17-concurrency.md#L108)):*
> ```Markdown
> ```
> 
> Just as a reminder (more details can be found [here](https://pmem.io/2016/01/12/cpp-02.html))
> ```

since you're moving the links to the bottom, pls do this one as well
___
*[_posts/2021/2021-09-17-concurrency.md, line 153 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjoGipiD8pT2J_BJ8nn:-MjoGipiD8pT2J_BJ8no:bpwb9ct) ([raw file](https://github.com/pmem/pmem.github.io/blob/b7cc47e439a26d170f0a37c428568ec5a447929b/_posts/2021/2021-09-17-concurrency.md#L153)):*
> ```
> Since `diff` variable is per-thread,
> ```
you repeat it here, perhaps just `Since it is per-thread...`
___
*[_posts/2021/2021-09-17-concurrency.md, line 154 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjoGc8Q0ai8yZE5qwWQ:-MjoGc8Q0ai8yZE5qwWR:b-s6umrw) ([raw file](https://github.com/pmem/pmem.github.io/blob/b7cc47e439a26d170f0a37c428568ec5a447929b/_posts/2021/2021-09-17-concurrency.md#L154)):*
> ```Markdown
> variable which will track how many elements were inserted or deleted by a
> thread. Since `diff` variable is per-thread, it can be safely modified in a
> transaction. On recovery, all `diff` variables can be summed-up to provide
> ```

`to provide` is doubled
___
*[_posts/2021/2021-09-17-concurrency.md, line 177 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjoHYlR-5FrEBk2g5FT:-MjoHYlR-5FrEBk2g5FU:b-p441vx) ([raw file](https://github.com/pmem/pmem.github.io/blob/b7cc47e439a26d170f0a37c428568ec5a447929b/_posts/2021/2021-09-17-concurrency.md#L177)):*
> ```Markdown
>             ... // allocate new node and insert it at the end
> 
>             local_diff++;
> ```

`local_diff`?
___
*[_posts/2021/2021-09-17-concurrency.md, line 315 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjoI_4a4h0sp0zwk44v:-MjoI_4b8x55dwvYAp7I:b-4p3n70) ([raw file](https://github.com/pmem/pmem.github.io/blob/b7cc47e439a26d170f0a37c428568ec5a447929b/_posts/2021/2021-09-17-concurrency.md#L315)):*
> ```Markdown
> suggested approach for concurrent, lock-free pmemobj-based application is to
> store pointer to newly allocated memory to a private (possibly per-thread)
> persistent variable before making it visible for other threads.
> ```

that's quite a long sentence - consider splitting into 2


<!-- Sent from Reviewable.io -->

2021-09-20 13:19 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160)* status: all files reviewed, 10 unresolved discussions (waiting on @lukaszstolarczuk, @pbalcer, and @vinser52)

___
*[_posts/2021/2021-09-17-concurrency.md, line 108 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjoGvCcE3GsddfrPDei:-Mk2L4WzBLKT2_pdr2HZ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b7cc47e439a26d170f0a37c428568ec5a447929b/_posts/2021/2021-09-17-concurrency.md#L108)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

since you're moving the links to the bottom, pls do this one as well
</blockquote></details>

Done.
___
*[_posts/2021/2021-09-17-concurrency.md, line 153 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjoGipiD8pT2J_BJ8nn:-Mk2LB92EzFY-UC6cSfW:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b7cc47e439a26d170f0a37c428568ec5a447929b/_posts/2021/2021-09-17-concurrency.md#L153)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

> ```
> Since `diff` variable is per-thread,
> ```
you repeat it here, perhaps just `Since it is per-thread...`
</blockquote></details>

Done.
___
*[_posts/2021/2021-09-17-concurrency.md, line 154 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjoGc8Q0ai8yZE5qwWQ:-Mk2LMTXBV-i4ApqDJoW:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b7cc47e439a26d170f0a37c428568ec5a447929b/_posts/2021/2021-09-17-concurrency.md#L154)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`to provide` is doubled
</blockquote></details>

Done.
___
*[_posts/2021/2021-09-17-concurrency.md, line 177 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjoHYlR-5FrEBk2g5FT:-Mk2LPYf6GfTFayFeRWW:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b7cc47e439a26d170f0a37c428568ec5a447929b/_posts/2021/2021-09-17-concurrency.md#L177)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`local_diff`?
</blockquote></details>

Done.
___
*[_posts/2021/2021-09-17-concurrency.md, line 315 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MjoI_4a4h0sp0zwk44v:-Mk2M6-o86jjrf8AGhWb:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b7cc47e439a26d170f0a37c428568ec5a447929b/_posts/2021/2021-09-17-concurrency.md#L315)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

that's quite a long sentence - consider splitting into 2
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-20 13:40 UTC, lukaszstolarczuk reviewed
:+1: 

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160#-:-Mk2Qqm11dDg5PhoQzdI:b-8fx2u7)* status: all files reviewed, 5 unresolved discussions (waiting on @pbalcer and @vinser52)



<!-- Sent from Reviewable.io -->

2021-09-24 10:27 UTC, pbalcer requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor, @pbalcer, and @vinser52)

___
*[_posts/2021/2021-09-17-concurrency.md, line 305 at r7](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MkMKcJXBxEW0sLm4vnk:-MkMKcJY77qyeIa0ac3B:b-jffdxp) ([raw file](https://github.com/pmem/pmem.github.io/blob/697cefb849c18a8335694510e1c65db0b0438e38/_posts/2021/2021-09-17-concurrency.md#L305)):*
> ```Markdown
> on persistent memory.
> 
> The first one is the fact that data modification might be visible before becoming
> ```

Avoid using passive voice (https://developers.google.com/tech-writing/one/active-voice)

First, I discussed ...
Then, I moved on to 
And, finally, I talked about ...

(or 'we')


<!-- Sent from Reviewable.io -->

2021-09-24 12:39 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk, @pbalcer, and @vinser52)

___
*[_posts/2021/2021-09-17-concurrency.md, line 305 at r7](https://reviewable.io/reviews/pmem/pmem.github.io/160#-MkMKcJXBxEW0sLm4vnk:-MkMoFT598H8nvVnl36c:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/697cefb849c18a8335694510e1c65db0b0438e38/_posts/2021/2021-09-17-concurrency.md#L305)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

Avoid using passive voice (https://developers.google.com/tech-writing/one/active-voice)

First, I discussed ...
Then, I moved on to 
And, finally, I talked about ...

(or 'we')


</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-24 13:12 UTC, pbalcer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/160#-:-MkMvzvn3mSHn9uXAvh1:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @vinser52)



<!-- Sent from Reviewable.io -->

2021-09-24 13:13 UTC, merged