blog: add post with pmemstream introduction
pmem/pmem.github.io pull request #187
Opened 2022-01-03 12:29 UTC by lukaszstolarczuk

2022-01-04 10:32 UTC, KFilipek reviewed
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/187)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[content/blog/2022/pmemstream-intro.md, line 36 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MsZDnsy3QQRfKJ6xw80:-MsZDnsz58T3rl3Lcehn:bed0z0t) ([raw file](https://github.com/pmem/pmem.github.io/blob/e47d06b5874c364606a6bbf6debd3eb623e4b4cd/content/blog/2022/pmemstream-intro.md#L36)):*
> ```Markdown
> # What is (lib)pmemstream?
> 
> In a few words, libpmemstream is:
> ```

in every point of README.md is just `pmemstream`, also in heading, so I prefer to stick to pmemstream name.



_Code quote:_
```Markdown
libpmemstream
```
___
*[content/blog/2022/pmemstream-intro.md, line 37 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MsZDzK76iP_gL-yxVys:-MsZDzK76iP_gL-yxVyt:b-oxjr2j) ([raw file](https://github.com/pmem/pmem.github.io/blob/e47d06b5874c364606a6bbf6debd3eb623e4b4cd/content/blog/2022/pmemstream-intro.md#L37)):*
> ```Markdown
> 
> In a few words, libpmemstream is:
>  - a library (the "lib" part of the name),
> ```

Please drop this part



_Code quote:_
```Markdown
(the "lib" part of the name)
```
___
*[content/blog/2022/pmemstream-intro.md, line 39 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MsZE9MB6AHjlkq_ucZA:-MsZE9MB6AHjlkq_ucZB:bs12hh0) ([raw file](https://github.com/pmem/pmem.github.io/blob/e47d06b5874c364606a6bbf6debd3eb623e4b4cd/content/blog/2022/pmemstream-intro.md#L39)):*
> ```Markdown
>  - a library (the "lib" part of the name),
>  - optimized for persistent memory (the "pmem" part),
>  - providing logging data structure (the "stream" part).
> ```

stream and log terms have many differences, I prefer to not consider it here. pmemstream is close enough with stream processing, but only in name.



_Code quote:_
```Markdown
(the "stream" part)
```
___
*[content/blog/2022/pmemstream-intro.md, line 42 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MsZGqly3afKAEkMwgw8:-MsZGqlz2VyY9bXS_R7V:b27hmw5) ([raw file](https://github.com/pmem/pmem.github.io/blob/e47d06b5874c364606a6bbf6debd3eb623e4b4cd/content/blog/2022/pmemstream-intro.md#L42)):*
> ```Markdown
> 
> Like most libraries in PMDK family, this one also focuses on delivering a generic, easy-to-use
> set of functions. libpmemstream implements a persistent logging data structure and provides stream
> ```

it doesn't provide stream processing functionality and never will be



_Code quote:_
```Markdown
set of functions. libpmemstream implements a persistent logging data structure and provides stream
processing functionality. It presents a contiguous logical address space, divided into regions, with
```


<!-- Sent from Reviewable.io -->

2022-01-12 11:44 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/187)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[content/blog/2022/pmemstream-intro.md, line 44 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtD3oUE4PewrnyKuRg_:-MtD3oUE4PewrnyKuRga:bg0zdun) ([raw file](https://github.com/pmem/pmem.github.io/blob/a840582558c7e573fb18cea2ae9b97fdd480390f/content/blog/2022/pmemstream-intro.md#L44)):*
> ```Markdown
> access to data. It presents a contiguous logical address space, divided into regions, with
> log entries of arbitrary size. This library may be foundational for various higher-level solutions
> (example use cases are mentioned later in this blog post).
> ```

I think it would be good to extend this description a bit. You can write about the core features here:
- data can only be appended (no, modifications of data in the middle of stream)
- append is atomic (takes care of data consistency issues)
- iterators for reading data (they provide stream-like functionality)
___
*[content/blog/2022/pmemstream-intro.md, line 90 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtD4Uv90wvs0Gvhuzje:-MtD4Uv90wvs0Gvhuzjf:b-ecmpe6) ([raw file](https://github.com/pmem/pmem.github.io/blob/a840582558c7e573fb18cea2ae9b97fdd480390f/content/blog/2022/pmemstream-intro.md#L90)):*
> ```Markdown
>     Right now, all functions are "blocking", and we want to change it for better performance
>     and a more flexible user experience. It will also allow exposing different types of medium
>     underneath (e.g., block devices with higher latency).
> ```

... and DSA
___
*[content/blog/2022/pmemstream-intro.md, line 91 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtD4rGy3J61KG_2Bqc_:-MtD4rGy3J61KG_2Bqca:b5x58sb) ([raw file](https://github.com/pmem/pmem.github.io/blob/a840582558c7e573fb18cea2ae9b97fdd480390f/content/blog/2022/pmemstream-intro.md#L91)):*
> ```Markdown
>     and a more flexible user experience. It will also allow exposing different types of medium
>     underneath (e.g., block devices with higher latency).
> - RDMA support. The special case of async API is to enable copying data using RDMA protocol. We believe
> ```

Hm, If we'd like to use librpma it would be to expose "remote stream" - basically replace local memory with remote memory. This is not really replication.

"The special case of async API" - I'd remove this, what you have above ". It will also allow exposing different types of medium
    underneath (e.g., block devices with higher latency)." is better. You could just add that this different medium could be remote memory.


<!-- Sent from Reviewable.io -->

2022-01-12 14:03 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/187)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[content/blog/2022/pmemstream-intro.md, line 44 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtD3oUE4PewrnyKuRg_:-MtDZCpdD9aNDcs36fhW:b-n3olps) ([raw file](https://github.com/pmem/pmem.github.io/blob/a840582558c7e573fb18cea2ae9b97fdd480390f/content/blog/2022/pmemstream-intro.md#L44)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think it would be good to extend this description a bit. You can write about the core features here:
- data can only be appended (no, modifications of data in the middle of stream)
- append is atomic (takes care of data consistency issues)
- iterators for reading data (they provide stream-like functionality)
</blockquote></details>

I didn't want to add these still-changing features, but it makes sense to put here the core. Thx and done.
___
*[content/blog/2022/pmemstream-intro.md, line 90 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtD4Uv90wvs0Gvhuzje:-MtDL_QmAL8Jj8DGWKo1:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/a840582558c7e573fb18cea2ae9b97fdd480390f/content/blog/2022/pmemstream-intro.md#L90)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

... and DSA
</blockquote></details>

Done.
___
*[content/blog/2022/pmemstream-intro.md, line 91 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtD4rGy3J61KG_2Bqc_:-MtDZ6wNBRz8w6Z6jYSn:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/a840582558c7e573fb18cea2ae9b97fdd480390f/content/blog/2022/pmemstream-intro.md#L91)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, If we'd like to use librpma it would be to expose "remote stream" - basically replace local memory with remote memory. This is not really replication.

"The special case of async API" - I'd remove this, what you have above ". It will also allow exposing different types of medium
    underneath (e.g., block devices with higher latency)." is better. You could just add that this different medium could be remote memory.

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-14 10:50 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/187)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[content/blog/2022/pmemstream-intro.md, line 90 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtD4Uv90wvs0Gvhuzje:-MtNB_UYEYF2kdeGL9of:bi3msvp) ([raw file](https://github.com/pmem/pmem.github.io/blob/a840582558c7e573fb18cea2ae9b97fdd480390f/content/blog/2022/pmemstream-intro.md#L90)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'd put DSA as separate 'feature' which is enabled by Async API (it's not a different medium). So maybe something like: "... (e.g., block devices which higher latency) and using DSA for offloading data movement from the main thread"?


<!-- Sent from Reviewable.io -->

2022-01-14 11:02 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/187)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[content/blog/2022/pmemstream-intro.md, line 36 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MsZDnsy3QQRfKJ6xw80:-MtNCxX49A0C48F8apLo:bk6t981) ([raw file](https://github.com/pmem/pmem.github.io/blob/e47d06b5874c364606a6bbf6debd3eb623e4b4cd/content/blog/2022/pmemstream-intro.md#L36)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

but the official package name we deliver is called `libpmemstream` :wink: re-written
</blockquote></details>

For now, it's true only for RPM-based distros
___
*[content/blog/2022/pmemstream-intro.md, line 39 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MsZE9MB6AHjlkq_ucZA:-MtNEpEf5XrFW2Vv_dKb:blmrhvo) ([raw file](https://github.com/pmem/pmem.github.io/blob/e47d06b5874c364606a6bbf6debd3eb623e4b4cd/content/blog/2022/pmemstream-intro.md#L39)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure what do you mean.
</blockquote></details>

I mean that functionality of pmemstream does not intersect in any point with streams
___
*[content/blog/2022/pmemstream-intro.md, line 34 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNDfC94POjnw25J5E3:-MtNDfCA3dppUk5RxoZs:bvtzylx) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L34)):*
> ```Markdown
> ---
> 
> # What is (lib)pmemstream?
> ```

I proposed to drop `(lib)`, because we don't have such phrase in whole pmemstream/README.md



_Code quote:_
```Markdown
(lib)
```


<!-- Sent from Reviewable.io -->

2022-01-14 11:29 UTC, pbalcer requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/187)* status: all files reviewed, 22 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[content/blog/2022/pmemstream-intro.md, line 90 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtD4Uv90wvs0Gvhuzje:-MtNKhvY330Gchn1WkIG:b-8fx2u7) ([raw file](https://github.com/pmem/pmem.github.io/blob/a840582558c7e573fb18cea2ae9b97fdd480390f/content/blog/2022/pmemstream-intro.md#L90)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I'd put DSA as separate 'feature' which is enabled by Async API (it's not a different medium). So maybe something like: "... (e.g., block devices which higher latency) and using DSA for offloading data movement from the main thread"?
</blockquote></details>

:+1: 
___
*[content/blog/2022/pmemstream-intro.md, line 36 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtND4ZI-VY8t-9kFgpi:-MtND4ZI-VY8t-9kFgpj:b-xu5mpa) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L36)):*
> ```Markdown
> # What is (lib)pmemstream?
> 
> In a few words, (lib)pmemstream is a library:
> ```

I suggest removing the "in a few words" part, it doesn't add anything.
___
*[content/blog/2022/pmemstream-intro.md, line 38 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNDi6NCH7Pzv4hUi1I:-MtNDi6NCH7Pzv4hUi1J:b7edek5) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L38)):*
> ```Markdown
> In a few words, (lib)pmemstream is a library:
>  - optimized for persistent memory (the "pmem" part),
>  - providing logging data structure (the "stream" part).
> ```

or, simply:
'pmemstream is a library that provides a pmem-optimized log data structure'
___
*[content/blog/2022/pmemstream-intro.md, line 41 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNEVyFEAfy37RLBHTk:-MtNEVyFEAfy37RLBHTl:b-oqonjc) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L41)):*
> ```Markdown
> 
> Like most libraries in PMDK family, this one also focuses on delivering a generic, easy-to-use
> set of functions. pmemstream implements a persistent logging data structure and provides stream-like
> ```

second sentence here just repeats what you've included at the beginning.
___
*[content/blog/2022/pmemstream-intro.md, line 43 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNEj6S30q4uSZh31Xq:-MtNEj6S30q4uSZh31Xr:b-r70omq) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L43)):*
> ```Markdown
> set of functions. pmemstream implements a persistent logging data structure and provides stream-like
> access to data. It presents a contiguous logical address space, divided into regions, with
> log entries of arbitrary size. This library may be foundational for various higher-level solutions
> ```

We intend for this library to be a foundation for more complex higher-level solutions. Read on to learn about a few example use cases we have in mind.
___
*[content/blog/2022/pmemstream-intro.md, line 48 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNFHYi1YhFsz9XGyD7:-MtNFHYi1YhFsz9XGyD8:b-wv871m) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L48)):*
> ```Markdown
> Current implementation, examples, and known caveats are accessible at the [pmemstream GitHub page][pmemstream_gh].
> Please bear in mind this library is still in an early stage of development. As this is a work in progress,
> it may change the behavior or the API without any announcement or any backward compatibility assurance.
> ```

..., its behavior or APIs may change without prior notice.
___
*[content/blog/2022/pmemstream-intro.md, line 52 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNF_oz5ochFKfTTbAJ:-MtNF_oz5ochFKfTTbAK:b-vwdwxw) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L52)):*
> ```Markdown
> # Why we implement it?
> 
> Keen PMDK users should know by now - we already have [libpmemlog][pmemlog_pmem_io] in our portfolio.
> ```

As keen PMDK ..., ...

As some of you might know, we ...
___
*[content/blog/2022/pmemstream-intro.md, line 55 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNG83WDEp4_HHwz9vi:-MtNG83WDEp4_HHwz9vj:bo0ac6t) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L55)):*
> ```Markdown
> Even though it's very similar in basic concept, it's implemented in a straightforward manner and
> does not allow easy extensions. When you read our early rationale for creating libpmemstream -
> ["Feature Request" issue on PMDK's GitHub page][pmdk_feat_issue] - you'll see we wanted something more.
> ```

more what?
___
*[content/blog/2022/pmemstream-intro.md, line 66 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNGf919To-ansfq72d:-MtNGf928tWOpIAtFRHf:bh5uo9l) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L66)):*
> ```Markdown
> - PMEM-buffered file I/O primitives that offload to a slower medium.
> 
> We aim to deliver a set of functions with various parameters, so this library will be helpful in a wide range
> ```

so it's our intention to make sure that pmemstream is useful in a wide ...
___
*[content/blog/2022/pmemstream-intro.md, line 67 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNGK2TAZtz_fPJmNxI:-MtNGK2TAZtz_fPJmNxJ:bldcnhg) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L67)):*
> ```Markdown
> 
> We aim to deliver a set of functions with various parameters, so this library will be helpful in a wide range
> of use cases. We understand every developer would have to write many boilerplate lines of code to get a logging
> ```

it's not boilerplate. It's hard for me to come up with something that slots in the middle of this paragraph, but maybe:

"This will hopefully eliminate the need for software developers to create their own custom algorithms for many common patterns in storage and memory solutions, especially those that utilize PMem."
___
*[content/blog/2022/pmemstream-intro.md, line 76 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNIkf34mRQ8XskMRrE:-MtNIkf34mRQ8XskMRrF:b-ujoox0) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L76)):*
> ```Markdown
> - iterators allow reading data in sequence (they provide stream-like functionality).
> 
> We hope everyone can benefit from a ready-to-use library:
> ```

This list reads really oddly. Try to make it into a normal paragraph.
___
*[content/blog/2022/pmemstream-intro.md, line 77 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNIZPd-gkqPJJk1PMb:-MtNIZPd-gkqPJJk1PMc:b-28rrhd) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L77)):*
> ```Markdown
> 
> We hope everyone can benefit from a ready-to-use library:
> - it's delivered with a set of tests - we wanted to assure it's as error-prone as possible,
> ```

error-prone? did you mean error-proof?

i would just say "reliable"
___
*[content/blog/2022/pmemstream-intro.md, line 86 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNIze6Ce3LKYKMYOYA:-MtNIze6Ce3LKYKMYOYB:b-uond1u) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c5 [...]

2022-01-14 12:02 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/187)* status: all files reviewed, 24 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[content/blog/2022/pmemstream-intro.md, line 41 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNCKev5uPyPRvnLrN9:-MtNCKev5uPyPRvnLrNA:b-5p7z4o) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L41)):*
> ```Markdown
> 
> Like most libraries in PMDK family, this one also focuses on delivering a generic, easy-to-use
> set of functions. pmemstream implements a persistent logging data structure and provides stream-like
> ```

Pmemstream on the beginning of the sentence should be capitalized.
___
*[static/images/posts/pmemstream_intro.png, line 0 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNA_YU9HpDy8I-GROp:-MtNA_YU9HpDy8I-GROq:bq70e41) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/static/images/posts/pmemstream_intro.png#L0)):*
This picture seems to have to low resolution. On preview it looks little bit blurry at 100% render size (Firefox)


<!-- Sent from Reviewable.io -->

2022-01-14 13:05 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/187)* status: all files reviewed, 24 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[static/images/posts/pmemstream_intro.png, line  at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNA_YU9HpDy8I-GROp:-MtNfmX_ASJXnxLJLx4a:bitqski) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/static/images/posts/pmemstream_intro.png#L)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

This picture seems to have to low resolution. On preview it looks little bit blurry at 100% render size (Firefox)
</blockquote></details>

On my Firefox looks quite normal, better than pmemstream page in my case (Fedora) xD


<!-- Sent from Reviewable.io -->

2022-01-21 10:21 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/187)* status: 0 of 2 files reviewed, 24 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @pbalcer)

___
*[content/blog/2022/pmemstream-intro.md, line 36 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MsZDnsy3QQRfKJ6xw80:-MtvrZjQCsjU3-jhFyAS:bffwy9c) ([raw file](https://github.com/pmem/pmem.github.io/blob/e47d06b5874c364606a6bbf6debd3eb623e4b4cd/content/blog/2022/pmemstream-intro.md#L36)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

For now, it's true only for RPM-based distros
</blockquote></details>

nope, it's the same name for Ubuntu as well.
___
*[content/blog/2022/pmemstream-intro.md, line 39 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MsZE9MB6AHjlkq_ucZA:-MtvryBn-Sot0_0a0IYI:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/e47d06b5874c364606a6bbf6debd3eb623e4b4cd/content/blog/2022/pmemstream-intro.md#L39)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I mean that functionality of pmemstream does not intersect in any point with streams
</blockquote></details>

Done.
___
*[content/blog/2022/pmemstream-intro.md, line 90 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtD4Uv90wvs0Gvhuzje:-Mtw4ofvAuDEhJza_h9m:bvd4gio) ([raw file](https://github.com/pmem/pmem.github.io/blob/a840582558c7e573fb18cea2ae9b97fdd480390f/content/blog/2022/pmemstream-intro.md#L90)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done, I hope.
___
*[content/blog/2022/pmemstream-intro.md, line 34 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNDfC94POjnw25J5E3:-MtvrYiA66Z54jhM_7UQ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L34)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I proposed to drop `(lib)`, because we don't have such phrase in whole pmemstream/README.md
</blockquote></details>

Done.
___
*[content/blog/2022/pmemstream-intro.md, line 36 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtND4ZI-VY8t-9kFgpi:-MtvroKHESW05Qhf53WS:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L36)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

I suggest removing the "in a few words" part, it doesn't add anything.
</blockquote></details>

Done.
___
*[content/blog/2022/pmemstream-intro.md, line 38 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNDi6NCH7Pzv4hUi1I:-MtvsAMN7ikGfDHpeSl5:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L38)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

or, simply:
'pmemstream is a library that provides a pmem-optimized log data structure'
</blockquote></details>

Done.
___
*[content/blog/2022/pmemstream-intro.md, line 41 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNEVyFEAfy37RLBHTk:-MtvsUksDH1qVOyx_Cpr:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L41)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

second sentence here just repeats what you've included at the beginning.
</blockquote></details>

Done.
___
*[content/blog/2022/pmemstream-intro.md, line 41 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNCKev5uPyPRvnLrN9:-MtvsVg7-nu75zw9U8hf:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L41)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Pmemstream on the beginning of the sentence should be capitalized.
</blockquote></details>

Done.
___
*[content/blog/2022/pmemstream-intro.md, line 43 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNEj6S30q4uSZh31Xq:-MtvtCDkCxdyui-VGSWN:bet6881) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L43)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

We intend for this library to be a foundation for more complex higher-level solutions. Read on to learn about a few example use cases we have in mind.
</blockquote></details>

Done. That's much better, thx
___
*[content/blog/2022/pmemstream-intro.md, line 48 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNFHYi1YhFsz9XGyD7:-MtvtXleAQxRxY8XZLfQ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L48)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

..., its behavior or APIs may change without prior notice.
</blockquote></details>

Done.
___
*[content/blog/2022/pmemstream-intro.md, line 52 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNF_oz5ochFKfTTbAJ:-Mtvtlzg7vgRQS8so0k3:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L52)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

As keen PMDK ..., ...

As some of you might know, we ...


</blockquote></details>

Done.
___
*[content/blog/2022/pmemstream-intro.md, line 55 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNG83WDEp4_HHwz9vi:-Mtvu5u2-fYbFgDlXiCm:b2ut8q7) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L55)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

more what?
</blockquote></details>

hmm... I guess you can just say "I want something more." :wink: 

Nonetheless, re-phrased.
___
*[content/blog/2022/pmemstream-intro.md, line 66 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNGf919To-ansfq72d:-Mtvvyha9x3P6WypDG3Q:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L66)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

so it's our intention to make sure that pmemstream is useful in a wide ...
</blockquote></details>

Done.
___
*[content/blog/2022/pmemstream-intro.md, line 67 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNGK2TAZtz_fPJmNxI:-MtvxS3I7LeYnHdIzhsq:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L67)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

it's not boilerplate. It's hard for me to come up with something that slots in the middle of this paragraph, but maybe:

"This will hopefully eliminate the need for software developers to create their own custom algorithms for many common patterns in storage and memory solutions, especially those that utilize PMem."


</blockquote></details>

Done.
___
*[content/blog/2022/pmemstream-intro.md, line 76 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MtNIkf34mRQ8XskMRrE:-Mtvxsya-dVi-Lv-ydqG:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/c607d03f29c52937c6ccf3c30c19d6bc7423349d/content/blog/2022/pmemstream-intro.md#L76)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

This list reads re [...]

2022-01-21 11:33 UTC, igchor reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/187#-:-MtwOfaS1WNmUrhgHv_u:bnfp4nl)* status: 0 of 2 files reviewed, 24 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @pbalcer)



<!-- Sent from Reviewable.io -->

2022-01-25 13:43 UTC, KFilipek reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/187#-:-MuGTWOB8lYnWMzIfy5W:bnfp4nl)* status: all files reviewed, 20 unresolved discussions (waiting on @karczex and @pbalcer)



<!-- Sent from Reviewable.io -->

2022-01-25 15:29 UTC, pbalcer requested changes
mostly lgtm, just a few minor nits.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/187#-:-MuGqYFc3DQXO52ENHno:b-u0zc67)* status: all files reviewed, 7 unresolved discussions (waiting on @karczex, @lukaszstolarczuk, and @pbalcer)

___
*[content/blog/2022/pmemstream-intro.md, line 6 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MuGp0XX8TlGKRWL4MqU:-MuGp0XX8TlGKRWL4MqV:bwpztuj) ([raw file](https://github.com/pmem/pmem.github.io/blob/d6070b50468299e0f874d57a8b7585b4dd309d19/content/blog/2022/pmemstream-intro.md#L6)):*
> ```Markdown
> 
> # Blog post creation date
> date: 2022-01-21
> ```

Please update this. I'll merge this immediately after you update the PR.
___
*[content/blog/2022/pmemstream-intro.md, line 50 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MuGpMeI8573Zor7oZkK:-MuGpMeI8573Zor7oZkL:b-nfsscz) ([raw file](https://github.com/pmem/pmem.github.io/blob/d6070b50468299e0f874d57a8b7585b4dd309d19/content/blog/2022/pmemstream-intro.md#L50)):*
> ```Markdown
> As keen PMDK users should know by now, we already have [libpmemlog][pmemlog_pmem_io] in our portfolio.
> Even though it's very similar in basic concept, it's implemented in a straightforward manner and
> does not allow easy extensions. Provided we couldn't easily add all new features to the libpmemlog
> ```

Because we couldn't
___
*[content/blog/2022/pmemstream-intro.md, line 51 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MuGpQrX2-BNc8IBf5x9:-MuGpQrX2-BNc8IBf5xA:b-bkkbd) ([raw file](https://github.com/pmem/pmem.github.io/blob/d6070b50468299e0f874d57a8b7585b4dd309d19/content/blog/2022/pmemstream-intro.md#L51)):*
> ```Markdown
> Even though it's very similar in basic concept, it's implemented in a straightforward manner and
> does not allow easy extensions. Provided we couldn't easily add all new features to the libpmemlog
> we decided to design it from scratch. If you're interested in our early rationale for creating
> ```

design something new from scratch
___
*[content/blog/2022/pmemstream-intro.md, line 62 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MuGpZES9VLf3sj_Q6Qy:-MuGpZES9VLf3sj_Q6Qz:bukfynr) ([raw file](https://github.com/pmem/pmem.github.io/blob/d6070b50468299e0f874d57a8b7585b4dd309d19/content/blog/2022/pmemstream-intro.md#L62)):*
> ```Markdown
> - PMEM-buffered file I/O primitives that offload to a slower medium.
> 
> We aim to deliver a set of functions with various parameters. Our intention was to ensure that pmemstream is
> ```

our intention is


<!-- Sent from Reviewable.io -->

2022-01-26 15:07 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/187)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @karczex, @KFilipek, and @pbalcer)

___
*[content/blog/2022/pmemstream-intro.md, line 6 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MuGp0XX8TlGKRWL4MqU:-MuLul0L7mSovpWFUL7d:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/d6070b50468299e0f874d57a8b7585b4dd309d19/content/blog/2022/pmemstream-intro.md#L6)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

Please update this. I'll merge this immediately after you update the PR.
</blockquote></details>

Done.
___
*[content/blog/2022/pmemstream-intro.md, line 50 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MuGpMeI8573Zor7oZkK:-MuLuriJ9IeUco3M5lZN:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/d6070b50468299e0f874d57a8b7585b4dd309d19/content/blog/2022/pmemstream-intro.md#L50)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

Because we couldn't
</blockquote></details>

Done.
___
*[content/blog/2022/pmemstream-intro.md, line 51 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MuGpQrX2-BNc8IBf5x9:-MuLv-981vcYkllUOWjt:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/d6070b50468299e0f874d57a8b7585b4dd309d19/content/blog/2022/pmemstream-intro.md#L51)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

design something new from scratch
</blockquote></details>

Done.
___
*[content/blog/2022/pmemstream-intro.md, line 62 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/187#-MuGpZES9VLf3sj_Q6Qy:-MuLv4sd0FXuw2i6JSdE:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/d6070b50468299e0f874d57a8b7585b4dd309d19/content/blog/2022/pmemstream-intro.md#L62)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

our intention is
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-26 15:09 UTC, merged