memory tiering part 1 blog post
pmem/pmem.github.io pull request #250
Opened 2022-06-14 12:16 UTC by bratpiorka

Preview: https://bratpiorka.github.io/blog//2022/06/memory-tiering-part-1/

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/250)

2022-06-17 08:32 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/250)* status: 0 of 6 files reviewed, 31 unresolved discussions (waiting on @bratpiorka and @lukaszstolarczuk)

___
*[`content/blog/2022/tiering-1.md` line 117 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4bvUEs6K6RLiO9mrk7:-N4bvUEs6K6RLiO9mrk8:b-2a5ijz) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L117)):*
> ```Markdown
> Memory tiering is about the distribution of allocations among all (or selected) 
> memory tiers in an application-aware manner. In this series of blog posts, 
> we will be classifying different types of memory tiering types depending on the scale 
> ```

`different types of memory tiering types` - doubled "types"
___
*[`content/blog/2022/tiering-1.md` line 118 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4bvcFF9N0vRAwLGGeD:-N4bvcFF9N0vRAwLGGeE:ba5xbg5) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L118)):*
> ```Markdown
> memory tiers in an application-aware manner. In this series of blog posts, 
> we will be classifying different types of memory tiering types depending on the scale 
> of changes to the application code:
> ```

changes required to apply to an application code (?)
___
*[`content/blog/2022/tiering-1.md` line 121 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4bwBIXAEUCQvPftez2:-N4bwBIXAEUCQvPftez3:b-t3nq1z) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L121)):*
> ```Markdown
> 
> * explicit tiering (e.g. using libnuma or Memkind API) - where the application is aware 
> of the existence of NUMA nodes with different properties and fully manages the target 
> ```

and it
___
*[`content/blog/2022/tiering-1.md` line 140 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4kfypb1K25ieMWUL9E:-N4kfypc0XxwiwJ8vLpo:b-iwjwqx) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L140)):*
> ```Markdown
> must set the tiering properties through configuration files or environment variables.
> 
> We will address explicit tiering and, partially, explicit auto-tiering later in this blog note.
> ```

`address`? maybe "describe in more detail"? or something similar
___
*[`content/blog/2022/tiering-1.md` line 140 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4kg8nK5xOeXkQEW7Wt:-N4kg8nK5xOeXkQEW7Wu:bmibups) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L140)):*
> ```Markdown
> must set the tiering properties through configuration files or environment variables.
> 
> We will address explicit tiering and, partially, explicit auto-tiering later in this blog note.
> ```

`later in this blog note`, maybe just "below" :wink: 
___
*[`content/blog/2022/tiering-1.md` line 146 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4kj3wmAWL9SQMZflN3:-N4kj3wmAWL9SQMZflN4:bzf5lxu) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L146)):*
> ```Markdown
> ### Simple algorithm that keeps target DRAM:PMEM ratio
> 
> To partially eliminate the above problems, the user can change the application code 
> ```

"the above problems"? maybe "problems described above" 
___
*[`content/blog/2022/tiering-1.md` line 150 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4kjrbQ0b477TZI-2ol:-N4kjrbQ0b477TZI-2om:bgx8be6) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L150)):*
> ```Markdown
> the allocator can count how much data has been placed on each tier and 
> avoid/select those tiers whose occupancy differs from the level 
> defined by the ratio. In this way, you can both control the ratio of memory 
> ```

`This way, ...`
___
*[`content/blog/2022/tiering-1.md` line 150 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4kjuNSAfaNfXoxA2kT:-N4kjuNSAfaNfXoxA2kU:b-ymt6lh) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L150)):*
> ```Markdown
> the allocator can count how much data has been placed on each tier and 
> avoid/select those tiers whose occupancy differs from the level 
> defined by the ratio. In this way, you can both control the ratio of memory 
> ```

few lines back you wrote "the user" now "you" - pls pick one
___
*[`content/blog/2022/tiering-1.md` line 151 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4kk8Od4E5kaIvLpgql:-N4kk8Od4E5kaIvLpgqm:b-uwpbvp) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L151)):*
> ```Markdown
> avoid/select those tiers whose occupancy differs from the level 
> defined by the ratio. In this way, you can both control the ratio of memory 
> resource usage and average the latency of data accesses.
> ```

"average"? "balance" or "level (out)"
___
*[`content/blog/2022/tiering-1.md` line 190 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4klg_R9FWqRriErPkw:-N4klg_R9FWqRriErPkx:bdxbr0c) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L190)):*
> ```Markdown
> to always keep some data on the medium offering the fastest access 
> but has no requirements for the access speed to the remaining data. 
> The Memkind library is ideally suited for such a scenario: for data requiring 
> ```

maybe finish this part early - "... for such a scenario."
___
*[`content/blog/2022/tiering-1.md` line 191 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4klJv61ebI1QAXg1SB:-N4klJv61ebI1QAXg1SC:b-zcbido) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L191)):*
> ```Markdown
> but has no requirements for the access speed to the remaining data. 
> The Memkind library is ideally suited for such a scenario: for data requiring 
> access with the lowest latency, the author chooses the “lowest latency” memory kind, 
> ```

"the author"?
___
*[`content/blog/2022/tiering-1.md` line 194 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4kldK_5-mrp_80SXTt:-N4kldK_5-mrp_80SXTu:bj1n3cs) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L194)):*
> ```Markdown
> and for the remaining data creates its own type of auto-tiered kind 
> (using internal API) based on one of the policies offered by Memkind, 
> such as “static ratio” or “dynamic threshold”. Below is an example of how to do that:
> ```

this sentence is quite long
___
*[`content/blog/2022/tiering-1.md` line 226 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4kiBD22xZPGfi6yIPh:-N4kiBD22xZPGfi6yIPi:bbtc35x) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L226)):*
> ```Markdown
> 
> [redis-github]: https://github.com/redis/redis
> [cxl-blog]: https://pmem.io/blog/2022/01/disaggregated-memory-in-pursuit-of-scale-and-efficiency
> ```

you can drop "https://pmem.io/" part from all "local" links :wink: 


<!-- Sent from Reviewable.io -->

2022-06-20 11:00 UTC, bratpiorka reviewed
build and deploy works but I'm not sure about the link :)

> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/250#-:-N5-lCy04wq2Z-3BPBAF:b-s7zd2c)* status: all files reviewed, 31 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`content/blog/2022/tiering-1.md` line 36 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4aXzsQ0NlxQboEQwKi:-N5-V8ESE-Cr3OBIPqHq:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L36)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`an in-memory ...`
</blockquote></details>

Done.



_Code quote:_
```Markdown
thub] (in-memory k
```
___
*[`content/blog/2022/tiering-1.md` line 36 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4aY4Tu7XdQOorLbQ7R:-N5-VS2-CQUpqLZ9DCxT:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L36)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

almost each line ends with a white space, pls remove
</blockquote></details>

Done.
___
*[`content/blog/2022/tiering-1.md` line 38 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4aYDVJ17TeR8gb8n3P:-N5-VWIbB2COflTPsw5t:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

doubled "DRAM" :wink: 
</blockquote></details>

Done.



_Code quote:_
```Markdown
e expensive and has limited DRAM capacity, so 
```
___
*[`content/blog/2022/tiering-1.md` line 38 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4aYHzy280Rr0IrYXQa:-N5-d7tZ5hntXCE2_LyT:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`the solution`? perhaps `a solution we propose in this blog post`...?
</blockquote></details>

Done.
___
*[`content/blog/2022/tiering-1.md` line 39 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4aYVvJEkqbYjKwMtRB:-N5-dt7s-4WbsG8RPdTv:b-9z9tb) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L39)):*
> In the future  other types 

I tried to make separate sentence from this but I couldn't figure out better version than current
___
*[`content/blog/2022/tiering-1.md` line 41 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4aYmnh9kecJP13Lpm9:-N5-VbH4-fxtGY2Dv29l:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L41)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

misspell configure
</blockquote></details>

Done.



_Code quote:_
```Markdown
u [onfigure PMEM
```
___
*[`content/blog/2022/tiering-1.md` line 41 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4aYqFzDaB4u43Rx5Z1:-N5-VeUj8xC9qfPNMq8t:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L41)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`to KMEM DAX`? not `as KMEM DAX`?
</blockquote></details>

Done.
___
*[`content/blog/2022/tiering-1.md` line 48 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4aZMTS82hmsQvo-hYK:-N5-VmtcCYDTMtga5p9L:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L48)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`(it can be influenced, e.g., by mbind)`
</blockquote></details>

Done.
___
*[`content/blog/2022/tiering-1.md` line 48 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4aZWLb0Ln98NZ3OxwM:-N5-X1Ds51x9UUPh0Sqp:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L48)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. by the/a distance
2. distance between what
</blockquote></details>

Done.
___
*[`content/blog/2022/tiering-1.md` line 49 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4a_jVp6IcADXqOeKpU:-N5-XDAo0pxyQtMVtD8I:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L49)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe you can use "numactl -H" not only on multi-socket machines, but it could be tricky/hard to do that - pls rephrase
</blockquote></details>

Done.
___
*[`content/blog/2022/tiering-1.md` line 50 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4a_p1c95zGpJd3Ix3I:-N5-XHIJ5GDZa3xU7Ikw:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L50)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls make it like this: \`numactl -H\`, not using a " * "
</blockquote></details>

Done.
___
*[`content/blog/2022/tiering-1.md` line 51 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4aa7wd4gmbXbG69Vpw:-N5-ecHq0we45_ckDWyF:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L51)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'd add some sentence like "let's consider an example
</blockquote></details>

Done.
___
*[`content/blog/2022/tiering-1.md` line 86 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4aaMOo7aD41GcwHq1i:-N5-f3Fy-14W1kPUe36L:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L86)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

since you have a separate section for these 2 downsides, I believe you can drop (or move) the part from " in the scenario..."
</blockquote></details>

Done.



_Code quote:_
```Markdown
d unpredictable resource assignment in the scenario, where multiple applicati
```
___
*[`content/blog/2022/tiering-1.md` line 91 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4aaWrF3uXLWKmUgItq:-N5-XMkT2E9U92tFRtPQ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L91)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Let's suppose
</blockquote></details>

Done.



_Code quote:_
```Markdown
uppose our applicati
```
___
*[`content/blog/2022/tiering-1.md` line 103 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4aahxi45CcmTtI8QBe:-N5-XPzk9Xk1aQlVTQWR:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L103)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

of a 
</blockquote></details>

Done.



_Code quote:_
```Markdown
hen the system is running more than one instan
```
___
*[`content/blog/2022/tiering-1.md` line 104 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/2 [...]

2022-06-20 15:17 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/250)* status: all files reviewed, 45 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, and @pbalcer)

___
*[`content/blog/2022/tiering-1.md` line 108 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N50S-QOD61GJoBiGFlP:-N50bqZy7juieksTh5BC:b45h) ([raw file](https://github.com/pmem/pmem.github.io/blob/1428bb4548ff92580560a35ff5796e45b55a7966/content/blog/2022/tiering-1.md#L108)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

`instance` is typically used in reference to virtual machines. maybe say `processes`?
</blockquote></details>


___
*[`content/blog/2022/tiering-1.md` line 122 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N50SlraEvNwmJYAVoPB:-N50cgzFEUpdcf5FrFzh:b45h) ([raw file](https://github.com/pmem/pmem.github.io/blob/1428bb4548ff92580560a35ff5796e45b55a7966/content/blog/2022/tiering-1.md#L122)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

best performing mode?
</blockquote></details>


___
*[`content/blog/2022/tiering-1.md` line 165 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N50Tq9z6Q3Nf_4ug_m6:-N50czJU7I9iS6t9QnR-:b45h) ([raw file](https://github.com/pmem/pmem.github.io/blob/1428bb4548ff92580560a35ff5796e45b55a7966/content/blog/2022/tiering-1.md#L165)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

This is not unfortunate. This is just how it works.
</blockquote></details>




<!-- Sent from Reviewable.io -->

2022-06-20 15:17 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/250)* status: all files reviewed, 45 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, and @pbalcer)

___
*[`content/blog/2022/tiering-1.md` line 42 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N50PGSCDP-mvN6bO3JD:-N50g9v3DDsBCPP_DqEY:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/1428bb4548ff92580560a35ff5796e45b55a7966/content/blog/2022/tiering-1.md#L42)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

You mentioned memory mode but never expanded on that.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-20 15:20 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/250)* status: all files reviewed, 45 unresolved discussions (waiting on @lukaszstolarczuk and @pbalcer)

___
*[`content/blog/2022/tiering-1.md` line 37 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N50P0Jf1In-CqPI_BQc:-N50gpVaB-oe0QHwzgfQ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/1428bb4548ff92580560a35ff5796e45b55a7966/content/blog/2022/tiering-1.md#L37)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

`Since fast access is essential for them, ...`
</blockquote></details>

Done.
___
*[`content/blog/2022/tiering-1.md` line 96 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N50QaA1-K898hGuMs9F:-N50gb_jCSUUrQktKZ5C:b-nlf0ib) ([raw file](https://github.com/pmem/pmem.github.io/blob/1428bb4548ff92580560a35ff5796e45b55a7966/content/blog/2022/tiering-1.md#L96)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

I don't understand what this sentence means.
</blockquote></details>

rephrased 
___
*[`content/blog/2022/tiering-1.md` line 98 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N50QoU8DWdePpL4Sej9:-N50bUCY6tavr3IHL3Tu:b-no9x65) ([raw file](https://github.com/pmem/pmem.github.io/blob/1428bb4548ff92580560a35ff5796e45b55a7966/content/blog/2022/tiering-1.md#L98)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

the high/low thing is confusing to me :)

Maybe something like this: "It may turn out that the kernel has placed the hot data on a low-performance (high-latency) numa node, and the cold data on high-performance (low-latency) one. Which is the opposite of what we want" ?

</blockquote></details>

rephrased
___
*[`content/blog/2022/tiering-1.md` line 116 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N50SB3O-ay6aR5jVt2S:-N50c_NW6iK0h1uF9-QD:b-hfpv0l) ([raw file](https://github.com/pmem/pmem.github.io/blob/1428bb4548ff92580560a35ff5796e45b55a7966/content/blog/2022/tiering-1.md#L116)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

what do you mean by application-aware?

The kernel doesn't know anything about the application, just that there are some pages. Maybe workload-aware?

</blockquote></details>

removed
___
*[`content/blog/2022/tiering-1.md` line 167 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N50TujUAvxxdH67zgyb:-N50gl7NDORk5iI82dDl:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/1428bb4548ff92580560a35ff5796e45b55a7966/content/blog/2022/tiering-1.md#L167)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

glibc library, because it operates on whole pages.
</blockquote></details>

Done.
___
*[`content/blog/2022/tiering-1.md` line 174 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N50U5SeCA6nwKHgtx0Q:-N50gkP97uYVb85K1YJ8:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/1428bb4548ff92580560a35ff5796e45b55a7966/content/blog/2022/tiering-1.md#L174)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

library allows allocating
</blockquote></details>

Done.
___
*[`content/blog/2022/tiering-1.md` line 176 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N50UN3oDCN56PeYfTlz:-N50glwR95Z1NUpAWgPT:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/1428bb4548ff92580560a35ff5796e45b55a7966/content/blog/2022/tiering-1.md#L176)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

drop 'mostly'
</blockquote></details>

Done.
___
*[`content/blog/2022/tiering-1.md` line 179 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N50USji1TkGmUixJ3-t:-N50gmng1viPV0i5_2gR:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/1428bb4548ff92580560a35ff5796e45b55a7966/content/blog/2022/tiering-1.md#L179)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

tiers .. tiers
</blockquote></details>

Done.
___
*[`content/blog/2022/tiering-1.md` line 180 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N50UW2s12myENxeqtr9:-N50gnKlCdANQROkn9hq:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/1428bb4548ff92580560a35ff5796e45b55a7966/content/blog/2022/tiering-1.md#L180)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

appropriate appropriate
</blockquote></details>

Done.
___
*[`content/blog/2022/tiering-1.md` line 182 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N50UZn43lzEz17nNbdw:-N50go4y5Am8d2KzjQoL:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/1428bb4548ff92580560a35ff5796e45b55a7966/content/blog/2022/tiering-1.md#L182)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

Notably, 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-21 08:50 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/250)* status: all files reviewed, 32 unresolved discussions (waiting on @lukaszstolarczuk and @pbalcer)

___
*[`content/blog/2022/tiering-1.md` line 169 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N54OEa85BrHObWIvkcC:-N54RxG7EU3WjlENLEFT:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/007846561b3326973cd075848adf659ee7c50a41/content/blog/2022/tiering-1.md#L169)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

just drop this sentence entirely.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-21 13:34 UTC, lukaszstolarczuk reviewed
hmm your CI is still not executed...?

https://github.com/bratpiorka/pmem.github.io/actions/workflows/gh-pages.yml

deployment should have happened and you should have the link to your own pmem.io webpage, like mine: https://lukaszstolarczuk.github.io/

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/250#-:-N55Szbw54GWwc9nhuHo:b-m5maqf)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @pbalcer)

___
*[`content/blog/2022/tiering-1.md` line 39 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N4aYVvJEkqbYjKwMtRB:-N55NtQs47VMdpHJBkDl:be77ye6) ([raw file](https://github.com/pmem/pmem.github.io/blob/b79bb68af0661ae05e7bcdd0ed16202a79b4e57f/content/blog/2022/tiering-1.md#L39)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

> In the future  other types 

I tried to make separate sentence from this but I couldn't figure out better version than current
</blockquote></details>

maybe it's all right :)
___
*[`content/blog/2022/tiering-1.md` line 39 at r5](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N55OFkFD_LpjWiKA6fy:-N55OFkFD_LpjWiKA6fz:b-q9mn1a) ([raw file](https://github.com/pmem/pmem.github.io/blob/1df62ca8ebf11a9226f48987fe25b6ab61cd83aa/content/blog/2022/tiering-1.md#L39)):*
> ```Markdown
> Since fast access is essential for them, they use DRAM to store their data.
> DRAM is quite expensive and has limited capacity, so a solution we propose in this blog post is to use PMEM
> (and in the future other types of memory available through CXL - see pmem.io blog post about it [here][cxl-blog]).
> ```

hmm maybe instead of writing "here" you can make a longer description for this link, e.g., `see a [pmem.io blog post about it][...]).`
___
*[`content/blog/2022/tiering-1.md` line 168 at r5](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N55S3YG6TtIYE3EbVaF:-N55S3YG6TtIYE3EbVaG:b-xduga7) ([raw file](https://github.com/pmem/pmem.github.io/blob/1df62ca8ebf11a9226f48987fe25b6ab61cd83aa/content/blog/2022/tiering-1.md#L168)):*
> ```Markdown
> and decide which data suits best which NUMA node. What is important,
> functions allocating on specific NUMA nodes are relatively slow compared
> to their counterparts from the standard glibc library, because it operates on whole pages.
> ```

they operate


<!-- Sent from Reviewable.io -->

2022-06-21 14:35 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/250)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk and @pbalcer)

___
*[`content/blog/2022/tiering-1.md` line 39 at r5](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N55OFkFD_LpjWiKA6fy:-N55W51r3oaNp0AH73UV:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/5e454cbdeb9d63a232e121432b45a0126db08d77/content/blog/2022/tiering-1.md#L39)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm maybe instead of writing "here" you can make a longer description for this link, e.g., `see a [pmem.io blog post about it][...]).`
</blockquote></details>

Done.
___
*[`content/blog/2022/tiering-1.md` line 168 at r5](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N55S3YG6TtIYE3EbVaF:-N55Vwu_8r-WU19VCKGV:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/5e454cbdeb9d63a232e121432b45a0126db08d77/content/blog/2022/tiering-1.md#L168)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

they operate
</blockquote></details>

Done.



_Code quote:_
```Markdown
brary, because it operates on who
```


<!-- Sent from Reviewable.io -->

2022-06-22 07:09 UTC, lukaszstolarczuk reviewed
> Reviewed 5 of 6 files at r1, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/250)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @pbalcer)

___
*[`content/blog/2022/tiering-1.md` line 39 at r5](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N55OFkFD_LpjWiKA6fy:-N59ALP4CrmHKO9mV0Jw:b-kqeoq7) ([raw file](https://github.com/pmem/pmem.github.io/blob/5e454cbdeb9d63a232e121432b45a0126db08d77/content/blog/2022/tiering-1.md#L39)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx, but you have now double `]]`

BTW, I think, not the latest version is deployed into your fork :wink: 
___
*[`content/blog/2022/tiering-1.md` line 42 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N59E8gG5EULbvCQbGge:-N59E8gG5EULbvCQbGgf:b-i4x8qd) ([raw file](https://github.com/pmem/pmem.github.io/blob/c6d88be4c676d5222c13e6305459f5cbd74cfc65/content/blog/2022/tiering-1.md#L42)):*
> ```Markdown
> PMEM can be used in two modes - [Memory Mode][memory-mode] and [App Direct][app-direct]. In Memory Mode,
> user sees DRAM and PMEM memory as single, combined memory node. In App Direct mode,
> when you [configure PMEM as KMEM DAX][kmem-dax], the PMEM memory will be directly available in the system and visible
> ```

the last `you` in the blog post :wink: the rest is now changed to "user", so perhaps, please update this as well


<!-- Sent from Reviewable.io -->

2022-06-22 08:13 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/250)* status: all files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @pbalcer)

___
*[`content/blog/2022/tiering-1.md` line 42 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N59E8gG5EULbvCQbGge:-N59T8GK8QHnKqhLx2lp:b-3dvw3h) ([raw file](https://github.com/pmem/pmem.github.io/blob/c6d88be4c676d5222c13e6305459f5cbd74cfc65/content/blog/2022/tiering-1.md#L42)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

heh, user configure**s** :smile_cat: 


<!-- Sent from Reviewable.io -->

2022-06-22 08:31 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/250)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk and @pbalcer)

___
*[`content/blog/2022/tiering-1.md` line 42 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N59E8gG5EULbvCQbGge:-N59XE-9B-r2ybeUkMSr:b7ujhrz) ([raw file](https://github.com/pmem/pmem.github.io/blob/c6d88be4c676d5222c13e6305459f5cbd74cfc65/content/blog/2022/tiering-1.md#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

heh, user configure**s** :smile_cat: 
</blockquote></details>

sorry :) now everything should be corrected


<!-- Sent from Reviewable.io -->

2022-06-22 09:01 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/250#-:-N59dEaHAFxho3sg6IIf:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @pbalcer)

___
*[`content/blog/2022/tiering-1.md` line 42 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N59E8gG5EULbvCQbGge:-N59d10y1eW-0_C-YYhu:bb74ptu) ([raw file](https://github.com/pmem/pmem.github.io/blob/c6d88be4c676d5222c13e6305459f5cbd74cfc65/content/blog/2022/tiering-1.md#L42)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

sorry :) now everything should be corrected
</blockquote></details>

Thx!


<!-- Sent from Reviewable.io -->

2022-06-22 10:13 UTC, pbalcer requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/250)* status: all files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @pbalcer)

___
*[`content/blog/2022/tiering-1.md` line 6 at r8](https://reviewable.io/reviews/pmem/pmem.github.io/250#-N59tgzqBuozEIJPYBmy:-N59tgzr7aKF52QJCgry:b-5te0xs) ([raw file](https://github.com/pmem/pmem.github.io/blob/81b7f1e3352a84fa53b3ff9b032cd69d77ceb8ad/content/blog/2022/tiering-1.md#L6)):*
> ```Markdown
> 
> # Blog post creation date
> date: 2022-06-21T00:00:00+00:00
> ```

update to today.


<!-- Sent from Reviewable.io -->

2022-06-22 10:19 UTC, merged