Add similarity search blog note
pmem/pmem.github.io pull request #251
Opened 2022-06-15 11:23 UTC by maciekpac

2022-06-17 12:08 UTC, lukaszstolarczuk reviewed
it reads very well, just a few minor issues from my side :wink: 

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/251#-:-N4lYv577J46lmoUUWUk:btnbrml)* status: all files reviewed, 9 unresolved discussions (waiting on @maciekpac and @pbalcer)

___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 28 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lBouCBk2vbun-Wrd5:-N4lBouCBk2vbun-Wrd6:bd5f1q) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L28)):*
> ```Markdown
> blogs: ['SimilaritySearch']
> # Blog tags
> tags: ["HNSW", "similarity search", "NeurIPS", "OptaNNE GraphNN", "DiskANN", "SPANN", "NeurIPS"]
> ```

I guess these tags may be a little too specific...? (for comparison, here are our current tags: https://pmem.io/tags )
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 28 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lYedd5K1mkemBH3D-:-N4lYedd5K1mkemBH3D0:binty9j) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L28)):*
> ```Markdown
> blogs: ['SimilaritySearch']
> # Blog tags
> tags: ["HNSW", "similarity search", "NeurIPS", "OptaNNE GraphNN", "DiskANN", "SPANN", "NeurIPS"]
> ```

misspell `GraphANN`
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 36 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lC0YL4dQbxXLFCv7h:-N4lC0YL4dQbxXLFCv7i:bo73vie) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L36)):*
> ```Markdown
> From a very high-level overview, computing solves problems. These problems, even though different and individual, are sometimes somehow related. A new algorithmic challenge can usually be solved by bringing it down to a well-defined problem with an existing solution. Today, we will be talking about one of such universal solutions - similarity search, which has found its application in various areas of life, from search engines that tell us what we want to find, through recommendation engines that tell us what to watch, where to eat and what to buy, all the way to data science that provides valuable input to business decisions.   
> 
> ### Similarity Search - what it is
> ```

perhaps \+ `?` (here, below, and in "Why Optane is a great fit")
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 92 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lLB557OY7U_p8Vwfl:-N4lLB557OY7U_p8Vwfm:bkfdo5b) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L92)):*
> ```Markdown
> ![An illustration of sample HNSW layers and their split between DRAM-PMEM](/images/posts/hnsw_dram_pmem.png "Sample layers and their split between DRAM-PMEM")
> 
> In short, all the nodes are already grouped by their access frequency. As you might have guessed, storing the not-so-frequently accessed nodes on a cheaper medium with higher latency would not hurt the performance that much, while giving the most performant memory to the top layers can give us a significant performance boost. This is where the Optane technology comes in - as a byte-addressable, sweet spot between destined for the top layers DRAM and slow SSD-based storage.
> ```

I think you can drop "as" here... or I'm not reading this sentence right :wink: 



_Code quote:_
```Markdown
This is where the Optane technology comes in - as a byte-addressable, sweet spot between destined for the top layers DRAM and slow SSD-based storage.
```
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 111 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lW4HQ9p8t6D4SsYtI:-N4lW4HQ9p8t6D4SsYtJ:b-rmq2mn) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L111)):*
> ```Markdown
> Also, the topic of this article was not to present a particular PMEM-enabled implementation of HNSW or any other algorithm, but rather to show how the properties of PMEM can be leveraged. We will be happy to describe a particular implementation once we have an official, open-source library destined for PMEM in particular.
> 
> What is noteworthy, HNSW is not the only algorithm adapted to work with heterogeneous memory. Other algorithms, such as [DiskANN](https://proceedings.neurips.cc/paper/2019/file/09853c7fb1d3f8ee67a61b6bf4a7f8e6-Paper.pdf) or [SPANN](https://proceedings.neurips.cc/paper/2021/file/299dc35e747eb77177d9cea10a802da2-Paper.pdf), take slightly different approaches to the problem and leverage slow memory tier differently. The former compresses vectors and keeps them in DRAM, while the graph and full vectors in are stored in slow memory. The latter clusters vectors and holds centroids in DRAM and uses SSD storage to keep full posting lists. It shows that heterogeneous memory, in general, is the key to optimizing costs in similarity search.
> ```

`vectors in are` -> `vectors are`
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 111 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lWG8a4vMPFvJx8Y2l:-N4lWG8a4vMPFvJx8Y2m:b-42rld7) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L111)):*
> ```Markdown
> Also, the topic of this article was not to present a particular PMEM-enabled implementation of HNSW or any other algorithm, but rather to show how the properties of PMEM can be leveraged. We will be happy to describe a particular implementation once we have an official, open-source library destined for PMEM in particular.
> 
> What is noteworthy, HNSW is not the only algorithm adapted to work with heterogeneous memory. Other algorithms, such as [DiskANN](https://proceedings.neurips.cc/paper/2019/file/09853c7fb1d3f8ee67a61b6bf4a7f8e6-Paper.pdf) or [SPANN](https://proceedings.neurips.cc/paper/2021/file/299dc35e747eb77177d9cea10a802da2-Paper.pdf), take slightly different approaches to the problem and leverage slow memory tier differently. The former compresses vectors and keeps them in DRAM, while the graph and full vectors in are stored in slow memory. The latter clusters vectors and holds centroids in DRAM and uses SSD storage to keep full posting lists. It shows that heterogeneous memory, in general, is the key to optimizing costs in similarity search.
> ```

in **a** slow memory. (?)
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 118 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lX5O06Ew8u34eZjoS:-N4lX5O06Ew8u34eZjoT:b72vzg5) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L118)):*
> ```Markdown
> 
> | Algorithm         | DEEP  | BIGANN    | MS Turing | MS SpaceV | Text-to-image | SSN++ |
> |-------------------|------:|----------:|----------:|----------:|--------------:|------:|
> ```

this table is shown on the preview without visible borders... I'm thinking maybe it's caused by the lack of `:` - it should be added on the beginning and at the end of each cell, e.g.

```
|DEEP|
|:--:|
```
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 120 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lYRHl4b36JHW2Qu2e:-N4lYRHl4b36JHW2Qu2f:b-k2cely) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L120)):*
> ```Markdown [...]

2022-06-17 15:21 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/251)* status: 2 of 3 files reviewed, 9 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, and @pbalcer)

___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 28 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lBouCBk2vbun-Wrd5:-N4m8Psd7vORHQvvPTN8:b-ejjo3a) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess these tags may be a little too specific...? (for comparison, here are our current tags: https://pmem.io/tags )
</blockquote></details>

Reduced to ["pmem", "similarity search"]
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 28 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lYedd5K1mkemBH3D-:-N4m8lJc306yUPLNUw0T:b-zcciuf) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

misspell `GraphANN`
</blockquote></details>

removed from tags; besides, I just checked it and it looks like there are two different spellings here:

https://arxiv.org/pdf/2205.03763.pdf

I think GraphANN is the correct one (spelling of the closed-source repo).
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 36 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lC0YL4dQbxXLFCv7h:-N4m9gbg2DRpghX2odXC:b2i2wrd) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L36)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps \+ `?` (here, below, and in "Why Optane is a great fit")
</blockquote></details>

I also hesitated a little bit whether they should be in the form of questions or affirmations

Reformed to questions.
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 92 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lLB557OY7U_p8Vwfl:-N4mAB_BB2CQ0InizF6y:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L92)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think you can drop "as" here... or I'm not reading this sentence right :wink: 
</blockquote></details>

Done.
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 111 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lW4HQ9p8t6D4SsYtI:-N4mAHGO48NZBr2rqP8V:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L111)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`vectors in are` -> `vectors are`
</blockquote></details>

Done.
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 111 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lWG8a4vMPFvJx8Y2l:-N4mAzMI9-jaR7gYwz_z:bdkcoh2) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L111)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

in **a** slow memory. (?)
</blockquote></details>

I'm not 100% sure about this one; I modified in to "in a slow memory **tier**" and modified previous sentence to avoid repetition of t*tier*
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 118 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lX5O06Ew8u34eZjoS:-N4mCaI4C7Xfp3hAAvUD:b8oidyw) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L118)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this table is shown on the preview without visible borders... I'm thinking maybe it's caused by the lack of `:` - it should be added on the beginning and at the end of each cell, e.g.

```
|DEEP|
|:--:|
```
</blockquote></details>

the |:--:| are about alignment, not borders;

I also wanted to add borders somehow, but it looks like it's not supported in markdown.

I added html/css formatting to this table, is it ok ?
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 124 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lXptz1_AI88R9Mq8O:-N4mByJj-1cVlSmMMes6:bj5w76u) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L124)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Is this sentence supposed to be a title for the table above? perhaps mark ith with cursive or add some other kind of notation, e.g.:
> title
</blockquote></details>

added both


<!-- Sent from Reviewable.io -->

2022-06-20 07:34 UTC, PatKamin reviewed
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/251)* status: all files reviewed, 13 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, and @pbalcer)

___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 52 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4zphK1DdPHVnRnMxGZ:-N4zphK29noo7FUPaKXG:b-vrdcsr) ([raw file](https://github.com/pmem/pmem.github.io/blob/6fa1c73c8cb256d7d672c7e821db7652fe0bb09c/content/blog/2022/similarity-search-opportunity-for-pmem.md#L52)):*
> ```Markdown
> ### Approximate Nearest Neighbor
> 
> It turns out that, if we sacrifice accuracy, we can get the complexity down to O(log(n)). Today, we will focus on one particular algorithm: [Hierarchical Navigable Small World](https://arxiv.org/abs/1603.09320) and on how we can leverage PMEM to achieve better TCO (Total Cost of Ownership) of a server machine that runs this algorithm.
> ```

Please, introduce the 'HNSW' abbreviation here. It's used in the next illustration description and surprises the reader a bit.



_Suggestion:_
```Markdown
[Hierarchical Navigable Small World](https://arxiv.org/abs/1603.09320)
```
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 92 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4ztFTn41DOf_2u5Cfg:-N4ztFTn41DOf_2u5Cfh:b3s7mpj) ([raw file](https://github.com/pmem/pmem.github.io/blob/6fa1c73c8cb256d7d672c7e821db7652fe0bb09c/content/blog/2022/similarity-search-opportunity-for-pmem.md#L92)):*
> ```Markdown
> ![An illustration of sample HNSW layers and their split between DRAM-PMEM](/images/posts/hnsw_dram_pmem.png "Sample layers and their split between DRAM-PMEM")
> 
> In short, all the nodes are already grouped by their access frequency. As you might have guessed, storing the not-so-frequently accessed nodes on a cheaper medium with higher latency would not hurt the performance that much, while giving the most performant memory to the top layers can give us a significant performance boost. This is where the Optane technology comes in - a byte-addressable, sweet spot between destined for the top layers DRAM and slow SSD-based storage.
> ```

Is the common practice storing these graphs on hard drives nowadays? I think it wasn't mentioned before. Please, add some comment what is the common practice.



_Code quote:_
```Markdown
while giving the most performant memory to the top layers can give us a significant performance boost
```
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 94 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4zwo4-5QfjZKUHiDeH:-N4zwo4-5QfjZKUHiDeI:bwl120q) ([raw file](https://github.com/pmem/pmem.github.io/blob/6fa1c73c8cb256d7d672c7e821db7652fe0bb09c/content/blog/2022/similarity-search-opportunity-for-pmem.md#L94)):*
> ```Markdown
> In short, all the nodes are already grouped by their access frequency. As you might have guessed, storing the not-so-frequently accessed nodes on a cheaper medium with higher latency would not hurt the performance that much, while giving the most performant memory to the top layers can give us a significant performance boost. This is where the Optane technology comes in - a byte-addressable, sweet spot between destined for the top layers DRAM and slow SSD-based storage.
> 
> Moreover, from the developer point of view, the accesses to nodes is virtually random; in such case, it's not just the higher bandwidth and lower latency that gives us an edge over SSDs, but also the byte-addressability and smaller overhead of fetching small chunks of memory.
> ```

the accesses to nodes **are**
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 96 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4zxRKd-JC1Ay_NGFZn:-N4zxRKd-JC1Ay_NGFZo:b-2vmmfp) ([raw file](https://github.com/pmem/pmem.github.io/blob/6fa1c73c8cb256d7d672c7e821db7652fe0bb09c/content/blog/2022/similarity-search-opportunity-for-pmem.md#L96)):*
> ```Markdown
> Moreover, from the developer point of view, the accesses to nodes is virtually random; in such case, it's not just the higher bandwidth and lower latency that gives us an edge over SSDs, but also the byte-addressability and smaller overhead of fetching small chunks of memory.
> 
> Another great advantage of this solution is the consistency of lookup time - each lookup needs to traverse through both, DRAM and PMEM in rather consistent proportions, which is much better than having random buffered/unbuffered SSD accesses.
> ```

Comma not needed here. `both` directly refers here to `DRAM and PMEM`.



_Code quote:_
```Markdown
both, DRAM
```


<!-- Sent from Reviewable.io -->

2022-06-20 10:22 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/251)* status: all files reviewed, 5 unresolved discussions (waiting on @maciekpac and @pbalcer)

___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 28 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lBouCBk2vbun-Wrd5:-N5-a-Nf5vyDljsftYXD:bbvtreo) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L28)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Reduced to ["pmem", "similarity search"]
</blockquote></details>

hmm maybe something generic like "research" or "pmem use case" or something similar...?
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 28 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lYedd5K1mkemBH3D-:-N5-aD9JA1z3P8P1MF4S:b-o5mlhi) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L28)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

removed from tags; besides, I just checked it and it looks like there are two different spellings here:

https://arxiv.org/pdf/2205.03763.pdf

I think GraphANN is the correct one (spelling of the closed-source repo).
</blockquote></details>

hah, ok
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 111 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lWG8a4vMPFvJx8Y2l:-N5-bk616Eu_Vd6iZvBa:b-khehtf) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L111)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I'm not 100% sure about this one; I modified in to "in a slow memory **tier**" and modified previous sentence to avoid repetition of t*tier*
</blockquote></details>

I wasn't either, now seems all right.
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 118 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lX5O06Ew8u34eZjoS:-N5-cDLo1VzDS2YB7iPn:bwdvn0f) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L118)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

the |:--:| are about alignment, not borders;

I also wanted to add borders somehow, but it looks like it's not supported in markdown.

I added html/css formatting to this table, is it ok ?
</blockquote></details>

yeah, I know that these are for alignment ":", but I thought, maybe it breaks the formatting somehow...

it's quite interesting, that you had to add the styling, but it looks good now!


<!-- Sent from Reviewable.io -->

2022-06-20 13:40 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/251)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, @PatKamin, and @pbalcer)

___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 120 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lYRHl4b36JHW2Qu2e:-N5-oZ3lE6adWnWxA_7m:b4kkjbl) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L120)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

misspell - `GraphANN`
</blockquote></details>

I think GraphANN is correct here ... or am I really missing something ?
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 52 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4zphK1DdPHVnRnMxGZ:-N5-nzcr3Z1vZyyFdsH6:ba5dby7) ([raw file](https://github.com/pmem/pmem.github.io/blob/6fa1c73c8cb256d7d672c7e821db7652fe0bb09c/content/blog/2022/similarity-search-opportunity-for-pmem.md#L52)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, introduce the 'HNSW' abbreviation here. It's used in the next illustration description and surprises the reader a bit.
</blockquote></details>

added "(HNSW)" after the link
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 92 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4ztFTn41DOf_2u5Cfg:-N5-ovRvBq3acGAeRby-:bc14n2t) ([raw file](https://github.com/pmem/pmem.github.io/blob/6fa1c73c8cb256d7d672c7e821db7652fe0bb09c/content/blog/2022/similarity-search-opportunity-for-pmem.md#L92)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Is the common practice storing these graphs on hard drives nowadays? I think it wasn't mentioned before. Please, add some comment what is the common practice.
</blockquote></details>

Most recent research focuses on SSDs, but it's not the only solution. HNSW itself is a DRAM-only algorithm, each dev/team/company can decide on their own whether it's better to use SSD (e.g. very big database/graph), a DRAM-only solution (e.g. not a big database, but very frequent lookups) or PMEM. In fact, other hardware, such as GPUs can be used for this problem as well, but this is again, out of the scope of this article.

I've modified the text to give some more insight, should I add something more ?
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 94 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4zwo4-5QfjZKUHiDeH:-N5-oIRD0E6TR55YHjpX:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/6fa1c73c8cb256d7d672c7e821db7652fe0bb09c/content/blog/2022/similarity-search-opportunity-for-pmem.md#L94)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

the accesses to nodes **are**
</blockquote></details>

Done.
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 96 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4zxRKd-JC1Ay_NGFZn:-N5-oQJG22ktQEVkfs00:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/6fa1c73c8cb256d7d672c7e821db7652fe0bb09c/content/blog/2022/similarity-search-opportunity-for-pmem.md#L96)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Comma not needed here. `both` directly refers here to `DRAM and PMEM`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-20 14:02 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/251)* status: all files reviewed, 5 unresolved discussions (waiting on @maciekpac, @PatKamin, and @pbalcer)

___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 28 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lBouCBk2vbun-Wrd5:-N50PtwL59tKb_2dH8AD:b-pxaerb) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm maybe something generic like "research" or "pmem use case" or something similar...?
</blockquote></details>

but this is still open :wink: 
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 120 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lYRHl4b36JHW2Qu2e:-N50PgbYA1Xn6M_fTvUf:bd2vccm) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L120)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I think GraphANN is correct here ... or am I really missing something ?
</blockquote></details>

you've already resolved this issue previously, it's an old comment :wink: 


<!-- Sent from Reviewable.io -->

2022-06-20 14:43 UTC, pbalcer requested changes
This is awesome! great job.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/251#-:-N50ZHWf2nlrJLpkhybg:blujpn1)* status: all files reviewed, 5 unresolved discussions (waiting on @maciekpac)

___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 33 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N50VJmy-iU0pXq2MFgS:-N50VJmy-iU0pXq2MFgT:bv2u7s9) ([raw file](https://github.com/pmem/pmem.github.io/blob/cb040d26764cb1431bf16dd44403e1e097f08824/content/blog/2022/similarity-search-opportunity-for-pmem.md#L33)):*
> ```Markdown
> type: "post"
> ---
> ```

please split up paragraphs at 80 lines. It's very difficult to review otherwise.
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 34 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N50V4ML9uKaBxH1C8KT:-N50V4ML9uKaBxH1C8KU:b-b2m7mn) ([raw file](https://github.com/pmem/pmem.github.io/blob/cb040d26764cb1431bf16dd44403e1e097f08824/content/blog/2022/similarity-search-opportunity-for-pmem.md#L34)):*
> ```Markdown
> ---
> 
> From a very high-level overview, computing solves problems. These problems, even though different and individual, are sometimes somehow related. A new algorithmic challenge can usually be solved by bringing it down to a well-defined problem with an existing solution. Today, we will be talking about one of such universal solutions - similarity search, which has found its application in various areas of life, from search engines that tell us what we want to find, through recommendation engines that tell us what to watch, where to eat and what to buy, all the way to data science that provides valuable input to business decisions.
> ```

At a high level, 
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 42 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N50WBxGCAMmjq_t97Ui:-N50WBxGCAMmjq_t97Uj:bxpstoi) ([raw file](https://github.com/pmem/pmem.github.io/blob/cb040d26764cb1431bf16dd44403e1e097f08824/content/blog/2022/similarity-search-opportunity-for-pmem.md#L42)):*
> ```Markdown
> ### Why do we need it?
> 
> We've already defined what the class of problems is and what the areas of application are, but how do they relate to each other? The answer is, we can use vectors to represent things. A vector can be used to represent someone's social network profile, a word, an item in an online shop, an online article, a photo or virtually anything else we can think of. Also, the distance between two vectors, in general case, is not constraint to some particular metrics, e.g. euclidean (the one we use to compute distance in the real world). If we come up with an idea on how to measure a distance between a donkey and the sound of scratching a blackboard, it's good enough for the algorithm. And what about finding similar things? We often look for similar items in online shops, similar movies to the ones we watched, search for similar food... Nonetheless, it would be a huge underestimation to say that similarity search can only be applied to areas where we directly search for similar things; it constitutes a building block for many other mathematical problems, with many more real-life applications.
> ```

is not constrained (?)

huge understatement


<!-- Sent from Reviewable.io -->

2022-06-20 15:29 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/251)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk, @PatKamin, and @pbalcer)

___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 28 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lBouCBk2vbun-Wrd5:-N50Voj2Cz-BoIfvkWVJ:bqds4oy) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

but this is still open :wink: 
</blockquote></details>

Added "research", "pmem use case"
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 92 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4ztFTn41DOf_2u5Cfg:-N50W4D65FthCIw4udxz:b-dneubm) ([raw file](https://github.com/pmem/pmem.github.io/blob/6fa1c73c8cb256d7d672c7e821db7652fe0bb09c/content/blog/2022/similarity-search-opportunity-for-pmem.md#L92)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Now when we're clear on that the main medium for storing these graphs is DRAM, the part where you mention that the top layers can be stored on DRAM to get a perf boost doesn't make sense. Cause it's already stored there even without PMEM. Rather you can (and probably should) emphasize here that with the usage of PMEM you can store much more or much bigger graphs than with the usage of DRAM alone (without a significant perf drop).
</blockquote></details>

I rephrased this paragraph a little bit. I think it's obvious that an algorithm using DRAM+PMEM would not be quicker than the same algorithm with DRAM-only.

At least not unless we use persistency to speed the execution up, which would be really strange if machine is not undergoing any reboots and there are no crashes+recoveries during the algorithm execution.

 I don't want to be too explicit here neither, to keep this article pleasant to read.  

I wanted to show that storing the top layer in lower-latency medium makes much more sense than storing the bottom layer there - single node access frequency is much higher in top layer(s). 

I tried to show the synergy of a multi-tier solution; this algorithm should provide much better TCO with multiple tiers than with any single, particular memory tier - i.e.  hnsw(DRAM+PMEM+SSD) > hnsw(DRAM) + hnsw(PMEM) + hnsw(SSD) 

What do you think about it right now?
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 33 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N50VJmy-iU0pXq2MFgS:-N50eP02BTSgqGQnrpoy:b26a4m4) ([raw file](https://github.com/pmem/pmem.github.io/blob/cb040d26764cb1431bf16dd44403e1e097f08824/content/blog/2022/similarity-search-opportunity-for-pmem.md#L33)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

please split up paragraphs at 80 lines. It's very difficult to review otherwise.
</blockquote></details>

At 80 lines, or at 80 words ?

Done, but left some lines longer, e.g. those with image input, or links - splitting them broke syntax highlighting in my editor; I also checked other articles and found that these lines were (at least sometimes) not split
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 34 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N50V4ML9uKaBxH1C8KT:-N50eOOJ73PFuAFioVdi:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cb040d26764cb1431bf16dd44403e1e097f08824/content/blog/2022/similarity-search-opportunity-for-pmem.md#L34)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

At a high level, 
</blockquote></details>

Done.
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 42 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N50WBxGCAMmjq_t97Ui:-N50iJm7Ao5DNvubns6s:bb7f2mf) ([raw file](https://github.com/pmem/pmem.github.io/blob/cb040d26764cb1431bf16dd44403e1e097f08824/content/blog/2022/similarity-search-opportunity-for-pmem.md#L42)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

is not constrained (?)

huge understatement


</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-06-20 15:55 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/251#-:-N50osVdExQGY5HAvJPc:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @PatKamin and @pbalcer)

___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 28 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N4lBouCBk2vbun-Wrd5:-N50nshW218UO8OjPPCb:bb74ptu) ([raw file](https://github.com/pmem/pmem.github.io/blob/cc16b1e7959319ece0c0417fac904c6c8ff23a06/content/blog/2022/similarity-search-opportunity-for-pmem.md#L28)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Added "research", "pmem use case"
</blockquote></details>

Thx!
___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 33 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N50VJmy-iU0pXq2MFgS:-N50nyW0-4UwgU4l3c8H:b-ow028d) ([raw file](https://github.com/pmem/pmem.github.io/blob/cb040d26764cb1431bf16dd44403e1e097f08824/content/blog/2022/similarity-search-opportunity-for-pmem.md#L33)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

At 80 lines, or at 80 words ?

Done, but left some lines longer, e.g. those with image input, or links - splitting them broke syntax highlighting in my editor; I also checked other articles and found that these lines were (at least sometimes) not split
</blockquote></details>

we don't require anyhow any precise chars count in the line (e.g. in CI), so a reasonable split is perfect


<!-- Sent from Reviewable.io -->

2022-06-21 05:56 UTC, PatKamin reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/251#-:-N53pSDuCJeKORYtAroC:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @pbalcer)



<!-- Sent from Reviewable.io -->

2022-06-21 10:37 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/251)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk, @PatKamin, and @pbalcer)

___
*[`content/blog/2022/similarity-search-opportunity-for-pmem.md` line 6 at r5](https://reviewable.io/reviews/pmem/pmem.github.io/251#-N54MhWa4ejcOcJRRW2P:-N54pYXW4Z3TXWoa1iV_:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/e0665337d8f56d8a1ddb32792a07303124c0a745/content/blog/2022/similarity-search-opportunity-for-pmem.md#L6)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

please update to today (00:00 time)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-21 11:25 UTC, merged