Add blog note - cutom transparent tiering
pmem/pmem.github.io pull request #252
Opened 2022-06-17 15:21 UTC by maciekpac

2022-06-17 15:23 UTC, maciekpac commented
Similarity search awaits for merge first

2022-06-20 07:46 UTC, PatKamin reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/252)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, and @pbalcer)

___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 12 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5-1N4mC-VlauNdYRjm:-N5-1N4mC-VlauNdYRjn:b6pebg2) ([raw file](https://github.com/pmem/pmem.github.io/blob/50b75ae19223ce66c4b9084839157061f2421eaf/content/blog/2022/writing-transparent-tiering-solution.md#L12)):*
> ```Markdown
> 
> # Blog post description
> description: "Writing custom transparent tiering solution - description of available options and trade offs between them"
> ```

trade-offs



_Code quote:_
```Markdown
trade offs
```
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 34 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5-1WCt71qMnFz8EkHP:-N5-1WCt71qMnFz8EkHQ:b-8mjbfd) ([raw file](https://github.com/pmem/pmem.github.io/blob/50b75ae19223ce66c4b9084839157061f2421eaf/content/blog/2022/writing-transparent-tiering-solution.md#L34)):*
> ```Markdown
> ---
> 
> This article is intended for those, who would like to learn how tiering/numa balancing or memory profiling solutions work behind the hood. We will focus on a high overview of how tiering/numa balancing could be designed, instead of dissecting any particular solution. This approach means that the readers can also benefit from general knowledge on topics such as Linux API, performance monitoring hardware or architecture of Linux apps. 
> ```

for those who - I think this whole phrase should be kept together.



_Code quote:_
```Markdown
those, who
```
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 34 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5-1xU_DdNldRqZnZer:-N5-1xU_DdNldRqZnZes:bfelmk8) ([raw file](https://github.com/pmem/pmem.github.io/blob/50b75ae19223ce66c4b9084839157061f2421eaf/content/blog/2022/writing-transparent-tiering-solution.md#L34)):*
> ```Markdown
> ---
> 
> This article is intended for those, who would like to learn how tiering/numa balancing or memory profiling solutions work behind the hood. We will focus on a high overview of how tiering/numa balancing could be designed, instead of dissecting any particular solution. This approach means that the readers can also benefit from general knowledge on topics such as Linux API, performance monitoring hardware or architecture of Linux apps. 
> ```

**under** the hood



_Code quote:_
```Markdown
behind the hood
```
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 34 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5-3Bm5Es4JR0ylVHSc:-N5-3Bm5Es4JR0ylVHSd:bcanu4m) ([raw file](https://github.com/pmem/pmem.github.io/blob/50b75ae19223ce66c4b9084839157061f2421eaf/content/blog/2022/writing-transparent-tiering-solution.md#L34)):*
> ```Markdown
> ---
> 
> This article is intended for those, who would like to learn how tiering/numa balancing or memory profiling solutions work behind the hood. We will focus on a high overview of how tiering/numa balancing could be designed, instead of dissecting any particular solution. This approach means that the readers can also benefit from general knowledge on topics such as Linux API, performance monitoring hardware or architecture of Linux apps. 
> ```

Perhaps you meant here: `performance monitoring of hardware` or `hardware performance monitoring`.



_Code quote:_
```Markdown
performance monitoring hardware
```
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 38 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5-3ZwD9-MdfqoLt-9J:-N5-3ZwD9-MdfqoLt-9K:bxx0n0r) ([raw file](https://github.com/pmem/pmem.github.io/blob/50b75ae19223ce66c4b9084839157061f2421eaf/content/blog/2022/writing-transparent-tiering-solution.md#L38)):*
> ```Markdown
> ### Key components
> 
> Before we dwell into details, we will shortly discuss key requirements and map them to components of the software we want to design. The basis of a tiering system consists of monitoring which pages to move and moving them. A user might want to use features such as:
> ```

delve into



_Code quote:_
```Markdown
dwell into
```


<!-- Sent from Reviewable.io -->

2022-06-20 14:38 UTC, PatKamin reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/252)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk and @pbalcer)



<!-- Sent from Reviewable.io -->

2022-06-20 15:01 UTC, pbalcer requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/252)* status: all files reviewed, 17 unresolved discussions (waiting on @lukaszstolarczuk and @maciekpac)

___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 33 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50Zf8s--Ba89U0oh1O:-N50Zf8s--Ba89U0oh1P:b-2bb6bm) ([raw file](https://github.com/pmem/pmem.github.io/blob/235a48c154da8e9c8d52b3a4db64f33261fb184f/content/blog/2022/writing-transparent-tiering-solution.md#L33)):*
> ```Markdown
> type: "post"
> ---
> ```

again, split at 80.
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 34 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50ZdvuDx9VOsfuOM2L:-N50ZdvuDx9VOsfuOM2M:b-wmw5gc) ([raw file](https://github.com/pmem/pmem.github.io/blob/235a48c154da8e9c8d52b3a4db64f33261fb184f/content/blog/2022/writing-transparent-tiering-solution.md#L34)):*
> ```Markdown
> ---
> 
> This article is intended for those who would like to learn how tiering/numa balancing or memory profiling solutions work under the hood. We will focus on a high overview of how tiering/numa balancing could be designed, instead of dissecting any particular solution. This approach means that the readers can also benefit from general knowledge on topics such as Linux API, hardware-accelerated performance monitoring or architecture of Linux apps.
> ```

high-level overview

Does the last sentence mean that readers can learn about that stuff or that they should have that knowledge already? I think you meant the former, but right now, to me at least, it seems that the current sentence has the latter meaning.
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 91 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50aEXx8QkrAjBKoj5i:-N50aEXx8QkrAjBKoj5j:b5q7v57) ([raw file](https://github.com/pmem/pmem.github.io/blob/235a48c154da8e9c8d52b3a4db64f33261fb184f/content/blog/2022/writing-transparent-tiering-solution.md#L91)):*
> ```Markdown
> Another way to monitor page accesses is via hardware mechanisms originally destined for profiling applications, such as [Intel PEBS](https://easyperf.net/blog/2018/06/08/Advanced-profiling-topics-PEBS-and-LBR#last-branch-record-lbr). It is worth noting that, in this case, the information about accesses comes with some delay - first, an access occurs, then it's stored in a buffer and, after some time, the event is processed by the user. PEBS also exposes info about the core the process was executed on. These features, however, are hardware specific and might not be available on all platforms or might not be supported by virtual machines.
> 
> Linux kernel provides an API that can be used to track hotness as well. The files to check are ```/sys/kernel/mm/page_idle/bitmap``` or ```/proc/kpageflags```. Both, the [former](https://www.kernel.org/doc/Documentation/vm/idle_page_tracking.txt) and the [latter](https://www.kernel.org/doc/html/latest/admin-guide/mm/pagemap.html?highlight=kpageflags) work by setting pages status to IDLE and checking when the status changes. The good thing about it is that it's hardware-agnostic, but might come with various performance. Also, not every kernel has support for this API enabled.
> ```

various performance overheads depending on the underlying implementation.

?
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 93 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50acHjDiG7BKTS4USf:-N50acHjDiG7BKTS4USg:b-llpnv4) ([raw file](https://github.com/pmem/pmem.github.io/blob/235a48c154da8e9c8d52b3a4db64f33261fb184f/content/blog/2022/writing-transparent-tiering-solution.md#L93)):*
> ```Markdown
> Linux kernel provides an API that can be used to track hotness as well. The files to check are ```/sys/kernel/mm/page_idle/bitmap``` or ```/proc/kpageflags```. Both, the [former](https://www.kernel.org/doc/Documentation/vm/idle_page_tracking.txt) and the [latter](https://www.kernel.org/doc/html/latest/admin-guide/mm/pagemap.html?highlight=kpageflags) work by setting pages status to IDLE and checking when the status changes. The good thing about it is that it's hardware-agnostic, but might come with various performance. Also, not every kernel has support for this API enabled.
> 
> Finally, kernel 5.15 added support for [DAMON](https://www.phoronix.com/scan.php?page=news_item&px=DAMON-For-Linux-5.15) - Data Access MONitor that was created for the exact purpose of *BA DUM TSS* monitoring data access.
> ```

what's the joke?:D
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 97 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50aft31DsJXa5wTFJQ:-N50aft31DsJXa5wTFJR:b-c2v5m8) ([raw file](https://github.com/pmem/pmem.github.io/blob/235a48c154da8e9c8d52b3a4db64f33261fb184f/content/blog/2022/writing-transparent-tiering-solution.md#L97)):*
> ```Markdown
> #### Decision-making
> 
> The most straight-forward way would be to adapt some well-known caching algorithm, such as [LRU](https://en.wikipedia.org/wiki/Cache_replacement_policies#Least_recently_used_(LRU)). The algorithm can be adapted e.g. by keeping two LRU queues, one for active pages and the other one for inactive and by swapping the most recently used page on PMEM with the least recently used on dram, when appropriate. This is the approach used by the Linux kernel.
> ```

the most straightforward way to do what?

"decision-making" is not sufficient imho.
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 99 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50atOQ3te3JkBANlmT:-N50atOQ3te3JkBANlmU:b-bpgh3e) ([raw file](https://github.com/pmem/pmem.github.io/blob/235a48c154da8e9c8d52b3a4db64f33261fb184f/content/blog/2022/writing-transparent-tiering-solution.md#L99)):*
> ```Markdown
> The most straight-forward way would be to adapt some well-known caching algorithm, such as [LRU](https://en.wikipedia.org/wiki/Cache_replacement_policies#Least_recently_used_(LRU)). The algorithm can be adapted e.g. by keeping two LRU queues, one for active pages and the other one for inactive and by swapping the most recently used page on PMEM with the least recently used on dram, when appropriate. This is the approach used by the Linux kernel.
> 
> What is important is not really when the page was used for the last time, but when and how often it would be used in the future. The person who knows such thighs best is probably either the program developer, whom we cannot ask (per requirement - tiering was supposed to be transparent), or the end user. Even if we could convince the end user to give us some hint on when they would access some data (e.g. in a database), this feature would still be so problematic to implement that I can safely assume that, in our case, we do not know the next data access time. The only thing we can do is try to forcast the accesses. A measure of how often the data was accessed in the past is a good start. Maybe there was some pattern in the data usage?
> ```

such things

The sentence that starts with "Even if..." reads very odd. 
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 107 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50bUjz7TBnqGCRyYG-:-N50bUjz7TBnqGCRyYG0:b-xbgavl) ([raw file](https://github.com/pmem/pmem.github.io/blob/235a48c154da8e9c8d52b3a4db64f33261fb184f/content/blog/2022/writing-transparent-tiering-solution.md#L107)):*
> ```Markdown
> ![Memory management - illustration](/images/posts/allocator_mm.png "Illustration of memory management - dependencies between user space, kernel space and hardware")
> 
> Page movement itself might boil down to a single function call, e.g. from the libnuma library, but there is also a question of what we really want to do. Do we want to move the page, or assure it stays in the moved place forever? Or, maybe, we would like to specify which nodes are acceptable and which ones are not - this might b [...]

2022-06-21 14:09 UTC, maciekpac reviewed
Added a paragraph in *Options - user space vs kernel space*

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/252#-:-N55YUSK978O06ovbMpg:b-lnxuef)* status: all files reviewed, 17 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, and @pbalcer)

___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 3 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50S_jX3PqX4lhe-AiE:-N50iy_vBMrBpt6X5wMM:b-vf0cs8) ([raw file](https://github.com/pmem/pmem.github.io/blob/50b75ae19223ce66c4b9084839157061f2421eaf/content/blog/2022/writing-transparent-tiering-solution.md#L3)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

mine blog note is named "Memory Tiering (part 1)" so maybe better name would be "Memory Tiering (part 2) - design decisions in Transparent Tiering solution?
</blockquote></details>

Hmm this was supposed to be "Memory Tiering (part 3)", but (part 2) awaits approval; I would just leave it as-is, unless we want to wait another few weeks for the second one.
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 6 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50StR6AMU0Ce7C7KYM:-N50jHwf4M2Jx7kkUaNO:b-o3xahs) ([raw file](https://github.com/pmem/pmem.github.io/blob/50b75ae19223ce66c4b9084839157061f2421eaf/content/blog/2022/writing-transparent-tiering-solution.md#L6)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

mine note creation date is set to "date: 2022-06-14T00:00:00+00:00" -
please set your creation date after this
</blockquote></details>

This was auto-generated by *hugo*, I would prefer not to change it. Besides, creation date is not the same as publication date
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 38 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50TlxP7MMxtphMpVdP:-N50qB262jhBuMtYe8Z1:b-61zfvu) ([raw file](https://github.com/pmem/pmem.github.io/blob/50b75ae19223ce66c4b9084839157061f2421eaf/content/blog/2022/writing-transparent-tiering-solution.md#L38)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I would not agree... we have a tiering solution that doesn't do page movement. Please clarify this here. 
</blockquote></details>

Changed to:

Before we delve into details, we will shortly discuss key requirements and
map them to components of the software we want to design. The basis of
a tiering system consists either of making a decision about the target tier
in allocation time, or of monitoring which pages to move and moving them.

We will focus on a solution that moves already allocated pages in runtime.
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 52 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50UPIPCYlwRNa6NAIc:-N54yEchD3OpqGIgVib8:bfpm4o7) ([raw file](https://github.com/pmem/pmem.github.io/blob/50b75ae19223ce66c4b9084839157061f2421eaf/content/blog/2022/writing-transparent-tiering-solution.md#L52)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Maybe more general - memory tiers monitoring? I would agree that some monitoring is need but I could imagine e.g. traffic monitoring or free space monitoring..
</blockquote></details>

modified to "monitoring hotness or other metrics"
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 53 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50UjNf2CdW_wh0Pp9L:-N54yKSO9AsxtlQLRung:b-bnpas9) ([raw file](https://github.com/pmem/pmem.github.io/blob/50b75ae19223ce66c4b9084839157061f2421eaf/content/blog/2022/writing-transparent-tiering-solution.md#L53)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Allocation decision making?
</blockquote></details>

I will keep it general; we need to decide where to place allocations, when to move, etc.

I don't want to bloat these points, I want the readers to have the impression that they understand things.
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 54 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50Ue067a5k4FXEeBpd:-N54yi190OoEY1gu3czx:b-lohbrp) ([raw file](https://github.com/pmem/pmem.github.io/blob/50b75ae19223ce66c4b9084839157061f2421eaf/content/blog/2022/writing-transparent-tiering-solution.md#L54)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

page movement is optional
</blockquote></details>

Changed the whole paragraph to:

In order to satisfy those requirements, the basic functionalities must
be implemented:

- handling configuration,
- monitoring hotness or other metrics,
- decision-making,
- page movement (or intelligent data placement).
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 97 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50W8mH1EqpDcAACec_:-N54z0zv6whQbXy6nau5:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/50b75ae19223ce66c4b9084839157061f2421eaf/content/blog/2022/writing-transparent-tiering-solution.md#L97)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

DRAM
</blockquote></details>

Done.
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 33 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50Zf8s--Ba89U0oh1O:-N50oUvFCwk6jfgg2Irj:b118ogo) ([raw file](https://github.com/pmem/pmem.github.io/blob/235a48c154da8e9c8d52b3a4db64f33261fb184f/content/blog/2022/writing-transparent-tiering-solution.md#L33)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

again, split at 80.
</blockquote></details>

Done, as before - omitted links, images and metadata at the top of the page.
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 34 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50ZdvuDx9VOsfuOM2L:-N50pP1BC49Xax4US88J:b-8ldxjj) ([raw file](https://github.com/pmem/pmem.github.io/blob/235a48c154da8e9c8d52b3a4db64f33261fb184f/content/blog/2022/writing-transparent-tiering-solution.md#L34)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

high-level overview

Does the last sentence mean that readers can learn about that stuff or that they should have that knowledge already? I think you meant the former, but right now, to me at least, it seems that the current sentence has the latter meaning.
</blockquote></details>

changed:
benefit from -> learn some
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 85 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50Wuqr8MNB6XQrYIdg:-N55QznY4NNZ8syshTxj:bblh94c) ([raw file](https://github.com/pmem/pmem.github.io/blob/235a48c154da8e9c8d52b3a4db64f33261fb184f/content/blog/2022/writing-transparent-tiering-solution.md#L85)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

here you add that hotness is only one of things we could like to monitor - other metrics could be free space, bandwidth, etc
</blockquote></details>

Added a whole paragraph: Other metrics
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 91 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50aEXx8QkrAjBKoj5i:-N55TFY3Bh5AiY8FW0ww:bdxoj4z) ([raw file](https://github.com/pmem/pmem.github.io/blob/235a48c154da8e9c8d52b3a4db64f33261fb184f/content/blog/2022/writing-transparent-tiering-solution.md#L91)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

various performance overheads depending on the underlying implementation.

?
</blockquote></details>

From what I know, it uses the same mechanism as memory reclaimer; I'm not sure if there are multiple underlying implementations, I would feel safer without  [...]

2022-06-21 14:52 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/252)* status: all files reviewed, 10 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, and @pbalcer)

___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 6 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50StR6AMU0Ce7C7KYM:-N55iIZhEXtNyRxDkA1J:bj8xk7a) ([raw file](https://github.com/pmem/pmem.github.io/blob/50b75ae19223ce66c4b9084839157061f2421eaf/content/blog/2022/writing-transparent-tiering-solution.md#L6)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

This was auto-generated by *hugo*, I would prefer not to change it. Besides, creation date is not the same as publication date
</blockquote></details>

in my blog note @pbalcer asked me to update that ..  
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 54 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50Ue067a5k4FXEeBpd:-N55i1DY369HSRIra_sb:bnb9exj) ([raw file](https://github.com/pmem/pmem.github.io/blob/50b75ae19223ce66c4b9084839157061f2421eaf/content/blog/2022/writing-transparent-tiering-solution.md#L54)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Changed the whole paragraph to:

In order to satisfy those requirements, the basic functionalities must
be implemented:

- handling configuration,
- monitoring hotness or other metrics,
- decision-making,
- page movement (or intelligent data placement).

</blockquote></details>

For "monitoring ... " the "or" part is without parentheses - could you unify this? Also, you could write it as: 
* action: intelligent data placement or movement


<!-- Sent from Reviewable.io -->

2022-06-22 07:23 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/252)* status: all files reviewed, 11 unresolved discussions (waiting on @maciekpac and @pbalcer)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N59HoRI7t2H7HGAosfB:-N59HoRI7t2H7HGAosfC:b-13mdfq) (no related file):*
can you please provide a preview? :)

___
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 6 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50StR6AMU0Ce7C7KYM:-N59GDIBBK6OYcFtND8n:b-gdwsgw) ([raw file](https://github.com/pmem/pmem.github.io/blob/50b75ae19223ce66c4b9084839157061f2421eaf/content/blog/2022/writing-transparent-tiering-solution.md#L6)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

in my blog note @pbalcer asked me to update that ..  
</blockquote></details>

I think we rather use it as a "publication" date - I'm not sure if *hugo* has a separate value for that, and it looks just better when we publish something and it has a more recent date


<!-- Sent from Reviewable.io -->

2022-06-22 11:24 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/252)* status: 3 of 4 files reviewed, 11 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, and @pbalcer)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N59HoRI7t2H7HGAosfB:-N5A8xz43hSmA8kcKbLD:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can you please provide a preview? :)
</blockquote></details>

Done.

___
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 6 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50StR6AMU0Ce7C7KYM:-N5A0ByJ1bdySUYMR6qp:b-hepnlm) ([raw file](https://github.com/pmem/pmem.github.io/blob/50b75ae19223ce66c4b9084839157061f2421eaf/content/blog/2022/writing-transparent-tiering-solution.md#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think we rather use it as a "publication" date - I'm not sure if *hugo* has a separate value for that, and it looks just better when we publish something and it has a more recent date
</blockquote></details>

Updated to today
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 54 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50Ue067a5k4FXEeBpd:-N5A325E43urblePRiu3:b-qg84l9) ([raw file](https://github.com/pmem/pmem.github.io/blob/50b75ae19223ce66c4b9084839157061f2421eaf/content/blog/2022/writing-transparent-tiering-solution.md#L54)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

For "monitoring ... " the "or" part is without parentheses - could you unify this? Also, you could write it as: 
* action: intelligent data placement or movement
</blockquote></details>

Modified to:

- handling configuration,
- monitoring hotness or other metrics,
- decision-making,
- action: page movement or intelligent data placement.

Also, added a paragraph "intelligent data placement"


<!-- Sent from Reviewable.io -->

2022-06-22 12:56 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/252)* status: all files reviewed, 9 unresolved discussions (waiting on @lukaszstolarczuk and @pbalcer)

___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 289 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5ATx7s29kjrU302s02:-N5ATx7t8M2VICUUPUWM:b-vi3k2h) ([raw file](https://github.com/pmem/pmem.github.io/blob/62536965b0ce5faa4f0138d571cb50d0e88e3fe8/content/blog/2022/writing-transparent-tiering-solution.md#L289)):*
> ```Markdown
> 
> Moreover, intelligent placement requires overriding the default allocator,
> e.g. with LD_PRELOAD - more on that in the next section.
> ```

great :)


<!-- Sent from Reviewable.io -->

2022-06-22 13:00 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/252)* status: 3 of 4 files reviewed, 9 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, and @pbalcer)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N59HoRI7t2H7HGAosfB:-N5AUvxu9GYh3MeISQCx:b-n2vwwq) (no related file):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Done.
</blockquote></details>

https://maciekpac.github.io/blog/2022/06/writing-transparent-tiering-solution/

___


<!-- Sent from Reviewable.io -->

2022-06-22 15:09 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/252)* status: all files reviewed, 9 unresolved discussions (waiting on @lukaszstolarczuk and @pbalcer)



<!-- Sent from Reviewable.io -->

2022-06-27 06:53 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/252)* status: all files reviewed, 9 unresolved discussions (waiting on @lukaszstolarczuk and @pbalcer)



<!-- Sent from Reviewable.io -->

2022-06-28 10:00 UTC, pbalcer requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/252)* status: all files reviewed, 9 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, and @pbalcer)

___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 93 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50acHjDiG7BKTS4USf:-N5dhVtE8h7pk4QDKbSb:b-91lhlc) ([raw file](https://github.com/pmem/pmem.github.io/blob/235a48c154da8e9c8d52b3a4db64f33261fb184f/content/blog/2022/writing-transparent-tiering-solution.md#L93)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

That the purpose of DAMON, once you know the full name (Data Access MONitor) is obvious. Should I remove *ba dum tss* ?
</blockquote></details>

it's fine.
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 67 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5dcNv8DWeoQ_VTzDvJ:-N5dcNv8DWeoQ_VTzDvK:b-hccyit) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L67)):*
> ```Markdown
> - action: page movement or intelligent data placement.
> 
> All of them can be implemented either in user space, using the libnuma library,
> ```

lib(rary) numa library

using [libnuma][link...].
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 73 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5dcePS4fVDoWUiAzRG:-N5dcePS4fVDoWUiAzRH:b-ym3dq6) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L73)):*
> ```Markdown
> ### Options - user space vs kernel space
> 
> One of the first decisions to make is to decide on whether the solution should
> ```

the first decision is to decide

`The first decision is choosing whether`

?
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 95 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5deeGL734Vcu-pVHsk:-N5deeGL734Vcu-pVHsl:berneaw) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L95)):*
> ```Markdown
> with neither,
> - portability: a user space solution should work with many different production
> systems, typically those who meet the minimum up-to-date criteria,
> ```

those that meet
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 96 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5detci1nHqXKb1FeTE:-N5detci1nHqXKb1FeTF:bmqs8rp) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L96)):*
> ```Markdown
> - portability: a user space solution should work with many different production
> systems, typically those who meet the minimum up-to-date criteria,
> - access to allocations - lower granularity than OS, which can only move pages.
> ```

can you elaborate a little bit more? 
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 108 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5df3MtAN-nMp82JFAW:-N5df3MtAN-nMp82JFAX:b-f1ce01) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L108)):*
> ```Markdown
> hotness might be placed on the same pages in user space, so that kernal can
> efficiently move data between different tiers. The placement can be done
> either in allocation time or in runtime, by merging partially-empty pages.
> ```

at allocation time or at runtime (?)
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 222 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5dj6eG5nM_MS9f78TQ:-N5dj6eG5nM_MS9f78TR:b-k6yvee) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L222)):*
> ```Markdown
> What is important is not really when the page was used for the last time, but
> when and how often it would be used in the future. The person who knows such
> thighs best is probably either the program developer, whom we cannot ask (per
> ```

things


<!-- Sent from Reviewable.io -->

2022-06-28 15:11 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/252)* status: all files reviewed, 21 unresolved discussions (waiting on @maciekpac and @pbalcer)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N59HoRI7t2H7HGAosfB:-N5eqjd2DQn66iEiwEfr:bnyw1fd) (no related file):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

https://maciekpac.github.io/blog/2022/06/writing-transparent-tiering-solution/
</blockquote></details>

thx!

FYI, the link changed :wink: 

https://maciekpac.github.io/blog/2022/06/memory-tiering-part-2-writing-transparent-tiering-solution/

___
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 3 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50S_jX3PqX4lhe-AiE:-N5erK__0Bd7y9tKMv3s:b-dbpicv) ([raw file](https://github.com/pmem/pmem.github.io/blob/50b75ae19223ce66c4b9084839157061f2421eaf/content/blog/2022/writing-transparent-tiering-solution.md#L3)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Hmm this was supposed to be "Memory Tiering (part 3)", but (part 2) awaits approval; I would just leave it as-is, unless we want to wait another few weeks for the second one.
</blockquote></details>

maybe add a link to the previous part? and add info on how it relates...?
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 83 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5ejfSO3QDuEjWSVCXo:-N5ejfSO3QDuEjWSVCXp:b-6wy1dy) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L83)):*
> ```Markdown
>     - calling syscalls in a loop is not that efficient,
> - better integration with default kernel balancing possible,
> - can use data structures from kernel, lower overhead:
> ```

hmm... you use "impersonal" verbs/nouns like "handling", "better integration possible" and here suddenly "can use" :wink: - perhaps `usage of kernel's data structures, ...`
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 84 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5ek-hUENjBkQHYKQjF:-N5ek-hUENjBkQHYKQjG:b-hppdc3) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L84)):*
> ```Markdown
> - better integration with default kernel balancing possible,
> - can use data structures from kernel, lower overhead:
>     - no need to duplicate data between userspace and kernelspace in order to
> ```

`userspace` & `kernelspace` (missing spaces)
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 102 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5ekqulE-JdcQjuGqe0:-N5ekqum4bcMj4DAeaVP:b-vjawod) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L102)):*
> ```Markdown
> systems that handle
> [balancing in kernel](https://documentation.suse.com/sles/15-SP1/html/SLES-all/cha-tuning-numactl.html),
> and in user space, available and on different stages of development.
> ```

`available` is written twice in this sentence
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 105 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5el-Oy50TsQK8fNDdD:-N5el-Oy50TsQK8fNDdE:b-3z7g8j) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L105)):*
> ```Markdown
> 
> There is also another question - can user and kernel space solutions work
> together? There are plenty of opportunities for that, e.g. objects of similar
> ```

`, e.g., `
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 110 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5el7bB8YVL89fz3yEJ:-N5el7bB8YVL89fz3yEK:b-wufkmj) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L110)):*
> ```Markdown
> either in allocation time or in runtime, by merging partially-empty pages.
> There is always a question of cost and of possible performance gain -
> performing any logic in ```malloc()``` can impact performance a lot, but so
> ```

nit: you can use just a single \` notation
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 117 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5emT9sD88CyyIxOYeS:-N5emT9sD88CyyIxOYeT:b-smk30f) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L117)):*
> ```Markdown
> It might seem to be a trivial thing to do, but the mechanism of configuring
> the application also requires some thought. In user space, a text config file
> or arguments passed via command line might be enough, but a kernel solution
> ```

`...enough. A kernel ...`
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 119 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5em_Dh4pxpYyx0NZL5:-N5em_Dh4pxpYyx0NZL6:bentyl0) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L119)):*
> ```Markdown
> or arguments passed via command line might be enough, but a kernel solution
> would require a more complicated config handling, either via additional system
> calls, or by a special file, e.g. writing to which would trigger
> ```

`calls or` (no comma)
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 119 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5emcVf-5dc6jLO4iBP:-N5emcVgB4v-VIKcuyUB:b-3z7g8j) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L119)):*
> ```Markdown
> or arguments passed via command line might be enough, but a kernel solution
> would require a more complicated config handling, either via additional system
> calls, or by a special file, e.g. writing to which would trigger
> ```

`, e.g., `
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 132 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5en3OGCjOhQsy5L9w-:-N5en3OH6F3Zr5DcqxCX:b-ypbfl4) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L132)):*
> ```Markdown
> easier to deal with in kernel space. A good example is the hotness tracking
> mechanism
> [from the Linux kernel](https://documentation.suse.com/sles/15-SP1/html/SLES-all/cha-tuning-numactl.html),
> ```

just confirming - this link is supposed to be the same one as was used above?

nit: if you want to re-use the same link, you can use syntax like e.g. in this post:
https://raw.githubusercontent.com/pmem/pmem.github.io/main/content/blog/2022/tiering-1.md
(see the absolute bottom of that file)
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 178 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5eodRF28x-rZUKe1Ew:-N5eodRF28x-rZUKe1Ex:bozladn) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L178)):*
> ```Markdown
> [instruction-level parallelism](https://en.wikipedia.org/wiki/Instruction-level_parallelism).
> [Branch prediction](https://en.wikipedia.org/wiki/Branch_predictor) and
> [instruction pipelineing](https://en.wikipedia.org/wiki/Instruction_pipelining)
> ```

`pipelineing` -> `pipelining`
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 201 at r6](https://reviewable.io/reviews/p [...]

2022-06-29 11:22 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/252)* status: 3 of 4 files reviewed, 21 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, and @pbalcer)

___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 3 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50S_jX3PqX4lhe-AiE:-N5jBciD4lundbVtA-D3:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/50b75ae19223ce66c4b9084839157061f2421eaf/content/blog/2022/writing-transparent-tiering-solution.md#L3)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe add a link to the previous part? and add info on how it relates...?
</blockquote></details>

Done.
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 93 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N50acHjDiG7BKTS4USf:-N5j-lj1EgYpkK_woXjf:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/235a48c154da8e9c8d52b3a4db64f33261fb184f/content/blog/2022/writing-transparent-tiering-solution.md#L93)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

it's fine.
</blockquote></details>

Done.
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 67 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5dcNv8DWeoQ_VTzDvJ:-N5j35J70OCq-sONBSSA:b-6z0law) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L67)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

lib(rary) numa library

using [libnuma][link...].
</blockquote></details>

corrected everywhere
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 73 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5dcePS4fVDoWUiAzRG:-N5iUKhf6QQHV2ZuL5oY:bej7x7y) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L73)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

the first decision is to decide

`The first decision is choosing whether`

?
</blockquote></details>

Changed to:

One of the first decisions to make is to choose whether the solution should
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 83 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5ejfSO3QDuEjWSVCXo:-N5iUzG3576WydE-X7zN:b-xb4cs) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L83)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm... you use "impersonal" verbs/nouns like "handling", "better integration possible" and here suddenly "can use" :wink: - perhaps `usage of kernel's data structures, ...`
</blockquote></details>

Changed to "availability of"
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 84 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5ek-hUENjBkQHYKQjF:-N5iV8lIB270zLmkSkST:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L84)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`userspace` & `kernelspace` (missing spaces)
</blockquote></details>

Done.
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 95 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5deeGL734Vcu-pVHsk:-N5ijUQv6Dl9bgeua30f:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L95)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

those that meet
</blockquote></details>

Done.
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 96 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5detci1nHqXKb1FeTE:-N5in5uv53-xUXzkPvu1:b-zhakhm) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L96)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

can you elaborate a little bit more? 
</blockquote></details>

Added the following paragraph:
```
The last point might need some clarification - individual allocations cannot
be moved between tiers, only pages can; however, individual allocations
are done in user space, with only occassional ```mmap()``` being handled
by the OS when the user space library (i.e. glibc, jemalloc, tcmalloc, mimalloc
or any other allocator) runs out of memory. It means that kernel only knows
about mappings; in the user space, individual calls to ```malloc()```
and ```free()``` can be hijacked and used for data placement, tier prediction
or grouping similar data on the same pages, so that it works better
with transparent data movement.
```
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 102 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5ekqulE-JdcQjuGqe0:-N5inJZ_8gHPWlvC4W6t:bwpsxwp) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L102)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`available` is written twice in this sentence
</blockquote></details>

shortened the sentence to
```
and in user space.```
```

___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 105 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5el-Oy50TsQK8fNDdD:-N5iyOVn8XmP4yDPz00M:b310so2) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L105)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`, e.g., `
</blockquote></details>

I was a little bit surprised to see the comma after *e.g.*, but it looks like it is used in AmE, which is our target.

https://en.wiktionary.org/wiki/e.g.

Corrected everywhere (Find & Replace All)
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 108 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5df3MtAN-nMp82JFAW:-N5j-9DuEHzXvincWGlI:b-5ys1rz) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L108)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

at allocation time or at runtime (?)
</blockquote></details>

google indeed shows more results for *at* runtime, modified everywhere
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 110 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5el7bB8YVL89fz3yEJ:-N5j-GPC2WKLfpRBAOHy:b-fmz9dz) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L110)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

nit: you can use just a single \` notation
</blockquote></details>

Thanks, I will keep it in mind for the future, but I think I will leave it as-is - it's rendered the same way and I think it makes no sense to modify it right now, especially because I might introduce errors in the process.
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 117 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5emT9sD88 [...]

2022-06-29 11:37 UTC, lukaszstolarczuk reviewed
:+1: 

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/252#-:-N5jF8we0RDkoAI9hgUa:b-8fx2u7)* status: all files reviewed, 8 unresolved discussions (waiting on @pbalcer)

___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 105 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5el-Oy50TsQK8fNDdD:-N5jEMq1Dyr5QDhj7NRE:b-lqpj30) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L105)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I was a little bit surprised to see the comma after *e.g.*, but it looks like it is used in AmE, which is our target.

https://en.wiktionary.org/wiki/e.g.

Corrected everywhere (Find & Replace All)
</blockquote></details>

huh, I never knew they use it differently in the UK, thx
___
*[`content/blog/2022/writing-transparent-tiering-solution.md` line 110 at r6](https://reviewable.io/reviews/pmem/pmem.github.io/252#-N5el7bB8YVL89fz3yEJ:-N5jEbBzBmP0goLI6LLO:b-8fx2u7) ([raw file](https://github.com/pmem/pmem.github.io/blob/07e4ab734b33b24071b12d9d0ba0373c6ec348ec/content/blog/2022/writing-transparent-tiering-solution.md#L110)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Thanks, I will keep it in mind for the future, but I think I will leave it as-is - it's rendered the same way and I think it makes no sense to modify it right now, especially because I might introduce errors in the process.
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->

2022-06-29 11:58 UTC, pbalcer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/252#-:-N5jJrO-A0z7kMhnxT3h:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)



<!-- Sent from Reviewable.io -->

2022-06-29 12:47 UTC, merged