Add libpmem2 part 1 blog post
pmem/pmem.github.io pull request #253
Opened 2022-06-20 12:50 UTC by wlemkows

2022-06-20 15:33 UTC, pbalcer requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/253)* status: 0 of 1 files reviewed, 13 unresolved discussions (waiting on @pbalcer and @wlemkows)

___
*[`content/blog/2022/libpmem2-part1.md` line 40 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50eM442SDRONLOxQYG:-N50eM454TSTcdy3YW0J:b4s6ulv) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L40)):*
> ```Markdown
> history. About seven years ago, the first persistent memory library
> known as [libpmem][libpmem-man] was started. The concept of persistent
> memory was becoming a reality. Initially, the [libpmem][libpmem-man] library
> ```

the pmem library or just `libpmem`
___
*[`content/blog/2022/libpmem2-part1.md` line 43 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50e_7aCg4VJ0mgj-ZS:-N50e_7aCg4VJ0mgj-ZT:b2p6xk3) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L43)):*
> ```Markdown
> provided simple support for memory allocation operations on pmem. Over time,
> hardware and software developments and customer needs made it necessary to
> develop the library with new features such as support for Windows, DevDax, RAS,
> ```

to evolve the library to include new features
___
*[`content/blog/2022/libpmem2-part1.md` line 49 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50eelb9-6GHE4n7CWI:-N50eelb9-6GHE4n7CWJ:bc5g7p9) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L49)):*
> ```Markdown
> ## New concept, new structures
> 
> [Libpmem2][libpmem2-man] is a low-level standalone library providing a
> ```

pmem2 is a 
___
*[`content/blog/2022/libpmem2-part1.md` line 56 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50emFBAg14MszzsfCT:-N50emFBAg14MszzsfCU:bacujtc) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L56)):*
> ```Markdown
> One of the big changes in [libpmem2][libpmem2-man] is the abandonment of this
> mechanism in favor of a more intuitive  and structured solution where the user
> does not have to deal with directly checking for the presence of pmem memory.
> ```

`... of persistent memory memory.`

just pmem.
___
*[`content/blog/2022/libpmem2-part1.md` line 57 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50evx-3aGfwe00eJqw:-N50evx-3aGfwe00eJqx:b-rwygd9) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L57)):*
> ```Markdown
> mechanism in favor of a more intuitive  and structured solution where the user
> does not have to deal with directly checking for the presence of pmem memory.
> He gets a set of structures on which he operates, and all the detection happens
> ```

Instead, software gets a set of structures on which it operates, 
___
*[`content/blog/2022/libpmem2-part1.md` line 63 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50fCvw58NEFLke-5qs:-N50fCvw58NEFLke-5qt:b-woldcp) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L63)):*
> ```Markdown
> **result = what + how**, where:
> 
> **map (result)** - this is created mapping in the virtual addreess space, represented
> ```

- the virtual address space mapping, represented...
___
*[`content/blog/2022/libpmem2-part1.md` line 64 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50fK5vEI6Hq9ieh6DU:-N50fK5vEI6Hq9ieh6DV:b-jk9rqi) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L64)):*
> ```Markdown
> 
> **map (result)** - this is created mapping in the virtual addreess space, represented
> in the library as a *pmem2_map* structure, on such a resulting object functions can be
> ```

. Through this object, software can access ... by calling the appropriate functions.
___
*[`content/blog/2022/libpmem2-part1.md` line 66 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50fW9l3dC3HT4PkvV7:-N50fW9l3dC3HT4PkvV8:b-arjtcm) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L66)):*
> ```Markdown
> in the library as a *pmem2_map* structure, on such a resulting object functions can be
> executed to read its address ([pmem2_map_get_address][pmem2-map-get-address]), ([pmem2_map_get_size][pmem2-map-get-size]),
> granularity ([pmem2_map_get_store_granularity][pmem2-map-get-store-granularity]) or flushing functions (about those in a moment).
> ```

more about these in a moment.
___
*[`content/blog/2022/libpmem2-part1.md` line 106 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50gQ12A1ZFWVkR4cBa:-N50gQ12A1ZFWVkR4cBb:b-a9td9d) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L106)):*
> ```Markdown
> caches are also protected during power failure and only the SFENCE command is necessary to
> maintain full data persistence. No flushing functions are necessary, so the write granularity is
> the finest, although it should be noted that the mechanism used here is neither optimal nor fast
> ```

?

was this meant to be in reference to deep_flush?
___
*[`content/blog/2022/libpmem2-part1.md` line 141 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50hsEL-UtpSI2UYv8M:-N50hsEL-UtpSI2UYv8N:b-usnpkh) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L141)):*
> ```Markdown
> - set the required store granularity to PAGE - the setting is correct,
> and writes will be performed at the best option for the user, in this case, cache line granularity.
> - set the required store granularity to CACHELINE - the setting is correct and writes will be
> ```

and writes will be performed using the highest-performance option available
___
*[`content/blog/2022/libpmem2-part1.md` line 253 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50i8qBCKIdPyeXMhie:-N50i8qBCKIdPyeXMhif:b-tn5zob) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L253)):*
> ```Markdown
> First, the pointer to the persistence function for the given map was read
> and then the function was called. No additional action from the user was required.
> The user does not have to decide which way to persist choose.
> ```

The software doesn't have to make any decisions on how to persist data.
___
*[`content/blog/2022/libpmem2-part1.md` line 256 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50iMNm1xiq1Pr2D4yT:-N50iMNm1xiq1Pr2D4yU:bhdgthy) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L256)):*
> ```Markdown
> The library has all the information required to perform this operation
> based on the previously declared granularity and the system properties.
> Exactly the same mechanism is applied to other functions operating on the *pmem2 map* object:
> ```

drop 'exactly'
___
*[`content/blog/2022/libpmem2-part1.md` line 261 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50iSQ3BBcWfl7ogbM4:-N50iSQ3BBcWfl7ogbM5:bguj3uz) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L261)):*
> ```Markdown
> ## Summary
> 
> This blog ends with the above example. You have learned the basic concept and functionality of the *libpmem2* library.
> ```

`In this blog post, I've discussed the basic concept and functionality of *libpmem2*. In the next post in this series, I [...]

2022-06-20 15:41 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/253)* status: 0 of 1 files reviewed, 43 unresolved discussions (waiting on @lukaszstolarczuk, @pbalcer, and @wlemkows)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50hit96Rf7ovCynLv-:-N50hit96Rf7ovCynLv0:bwmrl38) (no related file):*
can you please provide a preview of rendered post (on your fork)?

___
___
*[`content/blog/2022/libpmem2-part1.md` line 40 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50dug82QpvNouYhG1u:-N50dug82QpvNouYhG1v:b-bmk2z0) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L40)):*
> ```Markdown
> history. About seven years ago, the first persistent memory library
> known as [libpmem][libpmem-man] was started. The concept of persistent
> memory was becoming a reality. Initially, the [libpmem][libpmem-man] library
> ```

you don't have to link twice, the same link in a row
___
*[`content/blog/2022/libpmem2-part1.md` line 42 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50esTF3u3Co8k9Zj-9:-N50esTF3u3Co8k9Zj-A:b7rgz0s) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L42)):*
> ```Markdown
> memory was becoming a reality. Initially, the [libpmem][libpmem-man] library
> provided simple support for memory allocation operations on pmem. Over time,
> hardware and software developments and customer needs made it necessary to
> ```

`hw and sw developments`? did you mean `development of hw and sw`?
___
*[`content/blog/2022/libpmem2-part1.md` line 43 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50eDgN6H5bxXfdZyDz:-N50eDgO0vFkdwnwV2Qo:b-5u6jm0) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L43)):*
> ```Markdown
> provided simple support for memory allocation operations on pmem. Over time,
> hardware and software developments and customer needs made it necessary to
> develop the library with new features such as support for Windows, DevDax, RAS,
> ```

you may add links to our pmem glossary for these abbreviations
___
*[`content/blog/2022/libpmem2-part1.md` line 45 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50fAFsDEl-0fGmM8mn:-N50fAFsDEl-0fGmM8mo:bsues9k) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L45)):*
> ```Markdown
> develop the library with new features such as support for Windows, DevDax, RAS,
> eADR, and others. The initial API design was no longer sufficient
> and flexible. This led us to create an improved version of libpmem: [libpmem2][libpmem2-man].
> ```

again - link over and over to the same place is not required, I think :wink: 
___
*[`content/blog/2022/libpmem2-part1.md` line 55 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50fq436D8LYbn04m27:-N50fq436D8LYbn04m28:b-eekqgp) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L55)):*
> ```Markdown
> 
> One of the big changes in [libpmem2][libpmem2-man] is the abandonment of this
> mechanism in favor of a more intuitive  and structured solution where the user
> ```

This sentence is quite long - maybe finish up after "structured solution. The user now..."
___
*[`content/blog/2022/libpmem2-part1.md` line 56 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50fbyE40-VWVO34ea7:-N50fbyE40-VWVO34ea8:b-kldrns) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L56)):*
> ```Markdown
> One of the big changes in [libpmem2][libpmem2-man] is the abandonment of this
> mechanism in favor of a more intuitive  and structured solution where the user
> does not have to deal with directly checking for the presence of pmem memory.
> ```

either `... not have to directly check for ...` or `... not have to deal with direct checking for ...`
___
*[`content/blog/2022/libpmem2-part1.md` line 57 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50g033CUXIbqwzu2QO:-N50g033CUXIbqwzu2QP:bsjbr7m) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L57)):*
> ```Markdown
> mechanism in favor of a more intuitive  and structured solution where the user
> does not have to deal with directly checking for the presence of pmem memory.
> He gets a set of structures on which he operates, and all the detection happens
> ```

"he" - >"they" or continue with "user" or just switch to "you" :wink: 
___
*[`content/blog/2022/libpmem2-part1.md` line 63 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50gMmm6flG2z9cM8Vq:-N50gMmm6flG2z9cM8Vr:bhhzdw8) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L63)):*
> ```Markdown
> **result = what + how**, where:
> 
> **map (result)** - this is created mapping in the virtual addreess space, represented
> ```

this is the
___
*[`content/blog/2022/libpmem2-part1.md` line 63 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50gP_D86N39Wqsei6c:-N50gP_D86N39Wqsei6d:bwfcdb1) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L63)):*
> ```Markdown
> **result = what + how**, where:
> 
> **map (result)** - this is created mapping in the virtual addreess space, represented
> ```

`addreess` misspell
___
*[`content/blog/2022/libpmem2-part1.md` line 64 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50gZSc9PCMg0H8Ondg:-N50gZSc9PCMg0H8Ondh:b-y26gun) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L64)):*
> ```Markdown
> 
> **map (result)** - this is created mapping in the virtual addreess space, represented
> in the library as a *pmem2_map* structure, on such a resulting object functions can be
> ```

perhaps re-phrase, e.g.
`... structure. This structure can be later used ...`
___
*[`content/blog/2022/libpmem2-part1.md` line 68 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50hyCZ1Hwb9_9rBLCt:-N50hyCZ1Hwb9_9rBLCu:bts2h9k) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L68)):*
> ```Markdown
> granularity ([pmem2_map_get_store_granularity][pmem2-map-get-store-granularity]) or flushing functions (about those in a moment).
> 
> **source (what)** - information necessary to create a new *pmem2_map*, the object is represented as
> ```

`... a new *pmem2_map*, ...` I think it should be either `;` or `-`
___
*[`content/blog/2022/libpmem2-part1.md` line 69 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50i9BVAX9PoI6EQshQ:-N50i9BVAX9PoI6EQshR:b-ukaw8e) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L69)):*
> ```Markdown
> 
> **source (what)** - information necessary to create a new *pmem2_map*, the object is represented as
> *pmem2_source* structure in the library. As a source, you can use a file with the file descriptor,
> ```

either drop this `in the library` or move it to: "is represented in the lib as"
___
*[`content/blog/2022/libpmem2-part1.md` line 69 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50iT-S-DoVzfc9ZWiD:-N50iT-S-DoVzfc9ZWiE:banxrqj) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L69)):*
> ```Markdown
> 
> **source (what)** - information necessary to create a new *pmem2_map*, the object  [...]

2022-06-22 11:45 UTC, wlemkows reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/253)* status: 0 of 1 files reviewed, 43 unresolved discussions (waiting on @lukaszstolarczuk and @pbalcer)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50hit96Rf7ovCynLv-:-N5ADTtN6NQXJcfqGVl9:bknhi3g) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can you please provide a preview of rendered post (on your fork)?
</blockquote></details>

https://wlemkows.github.io/blog/2022/06/introduction-to-libpmem2-part-1/

___
___
*[`content/blog/2022/libpmem2-part1.md` line 40 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50eM442SDRONLOxQYG:-N54QTR6C0jf9htKgCqh:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L40)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

the pmem library or just `libpmem`
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 40 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50dug82QpvNouYhG1u:-N54Qk4R3qaqowWAzEHR:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L40)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you don't have to link twice, the same link in a row
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 42 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50esTF3u3Co8k9Zj-9:-N54R6EkE7xTqs8WEf27:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`hw and sw developments`? did you mean `development of hw and sw`?
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 43 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50e_7aCg4VJ0mgj-ZS:-N54RHXZ-ROZFf6UDI8g:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L43)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

to evolve the library to include new features
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 43 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50eDgN6H5bxXfdZyDz:-N54hJao6xmHfqgC-VkH:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L43)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you may add links to our pmem glossary for these abbreviations
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 45 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50fAFsDEl-0fGmM8mn:-N54hMhL7lQ2I1A93tPR:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L45)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

again - link over and over to the same place is not required, I think :wink: 
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 49 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50eelb9-6GHE4n7CWI:-N54hgfO6BKYmU2-AeIj:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L49)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

pmem2 is a 
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 55 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50fq436D8LYbn04m27:-N54hzYO8fV9w1_QfMt3:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L55)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

This sentence is quite long - maybe finish up after "structured solution. The user now..."
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 56 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50emFBAg14MszzsfCT:-N54i_5tCmzQXosbkxqF:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L56)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

`... of persistent memory memory.`

just pmem.

</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 56 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50fbyE40-VWVO34ea7:-N54kV7L80IkPcGlWGIM:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L56)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

either `... not have to directly check for ...` or `... not have to deal with direct checking for ...`
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 57 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50evx-3aGfwe00eJqw:-N54kgf15tDpTTXD2VAo:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L57)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

Instead, software gets a set of structures on which it operates, 
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 57 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50g033CUXIbqwzu2QO:-N54kxIx8dLMrnzws_QB:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L57)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"he" - >"they" or continue with "user" or just switch to "you" :wink: 
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 63 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50fCvw58NEFLke-5qs:-N54l9Fe1-_nR4RjapF1:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L63)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

- the virtual address space mapping, represented...
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 63 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50gMmm6flG2z9cM8Vq:-N54l9eMETnT5RKBGkjt:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L63)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this is the
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 63 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50gP_D86N39Wqsei6c:-N54lFlz7m_pDyTJrLQY:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L63)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`addreess` misspell
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 64 at r1](https [...]

2022-06-23 07:54 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/253)* status: all files reviewed, 32 unresolved discussions (waiting on @lukaszstolarczuk, @pbalcer, and @wlemkows)

___
*[`content/blog/2022/libpmem2-part1.md` line 42 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50esTF3u3Co8k9Zj-9:-N5EOPkqBjMKmiHNNmXm:buoz12) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L42)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm not sure if you can put a comma like this, now `software` is just out of context, I think.

I believe it should be no comma at all (you list only 2 things now "development of something" and "customer needs"):
`Over time, development of hardware and software and customer needs...`
___
*[`content/blog/2022/libpmem2-part1.md` line 81 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50jw0MBd6wAGRbKoWk:-N5ES-fSEUi23s1X1Tgu:b-3weg52) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L81)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`in the in the` :wink: 
___
*[`content/blog/2022/libpmem2-part1.md` line 85 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50kLNoCA36gEUfKbwA:-N5ESGwL40nxMrieaGP8:b-lnd2z4) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L85)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

hmm maybe it should be mentioned in the section above...?
___
*[`content/blog/2022/libpmem2-part1.md` line 28 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5EN_WuC-ly-_iAFvc7:-N5EN_WvByftppwbWhLF:br3gy01) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L28)):*
> ```Markdown
> blogs: ['PMDK']
> # Blog tags
> tags: ["libpmem2", "pmem2", "Intro"]
> ```

I think you can drop "pmem2"
___
*[`content/blog/2022/libpmem2-part1.md` line 36 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5ENiOg7bs0EiiD26x5:-N5ENiOg7bs0EiiD26x6:b-axav4v) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L36)):*
> ```Markdown
> ## A new beginning
> 
> This blog post will be about the recently created new library [libpmem2][libpmem2-man]
> ```

"recently created" or "new" :wink: 
___
*[`content/blog/2022/libpmem2-part1.md` line 37 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5ENu5dBW1YZNqqklJu:-N5ENu5dBW1YZNqqklJv:b2uzqb0) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L37)):*
> ```Markdown
> 
> This blog post will be about the recently created new library [libpmem2][libpmem2-man]
> in the PMDK. Before we go into details it's worth having a short look at the 
> ```

`... libpmem2 in the PMDK` maybe something like: `... libpmem2, which is a part of PMDK set of libraries.` or `... delivered as part of PMDK repository.` or something like that
___
*[`content/blog/2022/libpmem2-part1.md` line 44 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5EP73B7QGwIR7W9hHX:-N5EP73B7QGwIR7W9hHY:b-uitv40) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L44)):*
> ```Markdown
> development of hardware, software, and customer needs made it necessary to
> evolve the library to include new features such as support for Windows,
> [DevDax, RAS, eADR, and others][glossary-page]. The initial API design was no longer sufficient
> ```

not sure if `, and others` should be under the link, as well :wink: 
___
*[`content/blog/2022/libpmem2-part1.md` line 90 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5ESybLCeosrux8ray8:-N5ESybLCeosrux8ray9:bpiqgp7) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L90)):*
> ```Markdown
> Setting the granularity is the last step needed to successfully create a complete `pmem2_map` object.
> 
> Granularity is a value that was not present in the *libpmem*, this is another big difference
> ```

hmm.. I think it should be split into 2 sentences:
`*libpmem*. This is`
___
*[`content/blog/2022/libpmem2-part1.md` line 98 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5ETYhkAm59VfgYpft_:-N5ETYhkAm59VfgYpfta:b613zsn) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L98)):*
> ```Markdown
> - One that has traditional block storage devices (SSD, HDD) and must use system API calls such as `msync()`,
> `fsync()` on Linux, or `FlushFileBuffers()`, `FlushViewOfFile()` on Windows to write data reliably.
> In this case, each write is rounded up to page size, it is not possible to do a single write of smaller size.
> ```

I'd add "and":
`... to page size and it is not`
___
*[`content/blog/2022/libpmem2-part1.md` line 104 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5ETow751EE8SRfiPpJ:-N5ETow751EE8SRfiPpK:b-rhmali) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L104)):*
> ```Markdown
> For these instructions, the best possible write to memory is the size of the cache line.
> 
> - Or, a platform with an available eARD and the largest persistence domain where the processor
> ```

`eARD` misspell
___
*[`content/blog/2022/libpmem2-part1.md` line 104 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5EU48MBnnpVDvm_OGY:-N5EU48MBnnpVDvm_OGZ:b2741fn) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L104)):*
> ```Markdown
> For these instructions, the best possible write to memory is the size of the cache line.
> 
> - Or, a platform with an available eARD and the largest persistence domain where the processor
> ```

that's quite a long sentence, perhaps:
`during power failure. Only ...`
___
*[`content/blog/2022/libpmem2-part1.md` line 121 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5EUa5FCm9dhw-JTx9C:-N5EUa5FCm9dhw-JTx9D:b-i25u8b) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L121)):*
> ```Markdown
> ```
> 
> So back to creating our map recipe we need to set the granularity of interest in
> ```

`recipe, we`
___
*[`content/blog/2022/libpmem2-part1.md` line 135 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5EVohrBsincJEG7Ie8:-N5EVohrBsincJEG7Ie9:bl7bl3c) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L135)):*
> ```Markdown
> in this case, page granularity.
> - set the required store granularity to CACHELINE - your platform does not support it,
> the requirement is not merged, and you get an unhandled granularity error.
> ```

`the requirement is not merged` did you mean "met"?
___
*[`content/blog/2022/libpmem2-part1.md` line 161 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5EWlbo4NByW-bo5Wuu:-N5EWlbo4NByW-bo5Wuv:b95d43y) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L161)):*
> ```Markdown
> and writes will be performed using the highest-performance option available,
> in this case, byte granularit [...]

2022-06-24 10:37 UTC, pbalcer requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/253)* status: all files reviewed, 23 unresolved discussions (waiting on @lukaszstolarczuk, @pbalcer, and @wlemkows)

___
*[`content/blog/2022/libpmem2-part1.md` line 40 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50eM442SDRONLOxQYG:-N5K9LEXAvPoMt3x6K1N:b-4qwj5b) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L40)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

don't use articles before proper nouns. "Initially, libpmem provided ..."
___
*[`content/blog/2022/libpmem2-part1.md` line 42 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50esTF3u3Co8k9Zj-9:-N5K9flBBBk5nuROHAUA:b-w0a5ob) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure if you can put a comma like this, now `software` is just out of context, I think.

I believe it should be no comma at all (you list only 2 things now "development of something" and "customer needs"):
`Over time, development of hardware and software and customer needs...`
</blockquote></details>

I think it's fine with the comma. 
___
*[`content/blog/2022/libpmem2-part1.md` line 85 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50kLNoCA36gEUfKbwA:-N5KAG3m2FyvmTMeKOp4:b-h4y0g5) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L85)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm maybe it should be mentioned in the section above...?
</blockquote></details>

Maybe instead we can just say "The previously discussed parameters were optional. But there's one important configuration option that is mandatory - store granularity."
___
*[`content/blog/2022/libpmem2-part1.md` line 91 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50laD40jOgBQS5_WR2:-N5KAvUpA995xcFgY8AT:b-ik5p3e) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L91)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

It seems to me not so complicated, if I get any more comments in this place I will try to change it.
</blockquote></details>

In libpmem, we use a simple pmem/non-pmem distinction to differentiate between different types of mappings. However, this distinction is insufficient to capture the full spectrum of available platform types and potential differences in power-fail protected domains between systems.
___
*[`content/blog/2022/libpmem2-part1.md` line 109 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5KCUbU0YY8qhiUkaIh:-N5KCUbU0YY8qhiUkaIi:bwvb1fi) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L109)):*
> ```Markdown
> the finest possible.
> 
> As one can easily observe, a division into three types of granularity emerges, successively:
> ```

change one to 'we' (in general, avoid the use of 'we' or 'one' as a pronoun - but stick to one throughout a text if you use something)
drop 'easily'
___
*[`content/blog/2022/libpmem2-part1.md` line 124 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5KFR3EA4mNfDSGN6e9:-N5KFR3EA4mNfDSGN6eA:b-66h5hg) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L124)):*
> ```Markdown
> the config using the [pmem2_config_set_required_store_granularity][pmem2-config-set-required-store-granularity] function.
> The specific feature of this function is that the granularity value passed is not
> the precision with which the data should be written to the medium, but the worst possible
> ```

worst -> largest acceptable value
___
*[`content/blog/2022/libpmem2-part1.md` line 161 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5EWlbo4NByW-bo5Wuu:-N5KGYd6DPE5yABdUWQ9:b-3wj1mf) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L161)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

After reading this section my thought is... "so we do I need this granularity at all?" as long as I set "page" it will not break and always use the best possible choice... or am I missing something?
</blockquote></details>

See the granularity section of libpmem2's man page:
https://pmem.io/pmdk/manpages/linux/master/libpmem2/libpmem2.7/

The relevant paragraph:
```
The software should set this config parameter to a value that most accurately represents the target hardware characteristics and the storage patterns of the application. For example, a database storage engine that operates on large logical pages that reside either on SSDs or PMEM should set this value to PMEM2_GRANULARITY_PAGE.
```
___
*[`content/blog/2022/libpmem2-part1.md` line 186 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5EVC9Z9ehGF1CZwbZ0:-N5KH-Zg7gsOZ5slfErp:b-b4nz38) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L186)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

did you try to remove the HTML tags appearing here...?
</blockquote></details>

Yup, we either need to fix how code is displayed on the website or remove all empty newlines in the snippet...
___
*[`content/blog/2022/libpmem2-part1.md` line 262 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5EYDqcE8ED8kRlFavv:-N5KHMOtDPz2EeRTqswj:b-47w1zk) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L262)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

isn't this sentence pretty much repeated now (with the paragraph above)? please merge this two paragraphs together.
</blockquote></details>

Yes, my intention was to just replace the previous stuff.


<!-- Sent from Reviewable.io -->

2022-06-24 13:50 UTC, wlemkows reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/253)* status: 0 of 1 files reviewed, 20 unresolved discussions (waiting on @lukaszstolarczuk and @pbalcer)

___
*[`content/blog/2022/libpmem2-part1.md` line 40 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50eM442SDRONLOxQYG:-N5KRAdu3q8kuP_pC2iP:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L40)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

don't use articles before proper nouns. "Initially, libpmem provided ..."
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 42 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50esTF3u3Co8k9Zj-9:-N5KRU-s6mlAsIqahxAO:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L42)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

I think it's fine with the comma. 
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 81 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N50jw0MBd6wAGRbKoWk:-N5KTErA2tiSK3Cz7dCs:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bff7a3d9f12177919eb32eadd0a44f4cbc994444/content/blog/2022/libpmem2-part1.md#L81)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`in the in the` :wink: 
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 28 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5EN_WuC-ly-_iAFvc7:-N5KwIMg7Qz2URNBr6fq:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think you can drop "pmem2"
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 36 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5ENiOg7bs0EiiD26x5:-N5KPzqDEhLscBVV1l32:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L36)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"recently created" or "new" :wink: 
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 37 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5ENu5dBW1YZNqqklJu:-N5KQnYjDQm3oNQN5td4:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L37)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`... libpmem2 in the PMDK` maybe something like: `... libpmem2, which is a part of PMDK set of libraries.` or `... delivered as part of PMDK repository.` or something like that
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 90 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5ESybLCeosrux8ray8:-N5KTmuxB6S55eytSbEf:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L90)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm.. I think it should be split into 2 sentences:
`*libpmem*. This is`
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 98 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5ETYhkAm59VfgYpft_:-N5KxYw-DIBmOfa3_fa4:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L98)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'd add "and":
`... to page size and it is not`
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 104 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5ETow751EE8SRfiPpJ:-N5KwRU6EokQomXKPZZR:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L104)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`eARD` misspell
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 104 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5EU48MBnnpVDvm_OGY:-N5Kwe-p-dwUoCwLvOe2:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L104)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

that's quite a long sentence, perhaps:
`during power failure. Only ...`
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 109 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5KCUbU0YY8qhiUkaIh:-N5Kx5pV5n0b7y6dO7sL:b-atvj41) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L109)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

change one to 'we' (in general, avoid the use of 'we' or 'one' as a pronoun - but stick to one throughout a text if you use something)
drop 'easily'
</blockquote></details>

Thank you for this comment, it's always puzzles me.
___
*[`content/blog/2022/libpmem2-part1.md` line 121 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5EUa5FCm9dhw-JTx9C:-N5KTzSHERnVH13VTJSh:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L121)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`recipe, we`
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 124 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5KFR3EA4mNfDSGN6e9:-N5KU87qEU4-_QAyLo-G:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L124)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

worst -> largest acceptable value
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 135 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5EVohrBsincJEG7Ie8:-N5KUOkb4FtWdX0WSs9L:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L135)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`the requirement is not merged` did you mean "met"?
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 262 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5EYDqcE8ED8kRlFavv:-N5KvpdT1QaXvgy2zld9:bpn83yg) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L262)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

Yes, my intention was to just replace the previous stuff.
</blockquote></details>

My intention too,  but I forgot to remove it :) Thanks
___
*[`content/blog/2022/libpmem2-part1.md` line 281 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5EUwg28AizhCFX93De:-N5KUwbA6MT1LLKNoqRA:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/lib [...]

2022-06-24 13:59 UTC, wlemkows reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/253)* status: 0 of 1 files reviewed, 20 unresolved discussions (waiting on @lukaszstolarczuk and @pbalcer)

___
*[`content/blog/2022/libpmem2-part1.md` line 186 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5EVC9Z9ehGF1CZwbZ0:-N5L-c-VEFW8jI4By0ua:bg2nz6i) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L186)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

Yup, we either need to fix how code is displayed on the website or remove all empty newlines in the snippet...
</blockquote></details>

Done.
https://wlemkows.github.io/blog/2022/06/introduction-to-libpmem2-part-1/


<!-- Sent from Reviewable.io -->

2022-06-27 10:19 UTC, pbalcer requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/253)* status: 0 of 1 files reviewed, 21 unresolved discussions (waiting on @lukaszstolarczuk and @wlemkows)

___
*[`content/blog/2022/libpmem2-part1.md` line 37 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5ENu5dBW1YZNqqklJu:-N5ZGnlF0tnpIlouipQV:bbkhyau) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L37)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Missing space before sentences.
___
*[`content/blog/2022/libpmem2-part1.md` line 41 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5Zbwi1DTBFLYsLxKEf:-N5Zbwi1DTBFLYsLxKEg:br1ncyl) ([raw file](https://github.com/pmem/pmem.github.io/blob/6b5e9ae8b0cdcd765205873c50c35b87b99cdb93/content/blog/2022/libpmem2-part1.md#L41)):*
> ```Markdown
> known as [libpmem][libpmem-man] was started. The concept of persistent
> memory was becoming a reality. Initially, libpmem provided simple support
> for memory allocation operations on pmem. Over time,
> ```

memory management
___
*[`content/blog/2022/libpmem2-part1.md` line 45 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5Zc2Gd78hmt8dZT2NM:-N5Zc2Gd78hmt8dZT2NN:b-txwphl) ([raw file](https://github.com/pmem/pmem.github.io/blob/6b5e9ae8b0cdcd765205873c50c35b87b99cdb93/content/blog/2022/libpmem2-part1.md#L45)):*
> ```Markdown
> evolve the library to include new features such as support for Windows,
> [DevDax, RAS, eADR][glossary-page], and others. The initial API design was no longer sufficient
> and flexible. This led us to create an improved version of libpmem: **libpmem2**.
> ```

... sufficient and it wasn't flexible enough to extend.
___
*[`content/blog/2022/libpmem2-part1.md` line 82 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5ZdXY9C_sQJi44AdVC:-N5ZdXY9C_sQJi44AdVD:btzhyyj) ([raw file](https://github.com/pmem/pmem.github.io/blob/6b5e9ae8b0cdcd765205873c50c35b87b99cdb93/content/blog/2022/libpmem2-part1.md#L82)):*
> ```Markdown
> starting from very basic features like setting length ([pmem2_config_set_length][pmem2-config-set-length]), setting offset ([pmem2_config_set_offset][pmem2-config-set-offset]), defining mapping visibility ([pmem2_config_set_sharing][pmem2-config-set-sharing]), to more advanced features for indicating
> reservations ([pmem2_config_set_vm_reservation][pmem2-config-set-vm-reservation]), which will be discussed in the next part
> of this blog post series
> ```

missing `.` (`series.`)
___
*[`content/blog/2022/libpmem2-part1.md` line 86 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5Zdr2-0hojjgkGpVng:-N5Zdr200QKLWkzDq-HN:b-y3yi1b) ([raw file](https://github.com/pmem/pmem.github.io/blob/6b5e9ae8b0cdcd765205873c50c35b87b99cdb93/content/blog/2022/libpmem2-part1.md#L86)):*
> ```Markdown
> ## Meet granularity
> 
> The previously discussed parameters were optional. But there's one important configuration
> ```

are optional
___
*[`content/blog/2022/libpmem2-part1.md` line 164 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5ZeKOd2uDlLDz4jJXn:-N5ZeKOd2uDlLDz4jJXo:b-hx2mga) ([raw file](https://github.com/pmem/pmem.github.io/blob/6b5e9ae8b0cdcd765205873c50c35b87b99cdb93/content/blog/2022/libpmem2-part1.md#L164)):*
> ```Markdown
> in this case, byte granularity.
> 
> The behavior of the function should be clearer now, but even if you're still not sure
> ```

this sentence seems to be conflating the reader's understanding of granularity and runtime's understanding of granularity by software.
I would just remove the entire first part, leaving just:
`If you are not sure what the effective ...`


<!-- Sent from Reviewable.io -->

2022-06-27 14:18 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/253)* status: all files reviewed, 8 unresolved discussions (waiting on @lukaszstolarczuk, @pbalcer, and @wlemkows)

___
*[`content/blog/2022/libpmem2-part1.md` line 161 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5EWlbo4NByW-bo5Wuu:-N5_UO5l84j29GdqVxKy:b-dwwcqj) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L161)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

See the granularity section of libpmem2's man page:
https://pmem.io/pmdk/manpages/linux/master/libpmem2/libpmem2.7/

The relevant paragraph:
```
The software should set this config parameter to a value that most accurately represents the target hardware characteristics and the storage patterns of the application. For example, a database storage engine that operates on large logical pages that reside either on SSDs or PMEM should set this value to PMEM2_GRANULARITY_PAGE.
```
</blockquote></details>

yeah, I think I understand how it works, but based **purely on this blog post** I wouldn't understand why not just set "page" and leave pmem2 to pick the best option for me.

What confuses me is:

- in the intro paragraph it's said `the largest acceptable value that you as **the user allow**`, but later, in examples it always says:
`writes will be performed using the highest-performance option available, in this case XYZ` - so my understanding is, that the platform always picks the best option, and it makes the user input irrelevant

- in the manpage it says: `the library will create mappings where the new map granularity is lower or equal to the requested one.` - it may be lower, but (if I understand correctly), not always **the lowest**


<!-- Sent from Reviewable.io -->

2022-06-28 08:47 UTC, pbalcer reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/253)* status: all files reviewed, 8 unresolved discussions (waiting on @lukaszstolarczuk and @wlemkows)

___
*[`content/blog/2022/libpmem2-part1.md` line 161 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5EWlbo4NByW-bo5Wuu:-N5dSxaA0as4qpsvF54E:brjfgk1) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L161)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

yeah, I think I understand how it works, but based **purely on this blog post** I wouldn't understand why not just set "page" and leave pmem2 to pick the best option for me.

What confuses me is:

- in the intro paragraph it's said `the largest acceptable value that you as **the user allow**`, but later, in examples it always says:
`writes will be performed using the highest-performance option available, in this case XYZ` - so my understanding is, that the platform always picks the best option, and it makes the user input irrelevant

- in the manpage it says: `the library will create mappings where the new map granularity is lower or equal to the requested one.` - it may be lower, but (if I understand correctly), not always **the lowest**
</blockquote></details>

User software makes a granularity decision based on what makes sense for the storage algorithms that it uses. At runtime, pmem2 will detect what is the actual granularity of the underlying storage media, compare that against the chosen granularity, and then will either allow or decline to create a mapping using. If created, the mapping will have the highest-performance granularity option available at that precise moment. This is ok because libpmem2 does not define any functional differences between granularities.


<!-- Sent from Reviewable.io -->

2022-06-29 13:05 UTC, wlemkows reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/253)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`content/blog/2022/libpmem2-part1.md` line 161 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5EWlbo4NByW-bo5Wuu:-N5jZGoICGSWFqADetRg:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/7161cf1133bb8c74b4875e80870fbb509ce9718d/content/blog/2022/libpmem2-part1.md#L161)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done.
___
*[`content/blog/2022/libpmem2-part1.md` line 6 at r5](https://reviewable.io/reviews/pmem/pmem.github.io/253#-N5eg0WV4VVYcvO2glt4:-N5jZGP_4rmWkEj3Jkyo:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/4bc494a513f35dac4f3317652290c4ac9a4d436d/content/blog/2022/libpmem2-part1.md#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls bump this date :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-30 11:29 UTC, merged