add memkind sub-page
pmem/pmem.github.io pull request #262
Opened 2022-07-05 10:01 UTC by szadam

2022-07-05 10:17 UTC, lukaszstolarczuk reviewed
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk and @szadam)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6Cot8OBvnLiwvVG8jh:-N6Cot8OBvnLiwvVG8ji:b7br9k9) (no related file):*
on your fork the CI failed with some random message :smile: 

https://github.com/szadam/szadam.github.io/actions

___
*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6CrDXW-CC3NKOM6jNG:-N6CrDXW-CC3NKOM6jNH:bn3yl0y) (no related file):*
please add a link here with a preview of rendered website (on your fork)

___
___
*[`content/memkind/_index.md` line 15 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6Co0mi1TADLTIZ4aUU:-N6Co0mi1TADLTIZ4aUV:b-8u834p) ([raw file](https://github.com/pmem/pmem.github.io/blob/65704bf75a91e80deb21ab2be360bf881fe42ddb/content/memkind/_index.md#L15)):*
> ```Markdown
>     - script page 'themes/pmem-hugo/layouts/memkind/list.html', and
>     - content in 'data/<lang>/memkind'
> -->
> ```

missing EOF (in all files)


<!-- Sent from Reviewable.io -->

2022-07-06 10:41 UTC, lukaszstolarczuk commented
do you want a review here or in #264? 😉 

also, when you solve a review issue, please mark it as done (on Reviewable)

2022-07-06 14:30 UTC, szadam commented
okey, done





<!-- Sent from Reviewable.io -->

2022-07-06 14:30 UTC, szadam commented
*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6Cot8OBvnLiwvVG8jh:-N6IuvX51ApoOcOrimWm:bb7f2mf) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

on your fork the CI failed with some random message :smile: 

https://github.com/szadam/szadam.github.io/actions
</blockquote></details>

done




<!-- Sent from Reviewable.io -->

2022-07-06 14:31 UTC, szadam commented
*[`content/memkind/_index.md` line 15 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6Co0mi1TADLTIZ4aUU:-N6Iv2L5B6CrUg5EuBx-:bb7f2mf) ([raw file](https://github.com/pmem/pmem.github.io/blob/c644ca92e2e0d83b936ad11649bce15ad009d187/content/memkind/_index.md#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

missing EOF (in all files)
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-07-07 06:34 UTC, lukaszstolarczuk reviewed
hint: you can un-draft, if you believe this PR is ready for review :wink: 

> Reviewed 1 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262#-:-N6MMH4yAt8NFoRgzvlE:b6whq89)* status: all files reviewed, 4 unresolved discussions (waiting on @pbalcer and @szadam)

___
*[`data/en/memkind.yml` line 14 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6MLFa77nkogLMYlCPF:-N6MLFa77nkogLMYlCPG:bar0ze9) ([raw file](https://github.com/pmem/pmem.github.io/blob/8ceaada58b9aa9d03b3ff2f03b4767b69e4a96c1/data/en/memkind.yml#L14)):*
> ```YAML
>   content: "<p>The kinds of memory are defined by operating system memory policies that have been applied to virtual address ranges. Memory characteristics supported by memkind without user extension include control of NUMA and page size features. The jemalloc non-standard interface has been extended to enable specialized arenas to make requests for virtual memory from the operating system through the memkind partition interface. Through the other memkind interfaces the user can control and extend memory partition features and allocate memory while selecting enabled features.</p>
>             <p>Memkind is hosted on <a href=\"https://github.com/memkind\">GitHub</a></p>"
> ```

I think you should write here, at least a little, about why this project is on `pmem.io` website :wink: how are these related (you can mark this for a future update, it's not necessary now, I believe)
___
*[`data/en/memkind.yml` line 19 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6MKsVq7DTkVznENt1s:-N6MKsVrDTR_tDOux9Kh:b6tc6my) ([raw file](https://github.com/pmem/pmem.github.io/blob/8ceaada58b9aa9d03b3ff2f03b4767b69e4a96c1/data/en/memkind.yml#L19)):*
> ```YAML
>   enable: true
>   title: "Sources"
>   content: "<code>$ git clone https://github.com/memkind/memkind.git</code>"
> ```

I personally don't like that it just starts with the clone command and below are some links :wink: I know this is just an initial content of this web page, but in the future, I believe this should be updated
___
*[`data/en/memkind.yml` line 53 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6MKjio1OXMCyOB8acG:-N6MKjio1OXMCyOB8acH:bx04at1) ([raw file](https://github.com/pmem/pmem.github.io/blob/8ceaada58b9aa9d03b3ff2f03b4767b69e4a96c1/data/en/memkind.yml#L53)):*
> ```YAML
>   enable: true
>   content: "The contents of this web site and the associated <a href=\"https://github.com/pmem\">GitHub repositories</a> are BSD-licensed open source."
>   
> ```

still no EOL (you can see here this red mark)
___
*[`themes/pmem-hugo/layouts/memkind/list.html` line 89 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6MKc2cE3NGQ1bRm2F6:-N6MKc2d-YMax6RywNoV:biuopng) ([raw file](https://github.com/pmem/pmem.github.io/blob/8ceaada58b9aa9d03b3ff2f03b4767b69e4a96c1/themes/pmem-hugo/layouts/memkind/list.html#L89)):*
> ```HTML
> 
>   {{ end }}
>   
> ```

.

(the same issue)


<!-- Sent from Reviewable.io -->

2022-07-07 07:44 UTC, szadam commented
*[`data/en/memkind.yml` line 53 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6MKjio1OXMCyOB8acG:-N6MbPBE2tHVlheM0JTK:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/8ceaada58b9aa9d03b3ff2f03b4767b69e4a96c1/data/en/memkind.yml#L53)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

still no EOL (you can see here this red mark)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-07 07:44 UTC, szadam commented
*[`themes/pmem-hugo/layouts/memkind/list.html` line 89 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6MKc2cE3NGQ1bRm2F6:-N6MbTuE5G2QERfU6V_i:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/8ceaada58b9aa9d03b3ff2f03b4767b69e4a96c1/themes/pmem-hugo/layouts/memkind/list.html#L89)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.

(the same issue)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-07 07:58 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 2 unresolved discussions (waiting on @pbalcer and @szadam)



<!-- Sent from Reviewable.io -->

2022-07-07 08:19 UTC, szadam reviewed
> Reviewed 1 of 3 files at r2, 5 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 2 unresolved discussions (waiting on @pbalcer and @szadam)



<!-- Sent from Reviewable.io -->

2022-07-07 09:46 UTC, pbalcer requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 3 unresolved discussions (waiting on @szadam)

___
*[`data/en/memkind.yml` line 12 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6N1MgE5gb4HG1MfgUM:-N6N1MgE5gb4HG1MfgUN:bxwib4f) ([raw file](https://github.com/pmem/pmem.github.io/blob/c7eec6752761d9b7b8cdcc900d07c93bebb7ad13/data/en/memkind.yml#L12)):*
> ```YAML
>   enable: true
>   title: "Overview"
>   content: "<p>The kinds of memory are defined by operating system memory policies that have been applied to virtual address ranges. Memory characteristics supported by memkind without user extension include control of NUMA and page size features. The jemalloc non-standard interface has been extended to enable specialized arenas to make requests for virtual memory from the operating system through the memkind partition interface. Through the other memkind interfaces the user can control and extend memory partition features and allocate memory while selecting enabled features.</p>
> ```

This overview is outdated and somewhat flawed. I guess we can merge it as-is, but ideally, I'd like to see something better written that matches what memkind is today.


<!-- Sent from Reviewable.io -->

2022-07-08 10:28 UTC, PatKamin reviewed
> Reviewed 1 of 3 files at r2, 3 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 5 unresolved discussions (waiting on @bratpiorka, @kilobyte, @maciekpac, and @szadam)

___
*[`data/en/memkind.yml` line 13 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6SK6jp0uNEaZNqP_f4:-N6SK6jp0uNEaZNqP_f5:b-girnhg) ([raw file](https://github.com/pmem/pmem.github.io/blob/c7eec6752761d9b7b8cdcc900d07c93bebb7ad13/data/en/memkind.yml#L13)):*
> ```YAML
>   title: "Overview"
>   content: "<p>The kinds of memory are defined by operating system memory policies that have been applied to virtual address ranges. Memory characteristics supported by memkind without user extension include control of NUMA and page size features. The jemalloc non-standard interface has been extended to enable specialized arenas to make requests for virtual memory from the operating system through the memkind partition interface. Through the other memkind interfaces the user can control and extend memory partition features and allocate memory while selecting enabled features.</p>
>             <p>Memkind is hosted on <a href=\"https://github.com/memkind\">GitHub</a></p>"
> ```

I would redirect here to the repository itself: github.com/memkind/memkind
___
*[`data/en/memkind.yml` line 45 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6S2U5-3y8q54NLkW3E:-N6S2U5-3y8q54NLkW3F:b9nl9qo) ([raw file](https://github.com/pmem/pmem.github.io/blob/c7eec6752761d9b7b8cdcc900d07c93bebb7ad13/data/en/memkind.yml#L45)):*
> ```YAML
>           content: "<a href=\"https://github.com/memkind/memkind/issues/\">Create an issue</a> in our GitHub issues database. This is a good way to report problems or request new features."
>         list_item2:
>           content: "Join our <a href=\"https://groups.google.com/group/pmem\">Google Group</a> to participate in discussions on memkind, including the design of th API and future directions."
> ```

the design of **the** API


<!-- Sent from Reviewable.io -->

2022-07-08 14:30 UTC, bratpiorka commented
@lukaszstolarczuk we decided to keep 1 PR with all commits instead of merging "incomplete" page





<!-- Sent from Reviewable.io -->

2022-07-11 13:14 UTC, szadam commented
*[`data/en/memkind.yml` line 45 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6S2U5-3y8q54NLkW3E:-N6hOGWd1SSA5sH6BNSY:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/c7eec6752761d9b7b8cdcc900d07c93bebb7ad13/data/en/memkind.yml#L45)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

the design of **the** API
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-11 13:16 UTC, PatKamin reviewed
> Reviewed 3 of 6 files at r7, 3 of 4 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 4 unresolved discussions (waiting on @bratpiorka, @kilobyte, @maciekpac, and @szadam)



<!-- Sent from Reviewable.io -->

2022-07-11 13:33 UTC, bratpiorka reviewed
> Reviewed 1 of 3 files at r2, 3 of 5 files at r3, 1 of 2 files at r4, 1 of 7 files at r6, 3 of 6 files at r7, 2 of 4 files at r8, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 6 unresolved discussions (waiting on @kilobyte, @maciekpac, @PatKamin, and @szadam)

___
*[`data/en/memkind.yml` line 5 at r10](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6hS_yh7-nt3_6AGKUt:-N6hS_yh7-nt3_6AGKUu:b-qkjx1s) ([raw file](https://github.com/pmem/pmem.github.io/blob/aff249f060f1f4764a86127792cc6ac77e686b11/data/en/memkind.yml#L5)):*
> ```YAML
>   enable: true
>   bg_image: '/images/backgrounds/faq_header.jpg'
>   title: 'Memkind'
> ```

start from lowercase letter - "memkind"
___
*[`data/en/memkind.yml` line 13 at r10](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6hRXnS785MWiTsVk37:-N6hRXnT6EkzbHjtJRFX:b-dk0ct3) ([raw file](https://github.com/pmem/pmem.github.io/blob/aff249f060f1f4764a86127792cc6ac77e686b11/data/en/memkind.yml#L13)):*
> ```YAML
>   title: "Overview"
>   content: "<p>The kinds of memory are defined by operating system memory policies that have been applied to virtual address ranges. Memory characteristics supported by memkind without user extension include control of NUMA and page size features. The jemalloc non-standard interface has been extended to enable specialized arenas to make requests for virtual memory from the operating system through the memkind partition interface. Through the other memkind interfaces the user can control and extend memory partition features and allocate memory while selecting enabled features.</p>
>             <p>Memkind is hosted on <a href=\"https://github.com/memkind/memkind\">GitHub</a></p>"
> ```

please move "Memkind is hosted ... " sentence to paragraph below and change it to:

Memkind is hosted on GitHub [link]. To clone memkind repository please run the following command:

$ git clone https://github.com/memkind/memkind.git

Needed dependencies and detailed build instructions can be found in memkind’s readme [https://github.com/memkind/memkind/blob/master/README.md] file. 

or something like that


<!-- Sent from Reviewable.io -->

2022-07-12 09:35 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 7 unresolved discussions (waiting on @kilobyte, @maciekpac, and @szadam)

___
*[`data/en/memkind.yml` line 6 at r10](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6lk_i3E8YiFa26FQRf:-N6lk_i3E8YiFa26FQRg:b-4evk6s) ([raw file](https://github.com/pmem/pmem.github.io/blob/aff249f060f1f4764a86127792cc6ac77e686b11/data/en/memkind.yml#L6)):*
> ```YAML
>   bg_image: '/images/backgrounds/faq_header.jpg'
>   title: 'Memkind'
>   content: "User Extensible Heap Manager built on top of jemalloc which enables control of memory characteristics and a partitioning of the heap between kinds of memory."
> ```

I think you could remove "content" entirely and leave only the "overview" section.
___
*[`data/en/memkind.yml` line 12 at r10](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6lf0VZ8e9tHGA5o8L2:-N6lf0VZ8e9tHGA5o8L3:b-an6rym) ([raw file](https://github.com/pmem/pmem.github.io/blob/aff249f060f1f4764a86127792cc6ac77e686b11/data/en/memkind.yml#L12)):*
> ```YAML
>   enable: true
>   title: "Overview"
>   content: "<p>The kinds of memory are defined by operating system memory policies that have been applied to virtual address ranges. Memory characteristics supported by memkind without user extension include control of NUMA and page size features. The jemalloc non-standard interface has been extended to enable specialized arenas to make requests for virtual memory from the operating system through the memkind partition interface. Through the other memkind interfaces the user can control and extend memory partition features and allocate memory while selecting enabled features.</p>
> ```

please change this paragraph to: 


Memkind [https://github.com/memkind/Memkind] is an easy-to-use, general-purpose allocator built on top of jemalloc [https://github.com/jemalloc/jemalloc] which emphasizes fragmentation avoidance and scalable concurrency support. Memkind helps to fully utilize various kinds of memory available in the system, including DRAM, NVDIMM, and HBM, mostly by adding one additional argument - destination kind of memory – to standard malloc API calls. It also offers a transparent mode that allows memory tiering without any modification to the existing app, memory kinds based on file-backed memory on specified device or area supplied by the user, and much more. 


<!-- Sent from Reviewable.io -->

2022-07-13 07:58 UTC, szadam commented
*[`data/en/memkind.yml` line 5 at r10](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6hS_yh7-nt3_6AGKUt:-N6qZJQz41UIzpKf1veG:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/aff249f060f1f4764a86127792cc6ac77e686b11/data/en/memkind.yml#L5)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

start from lowercase letter - "memkind"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-13 07:58 UTC, szadam commented
*[`data/en/memkind.yml` line 6 at r10](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6lk_i3E8YiFa26FQRf:-N6qZKmo-EfkGwl6mpLh:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/aff249f060f1f4764a86127792cc6ac77e686b11/data/en/memkind.yml#L6)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I think you could remove "content" entirely and leave only the "overview" section.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-13 07:58 UTC, szadam commented
*[`data/en/memkind.yml` line 12 at r10](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6lf0VZ8e9tHGA5o8L2:-N6qZLy62VVqzoQXSGIq:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/aff249f060f1f4764a86127792cc6ac77e686b11/data/en/memkind.yml#L12)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please change this paragraph to: 


Memkind [https://github.com/memkind/Memkind] is an easy-to-use, general-purpose allocator built on top of jemalloc [https://github.com/jemalloc/jemalloc] which emphasizes fragmentation avoidance and scalable concurrency support. Memkind helps to fully utilize various kinds of memory available in the system, including DRAM, NVDIMM, and HBM, mostly by adding one additional argument - destination kind of memory – to standard malloc API calls. It also offers a transparent mode that allows memory tiering without any modification to the existing app, memory kinds based on file-backed memory on specified device or area supplied by the user, and much more. 




</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-13 07:59 UTC, szadam commented
*[`data/en/memkind.yml` line 13 at r10](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6hRXnS785MWiTsVk37:-N6qZNGF3YvkqO9GO9_5:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/aff249f060f1f4764a86127792cc6ac77e686b11/data/en/memkind.yml#L13)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please move "Memkind is hosted ... " sentence to paragraph below and change it to:

Memkind is hosted on GitHub [link]. To clone memkind repository please run the following command:

$ git clone https://github.com/memkind/memkind.git

Needed dependencies and detailed build instructions can be found in memkind’s readme [https://github.com/memkind/memkind/blob/master/README.md] file. 

or something like that
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-13 09:57 UTC, bratpiorka reviewed
> Reviewed 1 of 2 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 4 unresolved discussions (waiting on @kilobyte, @maciekpac, and @szadam)

___
*[`data/en/memkind.yml` line 20 at r12](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6qyvRK6v7pAjpp5wk3:-N6qyvRK6v7pAjpp5wk4:b-50gtbp) ([raw file](https://github.com/pmem/pmem.github.io/blob/6d5fd3eba02e973977cd9a452378bb15eadbadff/data/en/memkind.yml#L20)):*
> ```YAML
>     content1: "<p>Memkind is hosted on <a href=\"https://github.com/memkind/memkind\">GitHub</a>. To clone memkind repository please run the following command:</p>"
>     code:    "<p>$ git clone https://github.com/memkind/memkind.git</p>"
>     content2: "<p>Needed dependencies and detailed build instructions can be found in memkind's <a href=\"https://github.com/memkind/memkind/blob/master/README.md\">readme</a> file.</p>"
> ```

please add after "git clone..." sth like "You could also download latest packed sources using links below: " and move tar/zip links right after this sentence. Next please end up this paragraph with "Needed dependencies...."


<!-- Sent from Reviewable.io -->

2022-07-13 15:20 UTC, szadam commented
To view the documentation, follow the link: https://szadam.github.io/memkind/manpages/memkindallocator.3/

2022-07-13 15:21 UTC, szadam reviewed
> Reviewed 3 of 6 files at r7, 3 of 4 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 2 of 2 files at r13, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 4 unresolved discussions (waiting on @bratpiorka, @kilobyte, @maciekpac, and @szadam)



<!-- Sent from Reviewable.io -->

2022-07-13 15:37 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 6 files at r7, 1 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 8 unresolved discussions (waiting on @bratpiorka, @kilobyte, @maciekpac, and @szadam)

___
*[`content/memkind/manpages/memkindallocator.3.md` line 12 at r14](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6sBvtV9gp3uWSkCK1a:-N6sBvtV9gp3uWSkCK1b:bk6j7v6) ([raw file](https://github.com/pmem/pmem.github.io/blob/85e2ef30820cd001e1c948d280651727cd21858b/content/memkind/manpages/memkindallocator.3.md#L12)):*
> ```Markdown
> 
> [comment]: <> (SPDX-License-Identifier: BSD-2-Clause)
> [comment]: <> (Copyright 2019-2021, Intel Corporation)
> ```

2022 :wink: 
___
*[`content/memkind/manpages/memkindallocator.3.md` line 16 at r14](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6sBxhH1plvD61cCSY2:-N6sBxhH1plvD61cCSY3:bl726el) ([raw file](https://github.com/pmem/pmem.github.io/blob/85e2ef30820cd001e1c948d280651727cd21858b/content/memkind/manpages/memkindallocator.3.md#L16)):*
> ```Markdown
> [comment]: <> (libpmemkv.3 -- man page for libpmemkv)
> 
> [NAME](#name)<br />
> ```

instead of `<br />` you can just type `\` in md files
___
*[`content/memkind/manpages/memkindallocator.3.md` line 155 at r14](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6sCJS20kCSQp5i2k4m:-N6sCJS20kCSQp5i2k4n:b3kqx) ([raw file](https://github.com/pmem/pmem.github.io/blob/85e2ef30820cd001e1c948d280651727cd21858b/content/memkind/manpages/memkindallocator.3.md#L155)):*
> ```Markdown
> ## COPYRIGHT ##
> 
> Copyright (C) 2019 - 2021 Intel Corporation. All rights reserved.
> ```

.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 159 at r14](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6sC5tI178FJRYpn2dr:-N6sC5tI178FJRYpn2ds:b2kv30d) ([raw file](https://github.com/pmem/pmem.github.io/blob/85e2ef30820cd001e1c948d280651727cd21858b/content/memkind/manpages/memkindallocator.3.md#L159)):*
> ```Markdown
> ## SEE ALSO ##
> 
> **memkind**(3)
> ```

missing EOF
___
*[`data/en/memkind.yml` line 36 at r14](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6sBLtYBERisRb--0w3:-N6sBLtYBERisRb--0w4:b5qc7c3) ([raw file](https://github.com/pmem/pmem.github.io/blob/85e2ef30820cd001e1c948d280651727cd21858b/data/en/memkind.yml#L36)):*
> ```YAML
>           content: "<a href=\"https://github.com/memkind/memkind/zipball/master\">ZIP (master)</a>"  
>     link_list2:  
>       content: "Needed dependencies and detailed build instructions can be found in memkind's <a href=\"https://github.com/memkind/memkind/blob/master/README.md\">readme</a> file."
> ```

I believe it'd be better to link to just rendered README file:

https://github.com/memkind/memkind#memkind

// FYI, that `README.md` file in the repos seems just wrong :smile: :wink: 


<!-- Sent from Reviewable.io -->

2022-07-14 08:28 UTC, szadam reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 7 unresolved discussions (waiting on @bratpiorka, @kilobyte, @maciekpac, @pbalcer, and @szadam)

___
*[`data/en/memkind.yml` line 12 at r4](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6N1MgE5gb4HG1MfgUM:-N6vof1T7LqqRiymfhJ3:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/c7eec6752761d9b7b8cdcc900d07c93bebb7ad13/data/en/memkind.yml#L12)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

This overview is outdated and somewhat flawed. I guess we can merge it as-is, but ideally, I'd like to see something better written that matches what memkind is today.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 09:16 UTC, bratpiorka reviewed
> Reviewed 2 of 3 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 11 unresolved discussions (waiting on @kilobyte, @maciekpac, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/memkindallocator.3.md` line 64 at r14](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6vjObZ6fcJ1EuCSokF:-N6vjObZ6fcJ1EuCSokG:b-fiim66) ([raw file](https://github.com/pmem/pmem.github.io/blob/85e2ef30820cd001e1c948d280651727cd21858b/content/memkind/manpages/memkindallocator.3.md#L64)):*
> ```Markdown
> 
> `libmemkind::kinds::HIGHEST_CAPACITY_LOCAL`
> :   Allocate from a NUMA node that has the highest capacity among all NUMA Nodes from the local domain. NUMA Nodes have the same local domain for a set of CPUs associated with them, e.g. socket or sub-NUMA cluster. **Note:** If there are multiple NUMA nodes in the same local domain that have the highest capacity - allocation will be done from NUMA node with worse latency attribute. This kind requires locality information described in **SYSTEM CONFIGURATION** section.
> ```

make this a link to a SYSTEM CONFIGURATION section here and in other places



_Code quote:_
```Markdown
**SYSTEM CONFIGURATION**
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 143 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6vzC925AkZRxI34Jub:-N6vzC925AkZRxI34Juc:bj2odwc) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L143)):*
> ```Markdown
> **HUGETLB (huge pages)**
> 
> Current number of "persistent" huge pages can be read from /proc/sys/vm/nr_hugepages file. Proposed way of setting hugepages is: sudo sysctl vm.nr_hugepages=<number_of_hugepages>. More information can be found here: <https://www.kernel.org/doc/Documentation/vm/hugetlbpage.txt>
> ```

format this as a code



_Suggestion:_
```Markdown
sudo sysctl vm.nr_hugepages=<number_of_hugepages>
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 145 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6vzNET-YUtvlRtJTQx:-N6vzNET-YUtvlRtJTQy:bj2odwc) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L145)):*
> ```Markdown
> Current number of "persistent" huge pages can be read from /proc/sys/vm/nr_hugepages file. Proposed way of setting hugepages is: sudo sysctl vm.nr_hugepages=<number_of_hugepages>. More information can be found here: <https://www.kernel.org/doc/Documentation/vm/hugetlbpage.txt>
> 
> Interfaces for obtaining locality information are provided by libhwloc dependency. Functionality based on locality requires that memkind library is configured and built with the support of libhwloc (./configure --enable-hwloc).
> ```

format this as a code



_Code quote:_
```Markdown
./configure --enable-hwloc
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 147 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6vzT76DPriEvxo78gt:-N6vzT76DPriEvxo78gu:bj2odwc) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L147)):*
> ```Markdown
> Interfaces for obtaining locality information are provided by libhwloc dependency. Functionality based on locality requires that memkind library is configured and built with the support of libhwloc (./configure --enable-hwloc).
> 
> Interfaces for obtaining memory performance characteristics information are based on HMAT (Heterogeneous Memory Attribute Table) <https://uefi.org/sites/default/files/resources/ACPI_6_3_final_Jan30.pdf> Functionality based on memory performance characteristics requires that platform configuration fully supports HMAT and memkind library is configured and built with the support of libhwloc (./configure --enable-hwloc).
> ```

format this as a code



_Code quote:_
```Markdown
./configure --enable-hwloc
```
___
*[`data/en/memkind.yml` line 34 at r14](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6viwCM6qrI2jrJDcjU:-N6viwCM6qrI2jrJDcjV:b-r6h09x) ([raw file](https://github.com/pmem/pmem.github.io/blob/85e2ef30820cd001e1c948d280651727cd21858b/data/en/memkind.yml#L34)):*
> ```YAML
>           content: "<a href=\"https://github.com/memkind/memkind/tarball/master\">Tarball (master)</a>"
>         list_item2:
>           content: "<a href=\"https://github.com/memkind/memkind/zipball/master\">ZIP (master)</a>"  
> ```

remove all unnecessary whitespaces here and in other files



_Code quote:_
```YAML
··
```


<!-- Sent from Reviewable.io -->

2022-07-14 10:35 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 13 unresolved discussions (waiting on @kilobyte, @maciekpac, @pbalcer, and @szadam)

___
*[`data/en/memkind.yml` line 19 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wFlV0AGJ9NhFaAUTF:-N6wFlV0AGJ9NhFaAUTG:b-o17mxj) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/data/en/memkind.yml#L19)):*
> ```YAML
>   lists:
>     list_item1:
>       content: "<a href=\"./manpages/memkindallocator.3.html\">memkindallocator API</a>"
> ```

"memkind allocator API" as the name of the link reads better. Also, think about some short description what kinds of information can be found under this link (what part of memkind's API) - especially when other parts of the documentation are added, ie. hbwmalloc API, fixedallocator API.
___
*[`data/en/memkind.yml` line 25 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wGZENExRDvDj93wfS:-N6wGZENExRDvDj93wfT:buxlu64) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/data/en/memkind.yml#L25)):*
> ```YAML
>   enable: true
>   title: "Sources"
>   content: "Memkind is hosted on <a href=\"https://github.com/memkind/memkind\">GitHub</a>. To clone memkind repository please run the following command:"
> ```

I think there should be a comma separating `repository` and `please` words.


<!-- Sent from Reviewable.io -->

2022-07-14 11:17 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 16 unresolved discussions (waiting on @kilobyte, @maciekpac, @pbalcer, and @szadam)

___
*[`data/en/memkind.yml` line 44 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wORnXEGgM1gbxZ4WE:-N6wORnXEGgM1gbxZ4WF:b4cx5q2) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/data/en/memkind.yml#L44)):*
> ```YAML
>   lists:
>     list_item1:
>       content: "<a href=\"http://download.opensuse.org/repositories/home:/patrykka/\">RPMs for misc OSes</a>"
> ```

A sentence or two with an explanation that the packages are created for Fedora and OpenSUSE would be useful. No packages for debian-based OSes here particularly.
___
*[`data/en/memkind.yml` line 65 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wPm2L-B5ucuFSLwk1:-N6wPm2L-B5ucuFSLwk2:b-soyys2) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/data/en/memkind.yml#L65)):*
> ```YAML
>   lists:
>     link_list1:
>       content: "For more information on this library, contact <a href=\"mailto:rafal.rudnicki@intel.com\">Rafal Rudnicki</a>, <a href=\"mailto:patryk.kaminski@intel.com\">Patryk Kaminski</a> or <a href=\"mailto:piotr.balcer@intel.com\">Piotr Balcer</a>. Your participation, feedback, and questions are welcome. You can:"
> ```

Remove a comma after `feedback`.
___
*[`data/en/memkind.yml` line 77 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wPz-C-Vma1XpLfoi8:-N6wPz-C-Vma1XpLfoi9:b-p22wr3) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/data/en/memkind.yml#L77)):*
> ```YAML
> disclaimer:
>   enable: true
>   content: "The contents of this web site and the associated <a href=\"https://github.com/pmem\">GitHub repositories</a> are BSD-licensed open source."
> ```

What about licensing github.com/memkind/memkind repository? Pmem repository is not even being mentioned on this page in opposition to the memkind repo.


<!-- Sent from Reviewable.io -->

2022-07-14 12:23 UTC, szadam commented
*[`content/memkind/manpages/memkindallocator.3.md` line 16 at r14](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6sBxhH1plvD61cCSY2:-N6weOxP2K9jVMGqlSQ6:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/85e2ef30820cd001e1c948d280651727cd21858b/content/memkind/manpages/memkindallocator.3.md#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

instead of `<br />` you can just type `\` in md files
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 12:24 UTC, szadam commented
*[`content/memkind/manpages/memkindallocator.3.md` line 155 at r14](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6sCJS20kCSQp5i2k4m:-N6weeeN34t7lA5xRep9:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/85e2ef30820cd001e1c948d280651727cd21858b/content/memkind/manpages/memkindallocator.3.md#L155)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 12:49 UTC, PatKamin reviewed
> Reviewed 2 of 3 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 36 unresolved discussions (waiting on @kilobyte, @lukaszstolarczuk, @maciekpac, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/memkindallocator.3.md` line 16 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wQZiB-apW5_IKoYjl:-N6wQZiB-apW5_IKoYjm:b-usxj1y) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L16)):*
> ```Markdown
> [comment]: <> (libpmemkv.3 -- man page for libpmemkv)
> 
> [NAME](#name)\
> ```

Maybe it's just me but I see this list of links as some kind of a bug here, like sth that accidentally happens to be on this page. No title to these links and a far bigger font of the first section `NAME` following. Is it possible to add a section name here like `LIST OF CONTENTS` or sth similar without breaking the possibility of generating a manpage from this file? 
___
*[`content/memkind/manpages/memkindallocator.3.md` line 27 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wYc3JDJibvdpoytAP:-N6wYc3JDJibvdpoytAQ:b-bgzo7h) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L27)):*
> ```Markdown
> 
> **libmemkind::static_kind::allocator<T>** - The C++ allocator compatible with the C++ standard library allocator concepts
> Note: memkind_allocator.h functionality is considered as stable API (STANDARD API).
> ```

`Note:` in bold, as in other places in this doc. Please, check on all notes in this doc.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 32 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wROcq8XA51pKqPOUL:-N6wROcq8XA51pKqPOUM:b-n2r2nq) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L32)):*
> ```Markdown
> 
> ```c
> #include <memkin_allocator.h>
> ```

memkind_allocator.h
___
*[`content/memkind/manpages/memkindallocator.3.md` line 49 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wYVa-1iqxje1p2SRx:-N6wYVa-1iqxje1p2SRy:b3vl6j2) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L49)):*
> ```Markdown
> 
> `libmemkind::static_kind::allocator<T>` 
> :   is intended to be used with STL containers to allocate from static kinds memory. Memory management is base on memkind library. Refer **memkind**(3) man page for more details.
> ```

is based on the
___
*[`content/memkind/manpages/memkindallocator.3.md` line 54 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wSAlD46rRyksYDTMm:-N6wSAlD46rRyksYDTMn:b-ovypee) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L54)):*
> ```Markdown
> :   specifies allocator static kinds of memory, representing type of memory which offers different characteristics. The available types of allocator kinds of memory:
> 
> `libmemkind::kinds::DEFAULT` 
> ```

All these kinds should be indented as they provide more precise information to the previous paragraph (`libmemkind::kinds`) and represent a list of options following the colon at the end of the prev paragraph. You can also remove the colon ending the previous paragraph.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 55 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wWsr78QieSXSBwlYq:-N6wWsr78QieSXSBwlYr:b4tgdul) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L55)):*
> ```Markdown
> 
> `libmemkind::kinds::DEFAULT` 
> :   Default allocation using standard memory and default page size.
> ```

Please extend this by adding that the allocation can be made using any NUMA node containing memory.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 64 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wYoPe9zWKQf78GIbk:-N6wYoPe9zWKQf78GIbl:bksrmys) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L64)):*
> ```Markdown
> 
> `libmemkind::kinds::HIGHEST_CAPACITY_LOCAL`
> :   Allocate from a NUMA node that has the highest capacity among all NUMA Nodes from the local domain. NUMA Nodes have the same local domain for a set of CPUs associated with them, e.g. socket or sub-NUMA cluster. **Note:** If there are multiple NUMA nodes in the same local domain that have the highest capacity - allocation will be done from NUMA node with worse latency attribute. This kind requires locality information described in **SYSTEM CONFIGURATION** section.
> ```

`in the SYSTEM CONFIGURATION section` - also in other places.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 88 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6w_sdf1R8xsbXg4bgX:-N6w_sdf1R8xsbXg4bgY:b-k1owy) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L88)):*
> ```Markdown
> 
> `libmemkind::kinds::HBW` 
> :   Allocate from the closest high bandwidth memory NUMA node at the time of allocation. If there is not enough high bandwidth memory to satisfy the request, errno is set to ENOMEM and the allocated pointer is set to NULL. Note: This kind requires memory performance characteristics information described in **SYSTEM CONFIGURATION** section.
> ```

italics



_Code quote:_
```Markdown
errno
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 88 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6waGXUAU5xL7Nd0g8L:-N6waGXUAU5xL7Nd0g8M:bb7dslm) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L88)):*
> ```Markdown
> 
> `libmemkind::kinds::HBW` 
> :   Allocate from the closest high bandwidth memory NUMA node at the time of allocation. If there is not enough high bandwidth memory to satisfy the request, errno is set to ENOMEM and the allocated pointer is set to NULL. Note: This kind requires memory performance characteristics information described in **SYSTEM CONFIGURATION** section.
> ```

bold



_Code quote:_
```Markdown
ENOMEM
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 112 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6watrdBPz_R2HG7FYe:-N6watrdBPz_R2HG7FYf:b-k1owy) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L112)):*
> ```Markdown
> 
> `libmemkind::kinds::DAX_KMEM` 
> :   Allocate from the closest persistent memory NUMA node at the time of allocation. If there is not enough memory in the closest persistent memory NUMA node to satisfy the request, errno is set to **ENOMEM** and the allocated pointer is set to NULL.
> ```

italics



_Code quote:_
```Markdown
errno
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 115 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wb1XKDF85Qe00Vs2A:-N6wb1XKDF85Qe00Vs2B:bo5qqnd) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L115)):*
> ```Markdown
> 
> `libmemkind::kinds::DAX_KMEM_ALL` 
> :   Allocate from the closest persistent memory NUMA node available at the time of allocation. If there is not enough memory on any of persistent memory NUMA nodes to satisfy the request, errno is set to **ENOMEM** and the allocated pointer is set to NULL.
> ```

Italics - change in all other places, too.



_Code quote:_
```Markdown
errno
`` [...]

2022-07-14 13:24 UTC, szadam commented
*[`content/memkind/manpages/memkindallocator.3.md` line 27 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wYc3JDJibvdpoytAP:-N6wsOGFEQu-JvyFZ3W7:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L27)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

`Note:` in bold, as in other places in this doc. Please, check on all notes in this doc.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 13:24 UTC, szadam commented
*[`content/memkind/manpages/memkindallocator.3.md` line 32 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wROcq8XA51pKqPOUL:-N6wsQDB57l4frhJ1DJ9:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L32)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

memkind_allocator.h
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 13:24 UTC, szadam commented
*[`content/memkind/manpages/memkindallocator.3.md` line 64 at r14](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6vjObZ6fcJ1EuCSokF:-N6wsYxE2sHHZPopXVHc:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/85e2ef30820cd001e1c948d280651727cd21858b/content/memkind/manpages/memkindallocator.3.md#L64)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

make this a link to a SYSTEM CONFIGURATION section here and in other places
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 13:25 UTC, szadam commented
*[`content/memkind/manpages/memkindallocator.3.md` line 64 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wYoPe9zWKQf78GIbk:-N6wsaY88Y6yJcx5Pksg:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L64)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

`in the SYSTEM CONFIGURATION section` - also in other places.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 13:25 UTC, szadam commented
*[`content/memkind/manpages/memkindallocator.3.md` line 88 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6w_sdf1R8xsbXg4bgX:-N6wscNG5KkXRfVKwSWL:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L88)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

italics
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 13:25 UTC, szadam commented
*[`content/memkind/manpages/memkindallocator.3.md` line 88 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6waGXUAU5xL7Nd0g8L:-N6wsdMU9HcQLZz4kSWz:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L88)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

bold
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 13:25 UTC, szadam commented
*[`content/memkind/manpages/memkindallocator.3.md` line 115 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wb1XKDF85Qe00Vs2A:-N6wsf42AP0n89B4RNgd:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L115)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Italics - change in all other places, too.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 13:26 UTC, szadam commented
*[`content/memkind/manpages/memkindallocator.3.md` line 143 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6vzC925AkZRxI34Jub:-N6wsotI4NfzP73Kivv1:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L143)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

format this as a code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 13:26 UTC, szadam commented
*[`content/memkind/manpages/memkindallocator.3.md` line 143 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wh7Ha6yZOBdVwErvm:-N6wsr7Q7Q2-CYgG5QW8:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L143)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

italics
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 13:26 UTC, szadam commented
*[`content/memkind/manpages/memkindallocator.3.md` line 145 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6vzNET-YUtvlRtJTQx:-N6wss029hf4jCDaCisx:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L145)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

format this as a code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 13:26 UTC, szadam commented
*[`content/memkind/manpages/memkindallocator.3.md` line 145 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6whILn7yY5TtYDKMi3:-N6wstP89foSOLLThlYT:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L145)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

italics
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 13:26 UTC, szadam commented
*[`content/memkind/manpages/memkindallocator.3.md` line 147 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6vzT76DPriEvxo78gt:-N6wsubw--ClEaq1CKX6:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L147)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

format this as a code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 13:26 UTC, szadam commented
*[`content/memkind/manpages/memkindallocator.3.md` line 147 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6whRoJEIOWuMbAz4ED:-N6wsvdZ1n_GmFI0WdBT:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L147)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Italics, also in other places.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 13:26 UTC, szadam commented
*[`content/memkind/manpages/memkindallocator.3.md` line 147 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wiGYu67jpy1WJwMKl:-N6wswOEAhTm-NbVOqUP:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L147)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Italics, also in other places.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 13:26 UTC, szadam commented
*[`content/memkind/manpages/memkindallocator.3.md` line 147 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wiUcO5852qK9Ado8r:-N6wsz4-6deMrkOoF6p4:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L147)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

`See <link> for more information.` None of the links should be on there own, without a few words of explanation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 13:26 UTC, szadam commented
*[`content/memkind/manpages/memkindallocator.3.md` line 149 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wjC4b7J9UJBNebMcB:-N6wt00G6sWVALAu1Ysq:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L149)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

bold
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 13:27 UTC, szadam reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: 7 of 8 files reviewed, 36 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)



<!-- Sent from Reviewable.io -->

2022-07-14 14:26 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: 7 of 8 files reviewed, 34 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/memkindallocator.3.md` line 14 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6x4mcVC63MwT2YPIox:-N6x4mcVC63MwT2YPIoy:b-rq48i3) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L14)):*
> ```Markdown
> [comment]: <> (Copyright 2019-2022, Intel Corporation)
> 
> [comment]: <> (libpmemkv.3 -- man page for libpmemkv)
> ```

heh :wink: 
___
*[`content/memkind/manpages/memkindallocator.3.md` line 16 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wQZiB-apW5_IKoYjl:-N6wzzHV43avD-pWiXYr:b-mijefg) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L16)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Maybe it's just me but I see this list of links as some kind of a bug here, like sth that accidentally happens to be on this page. No title to these links and a far bigger font of the first section `NAME` following. Is it possible to add a section name here like `LIST OF CONTENTS` or sth similar without breaking the possibility of generating a manpage from this file? 
</blockquote></details>

heh :smile: That's actually a very good catch, I've been looking at these manpages for too long and never noticed that. I believe we may easily add a header (like "Table of content") to this list and the manpages will generate just fine
___
*[`data/en/memkind.yml` line 77 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wPz-C-Vma1XpLfoi8:-N6x5Foq53bF1tNAGM0X:b-r6pudu) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/data/en/memkind.yml#L77)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

What about licensing github.com/memkind/memkind repository? Pmem repository is not even being mentioned on this page in opposition to the memkind repo.
</blockquote></details>

hmm I think there's a general problem on this website - we write a lot of information about pmem or pmdk and very little about memory mode and related libraries

nonetheless, I believe you should update this disclaimer here


<!-- Sent from Reviewable.io -->

2022-07-15 08:29 UTC, szadam reviewed
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 34 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/memkindallocator.3.md` line 14 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6x4mcVC63MwT2YPIox:-N7-yB_j5KuAxGtCdhqQ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L14)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

heh :wink: 
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 16 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wQZiB-apW5_IKoYjl:-N7-yCcr-YQIy-XWEcyG:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

heh :smile: That's actually a very good catch, I've been looking at these manpages for too long and never noticed that. I believe we may easily add a header (like "Table of content") to this list and the manpages will generate just fine
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 54 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wSAlD46rRyksYDTMm:-N7-yLm62m_TMkJ3A098:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L54)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

All these kinds should be indented as they provide more precise information to the previous paragraph (`libmemkind::kinds`) and represent a list of options following the colon at the end of the prev paragraph. You can also remove the colon ending the previous paragraph.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 131 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wcrwzDOr2AGbNON9x:-N7-yO_u6O5p4cJBLnrs:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L131)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Shouldn't this note be in the `DESCRIPTION` section? Also, I think that all of the functions listed in the `SYNOPSIS` section should be described, even if there purpose and usage is obvious.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-15 08:51 UTC, PatKamin reviewed
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 20 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/memkindallocator.3.md` line 16 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wQZiB-apW5_IKoYjl:-N7-yuZADZXpbB2B0vAo:bq0b5hd) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L16)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

contents - there are multiple of contents here
___
*[`content/memkind/manpages/memkindallocator.3.md` line 32 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wROcq8XA51pKqPOUL:-N7-zL-pC1-rTDKgKFna:b-5bqci8) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L32)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

<memkind_allocator.h> - there is a missing `d` letter
___
*[`content/memkind/manpages/memkindallocator.3.md` line 49 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wYVa-1iqxje1p2SRx:-N7-zSZ460XfJG3BLW8i:b-4yjmr6) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L49)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

base -> based
___
*[`content/memkind/manpages/memkindallocator.3.md` line 131 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wcrwzDOr2AGbNON9x:-N701doBBZXz_SQGLkL4:b-m30k6n) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/content/memkind/manpages/memkindallocator.3.md#L131)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please, merge this with descriptions in the description section.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 57 at r17](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N70-aHL7tSlNJC0jZfq:-N70-aHL7tSlNJC0jZfr:b-v8ar7g) ([raw file](https://github.com/pmem/pmem.github.io/blob/f490c6499ccba4185849c24031cde22edf266f0d/content/memkind/manpages/memkindallocator.3.md#L57)):*
> ```Markdown
> 
> `libmemkind::static_kind::allocator<T>::deallocate(T *p, std::size_t n)`
> :   causes the allocated memory of size *n* bytes referenced by p to be made available for future allocations.
> ```

`p` in italics as a name of the argument.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 150 at r17](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N701xoWC6Gf0Wit1sgs:-N701xoWC6Gf0Wit1sgt:b-zh67m5) ([raw file](https://github.com/pmem/pmem.github.io/blob/f490c6499ccba4185849c24031cde22edf266f0d/content/memkind/manpages/memkindallocator.3.md#L150)):*
> ```Markdown
> Interfaces for obtaining 2MB (**HUGETLB**) memory need allocated huge pages in the kernel’s huge page pool.
> 
> HUGETLB (huge pages)
> ```

Move this header to the beginning of this section as this header refers to the very first sentence in this section, too.


<!-- Sent from Reviewable.io -->

2022-07-15 09:20 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 21 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/memkindallocator.3.md` line 8 at r17](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N707wx78RcHfSX2Bf9g:-N707wx78RcHfSX2Bf9h:b-o198mo) ([raw file](https://github.com/pmem/pmem.github.io/blob/f490c6499ccba4185849c24031cde22edf266f0d/content/memkind/manpages/memkindallocator.3.md#L8)):*
> ```Markdown
> disclaimer: "The contents of this web site and the associated <a href=\"https://github.com/memkind\">GitHub repositories</a> are BSD-licensed open source."
> aliases: ["memkindallocator.3.html"]
> title: "memkindallocator | PMDK"
> ```

I believe you can drop `| PMDK`
___
*[`content/memkind/manpages/memkindallocator.3.md` line 11 at r17](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N708jX-88kIrMHvaf03:-N708jX-88kIrMHvaf04:b9sd4r8) ([raw file](https://github.com/pmem/pmem.github.io/blob/f490c6499ccba4185849c24031cde22edf266f0d/content/memkind/manpages/memkindallocator.3.md#L11)):*
> ```Markdown
> ---
> 
> [comment]: <> (SPDX-License-Identifier: BSD-2-Clause)
> ```

don't we use BSD-3 actually? (maybe it's not the case for your project)


<!-- Sent from Reviewable.io -->

2022-07-15 09:53 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 21 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/memkindallocator.3.md` line 11 at r17](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N708jX-88kIrMHvaf03:-N70GkNx36yP53kNimQK:b-au8epk) ([raw file](https://github.com/pmem/pmem.github.io/blob/f490c6499ccba4185849c24031cde22edf266f0d/content/memkind/manpages/memkindallocator.3.md#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

don't we use BSD-3 actually? (maybe it's not the case for your project)
</blockquote></details>

In memkind the BSD-2 clause is used.


<!-- Sent from Reviewable.io -->

2022-07-15 10:12 UTC, PatKamin reviewed
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 20 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)



<!-- Sent from Reviewable.io -->

2022-07-19 09:31 UTC, szadam reviewed
> Reviewed 1 of 1 files at r20.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 19 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)



<!-- Sent from Reviewable.io -->

2022-07-19 10:27 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 18 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)



<!-- Sent from Reviewable.io -->

2022-07-19 18:49 UTC, szadam reviewed
> Reviewed 1 of 1 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 18 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`data/en/memkind.yml` line 34 at r14](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6viwCM6qrI2jrJDcjU:-N7Mml_OC2plIP5fQJYJ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/85e2ef30820cd001e1c948d280651727cd21858b/data/en/memkind.yml#L34)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

remove all unnecessary whitespaces here and in other files
</blockquote></details>

Done.
___
*[`data/en/memkind.yml` line 36 at r14](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6sBLtYBERisRb--0w3:-N7Mmn02AMNl6N51ylxJ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/85e2ef30820cd001e1c948d280651727cd21858b/data/en/memkind.yml#L36)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe it'd be better to link to just rendered README file:

https://github.com/memkind/memkind#memkind

// FYI, that `README.md` file in the repos seems just wrong :smile: :wink: 
</blockquote></details>

Done.
___
*[`data/en/memkind.yml` line 77 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wPz-C-Vma1XpLfoi8:-N7MmspVDkysJ2vQngTd:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/data/en/memkind.yml#L77)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm I think there's a general problem on this website - we write a lot of information about pmem or pmdk and very little about memory mode and related libraries

nonetheless, I believe you should update this disclaimer here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-19 18:53 UTC, szadam reviewed
> Reviewed 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 18 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`data/en/memkind.yml` line 65 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wPm2L-B5ucuFSLwk1:-N7Mn_Zo2aNP4KZrRY53:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/data/en/memkind.yml#L65)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove a comma after `feedback`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-20 07:57 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 17 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)



<!-- Sent from Reviewable.io -->

2022-07-22 11:03 UTC, haichangsi reviewed
> Reviewed 3 of 6 files at r7, 1 of 4 files at r8, 1 of 3 files at r14, 1 of 1 files at r21, 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 28 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/memkindallocator.3.md` line 31 at r23](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7VO-3MBpBvqNf3rP8F:-N7VO-3MBpBvqNf3rP8G:bzd7z25) ([raw file](https://github.com/pmem/pmem.github.io/blob/94ebfc7cb1f9f5b81bd1ecda4cd3809831bb2db0/content/memkind/manpages/memkindallocator.3.md#L31)):*
> ```Markdown
> **libmemkind::static_kind::allocator<T>** - The C++ allocator compatible with the C++ standard library allocator concepts
> 
> **Note:** memkind_allocator.h functionality is considered as stable API (STANDARD API).
> ```

as a stable API



_Code quote:_
```Markdown
as stable API
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 53 at r23](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7VOvkT3MiIwN5f37Vu:-N7VOvkT3MiIwN5f37Vv:b-y1yxmk) ([raw file](https://github.com/pmem/pmem.github.io/blob/94ebfc7cb1f9f5b81bd1ecda4cd3809831bb2db0/content/memkind/manpages/memkindallocator.3.md#L53)):*
> ```Markdown
> 
> `libmemkind::static_kind::allocator<T>` 
> :   is intended to be used with STL containers to allocate from static kinds memory. Memory management is based on the memkind library. Refer **memkind**(3) man page for more details.
> ```

kinds of memory



_Code quote:_
```Markdown
kinds memory
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 74 at r23](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7_ZRZA41nj-7ln9T1J:-N7_ZRZB-fbRjS3toF3m:b-awojyt) ([raw file](https://github.com/pmem/pmem.github.io/blob/94ebfc7cb1f9f5b81bd1ecda4cd3809831bb2db0/content/memkind/manpages/memkindallocator.3.md#L74)):*
> ```Markdown
> 
> >`libmemkind::kinds::DEFAULT` 
> >:   Default allocation using standard memory and default page size. The allocation can be made using any NUMA node containig memory.
> ```

The default allocation using standard memory and the default page size. The allocation can be made using any NUMA node containing memory.



_Code quote:_
```Markdown
Default allocation using standard memory and default page size. The allocation can be made using any NUMA node containig memory.
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 83 at r23](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7_UIc_2xOeIsd-M41f:-N7_UIcaDs7aUCpnOvs7:bdzjmlw) ([raw file](https://github.com/pmem/pmem.github.io/blob/94ebfc7cb1f9f5b81bd1ecda4cd3809831bb2db0/content/memkind/manpages/memkindallocator.3.md#L83)):*
> ```Markdown
> 
> >`libmemkind::kinds::HIGHEST_CAPACITY_LOCAL`
> >:   Allocate from a NUMA node that has the highest capacity among all NUMA Nodes from the local domain. NUMA Nodes have the same local domain for a set of CPUs associated with them, e.g. socket or sub-NUMA cluster. **Note:** If there are multiple NUMA nodes in the same local domain that have the highest capacity - allocation will be done from NUMA node with worse latency attribute. This kind requires locality information described in the [SYSTEM CONFIGURATION](#system-configuration) section.
> ```

the allocation



_Code quote:_
```Markdown
allocation
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 89 at r23](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7VQBxU6UCxszNTV-Qe:-N7VQBxU6UCxszNTV-Qf:bdzjmlw) ([raw file](https://github.com/pmem/pmem.github.io/blob/94ebfc7cb1f9f5b81bd1ecda4cd3809831bb2db0/content/memkind/manpages/memkindallocator.3.md#L89)):*
> ```Markdown
> 
> >`libmemkind::kinds::LOWEST_LATENCY_LOCAL` 
> >:   Allocate from a NUMA node that has the lowest latency among all NUMA Nodes from the local domain. NUMA Nodes have the same local domain for a set of CPUs associated with them, e.g. socket or sub-NUMA cluster. **Note:** If there are multiple NUMA nodes in the same local domain that have the lowest latency - allocation will be done from NUMA node with smaller memory capacity. This kind requires locality and memory performance characteristics information described in the [SYSTEM CONFIGURATION](#system-configuration) section.
> ```

the allocation



_Code quote:_
```Markdown
allocation
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 89 at r23](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7VQIcx5DOQnxWFy1Zu:-N7VQIcx5DOQnxWFy1Zv:b-rapu5x) ([raw file](https://github.com/pmem/pmem.github.io/blob/94ebfc7cb1f9f5b81bd1ecda4cd3809831bb2db0/content/memkind/manpages/memkindallocator.3.md#L89)):*
> ```Markdown
> 
> >`libmemkind::kinds::LOWEST_LATENCY_LOCAL` 
> >:   Allocate from a NUMA node that has the lowest latency among all NUMA Nodes from the local domain. NUMA Nodes have the same local domain for a set of CPUs associated with them, e.g. socket or sub-NUMA cluster. **Note:** If there are multiple NUMA nodes in the same local domain that have the lowest latency - allocation will be done from NUMA node with smaller memory capacity. This kind requires locality and memory performance characteristics information described in the [SYSTEM CONFIGURATION](#system-configuration) section.
> ```

from a NUMA



_Code quote:_
```Markdown
from NUMA
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 95 at r23](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7VQg2UBo9X7orB8W7P:-N7VQg2UBo9X7orB8W7Q:b3kqx) ([raw file](https://github.com/pmem/pmem.github.io/blob/94ebfc7cb1f9f5b81bd1ecda4cd3809831bb2db0/content/memkind/manpages/memkindallocator.3.md#L95)):*
> ```Markdown
> 
> >`libmemkind::kinds::HIGHEST_BANDWIDTH_LOCAL` 
> >:   Allocate from a NUMA node that has the highest bandwidth among all NUMA Nodes from the local domain. NUMA Nodes have the same local domain for a set of CPUs associated with them, e.g. socket or sub-NUMA cluster. **Note:** If there are multiple NUMA nodes in the same local domain that have the highest bandwidth - allocation will be done from NUMA node with smaller memory capacity. This kind requires locality and memory performance characteristics information described in the [SYSTEM CONFIGURATION](#system-configuration) section.
> ```

.



_Code quote:_
```Markdown
from NUMA
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 95 at r23](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7_UQlQ7KG53ITPlv_8:-N7_UQlQ7KG53ITPlv_9:b3kqx) ([raw file](https://github.com/pmem/pmem.github.io/blob/94ebfc7cb1f9f5b81bd1ecda4cd3809831bb2db0/content/memkind/manpages/memkindallocator.3.md#L95)):*
> ```Markdown
> 
> >`libmemkind::kinds::HIGHEST_BANDWIDTH_LOCAL` 
> >:   Allocate from a NUMA node that has the highest bandwidth among all NUMA Nodes from the local domain. NUMA Nodes have the same local domain for a set of CPUs associated with them, e.g. socket or sub-NUMA cluster. **Note:** If there are multiple NUMA nodes in the same local domain that have the highest bandwidth - allocation will be done from NUMA node with smaller memory capacity. This kind requires locality and memory performance characteristics information described in the [SYSTEM CONFIGURATION](#system-configuration) section.
> ```

.



_Code quote:_
```Markdown
allocation
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 110 at r23](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7VRSbw3T5v-vGyuUZC:-N7VRSbw3T5v-vGyuUZD:b6p9upp) ([raw file](https://github.com/pmem/pmem.github.io/blob/94ebfc7cb1f9f5b81bd1ecda4cd3809831bb2db0/content/memkind/manpages/memkindallocator.3.md#L110)):*
> ```Markdown
> 
> >`libmemkind::kinds::HBW_ALL` 
> >:   Same as `libmemkind::kinds::HBW` except decision regarding closest NUMA node is postponed until the time of first write.
> ```

of the first



_Code quote:_
```Markdown
of first
```
___
*[`data/en/memkind.yml` line 36 at r23](https://reviewable [...]

2022-07-22 11:08 UTC, haichangsi reviewed
> Reviewed 3 of 6 files at r7, 1 of 4 files at r8, 1 of 3 files at r14, 1 of 1 files at r21, 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 28 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)



<!-- Sent from Reviewable.io -->

2022-07-25 07:57 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r21, 1 of 3 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: 8 of 10 files reviewed, 23 unresolved discussions (waiting on @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)



<!-- Sent from Reviewable.io -->

2022-07-25 08:34 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: 8 of 10 files reviewed, 33 unresolved discussions (waiting on @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/memkindallocator.3.md` line 36 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7oMmu70AVtn5kjCry6:-N7oMmu70AVtn5kjCry7:b-hwyyvc) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/memkindallocator.3.md#L36)):*
> ```Markdown
> 
> ```c
> #include memkind_allocator.h
> ```

add <...> 



_Code quote:_
```Markdown
memkind_allocator.h
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 53 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7oUcFt33ErbpVBU0k_:-N7oUcFt33ErbpVBU0ka:b-y1eaz6) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/memkindallocator.3.md#L53)):*
> ```Markdown
> 
> `libmemkind::static_kind::allocator<T>` 
> :   is intended to be used with STL containers to allocate from static kinds memory. Memory management is based on the memkind library. Refer **memkind**(3) man page for more details.
> ```

make this a link



_Code quote:_
```Markdown
**memkind**
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 56 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7oN4EH8sER7Wge2bMO:-N7oN4EH8sER7Wge2bMP:b-w3x6pz) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/memkindallocator.3.md#L56)):*
> ```Markdown
> 
> `T *libmemkind::static_kind::allocator<T>::allocate(std::size_t n)`
> :   allocates uninitialized memory of size *n* bytes of the specified kind
> ```

add '.' at the end of this sentence



_Code quote:_
```Markdown
kind
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 63 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7oNiBH7CzaqlN5Kz41:-N7oNiBH7CzaqlN5Kz42:b-5en2yv) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/memkindallocator.3.md#L63)):*
> ```Markdown
> **Notes:**
> 
> >`T *libmemkind::static_kind::allocator<T>::allocate(std::size_t n)` allocates memory using >`memkind_malloc()`. Throw std::bad_alloc when:
> ```

remove '>'



_Code quote:_
```Markdown
ng >`m
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 68 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7oNqBA5dMoFVLjSSiX:-N7oNqBA5dMoFVLjSSiY:b-5en2yv) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/memkindallocator.3.md#L68)):*
> ```Markdown
> >+ or there is not enough memory to satisfy the request.
> >
> >`libmemkind::static_kind::allocator<T>::deallocate(T *p, std::size_t n)` deallocates memory >associated with pointer returned by `allocate()` using `memkind_free()`.
> ```

remove '>'



_Code quote:_
```Markdown
y >a
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 73 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7oSdfWCRkvsjoUP-E4:-N7oSdfX3AeUO4Eu4BDD:bg7wqw4) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/memkindallocator.3.md#L73)):*
> ```Markdown
> :   specifies allocator static kinds of memory, representing type of memory which offers different characteristics. The available types of allocator kinds of memory:
> 
> >`libmemkind::kinds::DEFAULT` 
> ```

Currently the libmemkind::kinds are indented similar to the "Notes" paragraph above. I think putting them in the second level header (##) named "Types of allocator kinds of memory" would look better.



_Code quote:_
```Markdown
>`li
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 146 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7oQP_v1c4xx4IojcSW:-N7oQP_v1c4xx4IojcSX:bjosn20) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/memkindallocator.3.md#L146)):*
> ```Markdown
> Template arguments:
> 
> + T is an object type aliased by value_type.
> ```

'.' -> ','



_Code quote:_
```Markdown
pe.
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 157 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7oTlW7B-OMwUJQP5Qz:-N7oTlW7B-OMwUJQP5R-:b-icq30j) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/memkindallocator.3.md#L157)):*
> ```Markdown
> 
> Locality information
> :   Interfaces for obtaining locality information are provided by *libhwloc* dependency. Functionality based on locality requires that memkind library is configured and built with the support of *libhwloc* (`./configure --enable-hwloc`).
> ```

This fragment doesn't look well... please remove (), add a ':' and move this fragment of code to a new line here and in the next paragaph



_Code quote:_
```Markdown
(`./configure --enable-hwloc`)
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 157 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7oULVo1Y1AWU4KsWM5:-N7oULVo1Y1AWU4KsWM6:b-fg2ptz) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/memkindallocator.3.md#L157)):*
> ```Markdown
> 
> Locality information
> :   Interfaces for obtaining locality information are provided by *libhwloc* dependency. Functionality based on locality requires that memkind library is configured and built with the support of *libhwloc* (`./configure --enable-hwloc`).
> ```

make this a link to https://www.open-mpi.org/projects/hwloc here and in the next paragraph



_Code quote:_
```Markdown
*libhwloc*
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 172 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7oQ1J38o0BGbcT8HkE:-N7oQ1J46S0XEK50Akad:bnftfs3) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/memkindallocator.3.md#L172)):*
> ```Markdown
> ## SEE ALSO ##
> 
> **memkind**(3)
> ```

make this reference a link



_Code quote:_
```Markdown
**memkind**(3)
```


<!-- Sent from Reviewable.io -->

2022-07-25 09:15 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: 8 of 10 files reviewed, 40 unresolved discussions (waiting on @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/hbwmalloc.3.md` line 128 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7oaqdzCnol-_WxaxcN:-N7oaqdzCnol-_WxaxcO:b-9cckmj) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/hbwmalloc.3.md#L128)):*
> ```Markdown
> Using this function in production code may result in serious performance penalty.
> 
> The *Flags* argument may include optional flags that modify function behavior:\
> ```

fix formatting
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 139 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7obzED4prcnVeLLDS3:-N7obzED4prcnVeLLDS4:bbnf5b2) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/hbwmalloc.3.md#L139)):*
> ```Markdown
> 
> Error codes described here are the POSIX standard error codes as
> defined in
> ```

do not break line here
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 146 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7obSsZAI7vyg95wUvN:-N7obSsZAI7vyg95wUvO:bmtio0j) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/hbwmalloc.3.md#L146)):*
> ```Markdown
> :   returns **ENODEV** if high-bandwidth memory is unavailable.
> 
> `hbw_posix_memalign()` and `hbw_posix_memalign_psize()`
> ```

fix formatting - this "and" shouldn't be bold



_Code quote:_
```Markdown
and 
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 147 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7obGMp5cESHXHuGuv_:-N7obGMp5cESHXHuGuva:b-lq25es) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/hbwmalloc.3.md#L147)):*
> ```Markdown
> 
> `hbw_posix_memalign()` and `hbw_posix_memalign_psize()`
> :   If the *alignment* parameter is not a power of two, or was not a multiple of *sizeof(void*)*, then EINVAL is returned. If the policy and pagesize combination is unsupported then **EINVAL** is returned. If there was insufficient memory to satisfy the request then **ENOMEM** is returned.
> ```

**EINVAL**
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 150 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7obl0N0DF-19aJW035:-N7obl0N0DF-19aJW036:b60the1) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/hbwmalloc.3.md#L150)):*
> ```Markdown
> 
> `hbw_set_policy()`
> :   returns EPERM if hbw_set_policy() was called more than once, or EINVAL if mode argument was neither HBW_POLICY_PREFERRED, HBW_POLICY_BIND, HBW_POLICY_BIND_ALL nor HBW_POLICY_INTERLEAVE.
> ```

**EPERM** -> bold all error return codes



_Code quote:_
```Markdown
EPERM 
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 170 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7ocD_61C7JNmTU1oC3:-N7ocD_61C7JNmTU1oC4:b-y1eaz6) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/hbwmalloc.3.md#L170)):*
> ```Markdown
> 
> MEMKIND_ARENA_NUM_PER_KIND
> :   This environment variable allows leveraging internal mechanism of the library for setting number of arenas per kind. Value should be a positive integer (not greater than **INT_MAX** defined in <*limits.h*>). The user should set the value based on the characteristics of application that is using the library. Higher value can provide better performance in extremely multithreaded applications at the cost of memory overhead. See section **IMPLEMENTATION NOTES** of **jemalloc**(3) for more details about arenas.
> ```

make this a link



_Code quote:_
```Markdown
*IMPLEMENTATION NOTES** 
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 186 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7ocNHf1aSFX5_BKDZz:-N7ocNHf1aSFX5_BKD_-:bj2odwc) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/hbwmalloc.3.md#L186)):*
> ```Markdown
> 
> HUGETLB (huge pages)
> :   Current number of "persistent" huge pages can be read from */proc/sys/vm/nr_hugepages* file. Proposed way of setting hugepages is: **sudo sysctl vm.nr_hugepages=<number_of_hugepages>**. More information can be found here: https://www.kernel.org/doc/Documentation/vm/hugetlbpage.txt
> ```

format this as a code



_Code quote:_
```Markdown
**sudo sysctl vm.nr_hugepages=<number_of_hugepages>**
```


<!-- Sent from Reviewable.io -->

2022-07-25 09:16 UTC, bratpiorka reviewed
> Reviewed 2 of 3 files at r25.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 41 unresolved discussions (waiting on @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/memkind.3.md` line 533 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7od1o3-3bwkFoi1IfG:-N7od1o3-3bwkFoi1IfH:bljnnho) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/memkind.3.md#L533)):*
> ```Markdown
> ## SEE ALSO ##
> 
> **malloc**(3), **malloc_usable_size**(3), **numa**(3), **hwloc**(3), **numactl**(8), **mbind**(2), **mmap**(2), **move_pages**(2), **jemalloc**(3), **memkind_dax_kmem**(3), **memkind_default**(3), **memkind_arena**(3), **memkind_fixed**(3), **memkind_hbw**(3), **memkind_hugetlb**(3), **memkind_pmem**(3), **syscall**(2), **write**(2)
> ```

fix EOF



_Code quote:_
```Markdown
 
```


<!-- Sent from Reviewable.io -->

2022-07-28 11:38 UTC, szadam reviewed
> Reviewed 1 of 3 files at r25.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: 9 of 10 files reviewed, 41 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/hbwmalloc.3.md` line 128 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7oaqdzCnol-_WxaxcN:-N83YdFd3mEXVh9OifKv:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/hbwmalloc.3.md#L128)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

fix formatting
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 139 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7obzED4prcnVeLLDS3:-N83ZUDS7bUt2nLM6XGb:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/hbwmalloc.3.md#L139)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

do not break line here
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 146 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7obSsZAI7vyg95wUvN:-N83ZUv45bnKXJeUY0qw:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/hbwmalloc.3.md#L146)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

fix formatting - this "and" shouldn't be bold
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 147 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7obGMp5cESHXHuGuv_:-N83Zc287HZuOK8vfPIe:b3kre) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/hbwmalloc.3.md#L147)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

**EINVAL**
</blockquote></details>

?
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 150 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7obl0N0DF-19aJW035:-N83Zrot3dkWZs2Lf516:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/hbwmalloc.3.md#L150)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

**EPERM** -> bold all error return codes
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 170 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7ocD_61C7JNmTU1oC3:-N83_0fR2lyO0JjTTfTP:biz9osb) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/hbwmalloc.3.md#L170)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

make this a link
</blockquote></details>

link to what destination exactly, where is jemalloc documentation?
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 186 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7ocNHf1aSFX5_BKDZz:-N83_et-A1HmV1QANGbp:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/hbwmalloc.3.md#L186)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

format this as a code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-28 11:39 UTC, szadam reviewed
> Reviewed 1 of 1 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 41 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)



<!-- Sent from Reviewable.io -->

2022-07-28 11:43 UTC, szadam commented
*[`content/memkind/manpages/memkindallocator.3.md` line 53 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7oUcFt33ErbpVBU0k_:-N83bJPXEU0UWOqHIlqO:b9xibt) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/memkindallocator.3.md#L53)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

make this a link
</blockquote></details>

link to what? this is memkind man page


<!-- Sent from Reviewable.io -->

2022-07-28 12:16 UTC, szadam commented
*[`data/en/memkind.yml` line 44 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wORnXEGgM1gbxZ4WE:-N83j0qR8zSrAgPHBnm7:bq5hrcx) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/data/en/memkind.yml#L44)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

A sentence or two with an explanation that the packages are created for Fedora and OpenSUSE would be useful. No packages for debian-based OSes here particularly.
</blockquote></details>

what should I write exactly?


<!-- Sent from Reviewable.io -->

2022-07-28 12:21 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 42 unresolved discussions (waiting on @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/hbwmalloc.3.md` line 147 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7obGMp5cESHXHuGuv_:-N83hmhKAA4I9VjEFKaB:b-9vqn3x) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/hbwmalloc.3.md#L147)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

?
</blockquote></details>

make all error codes bold
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 170 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7ocD_61C7JNmTU1oC3:-N83hvIS5-uN2ZFNmFfn:bm5kyp7) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/hbwmalloc.3.md#L170)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

link to what destination exactly, where is jemalloc documentation?
</blockquote></details>

hmm you are right, this is jemalloc... ok
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 75 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83j-wZ5ZJvFMJuGikq:-N83j-wZ5ZJvFMJuGikr:b-yqppm2) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L75)):*
> ```Markdown
> **Note:** `hbw_realloc()` may move the memory allocation, resulting in a different return value than *ptr*.
> 
> If *ptr* is *NULL*, the `hbw_realloc()` function behaves identically to `hbw_malloc()` for the specified size. If *size* is equal to zero, and *ptr* is not *NULL*, then the call is equivalent to *hbw_free(ptr)* and *NULL* is returned. The address *ptr*, if not *NULL*, was returned by a previous call to `hbw_malloc()`, `hbw_calloc()`, `hbw_realloc()` or `hbw_posix_memalign()`. Otherwise, or if *hbw_free(ptr)* was called before, undefined behavior occurs.
> ```

format as a code



_Code quote:_
```Markdown
*hbw_free(ptr)*
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 75 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83j3o_2tF2zzpT7dld:-N83j3o_2tF2zzpT7dle:b-yqppm2) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L75)):*
> ```Markdown
> **Note:** `hbw_realloc()` may move the memory allocation, resulting in a different return value than *ptr*.
> 
> If *ptr* is *NULL*, the `hbw_realloc()` function behaves identically to `hbw_malloc()` for the specified size. If *size* is equal to zero, and *ptr* is not *NULL*, then the call is equivalent to *hbw_free(ptr)* and *NULL* is returned. The address *ptr*, if not *NULL*, was returned by a previous call to `hbw_malloc()`, `hbw_calloc()`, `hbw_realloc()` or `hbw_posix_memalign()`. Otherwise, or if *hbw_free(ptr)* was called before, undefined behavior occurs.
> ```

format as a code



_Code quote:_
```Markdown
*hbw_free(ptr)*
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 77 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83jI7737xKyljs5Gtu:-N83jI7737xKyljs5Gtv:b-q8nv2h) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L77)):*
> ```Markdown
> If *ptr* is *NULL*, the `hbw_realloc()` function behaves identically to `hbw_malloc()` for the specified size. If *size* is equal to zero, and *ptr* is not *NULL*, then the call is equivalent to *hbw_free(ptr)* and *NULL* is returned. The address *ptr*, if not *NULL*, was returned by a previous call to `hbw_malloc()`, `hbw_calloc()`, `hbw_realloc()` or `hbw_posix_memalign()`. Otherwise, or if *hbw_free(ptr)* was called before, undefined behavior occurs.
> 
> **Note:** `hbw_realloc()` cannot be used with a pointer returned by `hbw_posix_memalign_psize()`.
> ```

do not break line before "Note" - keep this is one paragraph



_Code quote:_
```Markdown
**Note:**
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 109 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83jVqI9WKLeuOHLLq1:-N83jVqI9WKLeuOHLLq2:b-4eshe0) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L109)):*
> ```Markdown
> `hbw_set_policy()`
> :   sets the current fallback policy. The policy can be modified only once in the lifetime of an application and before calling `hbw_malloc()`, `hbw_calloc()`, `hbw_realloc()`, `hbw_posix_memalign()`, or `hbw_posix_memalign_psize()` function.\
> Note: If the policy is not set, than **HBW_POLICY_PREFERRED** will be used by default.
> ```

make "note" bold and do not break line here



_Code quote:_
```Markdown
Note: 
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 123 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83jg01DFopXiQIy9Kx:-N83jg01DFopXiQIy9Ky:b-yqppm2) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L123)):*
> ```Markdown
> >:  Interleave faulted pages from across all high bandwidth NUMA nodes using standard size pages (the Transparent Huge Page feature is disabled).
> 
> hbw_verify_memory_region()
> ```

format as a code



_Code quote:_
```Markdown
hbw_verify_memory_region()
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 126 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83jnVbAQehL00i0SFD:-N83jnVbAQehL00i0SFE:b-quzse9) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L126)):*
> ```Markdown
> :   verifies if memory region fully falls into high bandwidth memory. Returns 0 if memory address range from *addr* to *addr +* *size* is allocated in high bandwidth memory, -1 if any fragment of memory was not backed by high bandwidth memory (e.g. when memory is not initialized) or one of error codes described in [ERRORS](#errors) section.
> 
> Using this function in production code may result in serious performance penalty.
> ```

do not break line - keep this with previous paragraph and start with bold "Note"



_Code quote:_
```Markdown
Using this function in production code may result in serious performance penalty.
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 146 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83k32UETVA2EGZH6eP:-N83k32UETVA2EGZH6eQ:bb7dslm) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L146)):*
> ```Markdown
> 
> **`hbw_posix_memalign()`** and **`hbw_posix_memalign_psize()`**\
> If the *alignment* parameter is not a power of two, or was not a multiple of *sizeof(void*)*, then EINVAL is returned. If the policy and pagesize combination is unsupported then **EINVAL** is returned. If there was insufficient memory to satisfy the request then **ENOMEM** is returned.
> ```

bold



_Code quote:_
```Markdown
EINVAL
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 149 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83k8JzB3TelqbHvN4-:-N83k8JzB3TelqbHvN40:bb7dslm) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L149)):*
> ```Markdown
> 
> `hbw_set_policy()`
> :   returns **EPERM** if hbw_set_policy() was called more than once, or **EINVAL** if mode argument was neither HBW_POLICY_PREFERRED, HBW_POLICY_BIND, HBW_POLICY_BIND_ALL nor HBW_POLICY_INTERLEAVE.
> ```

bold



_Code quote:_
```Markdown
HBW_POLICY_PREFERRED, HBW_POLICY_BIND, HBW_POLICY_BIND_ALL nor HBW_POLICY_INTERLEAVE.
```
___
*[`content/memkind/manpages/memkindallocat [...]

2022-07-28 13:10 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 45 unresolved discussions (waiting on @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/memkind.3.md` line 270 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83uj4e057wy30M-fZ6:-N83uj4e057wy30M-fZ7:b-dvk0ve) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/memkind.3.md#L270)):*
> ```Markdown
> 
> MEMKIND_LOWEST_LATENCY_LOCAL_PREFERRED
> :   Same as MEMKIND_LOWEST_LATENCY_LOCAL except that if there is not enough memory in the NUMA node that has the lowest latency to satisfy the request, the allocation will fall back on other memory NUMA nodes.
> ```

format as a code '...'



_Code quote:_
```Markdown
MEMKIND_LOWEST_LATENCY_LOCAL
```
___
*[`content/memkind/manpages/memkind.3.md` line 324 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83ubIR7IN0tUvIJ72A:-N83ubIR7IN0tUvIJ72B:b-dvk0ve) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/memkind.3.md#L324)):*
> ```Markdown
> 
> MEMKIND_DAX_KMEM_INTERLEAVE
> :   Same as MEMKIND_DAX_KMEM except that the pages that support the allocation are interleaved across all persistent memory NUMA nodes.
> ```

format as a code '...'



_Code quote:_
```Markdown
MEMKIND_DAX_KMEM
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 31 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83vAox8foTaSKyayua:-N83vAox8foTaSKyayub:b-k1owy) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/memkindallocator.3.md#L31)):*
> ```Markdown
> **libmemkind::static_kind::allocator<T>** - The C++ allocator compatible with the C++ standard library allocator concepts
> 
> **Note:** memkind_allocator.h functionality is considered as stable API (STANDARD API).
> ```

italics



_Code quote:_
```Markdown
memkind_allocator.h
```


<!-- Sent from Reviewable.io -->

2022-07-28 13:12 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 49 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/hbwmalloc.3.md` line 77 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83jI7737xKyljs5Gtu:-N83tIaL07n1_QGnM-X0:bpyi5zs) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L77)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

do not break line before "Note" - keep this is one paragraph
</blockquote></details>

Actually, you can break lines - it'd be easier to read this wall of text here, but as Rafał stated you shouldn't leave an empty line, to keep this in one paragraph

// see similar approach in pmemstream's doc: https://github.com/pmem/pmemstream/blob/master/doc/libpmemstream.3.md?plain=1#L127
___
*[`content/memkind/manpages/memkind.3.md` line 53 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83uAejCAnaG1moHQCB:-N83uAejCAnaG1moHQCC:bw13v4s) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/memkind.3.md#L53)):*
> ```Markdown
> Link with -lmemkind
> 
> EXPERIMENTAL API:
> ```

I believe you'd have to visually differentiate (somehow) where is an experimental API and where's a "standard" API, e.g.:

```
...
--- EXPERIMENTAL API ---
...

--- STANDARD API ---
...
```
___
*[`content/memkind/manpages/memkind.3.md` line 464 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83v61UBnOZvcUhJsy_:-N83v61UBnOZvcUhJsya:b-z6fokz) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/memkind.3.md#L464)):*
> ```Markdown
> 
> */usr/bin/memkind-hbw-nodes*
> :   Prints a comma-separated list of high bandwidth nodes.
> ```

"prints"? I'm guessing a file does not "print" anything :wink: 
___
*[`content/memkind/manpages/memkind.3.md` line 508 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83vIwz8Sm__4EQhYu7:-N83vIwz8Sm__4EQhYu8:bnabn7x) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/memkind.3.md#L508)):*
> ```Markdown
> 
> HUGETLB (huge pages)
> :   Current number of "persistent" huge pages can be read from */proc/sys/vm/nr_hugepages* file. Proposed way of setting hugepages is: **sudo sysctl vm.nr_hugepages=<number_of_hugepages>**. More information can be found here: https://www.kernel.org/doc/Documentation/vm/hugetlbpage.txt
> ```

use md syntax for links `[]()`
___
*[`content/memkind/manpages/memkind.3.md` line 508 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83vNTZ2HeZ1ql_-pgf:-N83vNTZ2HeZ1ql_-pgg:bekh12e) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/memkind.3.md#L508)):*
> ```Markdown
> 
> HUGETLB (huge pages)
> :   Current number of "persistent" huge pages can be read from */proc/sys/vm/nr_hugepages* file. Proposed way of setting hugepages is: **sudo sysctl vm.nr_hugepages=<number_of_hugepages>**. More information can be found here: https://www.kernel.org/doc/Documentation/vm/hugetlbpage.txt
> ```

put commands into \`` (mark them as a code)


<!-- Sent from Reviewable.io -->

2022-07-28 13:14 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 49 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/memkind.3.md` line 464 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83v61UBnOZvcUhJsy_:-N83wJs01xtXn57Q3Gt8:bh7ll67) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/memkind.3.md#L464)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"prints"? I'm guessing a file does not "print" anything :wink: 
</blockquote></details>

these are executables, not a "files" - I think that the section title could be changed to ## UTILS ##


<!-- Sent from Reviewable.io -->

2022-07-28 13:16 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 49 unresolved discussions (waiting on @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/hbwmalloc.3.md` line 77 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83jI7737xKyljs5Gtu:-N83wjaJ6zSZ85-21zVt:b2c33pj) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L77)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Actually, you can break lines - it'd be easier to read this wall of text here, but as Rafał stated you shouldn't leave an empty line, to keep this in one paragraph

// see similar approach in pmemstream's doc: https://github.com/pmem/pmemstream/blob/master/doc/libpmemstream.3.md?plain=1#L127
</blockquote></details>

+1 agree - break line but keep one paragraph


<!-- Sent from Reviewable.io -->

2022-07-28 13:35 UTC, szadam reviewed
> Reviewed 1 of 1 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 49 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/memkindallocator.3.md` line 31 at r23](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7VO-3MBpBvqNf3rP8F:-N84-noQ9OnU_4Ob9EbM:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/94ebfc7cb1f9f5b81bd1ecda4cd3809831bb2db0/content/memkind/manpages/memkindallocator.3.md#L31)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

as a stable API
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 53 at r23](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7VOvkT3MiIwN5f37Vu:-N84-r5t9jkABRmnMHXb:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/94ebfc7cb1f9f5b81bd1ecda4cd3809831bb2db0/content/memkind/manpages/memkindallocator.3.md#L53)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

kinds of memory
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 74 at r23](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7_ZRZA41nj-7ln9T1J:-N84-vQlDw_hS-mynkW2:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/94ebfc7cb1f9f5b81bd1ecda4cd3809831bb2db0/content/memkind/manpages/memkindallocator.3.md#L74)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

The default allocation using standard memory and the default page size. The allocation can be made using any NUMA node containing memory.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 83 at r23](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7_UIc_2xOeIsd-M41f:-N84-wKn9_NYbxhThr-i:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/94ebfc7cb1f9f5b81bd1ecda4cd3809831bb2db0/content/memkind/manpages/memkindallocator.3.md#L83)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

the allocation
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 89 at r23](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7VQBxU6UCxszNTV-Qe:-N84-yCZ2OaRzRiyxxGS:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/94ebfc7cb1f9f5b81bd1ecda4cd3809831bb2db0/content/memkind/manpages/memkindallocator.3.md#L89)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

the allocation
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 89 at r23](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7VQIcx5DOQnxWFy1Zu:-N84-ypi312gsO5z7XpL:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/94ebfc7cb1f9f5b81bd1ecda4cd3809831bb2db0/content/memkind/manpages/memkindallocator.3.md#L89)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

from a NUMA
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 95 at r23](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7VQg2UBo9X7orB8W7P:-N8403VT5R0x-kvXaSIf:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/94ebfc7cb1f9f5b81bd1ecda4cd3809831bb2db0/content/memkind/manpages/memkindallocator.3.md#L95)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 95 at r23](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7_UQlQ7KG53ITPlv_8:-N8403iQ036K2Vdc4hvt:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/94ebfc7cb1f9f5b81bd1ecda4cd3809831bb2db0/content/memkind/manpages/memkindallocator.3.md#L95)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 110 at r23](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7VRSbw3T5v-vGyuUZC:-N8404F_78yg9Ewo1M60:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/94ebfc7cb1f9f5b81bd1ecda4cd3809831bb2db0/content/memkind/manpages/memkindallocator.3.md#L110)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

of the first
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 36 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7oMmu70AVtn5kjCry6:-N84-q1F79jYr0Yg2wyT:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/memkindallocator.3.md#L36)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

add <...> 
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 56 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7oN4EH8sER7Wge2bMO:-N84-shA9cCFxRPwQFOU:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/memkindallocator.3.md#L56)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

add '.' at the end of this sentence
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 63 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7oNiBH7CzaqlN5Kz41:-N84-twO9UobmBJhC7dM:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/memkindallocator.3.md#L63)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

remove '>'
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 68 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7oNqBA5dMoFVLjSSiX:-N84-uM1Df0ei0_AtOs1:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/memkindallocator.3.md#L68)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

remove '>'
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 73 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7oSdfWCRkvsjoUP-E4:-N84-urM95jTz5U3wsRo:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/memkindallocator.3.md#L73)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Currently the libmemkind::kinds are indented similar to the "Notes" paragraph above. I think putting them in the second level header (##) named "Types of allocator kinds of memory" would look better.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 146 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7oQP_v1c4xx4IojcSW:-N8406yJ-Nvzps-sslby:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/memkindallocator.3.md#L146)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

'.' -> ','
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 157 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7oTlW7B-OMwUJQP5Qz:-N8408O127Wam896MhFQ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/memkindallocator.3.md#L157)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquot [...]

2022-07-28 13:57 UTC, szadam commented
*[`content/memkind/manpages/hbwmalloc.3.md` line 147 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7obGMp5cESHXHuGuv_:-N845E5G-PfdEykEIqq6:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/hbwmalloc.3.md#L147)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

make all error codes bold
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-28 14:01 UTC, szadam reviewed
> Reviewed 1 of 1 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: 9 of 10 files reviewed, 49 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/hbwmalloc.3.md` line 75 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83j-wZ5ZJvFMJuGikq:-N8469F1Dk4ce-Dg7ou0:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L75)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

format as a code
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 75 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83j3o_2tF2zzpT7dld:-N8469dy1Pybj9mNbVFT:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L75)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

format as a code
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 77 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83jI7737xKyljs5Gtu:-N846AGT-BrSddyBQbzn:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L77)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

+1 agree - break line but keep one paragraph
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 109 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83jVqI9WKLeuOHLLq1:-N846AnMALM_JSjJPZO8:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L109)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

make "note" bold and do not break line here
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 123 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83jg01DFopXiQIy9Kx:-N846BEq1WEw-jKU_Kdr:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L123)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

format as a code
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 126 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83jnVbAQehL00i0SFD:-N846BZjC2JYDgGIsh9E:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L126)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

do not break line - keep this with previous paragraph and start with bold "Note"
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 146 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83k32UETVA2EGZH6eP:-N846CPVEHtASu-_k2YZ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L146)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

bold
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 149 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83k8JzB3TelqbHvN4-:-N846CkF8QaQOwJ6rGrw:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L149)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

bold
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-28 14:10 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: 9 of 10 files reviewed, 49 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/hbwmalloc.3.md` line 77 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83jI7737xKyljs5Gtu:-N847t9F4-B515vqiLJ4:bkwkffg) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L77)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

1. you don't have to add `\` - just break a line
2. you know, I meant all of these lines with descriptions (in all manpages) :wink: (see pmemstream doc link)
___
*[`content/memkind/manpages/memkind.3.md` line 464 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83v61UBnOZvcUhJsy_:-N8489nL0fiOK_vpMLxj:b-d7mqce) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/memkind.3.md#L464)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

these are executables, not a "files" - I think that the section title could be changed to ## UTILS ##
</blockquote></details>

ochh, that makes sense :smiley: but i guess, yeah - UTILS could be nice name


<!-- Sent from Reviewable.io -->

2022-07-28 14:36 UTC, szadam reviewed
> Reviewed 1 of 1 files at r28, 1 of 1 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 49 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/memkind.3.md` line 533 at r25](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7od1o3-3bwkFoi1IfG:-N84E8F88HqpGrZ-D8SB:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/beb5e4ccdf143ea9aa71d5bfbe91988754c6d2fa/content/memkind/manpages/memkind.3.md#L533)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

fix EOF
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkind.3.md` line 53 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83uAejCAnaG1moHQCB:-N84E-lM5_7fgm_9fnOn:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/memkind.3.md#L53)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe you'd have to visually differentiate (somehow) where is an experimental API and where's a "standard" API, e.g.:

```
...
--- EXPERIMENTAL API ---
...

--- STANDARD API ---
...
```
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkind.3.md` line 270 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83uj4e057wy30M-fZ6:-N84E2b8CIP0ZCzt6xWj:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/memkind.3.md#L270)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

format as a code '...'
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkind.3.md` line 324 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83ubIR7IN0tUvIJ72A:-N84E4KH1TGxZRc7VOa4:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/memkind.3.md#L324)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

format as a code '...'
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkind.3.md` line 464 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83v61UBnOZvcUhJsy_:-N84E5j0BmSjJ5DYtEMM:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/memkind.3.md#L464)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

ochh, that makes sense :smiley: but i guess, yeah - UTILS could be nice name
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkind.3.md` line 508 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83vIwz8Sm__4EQhYu7:-N84E7GG9o4aPFDN9K2w:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/memkind.3.md#L508)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

use md syntax for links `[]()`
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkind.3.md` line 508 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83vNTZ2HeZ1ql_-pgf:-N84E7dM0po683kA3Hux:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/memkind.3.md#L508)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

put commands into \`` (mark them as a code)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-28 15:14 UTC, szadam reviewed
> Reviewed 1 of 3 files at r25, 1 of 1 files at r31, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 49 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, and @pbalcer)

___
*[`data/en/memkind.yml` line 36 at r23](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7_Rpo_436Rc_g_wrAD:-N84Mku74AP7Us8b-jlb:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/94ebfc7cb1f9f5b81bd1ecda4cd3809831bb2db0/data/en/memkind.yml#L36)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

found in the memkind's
</blockquote></details>

Done.
___
*[`data/en/memkind.yml` line 50 at r23](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N7_TTV96II4zs-TcDoL:-N84MlIEABzpJOvWD_n1:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/94ebfc7cb1f9f5b81bd1ecda4cd3809831bb2db0/data/en/memkind.yml#L50)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

using the
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-28 15:15 UTC, szadam commented
*[`content/memkind/manpages/hbwmalloc.3.md` line 77 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83jI7737xKyljs5Gtu:-N84Ms_hCRXmy-msDEGt:b-f4h7in) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L77)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. you don't have to add `\` - just break a line
2. you know, I meant all of these lines with descriptions (in all manpages) :wink: (see pmemstream doc link)
</blockquote></details>

just break line didn't work later in man files


<!-- Sent from Reviewable.io -->

2022-07-29 07:09 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 47 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/hbwmalloc.3.md` line 77 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83jI7737xKyljs5Gtu:-N87lGcy-psjDbfWu6Ly:b-1ban8i) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L77)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

just break line didn't work later in man files
</blockquote></details>

heh, I believe, they should NOT be broken within manpages :wink: it only should be broken here (in raw format), for readability

If you really want to break lines (besides my above comment), then `\` is ok - but just use sporadically, I guess
___
*[`content/memkind/manpages/memkind.3.md` line 53 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83uAejCAnaG1moHQCB:-N87lw2P-1HGJ2o5Zv5p:b-8fx2u7) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/memkind.3.md#L53)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:+1: 
___
*[`content/memkind/manpages/memkind.3.md` line 508 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83vNTZ2HeZ1ql_-pgf:-N87mNEs-d0-qjaivWWC:b4uj8pt) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/memkind.3.md#L508)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I can see it's done elsewhere, but not here...?
___
*[`content/memkind/manpages/memkind.3.md` line 61 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N87lz0n3F7Gu87-l8Vd:-N87lz0n3F7Gu87-l8Ve:b6c3qsq) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/memkind.3.md#L61)):*
> ```Markdown
> int memkind_create_kind(memkind_memtype_t memtype_flags, memkind_policy_t policy, memkind_bits_t flags, memkind_t *kind);
> ```
> STANDARD API:
> ```

you can add some empty lines here to split these blocks of code, for readability


<!-- Sent from Reviewable.io -->

2022-07-29 13:53 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r28, 1 of 1 files at r29, 1 of 1 files at r30, 1 of 1 files at r31, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 35 unresolved discussions (waiting on @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/hbwmalloc.3.md` line 156 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N89DCV-DmDcJsF2qilt:-N89DCV-DmDcJsF2qilu:b-r8nqmh) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L156)):*
> ```Markdown
> The <*hbwmalloc.h*> file defines the external functions and enumerations for the hbwmalloc library. These interfaces define a heap manager that targets high bandwidth memory numa nodes.
> 
> ## FILES ##
> ```

change to UTILS



_Code quote:_
```Markdown
## FILES ##
```
___
*[`content/memkind/manpages/memkind.3.md` line 121 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N899UBeAOEzgiicO8jc:-N899UBeAOEzgiicO8jd:b-y1eaz6) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/memkind.3.md#L121)):*
> ```Markdown
> 
> HEAP MANAGEMENT:
> :   The functions described in this section define a heap manager with an interface modeled on the ISO C standard API’s, except that the user must specify the kind of memory with the first argument to each function. See the **KINDS** section below for a full description of the implemented kinds. For file-backed kind of memory see `memkind_create_pmem()` or `memkind_create_pmem_with_config()`. For memory kind created on user-specified area, please check `memkind_create_fixed()`.
> ```

make this a link



_Code quote:_
```Markdown
**KINDS**
```
___
*[`content/memkind/manpages/memkind.3.md` line 183 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N89A8OA53ceNwspEMmC:-N89A8OA53ceNwspEMmD:boud1y1) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/memkind.3.md#L183)):*
> ```Markdown
> `memkind_create_pmem()`
> :   is a convenient function used to create a file-backed kind of memory. It allocates a temporary file in the given directory *dir*. The file is created in a fashion similar to **tmpfile(3)**, so that the file name does not appear when the directory is listed and the space is automatically freed when the program terminates. The file is truncated to a size of *max_size* bytes and the resulting space is memory-mapped.
> Note that the actual file system space is not allocated immediately, but only on a call to `memkind_pmem_mmap()` (see `memkind_pmem(3)`). This allows to create a pmem memkind of a pretty large size without the need to reserve in advance the corresponding file system space for the entire heap. If the value of *max_size* equals 0, pmem memkind is only limited by the capacity of the file system mounted under *dir* argument. The minimum *max_size* value which allows to limit the size of kind by the library is defined as **MEMKIND_PMEM_MIN_SIZE**. Calling `memkind_create_pmem()` with a size smaller than that and different than 0 will return an error. The maximum allowed size is not limited by **memkind**, but by the file system specified by the *dir* argument. The *max_size* passed in is the raw size of the memory pool and **jemalloc** will use some of that space for its own metadata. Returns zero if the pmem memkind is created successfully or an error code from the [ERRORS](#errors) section if not.
> ```

this shouldn't be formatted as a code. Please create a link to memkind_pmem(3) instead



_Code quote:_
```Markdown
(see `memkind_pmem(3)`)
```
___
*[`content/memkind/manpages/memkind.3.md` line 186 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N89ATh6BKfq40QmdNZY:-N89ATh6BKfq40QmdNZZ:b-jlu8wu) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/memkind.3.md#L186)):*
> ```Markdown
> 
> `memkind_create_pmem_with_config()`
> :   is a second function used to create a file-backed kind of memory. Function behaves simillar to `memkind_create_pmem()` but instead of passing *dir* and *max_size* arguments, it uses *config* param to specify characteristics of created file-backed kind of memory (see **KIND CONFIGURATION MANAGEMENT section**).
> ```

fix formatting, make a link



_Code quote:_
```Markdown
**KIND CONFIGURATION MANAGEMENT section**
```
___
*[`content/memkind/manpages/memkind.3.md` line 212 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N89An0F2snJ-mszTkLh:-N89An0F2snJ-mszTkLi:bqvzhb0) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/memkind.3.md#L212)):*
> ```Markdown
> 
> `memkind_get_stat()`
> :   retrieves statistic of the specified type and returns it in *value*. For more details about *stat* see the **MEMORY STATISTICS TYPE** section below. Measured statistic applies to specific *kind*, when *NULL* is given as *kind* then statistic applies to memory used by the whole memkind library.\
> ```

there is no section named that :)



_Code quote:_
```Markdown
**MEMORY STATISTICS TYPE**
```
___
*[`content/memkind/manpages/memkind.3.md` line 506 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N89BDgaEMvgruBonoHS:-N89BDgaEMvgruBonoHT:bhzx82n) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/memkind.3.md#L506)):*
> ```Markdown
> 
> MEMKIND_BACKGROUND_THREAD_LIMIT
> :   Enable background worker threads. Value should be from range 0 to maximum number of cpus. Setting **MEMKIND_BACKGROUND_THREAD_LIMIT** to specific value will limit maximum number of background worker threads to this value. 0 means maximum number of background worker threads will be limited to maximum number of cpus.
> ```

don't start the sentence with a number - "... . Value 0 means ..."



_Code quote:_
```Markdown
. 0 means
```
___
*[`content/memkind/manpages/memkind.3.md` line 514 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N89BUPZ1yyUCFHBPGiC:-N89BUPZ1yyUCFHBPGiD:bthz5uc) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/memkind.3.md#L514)):*
> ```Markdown
> 
> + JEMALLOC - sets the jemalloc heap manager
> + bTBB - sets the Intel Threading Building Blocks heap manager. This option requires installed
> ```

bTBB? it is just "TBB". Also the description is broken up to two items - please merge the



_Code quote:_
```Markdown
+ bTBB
```
___
*[`content/memkind/manpages/memkind.3.md` line 524 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N89Bp1H6N91RN3PXxoR:-N89Bp1H6N91RN3PXxoS:b-9cckmj) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/memkind.3.md#L524)):*
> ```Markdown
> 
> HUGETLB (huge pages)
> :   Current number of "persistent" huge pages can be read from */proc/sys/vm/nr_hugepages* file. Proposed way of setting hugepages is: 'sudo sysctl vm.nr_hugepages=<number_of_hugepages>'. More information can be found [here](https://www.kernel.org/doc/Documentation/vm/hugetlbpage.txt)
> ```

fix formatting



_Code quote:_
```Markdown
'sudo sysctl vm.nr_hugepages=<number_of_hugepages>'
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 53 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N898c-o4ArU4KlByKth:-N898c-o4ArU4KlByKti:bhz4cff) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/memkindallocator.3.md#L53)):*
> ```Markdown
> 
> `libmemkind::static_kind::allocator<T>` 
> :   is intended to be used with STL containers to allocate from static kinds of memory All public member types an [...]

2022-08-02 07:15 UTC, szadam reviewed
> Reviewed 4 of 6 files at r32, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: 12 of 14 files reviewed, 35 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/hbwmalloc.3.md` line 77 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83jI7737xKyljs5Gtu:-N8SPGEP2zVSV107pUD1:bca7ayh) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L77)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

heh, I believe, they should NOT be broken within manpages :wink: it only should be broken here (in raw format), for readability

If you really want to break lines (besides my above comment), then `\` is ok - but just use sporadically, I guess
</blockquote></details>

okey ;)


<!-- Sent from Reviewable.io -->

2022-08-02 12:56 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: 12 of 14 files reviewed, 35 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)



<!-- Sent from Reviewable.io -->

2022-08-02 13:24 UTC, haichangsi reviewed
> containin

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262#-:-N7oRCukE883iOJdh98E:b-6058o8)* status: 12 of 14 files reviewed, 129 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/fixedallocator.3.md` line 52 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8TiPj0A1ukzoe3SXn5:-N8TiPj0A1ukzoe3SXn6:b2niczw) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/fixedallocator.3.md#L52)):*
> ```Markdown
> `libmemkind::fixed::allocator<T>` 
> :   is intended to be used with STL containers to allocate memory on specific area. Memory management is handled by jemalloc on the supplied area. Refer memkind(3) man page for more details.\
> All public member types and functions correspond to standard library allocator concepts and definitions. The current implementation supports C++11 standard.
> ```

the



_Code quote:_
```Markdown
supports C++11 standard.
```
___
*[`content/memkind/manpages/fixedallocator.3.md` line 63 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8TiVZj5-8Yd9V5owNp:-N8TiVZj5-8Yd9V5owNq:b3ksc) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/fixedallocator.3.md#L63)):*
> ```Markdown
> 
> * `libmemkind::fixed::allocator<T>::deallocate(T *p, std::size_t n)`
>   :   deallocates memory associated with pointer returned by `allocate()` using `memkind_free()`.
> ```

a



_Code quote:_
```Markdown
with pointer
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 37 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N88Teaq1Unhc3wsKSPB:-N88Tear5_G40KXawQmv:bzd7z25) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L37)):*
> ```Markdown
> **hbwmalloc** - The high bandwidth memory interface
> 
> **Note:** *hbwmalloc.h* functionality is considered as stable API (STANDARD API).
> ```

as a stable API



_Code quote:_
```Markdown
as stable API
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 92 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N88oS6PEKoEjWC9c4o9:-N88oS6PEKoEjWC9c4oA:b-pcgfr9) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L92)):*
> ```Markdown
> >HBW_PAGESIZE_2MB
> >:  The two megabyte page size option.
> **Note:** This page size requires huge pages configuration described in [SYSTEM CONFIGURATION](#system-configuration) section.
> ```

in the



_Code quote:_
```Markdown
in 
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 96 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N88ojm60vjWhps_nHIJ:-N88ojm60vjWhps_nHIK:b3kqx) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L96)):*
> ```Markdown
> >HBW_PAGESIZE_1GB (DEPRECATED)
> >:  This option allows the user to specify arbitrary sizes backed by 1GB chunks of huge pages. Huge pages are allocated even if the size is not a modulo of 1GB.
> **Note:** This page size requires huge pages configuration described in [SYSTEM CONFIGURATION](#system-configuration) section.
> ```

.



_Code quote:_
```Markdown
in 
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 99 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N88ohyn7TtRJujIm-mw:-N88ohyn7TtRJujIm-mx:b3kqx) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L99)):*
> ```Markdown
> 
> >HBW_PAGESIZE_1GB_STRICT (DEPRECATED)
> >:  The total size of the allocation must be a multiple of 1GB with this option, otherwise the allocation will fail. Note: This page size requires huge pages configuration described in [SYSTEM CONFIGURATION](#system-configuration) section.
> ```

.



_Code quote:_
```Markdown
in 
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 101 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N88r-VVD7JbvjlPO3WP:-N88r-VVD7JbvjlPO3WQ:bkly9lo) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L101)):*
> ```Markdown
> >:  The total size of the allocation must be a multiple of 1GB with this option, otherwise the allocation will fail. Note: This page size requires huge pages configuration described in [SYSTEM CONFIGURATION](#system-configuration) section.
> 
> >**Note:** **HBW_PAGESIZE_2MB**, **HBW_PAGESIZE_1GB** and **HBW_PAGESIZE_1GB_STRICT** options are not supported with **HBW_POLICY_INTERLEAVE** policy.
> ```

with the



_Code quote:_
```Markdown
with
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 107 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N88uQUkC7TBcYJEa36l:-N88uQUkC7TBcYJEa36m:b1n2dko) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L107)):*
> ```Markdown
> 
> `hbw_set_policy()`
> :   sets the current fallback policy. The policy can be modified only once in the lifetime of an application and before calling `hbw_malloc()`, `hbw_calloc()`, `hbw_realloc()`, `hbw_posix_memalign()`, or `hbw_posix_memalign_psize()` function.\
> ```

maybe 'any of: ... functions' ?



_Code quote:_
```Markdown
hbw_malloc()`, `hbw_calloc()`, `hbw_realloc()`, `hbw_posix_memalign()`, or `hbw_posix_memalign_psize()` function.\
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 108 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N88v6zo6t7izQ2iCPMs:-N88v6zo6t7izQ2iCPMt:bb7p50i) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L108)):*
> ```Markdown
> `hbw_set_policy()`
> :   sets the current fallback policy. The policy can be modified only once in the lifetime of an application and before calling `hbw_malloc()`, `hbw_calloc()`, `hbw_realloc()`, `hbw_posix_memalign()`, or `hbw_posix_memalign_psize()` function.\
> **Note:** If the policy is not set, than **HBW_POLICY_PREFERRED** will be used by default.
> ```

then



_Code quote:_
```Markdown
than
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 111 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8957Qo31432vcoCXaE:-N8957Qo31432vcoCXaF:bdyos64) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L111)):*
> ```Markdown
> 
> >HBW_POLICY_BIND
> >:  If insufficient high bandwidth memory from the nearest NUMA node is available to satisfy a request, the allocated pointer is set to *NULL* and *errno* is set to **ENOMEM**. If insufficient high bandwidth memory pages are available at fault time the Out Of Memory (OOM) Killer is triggered. Note that pages are faulted exclusively from the high bandwidth NUMA node nearest at time of allocation, not at time of fault.
> ```

at the time of the 



_Code quote:_
```Markdown
at time of allocation, not at time of fault
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 114 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N895Vnb7kbUof3-PQfF:-N895Vnb7kbUof3-PQfG:b3kqx) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L114)):*
> ```Markdown
> 
> >HBW_POLICY_BIND_ALL
> >:  If insufficient high bandwidth memory is available to satisfy a request, the allocated pointer is set to *NULL* and errno is set to **ENOMEM**. If insufficient high bandwidth memory pages are available at fault time the Out Of Memory (OOM) Killer is triggered. Note that pages are faulted from the high bandwidth NUMA nodes. Nearest NUMA node is se [...]

2022-08-03 10:26 UTC, bratpiorka reviewed
> Reviewed 1 of 4 files at r8, 6 of 6 files at r32, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 134 unresolved discussions (waiting on @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/fixedallocator.3.md` line 60 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8YC2Nm8n2GzhUoljcp:-N8YC2Nm8n2GzhUoljcq:be5n2xc) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/fixedallocator.3.md#L60)):*
> ```Markdown
> **Note:**
> * `T *libmemkind::fixed::allocator<T>::allocate(std::size_t n)`
>   :   allocates memory using memkind_malloc() on the area supplied to libmemkind::fixed::allocator(). Throw *std::bad_alloc* when *n* = 0 or there is not enough memory to satisfy the request.
> ```

format as a code with ``



_Code quote:_
```Markdown
libmemkind::fixed::allocator()
```
___
*[`content/memkind/manpages/libmemtier.3.md` line 93 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8YCwNH2g11zFS_R31E:-N8YCwNH2g11zFS_R31F:biey1pv) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/libmemtier.3.md#L93)):*
> ```Markdown
> 
> `memtier_builder_add_tier()`
> :   adds memory *kind* to the *builder*. This *kind* defines a memory tier used in the *memtier_memory* object. This function can be called more than once to create several different memory tiers. The "weight" of the tier is determined by the *kind_ratio* parameter. The higher it is relative to other tiers’ *kind_ratio*, the higher the share of allocated memory on that tier, e.g. given that ratio DRAM:KMEM_DAX is 1:4:
> ```

do not break line here, use a simple comma instead



_Code quote:_
```Markdown
:   adds memory *kind* to the *builder*. This *kind* defines a memory tier used in the *memtier_memory* object. This function can be called more than once to create several different memory tiers. The "weight" of the tier is determined by the *kind_ratio* parameter. The higher it is relative to other tiers’ *kind_ratio*, the higher the share of allocated memory on that tier, e.g. given that ratio DRAM:KMEM_DAX is 1:4:
+ sample allocation size: 20 GB total, 4 GB DRAM, 16 GB KMEM_DAX
```
___
*[`content/memkind/manpages/libmemtier.3.md` line 107 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8YDDX19EP_xixDHx6e:-N8YDDX19EP_xixDHx6f:b-9qky4a) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/libmemtier.3.md#L107)):*
> ```Markdown
> 
> `memtier_malloc()`
> :   allocates *size* bytes of memory on one of memory tiers defined by the memory. See **libmemtier**(7) for further details on memory tiers. **memkind_malloc**() is used for allocations. For further details on it’s behavior see **memkind**(3).
> ```

format as a code instead of bold



_Code quote:_
```Markdown
**memkind_malloc**
```
___
*[`content/memkind/manpages/libmemtier.3.md` line 107 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8YDa9v6ygttNemnhyV:-N8YDa9v6ygttNemnhyW:bklkdkx) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/libmemtier.3.md#L107)):*
> ```Markdown
> 
> `memtier_malloc()`
> :   allocates *size* bytes of memory on one of memory tiers defined by the memory. See **libmemtier**(7) for further details on memory tiers. **memkind_malloc**() is used for allocations. For further details on it’s behavior see **memkind**(3).
> ```

all references to other doc should be a links



_Code quote:_
```Markdown
**libmemtier**(7)
```
___
*[`content/memkind/manpages/libmemtier.7.md` line 114 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8YE4NLDB6cbnioCUDD:-N8YE4NLDB6cbnioCUDE:bua0aaz) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/libmemtier.7.md#L114)):*
> ```Markdown
> ## EXAMPLES ##
> 
> The following example will run ls with the memkind memory tiering library. Make sure that paths to both **libmemtier.so** and **libmemkind.so** are included in **LD_LIBRARY_PATH**. During the application run, 20% of the allocated memory will come from PMEM memory and 80% will come from DRAM ( *FS_DAX:DRAM* ratio is 1:4):
> ```

remove space after opening bracket



_Code quote:_
```Markdown
DRAM ( *FS_DAX:DRAM*
```


<!-- Sent from Reviewable.io -->

2022-08-03 11:02 UTC, szadam reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 134 unresolved discussions (waiting on @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/fixedallocator.3.md` line 52 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8TiPj0A1ukzoe3SXn5:-N8YFxB-CTRS3acXYEfp:bswax03) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/fixedallocator.3.md#L52)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

the
</blockquote></details>

you mean "the C++11 standard"?


<!-- Sent from Reviewable.io -->

2022-08-03 11:05 UTC, szadam reviewed
> Reviewed 4 of 4 files at r34, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 134 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/fixedallocator.3.md` line 60 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8YC2Nm8n2GzhUoljcp:-N8YN9oQ6wzjLxMXcLFs:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/fixedallocator.3.md#L60)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

format as a code with ``
</blockquote></details>

Done.
___
*[`content/memkind/manpages/fixedallocator.3.md` line 63 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8TiVZj5-8Yd9V5owNp:-N8YNAor7LkYLBIAARu1:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/fixedallocator.3.md#L63)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

a
</blockquote></details>

Done.
___
*[`content/memkind/manpages/libmemtier.3.md` line 93 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8YCwNH2g11zFS_R31E:-N8YNC4LEhQVLC4F-1vO:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/libmemtier.3.md#L93)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

do not break line here, use a simple comma instead
</blockquote></details>

Done.
___
*[`content/memkind/manpages/libmemtier.3.md` line 107 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8YDDX19EP_xixDHx6e:-N8YNC_L0s9zkE7RLhd4:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/libmemtier.3.md#L107)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

format as a code instead of bold
</blockquote></details>

Done.
___
*[`content/memkind/manpages/libmemtier.3.md` line 107 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8YDa9v6ygttNemnhyV:-N8YNDEe3mp0-nQmEgw-:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/libmemtier.3.md#L107)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

all references to other doc should be a links
</blockquote></details>

Done.
___
*[`content/memkind/manpages/libmemtier.7.md` line 114 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8YE4NLDB6cbnioCUDD:-N8YNF0MDX6Ua6z7egJ2:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/libmemtier.7.md#L114)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

remove space after opening bracket
</blockquote></details>

Done.
___
*[`content/memkind/manpages/pmemallocator.3.md` line 29 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8ThdjC9oMH0DTn9dnG:-N8YNGIp94BpJajfGSC-:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/pmemallocator.3.md#L29)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

a
</blockquote></details>

Done.
___
*[`content/memkind/manpages/pmemallocator.3.md` line 54 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8ThoUr4aP-0OG0Ntq-:-N8YNHN2A8GmCLF2FIOS:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/pmemallocator.3.md#L54)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

refer to/to the
</blockquote></details>

Done.
___
*[`content/memkind/manpages/pmemallocator.3.md` line 63 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8TfoSn0ZtM5MwY_ZYb:-N8YNI9aETE787QtV88r:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/pmemallocator.3.md#L63)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

the
</blockquote></details>

Done.
___
*[`content/memkind/manpages/pmemallocator.3.md` line 64 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8TiH5uCfBIWz2mGFB8:-N8YNIavBl-rtjeb_5Us:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/pmemallocator.3.md#L64)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

the
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-03 13:01 UTC, bratpiorka reviewed
> Reviewed 4 of 4 files at r34, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 130 unresolved discussions (waiting on @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/libmemtier.3.md` line 107 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8YDa9v6ygttNemnhyV:-N8Ymsn_DwIkTMh_WmMx:budtru8) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/libmemtier.3.md#L107)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

what about links to e.g. memkind(3) ?


<!-- Sent from Reviewable.io -->

2022-08-03 13:02 UTC, bratpiorka reviewed
I think we could merge this when we get to the 40th revision :) 

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262#-:-N8Yn52p1tU2qnzTrQPB:bq40035)* status: all files reviewed, 130 unresolved discussions (waiting on @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)



<!-- Sent from Reviewable.io -->

2022-08-03 17:48 UTC, szadam commented
*[`content/memkind/manpages/libmemtier.3.md` line 107 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8YDa9v6ygttNemnhyV:-N8ZodvH88B_BJob08vB:b-gginty) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/libmemtier.3.md#L107)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

what about links to e.g. memkind(3) ?
</blockquote></details>

my mistake, sorry


<!-- Sent from Reviewable.io -->

2022-08-03 18:16 UTC, szadam commented
*[`content/memkind/manpages/memkind.3.md` line 183 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N89A8OA53ceNwspEMmC:-N8Zv3D28vCidAv1zQaC:b-kznsuv) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/memkind.3.md#L183)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

this shouldn't be formatted as a code. Please create a link to memkind_pmem(3) instead
</blockquote></details>

it doesn't exist


<!-- Sent from Reviewable.io -->

2022-08-03 18:18 UTC, szadam commented
*[`content/memkind/manpages/memkind.3.md` line 183 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N89A8OA53ceNwspEMmC:-N8ZvSyoBoRy79oNL5DE:beh7ii6) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/memkind.3.md#L183)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

it doesn't exist
</blockquote></details>

or I don't know where?


<!-- Sent from Reviewable.io -->

2022-08-03 19:24 UTC, szadam reviewed
> Reviewed 1 of 4 files at r34, 4 of 4 files at r35, 1 of 1 files at r36, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 130 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, and @pbalcer)

___
*[`content/memkind/manpages/hbwmalloc.3.md` line 37 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N88Teaq1Unhc3wsKSPB:-N8_78ag4b1Bu913-gOk:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L37)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

as a stable API
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 92 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N88oS6PEKoEjWC9c4o9:-N8_79iE3yT1BAM0ybG6:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L92)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

in the
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 96 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N88ojm60vjWhps_nHIJ:-N8_7AHg2jlVJHKhw1we:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L96)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 99 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N88ohyn7TtRJujIm-mw:-N8_7Agq8JmgX1_61So-:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L99)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 101 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N88r-VVD7JbvjlPO3WP:-N8_7BYh9LukTBGv3Wyr:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L101)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

with the
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 107 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N88uQUkC7TBcYJEa36l:-N8_7m2o2bW5TRbi1IA9:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L107)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

maybe 'any of: ... functions' ?
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 108 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N88v6zo6t7izQ2iCPMs:-N8_7mTS39VNEK60y2EA:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L108)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

then
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 111 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8957Qo31432vcoCXaE:-N8_7nYv58mgBqyZYnlK:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L111)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

at the time of the 
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 114 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N895Vnb7kbUof3-PQfF:-N8_7o0x0SP7csXPctc3:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L114)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 117 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N897q0l8K5oKjudny44:-N8_7oKLAw53V_TvHduy:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L117)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 123 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N898-L63BFURNuNIhY9:-N8_7opU4TMjha008dCY:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L123)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

if a memory region
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 123 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N898H6Z7cAka09Sj1Dd:-N8_7pR77Fa1zjFLIhsP:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L123)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

in the
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 124 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N898b0e1P0Sv5r63uP8:-N8_7pxd5I3gsymO0WH_:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L124)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

in a serious
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 129 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N898tgcCHvcvkVtxZLo:-N8_7qPfBWFDsLkmsJ2W:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L129)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

the first byte
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 129 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N899B5DBhlpkJY5-Qx1:-N8_7r9eEbq1SP78FHHU:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L129)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

trigger the
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 156 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N89DCV-DmDcJsF2qilt:-N8_7rps9-PO2j9wK3kG:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L156)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

change to UTILS
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 167 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N89AS7g0ZaWHSqM7JCh:-N8_7shu6Ck_tOu2TSqd:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L167)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

of the
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 183 at [...]

2022-08-04 08:20 UTC, PatKamin reviewed
> Reviewed 1 of 4 files at r34, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 139 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`-- commits` line 19 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8bf9ceA47nVthBVSvZ):*
documentations -> documentation (there is no plural form for `documentation`)
___
*[`content/memkind/manpages/fixedallocator.3.md` line 1 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8biLPXEl3qE0u1nVjg:-N8biLPXEl3qE0u1nVjh:bo5cznj) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/fixedallocator.3.md#L1)):*
> ```Markdown
> ---
> ```

Add memkind graphics with stars as it's on the main memkind page. Here it's just a black stripe. Same on other sub-pages.
___
*[`content/memkind/manpages/fixedallocator.3.md` line 29 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8boa0U9T-_vrQYKTzm:-N8boa0U9T-_vrQYKTzn:b-5x6s8b) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/fixedallocator.3.md#L29)):*
> ```Markdown
> 
> **libmemkind::fixed::allocator<T>** - The C++ allocator compatible with the C++ standard library allocator concepts\
> **Note:** *pmem_allocator.h* functionality is considered as stable API (STANDARD API).
> ```

fixed_allocator.h



_Code quote:_
```Markdown
pmem_allocator.h
```
___
*[`content/memkind/manpages/fixedallocator.3.md` line 45 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8bnqlK15_wF4ZRHC5D:-N8bnqlK15_wF4ZRHC5E:b38vhp6) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/fixedallocator.3.md#L45)):*
> ```Markdown
> void libmemkind::fixed::allocator<T>::deallocate(T *p, std::size_t n) const;
> template <class U, class... Args> void libmemkind::fixed::allocator<T>::construct(U *p, Args... &&args) const;
> void libmemkind::fixed::allocator<T>::destroy(T *p) const;
> ```

All argument names in italics, as it's in the old manpage.



_Code quote:_
```Markdown
libmemkind::fixed::allocator(void *addr, size_t size);
template <typename U> libmemkind::fixed::allocator<T>::allocator(const libmemkind::fixed::allocator<U>&) noexcept;
template <typename U> libmemkind::fixed::allocator<T>::allocator(allocator<U>&& other) noexcept;
libmemkind::fixed::allocator<T>::~allocator();
T *libmemkind::fixed::allocator<T>::allocate(std::size_t n) const;
void libmemkind::fixed::allocator<T>::deallocate(T *p, std::size_t n) const;
template <class U, class... Args> void libmemkind::fixed::allocator<T>::construct(U *p, Args... &&args) const;
void libmemkind::fixed::allocator<T>::destroy(T *p) const;
```
___
*[`content/memkind/manpages/fixedallocator.3.md` line 51 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8bjKzB-Ams7Xi0C0gL:-N8bjKzC0o1lIOk3qIS2:b1cfwi9) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/fixedallocator.3.md#L51)):*
> ```Markdown
> 
> `libmemkind::fixed::allocator<T>` 
> :   is intended to be used with STL containers to allocate memory on specific area. Memory management is handled by jemalloc on the supplied area. Refer memkind(3) man page for more details.\
> ```

`memkind` in bold. Also, add a link to the appropriate web page.



_Code quote:_
```Markdown
memkind(3)
```
___
*[`content/memkind/manpages/fixedallocator.3.md` line 60 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8blUfF73vKMo9Lbk5A:-N8blUfF73vKMo9Lbk5B:b-8aa27w) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/fixedallocator.3.md#L60)):*
> ```Markdown
> **Note:**
> * `T *libmemkind::fixed::allocator<T>::allocate(std::size_t n)`
>   :   allocates memory using memkind_malloc() on the area supplied to `libmemkind::fixed::allocator()`. Throw *std::bad_alloc* when *n* = 0 or there is not enough memory to satisfy the request.
> ```

Bold.



_Code quote:_
```Markdown
memkind_malloc()
```
___
*[`content/memkind/manpages/fixedallocator.3.md` line 71 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8bohwu8nfPqMyXuBrR:-N8bohwu8nfPqMyXuBrS:b-5e8d1f) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/fixedallocator.3.md#L71)):*
> ```Markdown
> ## SEE ALSO ##
> 
> **memkind_pmem**(3), **memkind**(3)
> ```

Not mentioned in this manpage, remove.



_Code quote:_
```Markdown
**memkind_pmem**(3)
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 60 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8bkwss5TRa5jj9gGOU:-N8bkwss5TRa5jj9gGOV:brk8yob) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/memkindallocator.3.md#L60)):*
> ```Markdown
> 
> * `T *libmemkind::static_kind::allocator<T>::allocate(std::size_t n)`
>   :   allocates uninitialized memory of size *n* bytes of the specified kind using >`memkind_malloc()`. Throw **std::bad_alloc** when n = 0 or there is not enough memory to satisfy the request.
> ```

Remove `>`



_Code quote:_
```Markdown
>`memkind_malloc()`
```
___
*[`content/memkind/manpages/memkindallocator.3.md` line 63 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8bn0T07AdWHTbQggxZ:-N8bn0T07AdWHTbQggx_:brk8yob) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/memkindallocator.3.md#L63)):*
> ```Markdown
> 
> * `libmemkind::static_kind::allocator<T>::deallocate(T *p, std::size_t n)`
>   :   deallocates memory >associated with pointer returned by `allocate()` using `memkind_free()`.
> ```

Remove `>`



_Code quote:_
```Markdown
>associated
```


<!-- Sent from Reviewable.io -->

2022-08-04 11:21 UTC, PatKamin reviewed
> Reviewed 1 of 4 files at r35.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 170 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/fixedallocator.3.md` line 29 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8bwYzM3x6fgjjrZlJq:-N8bwYzM3x6fgjjrZlJr:bzd7z25) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/fixedallocator.3.md#L29)):*
> ```Markdown
> 
> **libmemkind::fixed::allocator<T>** - The C++ allocator compatible with the C++ standard library allocator concepts\
> **Note:** *pmem_allocator.h* functionality is considered as stable API (STANDARD API).
> ```

as a stable API



_Code quote:_
```Markdown
as stable API
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 56 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8c3Rkd5_dUgFGvtX3g:-N8c3Rkd5_dUgFGvtX3h:bbuh3s) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L56)):*
> ```Markdown
> hbw_policy_t hbw_get_policy(void);
> int hbw_set_policy(hbw_policy_t mode);
> int hbw_verify_memory_region(void *addr, size_t size, int flags);
> ```

All function arguments in italics.



_Code quote:_
```Markdown
int hbw_check_available(void);
void* hbw_malloc(size_t size);
void* hbw_calloc(size_t nmemb, size_t size);
void* hbw_realloc (void *ptr, size_t size);
void hbw_free(void *ptr);
size_t hbw_malloc_usable_size(void *ptr);
int hbw_posix_memalign(void **memptr, size_t alignment, size_t size);
int hbw_posix_memalign_psize(void **memptr, size_t alignment, size_t size, hbw_pagesize_t pagesize);
hbw_policy_t hbw_get_policy(void);
int hbw_set_policy(hbw_policy_t mode);
int hbw_verify_memory_region(void *addr, size_t size, int flags);
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 65 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8c46rA9mXQQMSAO7Qi:-N8c46rA9mXQQMSAO7Qj:b-tifjw5) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L65)):*
> ```Markdown
> 
> `hbw_malloc()`
> :   allocates *size* bytes of uninitialized high bandwidth memory. The allocated space is suitably aligned (after possible pointer coercion) for storage of any type of object. If *size* is zero then `hbw_malloc()` returns *NULL*.
> ```

NULL should not be in italics as in the memkindallocator manpage. Change that in all places.



_Code quote:_
```Markdown
*NULL*
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 73 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8c55TN7ALX41yrWd8j:-N8c55TN7ALX41yrWd8k:b74fei8) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L73)):*
> ```Markdown
> :   changes the size of the previously allocated high bandwidth memory referenced by *ptr* to *size* bytes. The contents of the memory remain unchanged up to the lesser of the new and old sizes. If the new size is larger, the contents of the newly allocated portion of the memory are undefined. Upon success, the memory referenced by *ptr* is freed and a pointer to the newly allocated high bandwidth memory is returned.\
>     **Note:** `hbw_realloc()` may move the memory allocation, resulting in a different return value than *ptr*.\
>     If *ptr* is *NULL*, the `hbw_realloc()` function behaves identically to `hbw_malloc()` for the specified size. If *size* is equal to zero, and *ptr* is not *NULL*, then the call is equivalent to `hbw_free(ptr)` and *NULL* is returned. The address *ptr*, if not *NULL*, was returned by a previous call to `hbw_malloc()`, `hbw_calloc()`, `hbw_realloc()` or `hbw_posix_memalign()`. Otherwise, or if `hbw_free(ptr)` was called before, undefined behavior occurs.\
> ```

`If *size* is equal to zero and *ptr* is not *NULL*, ` -> remove a comma before `and`



_Code quote:_
```Markdown
If *size* is equal to zero, and *ptr* is not *NULL*,
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 77 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8c5uHy3_06Anzdjlcl:-N8c5uHy3_06Anzdjlcm:b-vdaqm) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L77)):*
> ```Markdown
> 
> `hbw_free()`
> :    causes the allocated memory referenced by *ptr* to be made available for future allocations. If *ptr* is *NULL*, no action occurs. In other case the address *ptr*, if not *NULL*, must have been returned by a previous call to `hbw_malloc()`, `hbw_calloc()`, `hbw_realloc()`, `hbw_posix_memalign()` or `hbw_posix_memalign_psize()`. Otherwise, if *hbw_free(ptr)* was called before, undefined behavior occurs.
> ```

Backticks instead of asterisks.



_Code quote:_
```Markdown
*hbw_free(ptr)*
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 83 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8c7cBbBQgeKh5s2rj6:-N8c7cBbBQgeKh5s2rj7:b-zg1u26) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L83)):*
> ```Markdown
> 
> `hbw_posix_memalign()`
> :   allocates *size* bytes of high bandwidth memory such that the allocation’s base address is an even multiple of *alignment*, and returns the allocation in the value pointed to by *memptr*. The requested alignment must be a power of 2 at least as large as *sizeof(void*)*. If *size* is 0, then `hbw_posix_memalign()` returns 0, with a *NULL* returned in *memptr*.
> ```

(...) See the ERRORS section for other possible return values.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 103 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8c99WN8Rb-A-1HPKSr:-N8c99WN8Rb-A-1HPKSs:brlidap) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L103)):*
> ```Markdown
> >**Note:** **HBW_PAGESIZE_2MB**, **HBW_PAGESIZE_1GB** and **HBW_PAGESIZE_1GB_STRICT** options are not supported with the **HBW_POLICY_INTERLEAVE** policy.
> 
> `hbw_get_policy()`
> ```

Fallback policies are not described earlier in this man page and mentioning them here makes me confused. Either move this description after the hbw_set_policy() description or mention here that possible fallback policies are described there.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 111 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8cDKts0nSxQKVDckUM:-N8cDKts0nSxQKVDckUN:b-k1owy) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L111)):*
> ```Markdown
> 
> >HBW_POLICY_BIND
> >:  If insufficient high bandwidth memory from the nearest NUMA node is available to satisfy a request, the allocated pointer is set to *NULL* and *errno* is set to **ENOMEM**. If insufficient high bandwidth memory pages are available at fault time the Out Of Memory (OOM) Killer is triggered. Note that pages are faulted exclusively from the high bandwidth NUMA node nearest at time of allocation, not at the time of fault.
> ```

italics



_Code quote:_
```Markdown
Out Of Memory (OOM) Killer
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 111 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8cDyzw2W4AVX6iA6s_:-N8cDyzw2W4AVX6iA6sa:b-f10b7i) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L111)):*
> ```Markdown
> 
> >HBW_POLICY_BIND
> >:  If insufficient high bandwidth memory from the nearest NUMA node is available to satisfy a request, the allocated pointer is set to *NULL* and *errno* is set to **ENOMEM**. If insuff [...]

2022-08-04 11:21 UTC, PatKamin reviewed
> Reviewed 1 of 1 files at r36.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 170 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)



<!-- Sent from Reviewable.io -->

2022-08-04 12:05 UTC, PatKamin reviewed
> Reviewed 1 of 4 files at r35.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 193 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/libmemtier.3.md` line 30 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8caKMe0AR9ipGTA43O:-N8caKMe0AR9ipGTA43P:bzd7z25) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/libmemtier.3.md#L30)):*
> ```Markdown
> 
> **libmemtier** - memory tiering interface\
> **Note:** *memkind_memtier.h* functionality is considered as stable API (STANDARD API).
> ```

as a stable API



_Code quote:_
```Markdown
as stable API
```
___
*[`content/memkind/manpages/libmemtier.3.md` line 75 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8caTdp-Rdlxv7x6U9A:-N8caTdp-Rdlxv7x6U9B:b9rtr4g) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/libmemtier.3.md#L75)):*
> ```Markdown
> MEMTIER PROPERTY MANAGEMENT:
> ```c
> int memtier_ctl_set(struct memtier_builder *builder, const char *name, const void *val);
> ```

Italics for all arguments.



_Code quote:_
```Markdown
TIER MANAGEMENT:
```c
struct memtier_builder *memtier_builder_new(memtier_policy_t policy);
void memtier_builder_delete(struct memtier_builder *builder);
int memtier_builder_add_tier(struct memtier_builder *builder, memkind_t kind, unsigned kind_ratio);
struct memtier_memory *memtier_builder_construct_memtier_memory(struct memtier_builder *builder);
void memtier_delete_memtier_memory(struct memtier_memory *memory);
```
HEAP MANAGEMENT:
```c
void *memtier_malloc(struct memtier_memory *memory, size_t size);
void *memtier_kind_malloc(memkind_t kind, size_t size);
void *memtier_calloc(struct memtier_memory *memory, size_t num, size_t size);
void *memtier_kind_calloc(memkind_t kind, size_t num, size_t size);
void *memtier_realloc(struct memtier_memory *memory, void *ptr, size_t size);
void *memtier_kind_realloc(memkind_t kind, void *ptr, size_t size);
int memtier_posix_memalign(struct memtier_memory *memory, void **memptr, size_t alignment, size_t size);
int memtier_kind_posix_memalign(memkind_t kind, void **memptr, size_t alignment, size_t size);
size_t memtier_usable_size(void *ptr);
void memtier_free(void *ptr);
void memtier_kind_free(memkind_t kind, void *ptr);
size_t memtier_kind_allocated_size(memkind_t kind);
```
DECORATORS:
```c
void memtier_kind_malloc_post(memkind_t kind, size_t size, void **result);
void memtier_kind_calloc_post(memkind_t kind, size_t nmemb, size_t size, void **result);
void memtier_kind_posix_memalign_post(memkind_t kind, void **memptr, size_t alignment, size_t size, int *err);
void memtier_kind_realloc_post(memkind_t *kind, void *ptr, size_t size, void **result);
void memtier_kind_free_pre(void **ptr);
void memtier_kind_usable_size_post(void **ptr, size_t size);
```
MEMTIER PROPERTY MANAGEMENT:
```c
int memtier_ctl_set(struct memtier_builder *builder, const char *name, const void *val);
```
___
*[`content/memkind/manpages/libmemtier.3.md` line 87 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8caq5dDMaW2FGqVzJk:-N8caq5dDMaW2FGqVzJl:b-k1owy) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/libmemtier.3.md#L87)):*
> ```Markdown
> 
> `memtier_builder_new()`
> :   returns a pointer to a new *memtier_builder* object which is used for creating the *memtier_memory* object, policy determines the policy of allocations distribution between tiers by the *memtier_memory* object. See the **POLICIES** section in [**libmemtier**(7)](/memkind/manpages/libmemtier.7.html) for available options.
> ```

italics



_Code quote:_
```Markdown
policy
```
___
*[`content/memkind/manpages/libmemtier.3.md` line 93 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8cbXEoESu-65rH4_D_:-N8cbXEoESu-65rH4_Da:b4sxe4i) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/libmemtier.3.md#L93)):*
> ```Markdown
> 
> `memtier_builder_add_tier()`
> :   adds memory *kind* to the *builder*. This *kind* defines a memory tier used in the *memtier_memory* object. This function can be called more than once to create several different memory tiers. The "weight" of the tier is determined by the *kind_ratio* parameter. The higher it is relative to other tiers’ *kind_ratio*, the higher the share of allocated memory on that tier, e.g. given that ratio DRAM:KMEM_DAX is 1:4, sample allocation size: 20 GB total, 4 GB DRAM, 16 GB KMEM_DAX
> ```

given that the ratio between DRAM and KMEM_DAX is



_Code quote:_
```Markdown
given that ratio DRAM:KMEM_DAX
```
___
*[`content/memkind/manpages/libmemtier.3.md` line 93 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8cbe1hDx5imuSRq5N-:-N8cbe1hDx5imuSRq5N0:bi3kiqa) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/libmemtier.3.md#L93)):*
> ```Markdown
> 
> `memtier_builder_add_tier()`
> :   adds memory *kind* to the *builder*. This *kind* defines a memory tier used in the *memtier_memory* object. This function can be called more than once to create several different memory tiers. The "weight" of the tier is determined by the *kind_ratio* parameter. The higher it is relative to other tiers’ *kind_ratio*, the higher the share of allocated memory on that tier, e.g. given that ratio DRAM:KMEM_DAX is 1:4, sample allocation size: 20 GB total, 4 GB DRAM, 16 GB KMEM_DAX
> ```

the sample allocation sizes are:



_Code quote:_
```Markdown
sample allocation size:
```
___
*[`content/memkind/manpages/libmemtier.3.md` line 93 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8cdmXuEHIL1WS1ISPi:-N8cdmXuEHIL1WS1ISPj:b6n8mh0) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/libmemtier.3.md#L93)):*
> ```Markdown
> 
> `memtier_builder_add_tier()`
> :   adds memory *kind* to the *builder*. This *kind* defines a memory tier used in the *memtier_memory* object. This function can be called more than once to create several different memory tiers. The "weight" of the tier is determined by the *kind_ratio* parameter. The higher it is relative to other tiers’ *kind_ratio*, the higher the share of allocated memory on that tier, e.g. given that ratio DRAM:KMEM_DAX is 1:4, sample allocation size: 20 GB total, 4 GB DRAM, 16 GB KMEM_DAX
> ```

Add a note at the end of this description to see KINDS section in the memkind(3) for more information on kinds.
___
*[`content/memkind/manpages/libmemtier.3.md` line 106 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8ceKaO7MLxxRtK18sp:-N8ceKaO7MLxxRtK18sq:b-wnv91) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/libmemtier.3.md#L106)):*
> ```Markdown
> 
> `memtier_malloc()`
> :   allocates *size* bytes of memory on one of memory tiers defined by the memory. See [**libmemtier**(7)](/memkind/manpages/libmemtier.7.html) for further details on memory tiers. `memkind_malloc()` is used for allocations. For further details on it’s behavior see [**memkind**(3)](/memkind/manpages/memkind.3.html).
> ```

one of the memory tiers



_Code quote:_
```Markdown
one of memory tiers
```
___
*[`content/memkind/manpages/libmemtier.3.md` line 106 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8ceXU64xTjXynHqmOh:-N8ceXU64xTjXynHqmOi:bfkrgi8) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/libmemtier.3.md#L106)):*
> ```Markdown
> 
> `memtier_malloc()`
> :   allocates *size* bytes of memory on one of memory tiers defined  [...]

2022-08-05 08:22 UTC, szadam commented
*[`content/memkind/manpages/fixedallocator.3.md` line 1 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8biLPXEl3qE0u1nVjg:-N8h58pA9PAe1qqK9Vhm:b-so47se) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/fixedallocator.3.md#L1)):*
> Add memkind graphics with stars as it's on the main memkind page. Here it's just a black stripe. Same on other sub-pages.
I make it similar to other pmem documentation, so I don't change it.


<!-- Sent from Reviewable.io -->

2022-08-05 08:39 UTC, szadam commented
*[`content/memkind/manpages/fixedallocator.3.md` line 45 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8bnqlK15_wF4ZRHC5D:-N8h7VBHAmmUG5jNvNNO:b-hf3t89) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/fixedallocator.3.md#L45)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

All argument names in italics, as it's in the old manpage.
</blockquote></details>

I think that this looks good, like in other documentation. It is formatted us code and it is clear where the arguments are. In other case I will need to remove code block format.


<!-- Sent from Reviewable.io -->

2022-08-05 09:31 UTC, szadam reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 193 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/hbwmalloc.3.md` line 56 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8c3Rkd5_dUgFGvtX3g:-N8h9eG60rfGHqT3Zhva:b3kqx) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L56)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

All function arguments in italics.
</blockquote></details>

.
___
*[`content/memkind/manpages/libmemtier.3.md` line 75 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8caTdp-Rdlxv7x6U9A:-N8hEHRY2CFbaQUP25bB:boo8wor) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/libmemtier.3.md#L75)):*
> See the ERRORS section for other possible return values.
.
___
*[`content/memkind/manpages/memkindallocator.3.md` line 44 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8bxjRK89SNky4pLjW_:-N8hKxrk3ubE96851Q3u:b3kqx) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/memkindallocator.3.md#L44)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

All function arguments names in italics.
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2022-08-05 10:09 UTC, szadam reviewed
> Reviewed 4 of 4 files at r37, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 193 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, and @pbalcer)

___
*[`-- commits` line 19 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8bf9ceA47nVthBVSvZ):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

documentations -> documentation (there is no plural form for `documentation`)
</blockquote></details>

Done.
___
*[`content/memkind/manpages/fixedallocator.3.md` line 29 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8boa0U9T-_vrQYKTzm:-N8hTPU84neSZ0vt17rw:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/fixedallocator.3.md#L29)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

fixed_allocator.h
</blockquote></details>

Done.
___
*[`content/memkind/manpages/fixedallocator.3.md` line 29 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8bwYzM3x6fgjjrZlJq:-N8hTPqEA5IaarzBCEfO:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/fixedallocator.3.md#L29)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

as a stable API
</blockquote></details>

Done.
___
*[`content/memkind/manpages/fixedallocator.3.md` line 51 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8bjKzB-Ams7Xi0C0gL:-N8hTS5h3_SFrgBRYzrN:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/fixedallocator.3.md#L51)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

`memkind` in bold. Also, add a link to the appropriate web page.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/fixedallocator.3.md` line 60 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8blUfF73vKMo9Lbk5A:-N8hTScI2BworUKFrYOX:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/fixedallocator.3.md#L60)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Bold.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/fixedallocator.3.md` line 71 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8bohwu8nfPqMyXuBrR:-N8hTT6p4J2_ly2QiF1k:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/fixedallocator.3.md#L71)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Not mentioned in this manpage, remove.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 65 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8c46rA9mXQQMSAO7Qi:-N8hTUBt-obvN9onYcA3:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L65)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

NULL should not be in italics as in the memkindallocator manpage. Change that in all places.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 73 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8c55TN7ALX41yrWd8j:-N8hTUVbBB3MqDhXvKB8:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L73)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

`If *size* is equal to zero and *ptr* is not *NULL*, ` -> remove a comma before `and`
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 77 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8c5uHy3_06Anzdjlcl:-N8hTV1p-thQf4xXaon1:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L77)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Backticks instead of asterisks.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 83 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8c7cBbBQgeKh5s2rj6:-N8hTVKO533122TMqKql:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L83)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

(...) See the ERRORS section for other possible return values.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 103 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8c99WN8Rb-A-1HPKSr:-N8hTW7b0ek5efKApPE1:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L103)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Fallback policies are not described earlier in this man page and mentioning them here makes me confused. Either move this description after the hbw_set_policy() description or mention here that possible fallback policies are described there.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 111 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8cDKts0nSxQKVDckUM:-N8hTWn-EL_Spxm4OtYb:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L111)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

italics
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 111 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8cDyzw2W4AVX6iA6s_:-N8hTX3b6QTvH9oI035K:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L111)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

at the fault time
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 114 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8cDVo3A7YGOiRwb7FG:-N8hTXQWAoE_bHooN79h:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L114)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

italics
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 114 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8cDrPW5POk9CJZ3Fjx:-N8hTXmeByL8YlFj-MlZ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L114)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

at the fault time
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 114 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8cE4U_EsZVKs9hRpna:-N8hTYA52fMawDDhE7UM:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L114)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

italics
</blockquote></details>

Done.
___
*[`content/m [...]

2022-08-05 12:00 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 97 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/hbwmalloc.3.md` line 111 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8957Qo31432vcoCXaE:-N8hmqMb3sfh92F-hfSM:b-bajka) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L111)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not yet
___
*[`content/memkind/manpages/memkind.3.md` line 140 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8N7rRp46By7ESmTmq5:-N8ho1tc0_Je_g4yapPb:b3piybl) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/memkind.3.md#L140)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

if it is specified then you should use 'the' as you did in other sentences
___
*[`content/memkind/manpages/memkind.3.md` line 164 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8NO3Ji1a0bWAvTDku-:-N8hoNxi29RvZsv_oqTz:b54prk) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/memkind.3.md#L164)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

which specifies the directory path
___
*[`content/memkind/manpages/memkind.3.md` line 216 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8TNGNq-GGQb7qD4nLR:-N8hp0W887oK159y0cYb:b-rj3goy) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/memkind.3.md#L216)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

wraps the jemalloc's function
___
*[`content/memkind/manpages/memkind.3.md` line 216 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8TPpn55JNCne0AH4JL:-N8hpFlVDgIqEW1QtOUf:b-o9bci5) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/memkind.3.md#L216)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

when failed to parse an options string (because you parse a string)
___
*[`content/memkind/manpages/memkind.3.md` line 499 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8Ta7vV0ME-EHsu0Ryw:-N8hqZWx-qGUdFR_wMRa:b-8lfsas) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/memkind.3.md#L499)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I am wrong here, no 'the', sorry
___
*[`content/memkind/manpages/memkind.3.md` line 506 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8Tb2wL1HAzbtugv31c:-N8hrNNs4aZKAYHzoLZL:b-suxzoe) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/memkind.3.md#L506)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I am sorry, one more thing here, 'to the maximum'
___
*[`content/memkind/manpages/memkind.3.md` line 506 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8TbVKH3TR9vGU6DfCv:-N8hr_JK246I0GBOyHI9:b-bajka) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/memkind.3.md#L506)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not yet
___
*[`content/memkind/manpages/pmemallocator.3.md` line 54 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8ThoUr4aP-0OG0Ntq-:-N8hs4-61OnlxgI9t4Tl:b2niczw) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/pmemallocator.3.md#L54)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

the


<!-- Sent from Reviewable.io -->

2022-08-05 13:14 UTC, szadam reviewed
> Reviewed 3 of 3 files at r38, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 97 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, and @pbalcer)

___
*[`content/memkind/manpages/hbwmalloc.3.md` line 111 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8957Qo31432vcoCXaE:-N8i7tmv-OrwE1ETFnXJ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/hbwmalloc.3.md#L111)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

not yet
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkind.3.md` line 140 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8N7rRp46By7ESmTmq5:-N8i7yvm7Fx20UoJHSDx:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/memkind.3.md#L140)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

if it is specified then you should use 'the' as you did in other sentences
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkind.3.md` line 164 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8NO3Ji1a0bWAvTDku-:-N8i8-XB3y7SBcXDv5gD:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/memkind.3.md#L164)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

which specifies the directory path
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkind.3.md` line 216 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8TNGNq-GGQb7qD4nLR:-N8i81989scyuT5TCIlY:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/memkind.3.md#L216)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

wraps the jemalloc's function
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkind.3.md` line 216 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8TPpn55JNCne0AH4JL:-N8i81Ty-tXsTu1VNlOi:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/memkind.3.md#L216)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

when failed to parse an options string (because you parse a string)
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkind.3.md` line 499 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8Ta7vV0ME-EHsu0Ryw:-N8i84882RoptnOGNO51:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/memkind.3.md#L499)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

I am wrong here, no 'the', sorry
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkind.3.md` line 506 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8Tb2wL1HAzbtugv31c:-N8i84qN107d2yws6c1l:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/memkind.3.md#L506)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

I am sorry, one more thing here, 'to the maximum'
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkind.3.md` line 506 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8TbVKH3TR9vGU6DfCv:-N8i85lE-x7a0ViWbGFp:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/memkind.3.md#L506)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

not yet
</blockquote></details>

Done.
___
*[`content/memkind/manpages/pmemallocator.3.md` line 54 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8ThoUr4aP-0OG0Ntq-:-N8i8BG7DsmEvzXMt2-N:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/pmemallocator.3.md#L54)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

the
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-08 08:13 UTC, PatKamin reviewed
> Reviewed 2 of 4 files at r37, 1 of 3 files at r38, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 47 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/fixedallocator.3.md` line 1 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8biLPXEl3qE0u1nVjg:-N8wFwOf6YoCxqgdAvlz:b-2xus3u) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/fixedallocator.3.md#L1)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

> Add memkind graphics with stars as it's on the main memkind page. Here it's just a black stripe. Same on other sub-pages.
I make it similar to other pmem documentation, so I don't change it.
</blockquote></details>

OK. Indeed, there are same black stripes in pmemkv and pmemstream man pages. You may leave it as it is then, I suppose. I would just like to raise my concern that this looks VERY odd - like a bug on a web page.
___
*[`content/memkind/manpages/fixedallocator.3.md` line 45 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8bnqlK15_wF4ZRHC5D:-N8wH4nIEzOwJIHt7KeM:b17lw1c) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/fixedallocator.3.md#L45)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

I think that this looks good, like in other documentation. It is formatted us code and it is clear where the arguments are. In other case I will need to remove code block format.
</blockquote></details>

What about generated man page from this markdown file? Are there arguments in italics as they should be? I agree that this looks nice on the web page, but this file is also a skeleton for generating a manual file and it should be formatted properly as well. These functions doesn't have to be formatted as a code block to be readable, I think.
___
*[`content/memkind/manpages/fixedallocator.3.md` line 60 at r38](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8wM2GaDe7ETT-HBAup:-N8wM2GaDe7ETT-HBAuq:b1r3zb5) ([raw file](https://github.com/pmem/pmem.github.io/blob/5bbf8ae8c46ca7f7c762c6eb8a40e81eb1084b1f/content/memkind/manpages/fixedallocator.3.md#L60)):*
> ```Markdown
> **Note:**
> * `T *libmemkind::fixed::allocator<T>::allocate(std::size_t n)`
>   :   allocates memory using **memkind_malloc**() on the area supplied to `libmemkind::fixed::allocator()`. Throw *std::bad_alloc* when *n* = 0 or there is not enough memory to satisfy the request.
> ```

Whole equation should be formatted as italics to distinct it from the text.



_Code quote:_
```Markdown
*n* = 0
```
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 56 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8c3Rkd5_dUgFGvtX3g:-N8wMMkaEFont3GPRZ_E:b-796y05) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L56)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

.
</blockquote></details>

See comment in the fixedallocator md file.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 103 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8c99WN8Rb-A-1HPKSr:-N8wNSXW7HHBpQBOggXJ:b2tprd6) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L103)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

That's not what I meant. I meant that you could move this function description after the policies' description. I see policies list as a part of hbw_set_policy() description. Hence, hbw_get_policy() description can be moved after all possible policies are introduced.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 126 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8cEpetDy-yKcWgWYQ_:-N8wOhrZ8nQKiqOaL0D5:b-6lz1t0) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L126)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please, move this to the previous paragraph changing a `Note` into `Notes`
___
*[`content/memkind/manpages/libmemtier.3.md` line 87 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8caq5dDMaW2FGqVzJk:-N8wQw1R-GnW8BVoMHW4:b-7tvhuc) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/libmemtier.3.md#L87)):*
Now I realised that I didn't give a context. All function arguments mentioned in function descriptions should be in italics. With such a rule, the text should sth like:
> *policy* determines the policy of allocations
___
*[`content/memkind/manpages/libmemtier.3.md` line 93 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8cbXEoESu-65rH4_D_:-N8wTQqJ9qX40L7XwwUK:b2edwj6) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/libmemtier.3.md#L93)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`between` is the missing word.
___
*[`content/memkind/manpages/libmemtier.3.md` line 93 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8cdmXuEHIL1WS1ISPi:-N8wTXvECWh071m8GCqM:b-oguy42) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/libmemtier.3.md#L93)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Missing a dot at the end of the previous sentence.
___
*[`content/memkind/manpages/libmemtier.3.md` line 115 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8cf6pZ-IIhiLaC56eQ:-N8wUk4S7zbNfwERtkzB:b63887z) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/libmemtier.3.md#L115)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done, I can see plenty of memkind.3 man page references which are not links.
___
*[`content/memkind/manpages/libmemtier.3.md` line 93 at r38](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8wTk3bBf0N_-NebOVv:-N8wTk3bBf0N_-NebOVw:b3c0dmr) ([raw file](https://github.com/pmem/pmem.github.io/blob/5bbf8ae8c46ca7f7c762c6eb8a40e81eb1084b1f/content/memkind/manpages/libmemtier.3.md#L93)):*
> ```Markdown
> 
> `memtier_builder_add_tier()`
> :   adds memory *kind* to the *builder*. This *kind* defines a memory tier used in the *memtier_memory* object. This function can be called more than once to create several different memory tiers. The "weight" of the tier is determined by the *kind_ratio* parameter. The higher it is relative to other tiers’ *kind_ratio*, the higher the share of allocated memory on that tier, e.g. given that the ratio DRAM and KMEM_DAX is 1:4, the sample allocation sizes are: 20 GB total, 4 GB DRAM, 16 GB KMEM_DAX **NOTE:** For more information on kinds see **KINDS** section in the [**memkind**](/memkind/manpages/memkind.3.html)(3).
> ```

**Note:**



_Code quote:_
```Markdown
**NOTE:**
```
___
*[`content/memkind/manpages/libmemtier.3.md` line 93 at r38](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8wTvfW0vWezCoq7Fas:-N8wTvfW0vWezCoq7Fat:b69vyzn) ([raw file](https://github.com/pmem/pmem.github.io/blob/5bbf8ae8c46ca7f7c762c6eb8a40e81eb1084b1f/content/memkind/manpages/libmemtier.3.md#L93)):*
> ```Markdown
> 
> `memtier_builder_add_tier()`
> :   adds memor [...]

2022-08-08 08:39 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 39 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/memkind.3.md` line 506 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8TbVKH3TR9vGU6DfCv:-N8waOkcCeoDAUzgvQM1:bmhbj1x) ([raw file](https://github.com/pmem/pmem.github.io/blob/bc998eaf6fb8013f284bf5647bdfd8092f4f00aa/content/memkind/manpages/memkind.3.md#L506)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not yet, Value 0 means THE maximum number of background worker threads will be limited to the maximum number of cpus.


<!-- Sent from Reviewable.io -->

2022-08-08 10:01 UTC, PatKamin reviewed
> Reviewed 1 of 6 files at r32, 1 of 4 files at r34, 1 of 4 files at r37, 2 of 3 files at r38.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 36 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/memkind.3.md` line 155 at r38](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8wrAtj3eUQgDtJf4rv:-N8wrAtj3eUQgDtJf4rw:b-kr7x12) ([raw file](https://github.com/pmem/pmem.github.io/blob/5bbf8ae8c46ca7f7c762c6eb8a40e81eb1084b1f/content/memkind/manpages/memkind.3.md#L155)):*
> ```Markdown
> 
> #### KIND CONFIGURATION MANAGEMENT ####
> :   The functions described in this section define a way to create, delete and update kind specific configuration. Except of `memkind_config_new()`, user must specify the memkind configuration with the first argument to each function. API described here is most useful with file-backed kind of memory, e.g. `memkind_create_pmem_with_config()` method.
> ```

Remove `:` at the beginning of the paragraph.
___
*[`content/memkind/manpages/memkind.3.md` line 548 at r38](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8wsATi2Wigg2YSbaJE:-N8wsATi2Wigg2YSbaJF:b-70lb56) ([raw file](https://github.com/pmem/pmem.github.io/blob/5bbf8ae8c46ca7f7c762c6eb8a40e81eb1084b1f/content/memkind/manpages/memkind.3.md#L548)):*
> ```Markdown
> ## SEE ALSO ##
> 
> **malloc**(3), **malloc_usable_size**(3), **numa**(3), **hwloc**(3), **numactl**(8), **mbind**(2), **mmap**(2), **move_pages**(2), **jemalloc**(3), **memkind_dax_kmem**(3), **memkind_default**(3), **memkind_arena**(3), **memkind_fixed**(3), **memkind_hbw**(3), **memkind_hugetlb**(3), **memkind_pmem**(3), **syscall**(2), **write**(2)
> ```

I can't find a reference in this man page.



_Code quote:_
```Markdown
*move_pages**(2)
```
___
*[`content/memkind/manpages/pmemallocator.3.md` line 64 at r38](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8ws_6mCxVHRuAD1tdv:-N8ws_6mCxVHRuAD1tdw:b-46ydws) ([raw file](https://github.com/pmem/pmem.github.io/blob/5bbf8ae8c46ca7f7c762c6eb8a40e81eb1084b1f/content/memkind/manpages/pmemallocator.3.md#L64)):*
> ```Markdown
> + `libmemkind::allocation_policy::CONSERVATIVE`
>   :   Conservative allocator memory usage policy - prioritize memory usage at the cost of performance.\
> All public member types and functions corresponds to standard library allocator concepts and definitions. The current implementation supports the C++11 standard.
> ```

correspond



_Code quote:_
```Markdown
corresponds
```
___
*[`content/memkind/manpages/pmemallocator.3.md` line 72 at r38](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8wseO60xhKqqc5WARG:-N8wseO60xhKqqc5WARH:b-e7ujpe) ([raw file](https://github.com/pmem/pmem.github.io/blob/5bbf8ae8c46ca7f7c762c6eb8a40e81eb1084b1f/content/memkind/manpages/pmemallocator.3.md#L72)):*
> ```Markdown
> **Note:**
> * `T *libmemkind::pmem::allocator<T>::allocate(std::size_t n)`
>   :   allocates persistent memory using `memkind_malloc()`. Throw *std::bad_alloc* when *n* = 0 or there is not enough memory to satisfy the request.
> ```

The whole sentence should be in italics to distinct it from the rest of the text.



_Code quote:_
```Markdown
*n* = 0 
```
___
*[`data/en/memkind.yml` line 44 at r15](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N6wORnXEGgM1gbxZ4WE:-N8wtDs23KX3UEGLeEQD:bwkwloz) ([raw file](https://github.com/pmem/pmem.github.io/blob/cae9329aaa594cac2dc1e7752ee488b102c9db66/data/en/memkind.yml#L44)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

what should I write exactly?
</blockquote></details>

"RPMs for Fedora and OpenSuse OSes" for example.


<!-- Sent from Reviewable.io -->

2022-08-08 11:01 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 34 unresolved discussions (waiting on @bratpiorka, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/hbwmalloc.3.md` line 77 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83jI7737xKyljs5Gtu:-N8x6J8z5Iuu5NmJViZZ:b-j1ixju) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L77)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

okey ;)
</blockquote></details>

"okey"? I believe it's still not done... :wink: 


<!-- Sent from Reviewable.io -->

2022-08-08 11:13 UTC, bratpiorka reviewed
> Reviewed 3 of 4 files at r37, 3 of 3 files at r38, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 25 unresolved discussions (waiting on @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/memkind.3.md` line 183 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N89A8OA53ceNwspEMmC:-N8x92C34w5P41GGUWku:bdsi1db) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/memkind.3.md#L183)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

or I don't know where?
</blockquote></details>

ok, memkind_pmem isn't published
___
*[`content/memkind/manpages/memkind.3.md` line 186 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N89ATh6BKfq40QmdNZY:-N8x7ZGYCbHc-DRmZRSG:blv4a9j) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/memkind.3.md#L186)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sectiom -> section


<!-- Sent from Reviewable.io -->

2022-08-09 06:41 UTC, szadam reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 25 unresolved discussions (waiting on @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/hbwmalloc.3.md` line 77 at r26](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N83jI7737xKyljs5Gtu:-N90Ifw2-Z8Wamm6UflL:b-97e1i6) ([raw file](https://github.com/pmem/pmem.github.io/blob/195f7b02e50c49a9657c27b8d64976140e4abc4c/content/memkind/manpages/hbwmalloc.3.md#L77)):*
> heh, I believe, they should NOT be broken within manpages 😉 it only should be broken here (in raw format), for readability
I thought that this will make it more readability on website, but okey, I will change it.


<!-- Sent from Reviewable.io -->

2022-08-09 08:12 UTC, szadam reviewed
> Reviewed 8 of 8 files at r39, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 25 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, and @pbalcer)

___
*[`content/memkind/manpages/fixedallocator.3.md` line 45 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8bnqlK15_wF4ZRHC5D:-N90dg-0BbflPK9xtbs1:b-uik0o8) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/fixedallocator.3.md#L45)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

What about generated man page from this markdown file? Are there arguments in italics as they should be? I agree that this looks nice on the web page, but this file is also a skeleton for generating a manual file and it should be formatted properly as well. These functions doesn't have to be formatted as a code block to be readable, I think.
</blockquote></details>

The argument are highlighted
___
*[`content/memkind/manpages/fixedallocator.3.md` line 60 at r38](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8wM2GaDe7ETT-HBAup:-N90dqoU7AuBFAgrklp2:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/5bbf8ae8c46ca7f7c762c6eb8a40e81eb1084b1f/content/memkind/manpages/fixedallocator.3.md#L60)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Whole equation should be formatted as italics to distinct it from the text.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 56 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8c3Rkd5_dUgFGvtX3g:-N90ds6d4exHGF39h4ci:b32vin) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L56)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

See comment in the fixedallocator md file.
</blockquote></details>

:D
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 103 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8c99WN8Rb-A-1HPKSr:-N90dxcL7PzNTTceonsX:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L103)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

That's not what I meant. I meant that you could move this function description after the policies' description. I see policies list as a part of hbw_set_policy() description. Hence, hbw_get_policy() description can be moved after all possible policies are introduced.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/hbwmalloc.3.md` line 126 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8cEpetDy-yKcWgWYQ_:-N90e0cq0jRlmyhmssC0:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/hbwmalloc.3.md#L126)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, move this to the previous paragraph changing a `Note` into `Notes`
</blockquote></details>

Done.
___
*[`content/memkind/manpages/libmemtier.3.md` line 87 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8caq5dDMaW2FGqVzJk:-N90e1jk509FjSpDH-xV:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/libmemtier.3.md#L87)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Now I realised that I didn't give a context. All function arguments mentioned in function descriptions should be in italics. With such a rule, the text should sth like:
> *policy* determines the policy of allocations
</blockquote></details>

Done.
___
*[`content/memkind/manpages/libmemtier.3.md` line 93 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8cbXEoESu-65rH4_D_:-N90e2eoEDU_FWq8ZnCP:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/libmemtier.3.md#L93)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

`between` is the missing word.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/libmemtier.3.md` line 93 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8cdmXuEHIL1WS1ISPi:-N90e42q0oL66TT4Kq28:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/libmemtier.3.md#L93)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Missing a dot at the end of the previous sentence.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/libmemtier.3.md` line 115 at r36](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8cf6pZ-IIhiLaC56eQ:-N90e8IQ29DxN5SibMqz:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/82bb1f7c824023f1940517f2a91a7f19d56cf29b/content/memkind/manpages/libmemtier.3.md#L115)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Not done, I can see plenty of memkind.3 man page references which are not links.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/libmemtier.3.md` line 93 at r38](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8wTk3bBf0N_-NebOVv:-N90e4k72TDY61to6m5H:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/5bbf8ae8c46ca7f7c762c6eb8a40e81eb1084b1f/content/memkind/manpages/libmemtier.3.md#L93)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

**Note:**
</blockquote></details>

Done.
___
*[`content/memkind/manpages/libmemtier.3.md` line 93 at r38](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8wTvfW0vWezCoq7Fas:-N90e5j90ffZ65O9xRgt:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/5bbf8ae8c46ca7f7c762c6eb8a40e81eb1084b1f/content/memkind/manpages/libmemtier.3.md#L93)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

see the **KINDS** section
</blockquote></details>

Done.
___
*[`content/memkind/manpages/libmemtier.3.md` line 112 at r38](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8wUU3c4Mizeye1VgQv:-N90e7bQ3y8DCL9enpDH:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/5bbf8ae8c46ca7f7c762c6eb8a40e81eb1084b1f/content/memkind/manpages/libmemtier.3.md#L112)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Include the number of the man page in the link, as it's in other places.
</blockquote></details>

Done.
___
*[`content/memkind/manpages/libmemtier.3.md` line 160 at r38](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8wVucK6wA66vLDW4WK:-N90eAggCiYsciTX_9a7:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/5bbf8ae8c46ca7f7c762c6eb8a40e81eb1084b1f/content/memkind/manpages/libmemtier.3.md#L160)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

italics
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkind.3.md` line 186 at r31](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N89ATh6BKfq40QmdNZY:-N90eEin0sSg_c7qOSwZ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/bfa66d592235927941914e8f295c3c35d654248b/content/memkind/manpages/memkind.3.md#L186)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

sectiom -> section
</blockquote></details>

Done.
___
*[`content/memkind/manpages/memkind.3.md` line 506 at r33](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N8TbVKH3TR9vGU6DfCv:-N90eG9IESiW5cXxONRM:b-896fix) ( [...]

2022-08-09 08:20 UTC, szadam reviewed
> Reviewed 6 of 6 files at r40, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 25 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, and @pbalcer)



<!-- Sent from Reviewable.io -->

2022-08-09 10:02 UTC, bratpiorka reviewed
> Reviewed 2 of 8 files at r39, 6 of 6 files at r40, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 25 unresolved discussions (waiting on @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, @pbalcer, and @szadam)

___
*[`content/memkind/manpages/libmemtier.3.md` line 88 at r40](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N911pRb8ZkciHt1Rxkh:-N911pRb8ZkciHt1Rxki:b-9cckmj) ([raw file](https://github.com/pmem/pmem.github.io/blob/2b4cab9560cd6474c01fd683e6766a1523a30022/content/memkind/manpages/libmemtier.3.md#L88)):*
> ```Markdown
> 
> `memtier_builder_new()`
> :   returns a pointer to a new *memtier_builder* object which is used for creating the *memtier_memory* object, *p*olicy* determines the policy of allocations distribution between tiers by the *memtier_memory* object. See the **POLICIES** section in [**libmemtier**(7)](/memkind/manpages/libmemtier.7.html) for available options.
> ```

fix formatting



_Code quote:_
```Markdown
*p*olicy*
```


<!-- Sent from Reviewable.io -->

2022-08-09 11:16 UTC, szadam reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 25 unresolved discussions (waiting on @bratpiorka, @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, and @pbalcer)

___
*[`content/memkind/manpages/libmemtier.3.md` line 88 at r40](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N911pRb8ZkciHt1Rxkh:-N91JT7b4_tXmaZHoKWU:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/2b4cab9560cd6474c01fd683e6766a1523a30022/content/memkind/manpages/libmemtier.3.md#L88)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

fix formatting
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-09 12:27 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r41, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 24 unresolved discussions (waiting on @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, and @pbalcer)



<!-- Sent from Reviewable.io -->

2022-08-09 12:34 UTC, szadam reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 24 unresolved discussions (waiting on @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, and @pbalcer)



<!-- Sent from Reviewable.io -->

2022-08-10 08:07 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r42, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 24 unresolved discussions (waiting on @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, and @pbalcer)



<!-- Sent from Reviewable.io -->

2022-08-10 08:26 UTC, szadam reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 24 unresolved discussions (waiting on @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, and @pbalcer)



<!-- Sent from Reviewable.io -->

2022-08-10 08:27 UTC, szadam reviewed
> Reviewed 1 of 1 files at r41, 1 of 1 files at r42.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 24 unresolved discussions (waiting on @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, and @pbalcer)



<!-- Sent from Reviewable.io -->

2022-08-10 08:47 UTC, bratpiorka reviewed
@all - latest revision looks really good. Let's merge it and add other fixes in separate PR

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262#-:-N95myA6Cf5usTH-g3gh:b-pocs4k)* status: all files reviewed, 24 unresolved discussions (waiting on @haichangsi, @kilobyte, @lukaszstolarczuk, @maciekpac, @PatKamin, and @pbalcer)



<!-- Sent from Reviewable.io -->

2022-08-10 09:28 UTC, merged

2022-08-10 09:31 UTC, PatKamin reviewed
> Reviewed 2 of 8 files at r39, 3 of 6 files at r40, 1 of 1 files at r41, 1 of 1 files at r42, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/262)* status: all files reviewed, 5 unresolved discussions

___
*[`content/memkind/manpages/hbwmalloc.3.md` line 124 at r42](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N963IiG2jjM3tzTMOfM:-N963IiG2jjM3tzTMOfN:bktt03k) ([raw file](https://github.com/pmem/pmem.github.io/blob/ad725dc2caf601b029aa297c155137c2593dbcf6/content/memkind/manpages/hbwmalloc.3.md#L124)):*
> ```Markdown
> `hbw_verify_memory_region()`
> :   verifies if a memory region fully falls into high bandwidth memory. Returns 0 if memory address range from *addr* to *addr +* *size* is allocated in high bandwidth memory, -1 if any fragment of memory was not backed by high bandwidth memory (e.g. when memory is not initialized) or one of error codes described in the [ERRORS](#errors) section.
> **Notes:** Using this function in production code may result in a serious performance penalty. **The *flags* argument may include optional flags that modify function behavior:**
> ```

This sentence doesn't have to be in bold.



_Code quote:_
```Markdown
**The *flags* argument may include optional flags that modify function behavior:**
```
___
*[`content/memkind/manpages/libmemtier.3.md` line 94 at r42](https://reviewable.io/reviews/pmem/pmem.github.io/262#-N963fplCEt-CH4Oy_M0:-N963fplCEt-CH4Oy_M1:b-geaezu) ([raw file](https://github.com/pmem/pmem.github.io/blob/ad725dc2caf601b029aa297c155137c2593dbcf6/content/memkind/manpages/libmemtier.3.md#L94)):*
> ```Markdown
> 
> `memtier_builder_add_tier()`
> :   adds memory *kind* to the *builder*. This *kind* defines a memory tier used in the *memtier_memory* object. This function can be called more than once to create several different memory tiers. The "weight" of the tier is determined by the *kind_ratio* parameter. The higher it is relative to other tiers’ *kind_ratio*, the higher the share of allocated memory on that tier, e.g. given that the ratio between DRAM and KMEM_DAX is 1:4, the sample allocation sizes are: 20 GB total, 4 GB DRAM, 16 GB KMEM_DAX. 
> ```

Remove a whitespace at the end of the description.


<!-- Sent from Reviewable.io -->