librpmem content update
pmem/pmem.github.io pull request #312
Opened 2022-10-28 14:21 UTC by lukaszstolarczuk

- add deprecation and librpma notes,
- set fixed links to v1.12 (master branch will not contain librpmem soon).

// This change will be needed when https://github.com/pmem/pmdk/pull/5495 is merged... but it can actually be merged now

2022-10-28 21:06 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/312)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk and @wlemkows)

___
*[`content/pmdk/librpmem.md` line 33 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/312#-NFVPRg886JsfS0KJ4UD:-NFVPRg886JsfS0KJ4UE:b-pchx3c) ([raw file](https://github.com/pmem/pmem.github.io/blob/3c62c782ba9d893ebecaa005fac021ad8c556b69/content/pmdk/librpmem.md#L33)):*
> ```Markdown
> 
> Man pages that contains a list of the **Linux** interfaces provided:
> * Man page for [librpmem on the latest stable release](../manpages/linux/v1.12/librpmem/librpmem.7.html)
> ```

in ...



_Code quote:_
```Markdown
on the latest stable release
```


<!-- Sent from Reviewable.io -->

2022-10-31 08:25 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/312)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk and @wlemkows)



<!-- Sent from Reviewable.io -->

2022-10-31 10:41 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/312)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau and @wlemkows)

___
*[`content/pmdk/librpmem.md` line 33 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/312#-NFVPRg886JsfS0KJ4UD:-NFhcU7o-Et0vZMHOGjl:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/3c62c782ba9d893ebecaa005fac021ad8c556b69/content/pmdk/librpmem.md#L33)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

in ...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-31 10:46 UTC, PatKamin reviewed
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/312)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau, @lukaszstolarczuk, and @wlemkows)

___
*[`content/pmdk/librpmem.md` line 16 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/312#-NFhVsop4IAw0F8ClWCr:-NFhVsop4IAw0F8ClWCs:bfs9j5e) ([raw file](https://github.com/pmem/pmem.github.io/blob/3c62c782ba9d893ebecaa005fac021ad8c556b69/content/pmdk/librpmem.md#L16)):*
> ```Markdown
> ### The librpmem library
> 
> > **Note:** The alternative solution for accessing remote persistent memory is implemented by the [librpma](/librpma).
> ```

nit: `the librpma library` or `by librpma`
___
*[`content/pmdk/librpmem.md` line 41 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/312#-NFhWU4232jqYlzxV60R:-NFhWU4232jqYlzxV60S:b-fdyati) ([raw file](https://github.com/pmem/pmem.github.io/blob/3c62c782ba9d893ebecaa005fac021ad8c556b69/content/pmdk/librpmem.md#L41)):*
> ```Markdown
> 
> See the [rpmemd man page](../manpages/linux/v1.12/rpmemd/rpmemd.1.html)
> for the latest stable release documentation and examples or see older version:
> ```

See older version of an example? Or is it some link missing here?


<!-- Sent from Reviewable.io -->

2022-10-31 10:54 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/312)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk and @wlemkows)



<!-- Sent from Reviewable.io -->

2022-10-31 11:02 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/312)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau, @PatKamin, and @wlemkows)

___
*[`content/pmdk/librpmem.md` line 41 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/312#-NFhWU4232jqYlzxV60R:-NFhgKgpDC6fbY3xG_qv:bftp63g) ([raw file](https://github.com/pmem/pmem.github.io/blob/3c62c782ba9d893ebecaa005fac021ad8c556b69/content/pmdk/librpmem.md#L41)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

See older version of an example? Or is it some link missing here?
</blockquote></details>

I re-phrased it; the original wording is misleading because older versions are accessible within the link :wink: 

FYI, see "versions" table within a man page https://pmem.io/pmdk/librpmem/


<!-- Sent from Reviewable.io -->

2022-10-31 11:04 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/312)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau, @PatKamin, and @wlemkows)

___
*[`content/pmdk/librpmem.md` line 16 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/312#-NFhVsop4IAw0F8ClWCr:-NFhhJQp-eYyQkdsuC3G:bx8b5k9) ([raw file](https://github.com/pmem/pmem.github.io/blob/3c62c782ba9d893ebecaa005fac021ad8c556b69/content/pmdk/librpmem.md#L16)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: `the librpma library` or `by librpma`
</blockquote></details>

This is the original wording, it is consistent with other libraries, so I didn't change it here


<!-- Sent from Reviewable.io -->

2022-10-31 11:19 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/312)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin and @wlemkows)

___
*[`content/pmdk/librpmem.md` line 16 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/312#-NFhVsop4IAw0F8ClWCr:-NFhk_v45L9_YMx32B7W:b-fxykoy) ([raw file](https://github.com/pmem/pmem.github.io/blob/3c62c782ba9d893ebecaa005fac021ad8c556b69/content/pmdk/librpmem.md#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

This is the original wording, it is consistent with other libraries, so I didn't change it here
</blockquote></details>

"original" with what? ;-) 

Original wording of librpma is "`the librpma library`" or "`librpma`" :-)


<!-- Sent from Reviewable.io -->

2022-10-31 11:56 UTC, wlemkows commented on content/pmdk/librpmem.md
> +See the rpmemd man page documentation and examples
Also deprecated.

2022-10-31 12:45 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/312)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ldorau, @PatKamin, and @wlemkows)

___
*[`content/pmdk/librpmem.md` line 16 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/312#-NFhVsop4IAw0F8ClWCr:-NFi2NUWBN-atkOUuLrr:b-706fik) ([raw file](https://github.com/pmem/pmem.github.io/blob/3c62c782ba9d893ebecaa005fac021ad8c556b69/content/pmdk/librpmem.md#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

"original" with what? ;-) 

Original wording of librpma is "`the librpma library`" or "`librpma`" :-)

</blockquote></details>

hah, sorry, I got confused, too many "rpma" and "rpmem" stuff :smile:  I thought we were talking about the header

I fixed this line and the actual original content :wink: (`libxxx library` seems not cool to me :wink: I know there are other places with such wording, but I'm not touching it right now )
___
*[`content/pmdk/librpmem.md` line 40 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/312#-NFTy6MfMt0ACR9HooJh-r3-40:-NFi3jxc6oZGBmHODTan:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/a62a6140dbecf5071402ba4b804f31307760e1c2/content/pmdk/librpmem.md#L40)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

Also deprecated.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-31 12:46 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/312)* status: all files reviewed, 2 unresolved discussions (waiting on @PatKamin and @wlemkows)



<!-- Sent from Reviewable.io -->

2022-11-02 07:03 UTC, PatKamin reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/312#-:-NFr8gQK0ynmvlu4DSdX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @wlemkows)



<!-- Sent from Reviewable.io -->

2022-11-02 09:06 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/312)* status: all files reviewed, 1 unresolved discussion (waiting on @wlemkows)



<!-- Sent from Reviewable.io -->

2022-11-03 07:20 UTC, merged