Add information about the discontinuation of the project
pmem/pmem.github.io pull request #330
Opened 2023-02-10 11:12 UTC by szadam

Preview: https://szadam.github.io/pmemstream/

2023-02-13 07:14 UTC, wlemkows commented
Please create separate PR for each repository. It will be easier to merge changes when I start archiving.

2023-02-14 14:10 UTC, lukaszstolarczuk requested changes
I think it's acceptable to apply all updates at once :wink: this way we could have all changes pushed at the same time

> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330#-:-NOFFPYS3ACrV4-QPimh:b3ylfik)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @szadam and @wlemkows)

___
*[`data/en/miniasync.yml` line 8 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NOFF5u--iYB6eXSVbj5:-NOFF5u--iYB6eXSVbj6:b-h546tx) ([raw file](https://github.com/pmem/pmem.github.io/blob/7a982ccb266a9a41b8fe8e893fc23cb1847f521b/data/en/miniasync.yml#L8)):*
> ```YAML
>   content: "The <strong>Mini Library for Asynchronous Programming in C</strong> is a C low-level concurrency library for asynchronous functions.<br />
>   This is still an experimental, pre-release software.<br />
>   Up-to-date information and the most recent changes can be found on <a href=\"https://github.com/pmem/miniasync\">our GitHub page</a>."
> ```

pls apply similar update to this section, like for pmemstream
___
*[`data/en/miniasync.yml` line 19 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NOFEJkPB-cU0LFPmr7X:-NOFEJkPB-cU0LFPmr7Y:b-lurp1a) ([raw file](https://github.com/pmem/pmem.github.io/blob/7a982ccb266a9a41b8fe8e893fc23cb1847f521b/data/en/miniasync.yml#L19)):*
> ```YAML
>       list_items:
>         list_item1:
>           content: "(available soon)"
> ```

BTW, this could be updated - we rather don't deliver these - we can point to a directory with manpages on GitHub
___
*[`data/en/miniasync.yml` line 27 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NOFEUXrAdfakCE9TyGA:-NOFEUXrAdfakCE9TyGB:b-c8a0hu) ([raw file](https://github.com/pmem/pmem.github.io/blob/7a982ccb266a9a41b8fe8e893fc23cb1847f521b/data/en/miniasync.yml#L27)):*
> ```YAML
>   lists:
>     branch_list1: 
>       content: "<p>The **pmemstream** project will no longer be maintained by Intel.</p>"
> ```

`**` syntax will not work, pls make it use `<b>` syntax
___
*[`data/en/miniasync.yml` line 27 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NOFFkQ13G5l04nHNJjX:-NOFFkQ13G5l04nHNJjY:bbo6pp1) ([raw file](https://github.com/pmem/pmem.github.io/blob/7a982ccb266a9a41b8fe8e893fc23cb1847f521b/data/en/miniasync.yml#L27)):*
> ```YAML
>   lists:
>     branch_list1: 
>       content: "<p>The **pmemstream** project will no longer be maintained by Intel.</p>"
> ```

pmemstream?
___
*[`data/en/miniasync.yml` line 38 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NOFEkBN8_GFCabJNy4F:-NOFEkBN8_GFCabJNy4G:b-3o75lw) ([raw file](https://github.com/pmem/pmem.github.io/blob/7a982ccb266a9a41b8fe8e893fc23cb1847f521b/data/en/miniasync.yml#L38)):*
> ```YAML
>                     maintain patches for the open source software community, please create your own fork of this project."
>         list_item3:
>           content: "You will find more information <a href=\"https://pmem.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/\">here</a>."
> ```

on pmem.io you can use short links (you just link to another section on the same page) - `a href=\"/blog/2022/11/update-on-p...`
___
*[`themes/pmem-hugo/layouts/miniasync/list.html` line 38 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NOFFFne1peAInutMEfJ:-NOFFFne1peAInutMEfK:bbo6pp1) ([raw file](https://github.com/pmem/pmem.github.io/blob/7a982ccb266a9a41b8fe8e893fc23cb1847f521b/themes/pmem-hugo/layouts/miniasync/list.html#L38)):*
> ```HTML
> 
>             <!-- Discontinuation of the project -->
>             {{ $data := index site.Data site.Language.Lang }} {{ if $data.pmemstream.Discontinuation.enable }} {{ with $data.pmemstream.Discontinuation }}
> ```

pmemstream?


<!-- Sent from Reviewable.io -->

2023-02-23 11:26 UTC, szadam commented
I think that I will leave it as it is. If necessary, it will be easy to create a new PR for some repositories from an already created commit.





<!-- Sent from Reviewable.io -->

2023-02-23 13:15 UTC, szadam reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk and @wlemkows)

___
*[`data/en/miniasync.yml` line 8 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NOFF5u--iYB6eXSVbj5:-NOyPFbDAU-Ylq_suH8K:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/7a982ccb266a9a41b8fe8e893fc23cb1847f521b/data/en/miniasync.yml#L8)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls apply similar update to this section, like for pmemstream
</blockquote></details>

Done.
___
*[`data/en/miniasync.yml` line 19 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NOFEJkPB-cU0LFPmr7X:-NOyPGb550kqBVZ4Rqaz:b5wcv51) ([raw file](https://github.com/pmem/pmem.github.io/blob/7a982ccb266a9a41b8fe8e893fc23cb1847f521b/data/en/miniasync.yml#L19)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

BTW, this could be updated - we rather don't deliver these - we can point to a directory with manpages on GitHub
</blockquote></details>

Maybe sth like that?
___
*[`data/en/miniasync.yml` line 27 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NOFEUXrAdfakCE9TyGA:-NOyPLBbD7yBU_q3lixb:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/7a982ccb266a9a41b8fe8e893fc23cb1847f521b/data/en/miniasync.yml#L27)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`**` syntax will not work, pls make it use `<b>` syntax
</blockquote></details>

Done.
___
*[`data/en/miniasync.yml` line 27 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NOFFkQ13G5l04nHNJjX:-NOyPMUdCGzxHfxvoHii:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/7a982ccb266a9a41b8fe8e893fc23cb1847f521b/data/en/miniasync.yml#L27)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pmemstream?
</blockquote></details>

Done.
___
*[`data/en/miniasync.yml` line 38 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NOFEkBN8_GFCabJNy4F:-NOyPOJr6kWo7jsr6egi:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/7a982ccb266a9a41b8fe8e893fc23cb1847f521b/data/en/miniasync.yml#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

on pmem.io you can use short links (you just link to another section on the same page) - `a href=\"/blog/2022/11/update-on-p...`
</blockquote></details>

Done.
___
*[`themes/pmem-hugo/layouts/miniasync/list.html` line 38 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NOFFFne1peAInutMEfJ:-NOyPQ_k6nkKKjAj_jm4:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/7a982ccb266a9a41b8fe8e893fc23cb1847f521b/themes/pmem-hugo/layouts/miniasync/list.html#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pmemstream?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-28 11:11 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 4 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 6 unresolved discussions (waiting on @szadam and @wlemkows)

___
*[`data/en/miniasync.yml` line 8 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NOFF5u--iYB6eXSVbj5:-NPMLeLlEDcLaBqPoZEM:by76n6n) ([raw file](https://github.com/pmem/pmem.github.io/blob/7a982ccb266a9a41b8fe8e893fc23cb1847f521b/data/en/miniasync.yml#L8)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This "up-to-date" may be misleading :wink:  - pls update as in other repos with "More"
___
*[`data/en/miniasync.yml` line 19 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NOFEJkPB-cU0LFPmr7X:-NPML_u20ZZKOEaJGGvc:b-8fx2u7) ([raw file](https://github.com/pmem/pmem.github.io/blob/7a982ccb266a9a41b8fe8e893fc23cb1847f521b/data/en/miniasync.yml#L19)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Maybe sth like that?
</blockquote></details>

:+1: 
___
*[`data/en/miniasync.yml` line 13 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPMLAMRCZ84XA2XkMwK:-NPMLAMRCZ84XA2XkMwL:bbl8nlc) ([raw file](https://github.com/pmem/pmem.github.io/blob/235aca9c2ed8122d0b0447405b60bc4f1222f498/data/en/miniasync.yml#L13)):*
> ```YAML
> c_api:
>   enable: true
>   content: "<p>C API of miniasync is documented in the form of manpages.</p>
> ```

You've changed the syntax from `lists:` to just `content:` - now, you have to include this change in miniasync/lists.html file

you can see on the preview, this section is gone: https://szadam.github.io/miniasync/
___
*[`data/en/pmdk.yml` line 16 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPMJ4Zs2dfSGJ8ptd1v:-NPMJ4Zs2dfSGJ8ptd1w:b-3jy1qt) ([raw file](https://github.com/pmem/pmem.github.io/blob/235aca9c2ed8122d0b0447405b60bc4f1222f498/data/en/pmdk.yml#L16)):*
> ```YAML
>   lists:
>     branch_list1: 
>       content: "<p>The <strong>Libvmem</strong>, <strong>Libpmemobj-cpp</strong>, <strong>Libpmemkv</strong>, <strong>pmdk-convert</strong> and <strong>vmemcache</strong> libraries will no longer be maintained by Intel.</p>"
> ```

missing at least rpmem and set
___
*[`data/en/pmdk.yml` line 16 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPMJHOC4Z0aSxTDXUkL:-NPMJHOC4Z0aSxTDXUkM:b-kogr6l) ([raw file](https://github.com/pmem/pmem.github.io/blob/235aca9c2ed8122d0b0447405b60bc4f1222f498/data/en/pmdk.yml#L16)):*
> ```YAML
>   lists:
>     branch_list1: 
>       content: "<p>The <strong>Libvmem</strong>, <strong>Libpmemobj-cpp</strong>, <strong>Libpmemkv</strong>, <strong>pmdk-convert</strong> and <strong>vmemcache</strong> libraries will no longer be maintained by Intel.</p>"
> ```

pls use lowercase names of the libs; like in the libraries' list below
___
*[`data/en/pmdk.yml` line 54 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPMJ-jI8uS1AcAk0W8q:-NPMJ-jI8uS1AcAk0W8r:b6j7ikj) ([raw file](https://github.com/pmem/pmem.github.io/blob/235aca9c2ed8122d0b0447405b60bc4f1222f498/data/en/pmdk.yml#L54)):*
> ```YAML
>                 <p>See the <a href=\"./libpmem2\">libpmem2 page</a> for documentation and examples.</p>"
>     library_item6:
>       title: 'libpmemset'
> ```

we should update this entry as well
___
*[`themes/pmem-hugo/layouts/pmemstream/list.html` line 38 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPMhk0k8Ja8pn_-AN1H:-NPMhk0lExTxfXcz-tTX:b-ac5peh) ([raw file](https://github.com/pmem/pmem.github.io/blob/235aca9c2ed8122d0b0447405b60bc4f1222f498/themes/pmem-hugo/layouts/pmemstream/list.html#L38)):*
> ```HTML
>             <!-- end c api -->
> 
>             <!-- Discontinuation of the project -->
> ```

Actually this "discontinuation message" should be above the "Documentation" section, please move it above + I believe you'd have to add a title for `c_api` section (as I stated above, it could be named "Documentation")

pls apply also for miniasync


<!-- Sent from Reviewable.io -->

2023-02-28 14:33 UTC, szadam reviewed
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk and @wlemkows)

___
*[`data/en/miniasync.yml` line 8 at r1](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NOFF5u--iYB6eXSVbj5:-NPNRFoC6Ff4QnYR0NhQ:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/7a982ccb266a9a41b8fe8e893fc23cb1847f521b/data/en/miniasync.yml#L8)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

This "up-to-date" may be misleading :wink:  - pls update as in other repos with "More"
</blockquote></details>

Done.
___
*[`data/en/miniasync.yml` line 13 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPMLAMRCZ84XA2XkMwK:-NPNRHrM5NuUNXZ4W_px:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/235aca9c2ed8122d0b0447405b60bc4f1222f498/data/en/miniasync.yml#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

You've changed the syntax from `lists:` to just `content:` - now, you have to include this change in miniasync/lists.html file

you can see on the preview, this section is gone: https://szadam.github.io/miniasync/
</blockquote></details>

Done.
___
*[`data/en/pmdk.yml` line 16 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPMJ4Zs2dfSGJ8ptd1v:-NPNRJFA49-90-QWcVo5:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/235aca9c2ed8122d0b0447405b60bc4f1222f498/data/en/pmdk.yml#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

missing at least rpmem and set
</blockquote></details>

Done.
___
*[`data/en/pmdk.yml` line 16 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPMJHOC4Z0aSxTDXUkL:-NPNRKECBZEbFFzGdF8T:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/235aca9c2ed8122d0b0447405b60bc4f1222f498/data/en/pmdk.yml#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls use lowercase names of the libs; like in the libraries' list below
</blockquote></details>

Done.
___
*[`data/en/pmdk.yml` line 54 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPMJ-jI8uS1AcAk0W8q:-NPNRLE71IW9bFpwm_ap:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/235aca9c2ed8122d0b0447405b60bc4f1222f498/data/en/pmdk.yml#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we should update this entry as well
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-28 14:56 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 5 unresolved discussions (waiting on @szadam and @wlemkows)

___
*[`data/en/pmdk.yml` line 54 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPMJ-jI8uS1AcAk0W8q:-NPNUO4t2YxoOd-tNBbE:b-az7ynf) ([raw file](https://github.com/pmem/pmem.github.io/blob/235aca9c2ed8122d0b0447405b60bc4f1222f498/data/en/pmdk.yml#L54)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

hmm.. I mean, we've deleted set and rpmem from the repository, perhaps we should mention that it's available only in release1.12.1 and before...?

@wlemkows, can you please share your input on this one
___
*[`themes/pmem-hugo/layouts/miniasync/list.html` line 41 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPNVP-4C_k2gEE8fl1m:-NPNVP-4C_k2gEE8fl1n:b8xh3ic) ([raw file](https://github.com/pmem/pmem.github.io/blob/c00ddd4adc8c99003fb2c96125e8eeece98316fe/themes/pmem-hugo/layouts/miniasync/list.html#L41)):*
> ```HTML
>             {{ end }}  
>             {{ end }} {{ end }}
>             <!-- Discontinuation of the project -->
> ```

end ...
___
*[`themes/pmem-hugo/layouts/pmdk/list.html` line 36 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPNWDwS1bGOWhq23QW2:-NPNWDwS1bGOWhq23QW3:b-p4wrdk) ([raw file](https://github.com/pmem/pmem.github.io/blob/c00ddd4adc8c99003fb2c96125e8eeece98316fe/themes/pmem-hugo/layouts/pmdk/list.html#L36)):*
> ```HTML
>         </ul>
>       </div>
>     </div>
> ```

I think you've closed one <div> too little

Right now, we have too much empty space around this section, I think the missing "div" may be the problem, but please check
___
*[`themes/pmem-hugo/layouts/pmdk/list.html` line 39 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPNWGYD4jEsWjKV7xGx:-NPNWGYD4jEsWjKV7xGy:b8xh3ic) ([raw file](https://github.com/pmem/pmem.github.io/blob/c00ddd4adc8c99003fb2c96125e8eeece98316fe/themes/pmem-hugo/layouts/pmdk/list.html#L39)):*
> ```HTML
> {{ end }}  
> {{ end }} {{ end }}
> <!-- Discontinuation of the project -->
> ```

end ...
___
*[`themes/pmem-hugo/layouts/pmemstream/list.html` line 38 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPMhk0k8Ja8pn_-AN1H:-NPNWYQz8VFDqZnvc7t9:bb7dx2z) ([raw file](https://github.com/pmem/pmem.github.io/blob/235aca9c2ed8122d0b0447405b60bc4f1222f498/themes/pmem-hugo/layouts/pmemstream/list.html#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Actually this "discontinuation message" should be above the "Documentation" section, please move it above + I believe you'd have to add a title for `c_api` section (as I stated above, it could be named "Documentation")

pls apply also for miniasync
</blockquote></details>

bump


<!-- Sent from Reviewable.io -->

2023-02-28 17:23 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 2 unresolved discussions (waiting on @szadam and @wlemkows)

___
*[`themes/pmem-hugo/layouts/pmdk/list.html` line 36 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPNWDwS1bGOWhq23QW2:-NPO-XyG4inEeDJTPjro:b4kciq4) ([raw file](https://github.com/pmem/pmem.github.io/blob/c00ddd4adc8c99003fb2c96125e8eeece98316fe/themes/pmem-hugo/layouts/pmdk/list.html#L36)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

maybe sth like that?
</blockquote></details>

I don't want to be very picky and meticulous, but there are some extra spaces and lines in there. If you can fix that, it'd be great, but if that's not an easy task, then let it go.

This is what I'm talking about:
![image.png](https://files.reviewableusercontent.io/images/reviewable/29728779/4oQpw2JkbyhEiapJ2XPBTxb3/image.png)


<!-- Sent from Reviewable.io -->

2023-03-02 16:21 UTC, szadam commented
*[`themes/pmem-hugo/layouts/pmdk/list.html` line 36 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPNWDwS1bGOWhq23QW2:-NPY71ljBEGk0w_85Wy6:b-9pakim) ([raw file](https://github.com/pmem/pmem.github.io/blob/c00ddd4adc8c99003fb2c96125e8eeece98316fe/themes/pmem-hugo/layouts/pmdk/list.html#L36)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I don't want to be very picky and meticulous, but there are some extra spaces and lines in there. If you can fix that, it'd be great, but if that's not an easy task, then let it go.

This is what I'm talking about:
![image.png](https://files.reviewableusercontent.io/images/reviewable/29728779/4oQpw2JkbyhEiapJ2XPBTxb3/image.png)

</blockquote></details>

Okey, so maybe like that?


<!-- Sent from Reviewable.io -->

2023-03-02 16:25 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 1 unresolved discussion (waiting on @wlemkows)

___
*[`themes/pmem-hugo/layouts/pmdk/list.html` line 36 at r3](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPNWDwS1bGOWhq23QW2:-NPY82Dp56BQG5OgZMif:byzbep0) ([raw file](https://github.com/pmem/pmem.github.io/blob/c00ddd4adc8c99003fb2c96125e8eeece98316fe/themes/pmem-hugo/layouts/pmdk/list.html#L36)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Okey, so maybe like that?
</blockquote></details>

perfect! thx!


<!-- Sent from Reviewable.io -->

2023-03-02 16:52 UTC, szadam reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 1 unresolved discussion (waiting on @wlemkows)



<!-- Sent from Reviewable.io -->

2023-03-03 09:18 UTC, wlemkows reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[`data/en/pmdk.yml` line 54 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPMJ-jI8uS1AcAk0W8q:-NPaknwh6ygBUNos2vUh:bao55ej) ([raw file](https://github.com/pmem/pmem.github.io/blob/235aca9c2ed8122d0b0447405b60bc4f1222f498/data/en/pmdk.yml#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm.. I mean, we've deleted set and rpmem from the repository, perhaps we should mention that it's available only in release1.12.1 and before...?

@wlemkows, can you please share your input on this one
</blockquote></details>

Do you have a preview of this piece? I'm not aware of what place on pmem.io we are talking about.


<!-- Sent from Reviewable.io -->

2023-03-03 09:55 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 2 unresolved discussions (waiting on @szadam and @wlemkows)

___
*[`data/en/pmdk.yml` line 54 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPMJ-jI8uS1AcAk0W8q:-NPatC2D6NWGTVjiL7BM:b-flvemk) ([raw file](https://github.com/pmem/pmem.github.io/blob/235aca9c2ed8122d0b0447405b60bc4f1222f498/data/en/pmdk.yml#L54)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

Do you have a preview of this piece? I'm not aware of what place on pmem.io we are talking about.
</blockquote></details>

we're talking about the section of /pmdk microsite and list of all libraries; pmemset (and rpmem) in this particular case

https://szadam.github.io/pmdk/
___
*[`data/en/pmdk.yml` line 16 at r7](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPat1th0PXXU9p_T-9w:-NPat1th0PXXU9p_T-9x:b6wlvmh) ([raw file](https://github.com/pmem/pmem.github.io/blob/daa83eff751cc13fffefde993b2fe55a922aae97/data/en/pmdk.yml#L16)):*
> ```YAML
>   lists:
>     branch_list1: 
>       content: "<p>The <strong>libpmemobj</strong>, <strong>libpmemset</strong>, <strong>libvmem</strong>, <strong>librpmem</strong>, <strong>libvmemcache</strong>, <strong>pmdk-convert</strong> and <strong>pmemkv</strong> libraries will no longer be maintained by Intel.</p>"
> ```

yy, what happened here? :smile: we're not dropping libpmemobj :wink: 


<!-- Sent from Reviewable.io -->

2023-03-03 11:13 UTC, szadam reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`data/en/pmdk.yml` line 54 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPMJ-jI8uS1AcAk0W8q:-NPb7-ic2qqiMjoN41DU:b2msbr9) ([raw file](https://github.com/pmem/pmem.github.io/blob/235aca9c2ed8122d0b0447405b60bc4f1222f498/data/en/pmdk.yml#L54)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

Oh I see. So I agree with @lukaszstolarczuk . We should mention it.
</blockquote></details>

maybe sth like that?
___
*[`data/en/pmdk.yml` line 16 at r7](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPat1th0PXXU9p_T-9w:-NPbA6ve85wp5uq9maPi:b-dlnpt) ([raw file](https://github.com/pmem/pmem.github.io/blob/daa83eff751cc13fffefde993b2fe55a922aae97/data/en/pmdk.yml#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

yy, what happened here? :smile: we're not dropping libpmemobj :wink: 
</blockquote></details>

my mistake


<!-- Sent from Reviewable.io -->

2023-03-03 12:37 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 3 unresolved discussions (waiting on @szadam)

___
*[`data/en/pmdk.yml` line 54 at r2](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPMJ-jI8uS1AcAk0W8q:-NPbT3hE4_gWnAuAElIW:b-c4sasu) ([raw file](https://github.com/pmem/pmem.github.io/blob/235aca9c2ed8122d0b0447405b60bc4f1222f498/data/en/pmdk.yml#L54)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

maybe sth like that?
</blockquote></details>

it works for me :)
___
*[`data/en/pmdk.yml` line 56 at r8](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPbT7T89PphB-3x4qqH:-NPbT7T89PphB-3x4qqI:b-dun5a5) ([raw file](https://github.com/pmem/pmem.github.io/blob/eb3ca21e2d901b8d6322a636a11ce677071c89c6/data/en/pmdk.yml#L56)):*
> ```YAML
>       title: 'libpmemset'
>       content: "<p><strong>libpmemset</strong> aims to provide support for persistent file I/O operations, runtime mapping concatenation and multi-part support across poolsets. It relies on synchronous event streams for pool modifications.</p>
>                 <blockquote><p><strong>Note:</strong> <strong>libpmemset</strong> is available only in release 1.12.1 and before, so it is no longer available on the master branch. </p></blockquote>
> ```

`the release`
___
*[`data/en/pmdk.yml` line 56 at r8](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPbT8y4EQl3zOJF4GoP:-NPbT8y4EQl3zOJF4GoQ:b-dgvpma) ([raw file](https://github.com/pmem/pmem.github.io/blob/eb3ca21e2d901b8d6322a636a11ce677071c89c6/data/en/pmdk.yml#L56)):*
> ```YAML
>       title: 'libpmemset'
>       content: "<p><strong>libpmemset</strong> aims to provide support for persistent file I/O operations, runtime mapping concatenation and multi-part support across poolsets. It relies on synchronous event streams for pool modifications.</p>
>                 <blockquote><p><strong>Note:</strong> <strong>libpmemset</strong> is available only in release 1.12.1 and before, so it is no longer available on the master branch. </p></blockquote>
> ```

`before. It is no `
___
*[`data/en/pmdk.yml` line 84 at r8](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPbTNCA1X5H5tQVLu03:-NPbTNCA1X5H5tQVLu04:b-5yhyne) ([raw file](https://github.com/pmem/pmem.github.io/blob/eb3ca21e2d901b8d6322a636a11ce677071c89c6/data/en/pmdk.yml#L84)):*
> ```YAML
>       content: "<p><strong>librpmem</strong> provides low-level support for remote access to persistent memory utilizing RDMA-capable RNICs.</p>
>                 <p>See the <a href=\"./librpmem\">librpmem page</a> for documentation and examples.</p>
>                 <blockquote><p><strong>Note:</strong> <strong>librpmem</strong> is available only in release 1.12.1 and before, so it is no longer available on the master branch. </p></blockquote>
> ```

same issues, as above, here


<!-- Sent from Reviewable.io -->

2023-03-06 10:09 UTC, szadam reviewed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`data/en/pmdk.yml` line 56 at r8](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPbT7T89PphB-3x4qqH:-NPqOUaED7c0CeyfhICx:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/eb3ca21e2d901b8d6322a636a11ce677071c89c6/data/en/pmdk.yml#L56)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`the release`
</blockquote></details>

Done.
___
*[`data/en/pmdk.yml` line 56 at r8](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPbT8y4EQl3zOJF4GoP:-NPqOVFd3Ce3qYv3y-3C:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/eb3ca21e2d901b8d6322a636a11ce677071c89c6/data/en/pmdk.yml#L56)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`before. It is no `
</blockquote></details>

Done.
___
*[`data/en/pmdk.yml` line 84 at r8](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPbTNCA1X5H5tQVLu03:-NPqOWIa8UAFOzVP7rUH:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/eb3ca21e2d901b8d6322a636a11ce677071c89c6/data/en/pmdk.yml#L84)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

same issues, as above, here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-06 11:05 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szadam)



<!-- Sent from Reviewable.io -->

2023-03-06 14:41 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @szadam and @wlemkows)

___
*[`data/en/pmemkv.yml` line 14 at r10](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPrM2POEUazNOvw6_yf:-NPrM2POEUazNOvw6_yg:brahnbb) ([raw file](https://github.com/pmem/pmem.github.io/blob/b9dfbff753fe807c942ea347963078bd77ee9b34/data/en/pmemkv.yml#L14)):*
> ```YAML
>   lists:
>     branch_list1: 
>       content: "<p>The <strong>pmemkv</strong> libraries will no longer be maintained by Intel.</p>"
> ```

pls make it more precise: `pmemkv library and its language bindings`
___
*[`themes/pmem-hugo/layouts/pmemkv/list.html` line 17 at r10](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPrMOEG8j6zOya2pZ3L:-NPrMOEG8j6zOya2pZ3M:b-ohs0or) ([raw file](https://github.com/pmem/pmem.github.io/blob/b9dfbff753fe807c942ea347963078bd77ee9b34/themes/pmem-hugo/layouts/pmemkv/list.html#L17)):*
> ```HTML
> 
> <!-- Discontinuation of the project -->
> {{ $data := index site.Data site.Language.Lang }} {{ if $data.pmdk.Discontinuation.enable }} {{ with $data.pmdk.Discontinuation }}
> ```

hehe, `pmdk` nope :stuck_out_tongue_winking_eye: 


<!-- Sent from Reviewable.io -->

2023-03-06 17:56 UTC, szadam reviewed
> Reviewed 10 of 10 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`data/en/pmemkv.yml` line 14 at r10](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPrM2POEUazNOvw6_yf:-NPs3D_E59EwvtqCxtaq:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b9dfbff753fe807c942ea347963078bd77ee9b34/data/en/pmemkv.yml#L14)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls make it more precise: `pmemkv library and its language bindings`
</blockquote></details>

Done.
___
*[`themes/pmem-hugo/layouts/pmemkv/list.html` line 17 at r10](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPrMOEG8j6zOya2pZ3L:-NPs3FoHEKJibSyEUAnd:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/b9dfbff753fe807c942ea347963078bd77ee9b34/themes/pmem-hugo/layouts/pmemkv/list.html#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hehe, `pmdk` nope :stuck_out_tongue_winking_eye: 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-07 13:43 UTC, lukaszstolarczuk requested changes
> Reviewed 9 of 10 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 17 unresolved discussions (waiting on @szadam)

___
*[`-- commits` line 25 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwFOHcDrBHZTtWtPB7):*
`of the pmem repositories` -> `in the repoindex`
___
*[`content/libpmemobj-cpp/_index.md` line 15 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwIjJKDqeGUWJqZGFT:-NPwIjJKDqeGUWJqZGFU:bps2ejx) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/libpmemobj-cpp/_index.md#L15)):*
> ```Markdown
> ---
> 
> ### ⚠️ Discontinuation of the project
> ```

now, some repos has this :warning:  icon and some do not - please pick one version :wink:  ( I think we're good without this icon )
___
*[`content/libpmemobj-cpp/_index.md` line 22 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwDel9CYRdawXWzl_Y:-NPwDel9CYRdawXWzl_Z:b44lfg6) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/libpmemobj-cpp/_index.md#L22)):*
> ```Markdown
> - If you have an ongoing need to use this project, are interested in independently developing it, or would like to
> maintain patches for the open source software community, please create your own fork of this project.
> - You will find more information [here](https://pmem.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/).
> ```

pls update the link (in all places) not to use "https://pmem.io"
___
*[`content/pmdk/libpmemset.md` line 31 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwAwBP4J-UBpRkCM11:-NPwAwBP4J-UBpRkCM12:b-8l8k58) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/pmdk/libpmemset.md#L31)):*
> ```Markdown
> Man pages that contain a list of the **Linux** interfaces provided:
> 
> * Man page for <a href="../manpages/linux/master/libpmemset/libpmemset.7.html">libpmemset current master</a>
> ```

as we discussed - master branch does not contain any information about set, two issues here:

1. pls mention which releases contain this library
2. as a workaround for the missing docs, we just discussed, it could be easiest to just link to a documentation on the selected branch in the repository, e.g., here: https://github.com/pmem/pmdk/tree/stable-1.12/doc/libpmemset
___
*[`content/pmdk/libpmemset.md` line 33 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwFvtO4i8GIYyG_6CF:-NPwFvtO4i8GIYyG_6CG:bemyxwq) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/pmdk/libpmemset.md#L33)):*
> ```Markdown
> * Man page for <a href="../manpages/linux/master/libpmemset/libpmemset.7.html">libpmemset current master</a>
> 
> Man pages that contain a list of the **Windows** interfaces provided:
> ```

@wlemkows, should we already drop Windows info/links...?

Since we don't have a separate directory for Windows manpages, I think we might do that already, but perhaps only for documentation links. Other info, like Building repositories on Windows - it may stay, I think, for now...?


If we drop, then, @szadam, pls apply to all repos
___
*[`content/pmdk/librpmem.md` line 25 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwCuBS1cEuL8hurkVh:-NPwCuBS1cEuL8hurkVi:brkyt7n) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/pmdk/librpmem.md#L25)):*
> ```Markdown
> ### The librpmem library
> 
> > **Note:** The alternative solution for accessing remote persistent memory is implemented by [librpma](/librpma).
> ```

btw, please add here an empty line between these two Notes
___
*[`content/pmdk/librpmem.md` line 27 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwD-nG2jea44J0oDZL:-NPwD-nG2jea44J0oDZM:b-sr9btv) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/pmdk/librpmem.md#L27)):*
> ```Markdown
> > **Note:** The alternative solution for accessing remote persistent memory is implemented by [librpma](/librpma).
> > **Note:** This is a **deprecated** API and should not be used in production environments.
> ```

pls add info here, as well - the last pmdk release, which contains this library
___
*[`content/pmdk/librpmem.md` line 42 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwD4l09EjexF-_ffnY:-NPwD4l09EjexF-_ffnZ:b-e6clcz) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/pmdk/librpmem.md#L42)):*
> ```Markdown
> 
> Man pages that contains a list of the **Linux** interfaces provided:
> * Man page for [librpmem in the latest stable release](../manpages/linux/v1.12/librpmem/librpmem.7.html)
> ```

pls also update with a link to docs in the repository  (I know this link works, but it doesn't link properly to other rpmem's manpages)
___
*[`content/pmdk/libvmem.md` line 35 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwDZrkDY1VcOwodTgV:-NPwDZrl0vKrKmzkvg16:bij2jes) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/pmdk/libvmem.md#L35)):*
> ```Markdown
> >**Note:**
> Since persistent memory support
> has been integrated into [libmemkind](https://github.com/memkind/memkind),
> ```

btw, pls fix the link to just `/memkind`
___
*[`content/pmdk/libvmem.md` line 42 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwFpiQA-puW-uDzsoo:-NPwFpiQA-puW-uDzsop:b-iqa0y2) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/pmdk/libvmem.md#L42)):*
> ```Markdown
> Man pages that contains a list of the **Linux** interfaces provided:
> 
> * Man page for <a href="../manpages/linux/master/libvmem/libvmem.7.html">libvmem current master</a>
> ```

I'd set link to: https://github.com/pmem/vmem/tree/master/doc
___
*[`content/pmdk/libvmem.md` line 51 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwDqJ8AcLSxh_gBn2B:-NPwDqJ92ibPZJvLgT2E:b-dyajvc) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/pmdk/libvmem.md#L51)):*
> ```Markdown
> ### libvmem Examples
> 
> #### More Detail Coming Soon
> ```

heh, pls drop this line
___
*[`content/vmemcache/_index.md` line 16 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwGxTn56HmV4Un4hd9:-NPwGxTn56HmV4Un4hdA:b-2cd3a5) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/vmemcache/_index.md#L16)):*
> ```Markdown
> 
> ### ⚠️ Discontinuation of the project
> The **VMemCache** project will no longer be maintained by Intel.
> ```

why the uppercase? pls make it just `libvmemcache`
___
*[`content/vmemcache/_index.md` line 36 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwH7Z5C_rkeAQEkUFW:-NPwH7Z5C_rkeAQEkUFX:bln3cv8) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/vmemcache/_index.md#L36)):*
> ```Markdown
> The cache is tuned to work optimally with relatively large value sizes. The smallest possible size is 256 bytes, but libvmemcache works best if the expected value sizes are above 1 kilobyte.
> 
> See the <a href="./vmemcache/manpages/master/vmemcache.3.html">libvmemcache man page</a> for current master documentation and examples
> ```

https://github.com/pmem/vmemcache/blob/master/doc/vmemcache.md (pls re-phrase in places like this, so it'd make sense after we change the link to GitHub repo page - for example here, we don't have any example in the linked md file)
___
*[`data/en/pmemkv.yml` line 14 at r10](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPrM2POEUazNOvw6_yf:-NPwI95T-iBgy8s9Gsa4:b-23y54i) ([raw file](https://github.com/pmem/pmem.github.io/blob/b9dfbff753fe807c942ea347963 [...]

2023-03-08 09:42 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 13 unresolved discussions (waiting on @szadam)

___
*[`data/en/repoindex.yml` line 151 at r12](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NQ-_eIO0mdRO1LsxcLQ:-NQ-_eIO0mdRO1LsxcLR:b-uvr4v6) ([raw file](https://github.com/pmem/pmem.github.io/blob/ce8f2cf6895baa3a75afd09399878ce79af9d9c6/data/en/repoindex.yml#L151)):*
> ```YAML
>                 cell3:
>                   content: "<a href=\"../pmdk-convert\">pmdk-convert</a>"
>             rowA4:
> ```

pls move valgrind and rpma to up in the table, just after the `pmdk` (it looks a little "sad" down there :wink: )


<!-- Sent from Reviewable.io -->

2023-03-08 09:54 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 13 unresolved discussions (waiting on @szadam)

___
*[`content/pmdk/libpmemset.md` line 33 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwFvtO4i8GIYyG_6CF:-NQ-chGLCfzthfbhXGyu:b7jhlpg) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/pmdk/libpmemset.md#L33)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

@wlemkows, should we already drop Windows info/links...?

Since we don't have a separate directory for Windows manpages, I think we might do that already, but perhaps only for documentation links. Other info, like Building repositories on Windows - it may stay, I think, for now...?


If we drop, then, @szadam, pls apply to all repos
</blockquote></details>

Actually, I discussed it with Weronika and we should leave Windows information here for now. Please just update the links to docs (to GitHub repo) and that's it.

We will update Windows info in a separate PR.


<!-- Sent from Reviewable.io -->

2023-03-08 17:07 UTC, szadam commented
*[`content/vmemcache/_index.md` line 16 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwGxTn56HmV4Un4hd9:-NQ1BCpWBjdBpu6C0cFg:b-muy1do) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/vmemcache/_index.md#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why the uppercase? pls make it just `libvmemcache`
</blockquote></details>


I took it from the header ;)


<!-- Sent from Reviewable.io -->

2023-03-08 17:30 UTC, szadam reviewed
> Reviewed 6 of 8 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: 14 of 16 files reviewed, 11 unresolved discussions (waiting on @lukaszstolarczuk and @wlemkows)

___
*[`content/libpmemobj-cpp/_index.md` line 15 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwIjJKDqeGUWJqZGFT:-NQ1G9339dHgoPkWZg7S:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/libpmemobj-cpp/_index.md#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

now, some repos has this :warning:  icon and some do not - please pick one version :wink:  ( I think we're good without this icon )
</blockquote></details>

Done.
___
*[`content/pmdk/libpmemset.md` line 31 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwAwBP4J-UBpRkCM11:-NQ1GBuW9ZLPOqJt1tGk:bdxmist) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/pmdk/libpmemset.md#L31)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

as we discussed - master branch does not contain any information about set, two issues here:

1. pls mention which releases contain this library
2. as a workaround for the missing docs, we just discussed, it could be easiest to just link to a documentation on the selected branch in the repository, e.g., here: https://github.com/pmem/pmdk/tree/stable-1.12/doc/libpmemset
</blockquote></details>

Sth like that?
___
*[`content/pmdk/libpmemset.md` line 33 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwFvtO4i8GIYyG_6CF:-NQ1GGpr-Y2pLtKtY7c9:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/pmdk/libpmemset.md#L33)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Actually, I discussed it with Weronika and we should leave Windows information here for now. Please just update the links to docs (to GitHub repo) and that's it.

We will update Windows info in a separate PR.
</blockquote></details>

Done.
___
*[`content/pmdk/librpmem.md` line 27 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwD-nG2jea44J0oDZL:-NQ1GKj82sSrWkFiSE0k:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/pmdk/librpmem.md#L27)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add info here, as well - the last pmdk release, which contains this library
</blockquote></details>

Done.
___
*[`content/pmdk/librpmem.md` line 42 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwD4l09EjexF-_ffnY:-NQ1GLmy7X227xr05ze-:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/pmdk/librpmem.md#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls also update with a link to docs in the repository  (I know this link works, but it doesn't link properly to other rpmem's manpages)
</blockquote></details>

Done.
___
*[`content/pmdk/libvmem.md` line 42 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwFpiQA-puW-uDzsoo:-NQ1GO-L0exKEnyqz_mD:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/pmdk/libvmem.md#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'd set link to: https://github.com/pmem/vmem/tree/master/doc
</blockquote></details>

Done.
___
*[`content/pmdk/libvmem.md` line 51 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwDqJ8AcLSxh_gBn2B:-NQ1GOtSEJhK9OZIBVwa:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/pmdk/libvmem.md#L51)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

heh, pls drop this line
</blockquote></details>

Done.
___
*[`content/vmemcache/_index.md` line 16 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwGxTn56HmV4Un4hd9:-NQ1GR4A-5YE4Jz89B5E:bb7f2mf) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/vmemcache/_index.md#L16)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

I took it from the header ;)
</blockquote></details>

done
___
*[`content/vmemcache/_index.md` line 36 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwH7Z5C_rkeAQEkUFW:-NQ1GSUq61zHSp5l7tMf:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/vmemcache/_index.md#L36)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

https://github.com/pmem/vmemcache/blob/master/doc/vmemcache.md (pls re-phrase in places like this, so it'd make sense after we change the link to GitHub repo page - for example here, we don't have any example in the linked md file)
</blockquote></details>

Done.
___
*[`data/en/repoindex.yml` line 151 at r12](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NQ-_eIO0mdRO1LsxcLQ:-NQ1GYOqAE7DUGsgWxYK:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/ce8f2cf6895baa3a75afd09399878ce79af9d9c6/data/en/repoindex.yml#L151)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls move valgrind and rpma to up in the table, just after the `pmdk` (it looks a little "sad" down there :wink: )
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-08 17:42 UTC, szadam reviewed
> Reviewed 1 of 1 files at r14, 5 of 5 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 11 unresolved discussions (waiting on @lukaszstolarczuk and @wlemkows)

___
*[`content/libpmemobj-cpp/_index.md` line 22 at r11](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NPwDel9CYRdawXWzl_Y:-NQ1JK1-AXYPBKJedb8c:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/0898d7b75491d6b0105243d2115a9f22ab39c8c4/content/libpmemobj-cpp/_index.md#L22)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls update the link (in all places) not to use "https://pmem.io"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-09 12:06 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 8 files at r13, 1 of 1 files at r14, 4 of 5 files at r15, 5 of 5 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 3 unresolved discussions (waiting on @szadam)

___
*[`content/pmdk/libpmemset.md` line 28 at r16](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NQ5CgYL3J2359ZIVSTf:-NQ5CgYM8Aj4SiUeO2ty:b-rmle86) ([raw file](https://github.com/pmem/pmem.github.io/blob/2e9971f819490f35cc3d6a0a1b48c398a1246b81/content/pmdk/libpmemset.md#L28)):*
> ```Markdown
> persistent application should have.
> 
> Releases that contain this library:
> ```

you can write something like:

```
This library is only available on two code branches:
* [stable-1.11](https://github.com/pmem/pmdk/tree/stable-1.11)
* [stable-1.12](https://github.com/pmem/pmdk/tree/stable-1.12)


It'd be the best choice to use the most recent release from these two branches - **1.12.1**.
```
___
*[`content/pmdk/librpmem.md` line 29 at r16](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NQ5DzED0rQYvSOUdpLR:-NQ5DzED0rQYvSOUdpLS:bxbtkgq) ([raw file](https://github.com/pmem/pmem.github.io/blob/2e9971f819490f35cc3d6a0a1b48c398a1246b81/content/pmdk/librpmem.md#L29)):*
> ```Markdown
> > **Note:** This is a **deprecated** API and should not be used in production environments.
> 
> The last PMDK release, which contains this library is [stable-1.12](https://github.com/pmem/pmdk/tree/stable-1.12).
> ```

pls write something similar to libpmemset, but here you don't have to mention all branches (there's a lot of them, I guess) - just the last branch and the most recent release.
___
*[`data/en/repoindex.yml` line 151 at r12](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NQ-_eIO0mdRO1LsxcLQ:-NQ4e6CNBg4gGtSmkFWP:bdi4cst) ([raw file](https://github.com/pmem/pmem.github.io/blob/ce8f2cf6895baa3a75afd09399878ce79af9d9c6/data/en/repoindex.yml#L151)):*
> and rpma

:wink: 


<!-- Sent from Reviewable.io -->

2023-03-10 17:21 UTC, szadam reviewed
> Reviewed 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`content/pmdk/libpmemset.md` line 28 at r16](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NQ5CgYL3J2359ZIVSTf:-NQBXRNuEGmChFQwX2U6:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/2e9971f819490f35cc3d6a0a1b48c398a1246b81/content/pmdk/libpmemset.md#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can write something like:

```
This library is only available on two code branches:
* [stable-1.11](https://github.com/pmem/pmdk/tree/stable-1.11)
* [stable-1.12](https://github.com/pmem/pmdk/tree/stable-1.12)


It'd be the best choice to use the most recent release from these two branches - **1.12.1**.
```
</blockquote></details>

Done.
___
*[`content/pmdk/librpmem.md` line 29 at r16](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NQ5DzED0rQYvSOUdpLR:-NQBXSQp90qaPjk5JHla:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/2e9971f819490f35cc3d6a0a1b48c398a1246b81/content/pmdk/librpmem.md#L29)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls write something similar to libpmemset, but here you don't have to mention all branches (there's a lot of them, I guess) - just the last branch and the most recent release.
</blockquote></details>

Done.
___
*[`data/en/repoindex.yml` line 151 at r12](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NQ-_eIO0mdRO1LsxcLQ:-NQBXWOp22yqaIp_k26s:b-o8wj9h) ([raw file](https://github.com/pmem/pmem.github.io/blob/ce8f2cf6895baa3a75afd09399878ce79af9d9c6/data/en/repoindex.yml#L151)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

> and rpma

:wink: 
</blockquote></details>

okay, my fault


<!-- Sent from Reviewable.io -->

2023-03-13 08:27 UTC, lukaszstolarczuk reviewed
:+1: 

> Reviewed 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330#-:-NQP45S80g9-USer64Fe:b-8fx2u7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szadam)



<!-- Sent from Reviewable.io -->

2023-03-14 11:42 UTC, lukaszstolarczuk requested changes
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 1 unresolved discussion (waiting on @szadam)

___
*[`content/pmemkv-java/_index.md` line 45 at r18](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NQUvV7s9datRUK9rmJw:-NQUvV7s9datRUK9rmJx:b2zb80u) ([raw file](https://github.com/pmem/pmem.github.io/blob/5df799401f83a3061b4aa5303980d537f7e7be2e/content/pmemkv-java/_index.md#L45)):*
> ```Markdown
> | Version branch | First release date | Last patch release | Maintenance status |
> | -------------- | ------------------ | ------------------ | ------------------ |
> | stable-1.2 | Jul 02, 2021 | N/A | Full |
> ```

pls update here all rows to EOL


<!-- Sent from Reviewable.io -->

2023-03-14 14:21 UTC, lukaszstolarczuk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330#-:-NQVUtQiAJidoel6rjBB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szadam)



<!-- Sent from Reviewable.io -->

2023-03-17 11:07 UTC, wlemkows commented on data/en/pmdk.yml
> +      content: "<p>The <strong>libpmemset</strong>, <strong>libvmem</strong>, <strong>librpmem</strong>, <strong>libvmemcache</strong>, <strong>pmdk-convert</strong>, <strong>libpmemobj-cpp</strong>
also libpmemblk, libpmemlog

2023-03-20 06:37 UTC, szadam reviewed
> Reviewed 4 of 4 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 1 unresolved discussion (waiting on @wlemkows)

___
*[`data/en/pmdk.yml` line 16 at r19](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NP1u5qSB_a9ChyFfAiX-r19-16:-NQxjFDw6m0CUdn16L0b:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/35a62bd9f07a8e1f1d302c3a4652be98c9695ae9/data/en/pmdk.yml#L16)):*
<details><summary><i>Previously, wlemkows (Weronika Lewandowska) wrote…</i></summary><blockquote>

also libpmemblk, libpmemlog
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-20 07:51 UTC, lukaszstolarczuk requested changes
> Reviewed 1 of 4 files at r20.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 4 unresolved discussions (waiting on @szadam and @wlemkows)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NQxz4rq-u1TxZdXC4t7:-NQxz4rq-u1TxZdXC4t8:bhhpn4f) (no related file):*
please re-base with the latest main

___
___
*[`content/pmdk/libpmemblk.md` line 46 at r20](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NQxzjZrCPCWFrvDaWzh:-NQxzjZrCPCWFrvDaWzi:b-7g80j1) ([raw file](https://github.com/pmem/pmem.github.io/blob/eac8a40a7b0c9210c602286540287426957beeab/content/pmdk/libpmemblk.md#L46)):*
> ```Markdown
> ### libpmemblk Examples
> 
> #### More Detail Coming Soon
> ```

pls drop this line
___
*[`content/pmdk/libpmemobj.md` line 15 at r20](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NQxznmU3T5QyWCq5wod:-NQxznmU3T5QyWCq5woe:bb7lgjf) ([raw file](https://github.com/pmem/pmem.github.io/blob/eac8a40a7b0c9210c602286540287426957beeab/content/pmdk/libpmemobj.md#L15)):*
> ```Markdown
> 
> ### Discontinuation of the project
> The **libpmemobj** project will no longer be maintained by Intel.
> ```

nope
___
*[`data/en/pmdk.yml` line 16 at r19](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NP1u5qSB_a9ChyFfAiX-r19-16:-NQxyi8r60lGjNMomNws:b-nw081d) ([raw file](https://github.com/pmem/pmem.github.io/blob/35a62bd9f07a8e1f1d302c3a4652be98c9695ae9/data/en/pmdk.yml#L16)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

heh, nope - no "libpmemobj"


<!-- Sent from Reviewable.io -->

2023-03-21 13:22 UTC, szadam reviewed
> Reviewed 4 of 4 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk and @wlemkows)

___
*[`content/pmdk/libpmemblk.md` line 46 at r20](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NQxzjZrCPCWFrvDaWzh:-NR3KGLm58dLEGbYu7la:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/eac8a40a7b0c9210c602286540287426957beeab/content/pmdk/libpmemblk.md#L46)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls drop this line
</blockquote></details>

Done.
___
*[`data/en/pmdk.yml` line 16 at r19](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NP1u5qSB_a9ChyFfAiX-r19-16:-NR3KMBy0nCxxzN9nj9v:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/35a62bd9f07a8e1f1d302c3a4652be98c9695ae9/data/en/pmdk.yml#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

heh, nope - no "libpmemobj"
</blockquote></details>

Done.
___
*[`content/pmdk/libpmemobj.md` line 15 at r20](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NQxznmU3T5QyWCq5wod:-NR3KOEY2WadosfxaJkU:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/eac8a40a7b0c9210c602286540287426957beeab/content/pmdk/libpmemobj.md#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

nope
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-21 13:49 UTC, lukaszstolarczuk reviewed
> Reviewed 4 of 4 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 3 unresolved discussions (waiting on @szadam and @wlemkows)

*[a discussion](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NQxz4rq-u1TxZdXC4t7:-NR3QVhOCXM-XoX8uWy1:bb7dx2z) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please re-base with the latest main
</blockquote></details>

bump

___
___
*[`content/pmdk/libpmemlog.md` line 43 at r21](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NR3Njir3xLyvg4709A1:-NR3Njir3xLyvg4709A2:b-7g80j1) ([raw file](https://github.com/pmem/pmem.github.io/blob/5f9ed85d0b91db15213a11769ffd6322bfc7e46c/content/pmdk/libpmemlog.md#L43)):*
> ```Markdown
> ### libpmemlog Examples
> 
> #### More Detail Coming Soon
> ```

pls drop this line


<!-- Sent from Reviewable.io -->

2023-03-21 15:24 UTC, szadam reviewed
> Reviewed 5 of 5 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk and @wlemkows)

___
*[`content/pmdk/libpmemlog.md` line 43 at r21](https://reviewable.io/reviews/pmem/pmem.github.io/330#-NR3Njir3xLyvg4709A1:-NR3lC7l0dvodeROZKer:b-896fix) ([raw file](https://github.com/pmem/pmem.github.io/blob/5f9ed85d0b91db15213a11769ffd6322bfc7e46c/content/pmdk/libpmemlog.md#L43)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls drop this line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-21 15:44 UTC, szadam reviewed
> Reviewed 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk and @wlemkows)



<!-- Sent from Reviewable.io -->

2023-03-21 15:51 UTC, szadam reviewed
> Reviewed 1 of 1 files at r6, 1 of 2 files at r12, 1 of 1 files at r18, 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk and @wlemkows)



<!-- Sent from Reviewable.io -->

2023-03-22 08:14 UTC, wlemkows approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2023-03-22 08:23 UTC, lukaszstolarczuk approved these changes
:ok: 

> Reviewed 5 of 5 files at r22, 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330#-:-NR7PaYq0ijWvk2o8poy:b-8eogq1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szadam)



<!-- Sent from Reviewable.io -->

2023-03-22 08:27 UTC, wlemkows approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmem.github.io/330)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szadam)



<!-- Sent from Reviewable.io -->

2023-03-22 08:27 UTC, merged